import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AUTH_HORIZONTAL_PADDING } from '../src/constants/auth-styles';
import { colors } from '../src/constants/colors';
import { layout } from '../src/constants/layout';
import { typography } from '../src/constants/typography';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function Body({ children }: { children: string }) {
  return <Text style={styles.body}>{children}</Text>;
}

export default function TermsScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.screen} edges={['top']}>
      <ScrollView contentContainerStyle={styles.content}>
        <Pressable onPress={() => router.back()} style={styles.backButton}>
          <Text style={styles.backText}>Back</Text>
        </Pressable>

        <Text style={styles.pageTitle}>Terms of Service</Text>
        <Text style={styles.updated}>Last updated: July 7, 2026</Text>

        <Section title="1. Acceptance">
          <Body>
            By accessing or using Astradio at astradio.io or the Astradio mobile application, you agree to these
            terms. If you do not agree, do not use the service.
          </Body>
        </Section>

        <Section title="2. What Astradio Does">
          <Body>
            Astradio composes personalized astrological readings and audio compositions from natal chart data you
            provide. Readings and audio are for entertainment and self-reflection. They are not professional advice of
            any kind.
          </Body>
        </Section>

        <Section title="3. Your Account">
          <Body>
            You must provide accurate birth data to use chart features. You are responsible for keeping your login
            credentials secure. You may delete your account at any time through the app settings, which removes your
            data from our systems.
          </Body>
        </Section>

        <Section title="4. Content You Create">
          <Body>
            You retain ownership of any content you post (profile bios, community posts, audio labels). By posting to
            Astradio&apos;s community features, you grant us a license to display that content within the platform. We
            do not sell or sublicense your content to third parties.
          </Body>
        </Section>

        <Section title="5. Content We Create">
          <Body>
            Readings, transit summaries, compatibility reports, and audio compositions generated by Astradio are
            produced for your personal use. You may share them, but you may not resell or redistribute them
            commercially.
          </Body>
        </Section>

        <Section title="6. Acceptable Use">
          <Body>
            Do not use Astradio to harass, impersonate, or harm others. Do not upload offensive or illegal content. We
            reserve the right to remove content or suspend accounts that violate these terms.
          </Body>
        </Section>

        <Section title="7. Audio Compositions">
          <Body>
            Audio is composed using AI-assisted generation. Compositions are unique to your chart data but are not
            guaranteed to be musically distinct from compositions generated for other users. Audio files are stored on
            our servers and available as long as your account is active.
          </Body>
        </Section>

        <Section title="8. Availability">
          <Body>
            Astradio is provided as-is. We do not guarantee uninterrupted availability. We may modify or discontinue
            features at any time.
          </Body>
        </Section>

        <Section title="9. Limitation of Liability">
          <Body>
            Astradio is not liable for decisions you make based on readings or compositions. Our total liability for any
            claim related to the service is limited to the amount you have paid us in the twelve months preceding the
            claim, if any.
          </Body>
        </Section>

        <Section title="10. Changes">
          <Body>
            We may update these terms. Continued use after changes constitutes acceptance. Material changes will be
            communicated through the app or by email.
          </Body>
        </Section>

        <Section title="11. Contact">
          <Text style={styles.body}>
            Questions about these terms can be directed to{' '}
            <Text style={styles.link} onPress={() => void Linking.openURL('mailto:support@astradio.io')}>
              support@astradio.io
            </Text>
            .
          </Text>
        </Section>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: AUTH_HORIZONTAL_PADDING,
    paddingBottom: layout.screenBottomPadding,
  },
  backButton: {
    paddingVertical: 8,
    marginBottom: 8,
  },
  backText: {
    ...typography.bodySecondary,
    color: colors.accent.DEFAULT,
  },
  pageTitle: {
    ...typography.screenTitle,
    color: colors.text.primary,
    marginBottom: 8,
  },
  updated: {
    ...typography.caption,
    color: colors.text.secondary,
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  section: {
    marginBottom: 28,
    gap: 12,
  },
  sectionTitle: {
    fontFamily: 'Cormorant-SemiBold',
    fontSize: 22,
    color: colors.text.primary,
  },
  body: {
    ...typography.bodyPrimary,
    color: colors.text.secondary,
    lineHeight: 22,
  },
  link: {
    color: colors.accent.DEFAULT,
  },
});
