/**
 * Batch 6: Mercury feed rewrites (natal → transit-relational). Feed field only.
 * Run: npx tsx vnext/scripts/apply-batch6-mercury-feed.ts
 */
import * as fs from 'fs';
import * as path from 'path';

const MERCURY = path.join(__dirname, '../projection/insight-library/insight-library-aspects-mercury.ts');

function escapeForRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const FEED_PATCHES: Record<string, string> = {
  URANUS_MERCURY_CONJUNCTION: `Transiting Uranus meets natal Mercury at the same degree between these charts today. One person's disruptive clarity and the other person's articulation are fused right now. The current sky is opening a window where innovation and communication aren't separate—when Uranus breaks pattern, Mercury translates it immediately into language. When Mercury articulates, Uranus shows what that communication disrupts. Use this for conversations that require both breakthrough insight and clear expression.`,
  URANUS_MERCURY_OPPOSITION: `Transiting Uranus opposes natal Mercury between these charts today. One person's disruptive innovation and the other person's need for clear communication are at maximum distance. The current sky is making visible the gap between revolutionary insight and articulate expression. When Uranus wants to break pattern, Mercury needs coherent language. When Mercury articulates carefully, Uranus experiences it as constraining the breakthrough. The distance shows that disruption and communication don't always arrive together.`,
  URANUS_MERCURY_SQUARE: `Transiting Uranus is at friction point with natal Mercury between these charts today. One person's disruptive clarity and the other person's need for coherent expression are cutting across each other. The current sky is making visible the tension between breakthrough and articulation. When Uranus breaks pattern, Mercury struggles to translate it. When Mercury communicates carefully, Uranus experiences it as preventing the innovation. The friction is structural—both revolution and clarity are legitimate but geometrically incompatible right now.`,
  URANUS_MERCURY_TRINE: `Transiting Uranus is flowing with natal Mercury between these charts today. One person's disruptive innovation and the other person's articulation are drawing from the same elemental source. The current sky is amplifying how easily breakthrough and communication support each other. When Uranus breaks pattern, Mercury knows how to translate it. When Mercury articulates, Uranus shows what innovation that expression enables. Use this for conversations where both revolutionary insight and clear language are present.`,
  URANUS_MERCURY_SEXTILE: `Transiting Uranus is cooperating productively with natal Mercury between these charts today. One person's disruptive clarity and the other person's articulation are operating in compatible modes. The current sky is opening channels where innovation and communication can support each other. When Uranus breaks pattern, Mercury can translate it without demanding total revolution. When Mercury articulates, Uranus can contribute insight without disrupting the coherence. Use this for exchanges that need both breakthrough and clarity without the two modes fighting.`,
  NEPTUNE_MERCURY_CONJUNCTION: `Transiting Neptune meets natal Mercury at the same degree between these charts today. One person's transcendent vision and the other person's articulation are fused right now. The current sky is opening a window where mysticism and communication aren't separate—when Neptune dissolves boundaries, Mercury translates the ineffable into language. When Mercury articulates, Neptune shows what spiritual dimension that expression carries. Use this for conversations that require both mystical insight and poetic language.`,
  NEPTUNE_MERCURY_OPPOSITION: `Transiting Neptune opposes natal Mercury between these charts today. One person's mystical dissolution and the other person's need for clear communication are at maximum distance. The current sky is making visible the gap between transcendent vision and articulate expression. When Neptune wants to dissolve into the ineffable, Mercury needs concrete language. When Mercury articulates precisely, Neptune experiences it as missing the spiritual dimension. The distance shows that mysticism and clarity don't always converge.`,
  NEPTUNE_MERCURY_SQUARE: `Transiting Neptune is at friction point with natal Mercury between these charts today. One person's transcendent vision and the other person's need for coherent expression are cutting across each other. The current sky is making visible the tension between mysticism and clarity. When Neptune dissolves boundaries, Mercury struggles to articulate it. When Mercury communicates precisely, Neptune experiences it as reducing the ineffable to mere words. The friction is structural—both spiritual vision and clear language are legitimate but geometrically incompatible right now.`,
  NEPTUNE_MERCURY_TRINE: `Transiting Neptune is flowing with natal Mercury between these charts today. One person's mystical vision and the other person's articulation are drawing from the same elemental source. The current sky is amplifying how easily transcendence and communication support each other. When Neptune dissolves boundaries, Mercury knows how to translate the ineffable into language. When Mercury articulates, Neptune shows what spiritual dimension that expression carries. Use this for conversations where both mystical insight and poetic clarity are present.`,
  NEPTUNE_MERCURY_SEXTILE: `Transiting Neptune is cooperating productively with natal Mercury between these charts today. One person's transcendent vision and the other person's articulation are operating in compatible modes. The current sky is opening channels where mysticism and communication can support each other. When Neptune dissolves boundaries, Mercury can translate it without demanding concrete precision. When Mercury articulates, Neptune can contribute spiritual dimension without overwhelming the clarity. Use this for exchanges that need both mystical insight and language without the two modes fighting.`,
  PLUTO_MERCURY_CONJUNCTION: `Transiting Pluto meets natal Mercury at the same degree between these charts today. One person's transformative intensity and the other person's articulation are fused right now. The current sky is opening a window where depth and communication aren't separate—when Pluto demands truth beneath the surface, Mercury articulates what's hidden. When Mercury speaks, Pluto shows what power that language carries. Use this for conversations that require both psychological depth and penetrating expression.`,
  PLUTO_MERCURY_OPPOSITION: `Transiting Pluto opposes natal Mercury between these charts today. One person's transformative intensity and the other person's need for clear communication are at maximum distance. The current sky is making visible the gap between depth and articulation. When Pluto demands total truth, Mercury needs manageable language. When Mercury articulates carefully, Pluto experiences it as avoiding what's actually happening beneath the surface. The distance shows that psychological depth and clear expression don't always arrive together.`,
  PLUTO_MERCURY_SQUARE: `Transiting Pluto is at friction point with natal Mercury between these charts today. One person's transformative intensity and the other person's need for coherent expression are cutting across each other. The current sky is making visible the tension between depth and clarity. When Pluto demands truth beneath the surface, Mercury struggles to articulate it without being overwhelmed. When Mercury communicates carefully, Pluto experiences it as avoiding necessary confrontation with what's real. The friction is structural—both psychological depth and clear language are legitimate but geometrically incompatible right now.`,
  PLUTO_MERCURY_TRINE: `Transiting Pluto is flowing with natal Mercury between these charts today. One person's transformative intensity and the other person's articulation are drawing from the same elemental source. The current sky is amplifying how easily depth and communication support each other. When Pluto demands truth beneath the surface, Mercury knows how to articulate it. When Mercury speaks, Pluto shows what transformation that language enables. Use this for conversations where both psychological depth and penetrating clarity are present.`,
  PLUTO_MERCURY_SEXTILE: `Transiting Pluto is cooperating productively with natal Mercury between these charts today. One person's transformative intensity and the other person's articulation are operating in compatible modes. The current sky is opening channels where depth and communication can support each other. When Pluto demands truth, Mercury can articulate it without total confrontation. When Mercury speaks, Pluto can contribute psychological insight without overwhelming the conversation. Use this for exchanges that need both depth and clarity without the two modes fighting.`,
  MOON_MERCURY_OPPOSITION: `Transiting Moon opposes natal Mercury between these charts today. One person's emotional instinct and the other person's need for clear communication are at maximum distance. The current sky is making visible the gap between what's felt and what can be articulated. When the Moon needs to feel without analyzing, Mercury wants to translate the feeling into language. When Mercury articulates precisely, the Moon experiences it as intellectualizing genuine emotion. The distance shows that feeling and expression don't always converge in the same moment.`,
  MERCURY_VENUS_OPPOSITION: `Transiting Mercury opposes natal Venus between these charts today. One person's articulation and the other person's aesthetic sense are at maximum distance. The current sky is making visible the gap between what can be said and what feels beautiful. When Mercury wants to express something clearly, Venus needs it to land with grace. When Venus values harmony, Mercury experiences it as avoiding necessary clarity. The distance shows that expression and beauty don't always arrive together.`,
  MERCURY_VENUS_SEXTILE: `Transiting Mercury is cooperating productively with natal Venus between these charts today. One person's articulation and the other person's aesthetic sense are operating in compatible modes. The current sky is opening channels where expression and beauty can support each other. When Mercury articulates, Venus knows how to make it graceful. When Venus values harmony, Mercury can contribute clarity without disrupting the aesthetic. Use this for conversations that need both clear expression and pleasing delivery.`,
  MERCURY_MARS_OPPOSITION: `Transiting Mercury opposes natal Mars between these charts today. One person's articulation and the other person's drive for action are at maximum distance. The current sky is making visible the gap between what can be said and what needs to be done. When Mercury wants to discuss, Mars wants to act. When Mars pushes forward, Mercury experiences it as bypassing necessary conversation. The distance shows that expression and action don't always converge in the same moment.`,
  MERCURY_MARS_SEXTILE: `Transiting Mercury is cooperating productively with natal Mars between these charts today. One person's articulation and the other person's drive are operating in compatible modes. The current sky is opening channels where expression and action can support each other. When Mercury articulates the plan, Mars knows how to execute it. When Mars drives forward, Mercury can provide the language that clarifies the direction. Use this for exchanges where both clear communication and decisive action contribute productively.`,
  MERCURY_MERCURY_CONJUNCTION: `Transiting Mercury meets natal Mercury at the same degree between these charts today. Two articulation styles, two ways of processing information, are occupying the same space right now. The current sky is opening a window where both people's communication patterns are fused—when one person articulates, the other recognizes the thought process immediately. When one translates experience into language, the other already knows that vocabulary. Use this for conversations that require mutual understanding without explanation.`,
  MERCURY_MERCURY_OPPOSITION: `Transiting Mercury opposes natal Mercury between these charts today. Two articulation styles, two ways of processing information, are at maximum distance. The current sky is making visible the gap between how each person thinks and communicates. When one person articulates their perspective, the other experiences it as opposite to their own thought process. When one translates experience into language, the other uses completely different vocabulary. The distance shows that mutual understanding requires deliberate translation right now.`,
  MERCURY_MERCURY_SQUARE: `Transiting Mercury is at friction point with natal Mercury between these charts today. Two articulation styles, two ways of processing information, are cutting across each other. The current sky is making visible the tension between different thought processes. When one person articulates their perspective, the other experiences it as interfering with their own communication style. When one translates experience into language, the other's vocabulary creates friction. Both ways of thinking are legitimate but geometrically incompatible right now.`,
  MERCURY_MERCURY_TRINE: `Transiting Mercury is flowing with natal Mercury between these charts today. Two articulation styles, two ways of processing information, are drawing from the same elemental source. The current sky is amplifying how easily both people's communication patterns support each other. When one person articulates, the other recognizes the thought process as compatible with their own. When one translates experience into language, the other's vocabulary reinforces it. Use this for conversations where mutual understanding flows naturally.`,
  MERCURY_MERCURY_SEXTILE: `Transiting Mercury is cooperating productively with natal Mercury between these charts today. Two articulation styles, two ways of processing information, are operating in compatible modes. The current sky is opening channels where both people's communication patterns can support each other. When one person articulates, the other can build on that expression. When one translates experience into language, the other's vocabulary contributes without competing. Use this for exchanges where different thought processes complement rather than clash.`,
};

let src = fs.readFileSync(MERCURY, 'utf8');
let ok = 0;

for (const [key, feed] of Object.entries(FEED_PATCHES)) {
  const keyRe = new RegExp(
    `(\\s+${escapeForRegex(key)}:\\s*\\{)([\\s\\S]*?)(\\n\\s+\\},)`
  );
  const m = src.match(keyRe);
  if (!m) {
    console.error('MISSING', key);
    continue;
  }
  let body = m[2]!;
  const feedRe = /\n\s+feed:\s*`[^`]*`,/;
  if (!feedRe.test(body)) {
    console.error('NO feed field', key);
    continue;
  }
  body = body.replace(feedRe, `\n    feed: \`${feed}\`,`);
  src = src.replace(keyRe, `$1${body}$3`);
  ok++;
  console.log('OK', key);
}

fs.writeFileSync(MERCURY, src, 'utf8');
console.log({ ok, expected: Object.keys(FEED_PATCHES).length });
if (ok !== Object.keys(FEED_PATCHES).length) process.exit(1);
