/**
 * Astradio Insight Library — Pluto Aspects to Personal Planets (Batch 2)
 *
 * 20 objects: PLUTO × SUN, MOON, VENUS, MARS × 5 aspects
 * Place at: vnext/projection/insight-library/insight-library-aspects-pluto.ts
 */

import type { AspectInsight } from './insight-library-types';

export const PLUTO_ASPECT_INSIGHTS: Readonly<Record<string, AspectInsight>> = {

  PLUTO_SUN_CONJUNCTION: {
    key: 'PLUTO_SUN_CONJUNCTION', pair: 'PLUTO_SUN', aspect: 'conjunction', intensity: 'Extreme',
    core: `Pluto, the transpersonal principle of transformation through depth, the destruction of what is no longer genuinely alive, and the encounter with the unconscious forces that shape life from below the level of ordinary awareness, fuses with the Sun, the seat of conscious identity and the purposeful drive toward self-expression. When these two occupy the same degree, identity and transformation become one system. This person does not experience themselves as having a fixed, continuous identity that moves through time. They experience identity itself as a process of perpetual death and regeneration, with each significant life phase requiring the genuine death of a previous version of the self before the next can emerge. What results is a person of extraordinary psychological depth, genuine personal power, and a capacity for self-transformation that others may find both compelling and unsettling. Born into a generational signature of Pluto's transit through a zodiac sign, their individual Sun carries the collective transformative force of their entire generation as a personal character trait.`,
    behavioral: `The ego does not experience power as something it claims from the surface. It experiences power as something that moves through it from below, from the depths of the unconscious, from the part of the psyche that has been through genuine descent and return. The result is a person with an unusual quality of psychological intensity, a presence that others feel as genuinely powerful even when this person is being quiet, a capacity for insight into the hidden motivations of both self and others that can be disarming, and a willingness to engage with the darkest, most difficult dimensions of human experience that others avoid. The shadow requires honest naming: the same power that makes this person genuinely compelling can express as controlling behavior, as a compulsive need to penetrate the defenses of others, or as the destructive exercise of personal power when the transformative principle is not yet fully integrated into conscious choice.`,
    friendship: `Friends experience a person with extraordinary psychological depth and genuine personal power who can be both profoundly supportive and, at times, uncomfortably penetrating. Someone whose presence reveals things that were not intended to be visible.`,
    romantic: `Partners often describe the experience of being seen more completely than they have been seen before, and also the experience of a relational dynamic that carries real intensity and real power. Relationships with Pluto-Sun people are rarely neutral. They transform the people who enter them.`,
    feed: `Pluto's transit is pressing on the deepest identity structures in this connection right now. Something that was genuinely hidden about who each person is in relation to the other is becoming visible today, and what surfaces cannot simply be put back below.`,
    sonic: `The Sun's natural clarity and purposefulness are present in the conjunction but they are being driven by something far deeper than ordinary ego intention. The melodic lines have the Sun's direction but they are moving under enormous subterranean pressure, as if the purposeful surface is the visible tip of something vast and dark beneath. The rhythm has the Sun's consistent forward motion but Pluto's relentless, inevitable quality. The harmonic language is major but densely chromatic, the Sun's tonality saturated with Pluto's subterranean pressure. Listen for the quality of music where something purposeful is also unmistakably being driven by forces far deeper than the surface purpose, where the direction is clear and the power behind it is genuinely subterranean.`,
  },

  PLUTO_SUN_SEXTILE: {
    key: 'PLUTO_SUN_SEXTILE', pair: 'PLUTO_SUN', aspect: 'sextile', intensity: 'Medium',
    core: `Pluto, transformation, depth, and the regenerative force of the unconscious, and the Sun, conscious identity and purposeful self-expression, are in a 60-degree relationship of easy, productive cooperation. The person has genuine access to Pluto's transformative depth and psychological power without the compulsive intensity that the conjunction produces. They can engage with the hidden, the powerful, and the transformative dimensions of experience as genuine resources rather than as forces that perpetually dismantle the established self.`,
    behavioral: `The ego's drive for self-expression and Pluto's transformative, depth-oriented principle are in productive communication. The Sun can draw on Pluto's psychological depth, insight into hidden dynamics, and genuine personal power as resources without being compulsively driven by them. The result is real psychological insight, genuine personal power that is available rather than compulsive, and a capacity for engaging with difficult, transformative material that others might avoid.`,
    friendship: `Psychologically perceptive, genuinely trustworthy with difficult material, and capable of sustaining relationships through genuine transformation.`,
    romantic: `Partners find a quality of genuine psychological depth and transformative capacity that makes the relationship feel meaningful rather than superficial.`,
    feed: `Today's transit is opening the productive channel between depth and self-expression in this connection. There is a quality of genuine psychological power and transformative insight available between these charts right now.`,
    sonic: `The Sun's directional clarity is supported by Pluto's depth without being overwhelmed by it in the sextile. The melodic lines have the Sun's purpose and move through genuinely deep harmonic space, purposeful on the surface and substantial underneath. Listen for the quality of music where something purposeful also sounds genuinely deep, where the direction is clear and the power behind it is real but not compulsive.`,
  },

  PLUTO_SUN_SQUARE: {
    key: 'PLUTO_SUN_SQUARE', pair: 'PLUTO_SUN', aspect: 'square', intensity: 'Very high',
    core: `Pluto, the principle of transformation through depth, the destruction of what is no longer genuinely alive, and compulsive unconscious force, meets the Sun, conscious identity and the drive toward purposeful, continuous self-expression, at a 90-degree angle of profound, sustained tension. Pluto compels the transformation of what the Sun has built. The Sun consolidates identity. Pluto destroys the consolidated form and demands regeneration from the ruins. The 90-degree angle means neither force simply yields, and the person experiences a recurring tension between the Sun's legitimate need for continuous, coherent self-expression and Pluto's equally compulsive insistence that what has been built must be destroyed before something genuinely new can emerge.`,
    behavioral: `The Sun's natural drive toward stable, purposeful self-expression keeps encountering Pluto's insistence that the established identity contains hidden elements, suppressed power, denied darkness, disowned compulsion, that must be brought into conscious light and integrated before the Sun can genuinely be who it claims to be. This person's life moves through episodes of genuine power and identity crisis. They build a version of themselves, establish it in the world, and then Pluto compels a confrontation with what that version of the self has excluded, suppressed, or denied. The confrontation is not gentle. The power that emerges from genuine Pluto-Sun square integration is among the most authentic in the natal chart, because it has been earned through the genuine death and regeneration of the false self.`,
    friendship: `Friends experience a person of extraordinary psychological depth and genuine personal power who moves through significant identity transformations with a regularity that can be both impressive and occasionally disorienting to witness.`,
    romantic: `Partners may find this person's transformations both compelling and challenging. The version of the person they committed to is periodically dismantled by Pluto, and the relationship must repeatedly accommodate the emergence of the next version.`,
    feed: `Pluto's transit is pressing on the deepest tension between who each person presents as being and who they actually are in this connection right now. Something hidden and genuinely powerful is closer to the surface between these charts today than it usually is, and what it reveals deserves honest engagement.`,
    sonic: `The Sun's melodic lines move with purpose and are being compressed from beneath by Pluto's enormous subterranean weight in the square. The surface purpose and the underground force are in sustained 90-degree tension. The harmonic language has the Sun's major tonality saturated by Pluto's chromatic density, the familiar tonal surface under enormous subterranean pressure. Listen for the quality of music where something purposeful is also under enormous pressure from below, where the surface direction is clear and the depth beneath it is vast and compulsive and is working on the surface from below.`,
  },

  PLUTO_SUN_TRINE: {
    key: 'PLUTO_SUN_TRINE', pair: 'PLUTO_SUN', aspect: 'trine', intensity: 'Medium',
    core: `Pluto, transformation, depth, and the regenerative unconscious force, and the Sun, conscious identity and purposeful self-expression, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces are naturally aligned. Pluto's transformative depth and the Sun's purposeful self-expression move in the same direction without the compulsive intensity of harder aspects. The person has natural access to Pluto's psychological depth, personal power, and transformative capacity as integrated qualities of their identity rather than as forces that periodically dismantle it.`,
    behavioral: `The ego's drive for self-expression and Pluto's transformative principle are drawing from the same elemental source. The Sun can express itself with genuine psychological depth and personal power as natural qualities, without the compulsive intensity or identity crisis that harder Pluto-Sun aspects produce. The result is a person with genuine personal power, real psychological insight, and a capacity for purposeful transformation that serves the self rather than dismantling it.`,
    friendship: `Genuinely powerful in their presence, psychologically perceptive, and capable of sustaining transformative relationships without the compulsive intensity of harder Pluto aspects.`,
    romantic: `Partners find a quality of genuine personal power and psychological depth that makes the relationship feel substantive and transformative in a healthy sense.`,
    feed: `The current sky is amplifying the natural alignment between depth and self-expression in this connection. The genuine psychological power and transformative capacity that runs between these charts is more naturally directed right now.`,
    sonic: `The Sun's purposeful melodic direction moves through Pluto's deep subterranean harmonic space without being overwhelmed by it in the trine. The surface purpose and the underlying depth are in natural agreement. The harmonic language is major with genuine Plutonian depth, purposeful tonality with real subterranean substance. Listen for the quality of music where something purposeful also sounds genuinely powerful from within, where the direction is clear and the depth supporting it is real and integrated.`,
  },

  PLUTO_SUN_OPPOSITION: {
    key: 'PLUTO_SUN_OPPOSITION', pair: 'PLUTO_SUN', aspect: 'opposition', intensity: 'Very high',
    core: `Pluto, transformation through depth, the unconscious, and the regenerative destruction of what is no longer genuinely alive, stands at full polarity with the Sun, conscious identity and the drive toward purposeful self-expression and recognition. At 180 degrees, the Sun asserts its right to express and to be seen. Pluto challenges whether that expression is genuinely authentic or whether it is hiding something that needs to be examined. The opposition tends to externalize. The person encounters Pluto's transformative, power-oriented, depth-driving principle through other people, through power struggles with significant others, through encounters with people who seem to hold power over the person's sense of self, or through external events that force a fundamental revision of who the person understands themselves to be.`,
    behavioral: `The ego tends to experience Pluto's transformative, power-testing function as something that comes from outside rather than from within. The person may repeatedly encounter people or circumstances that hold a kind of psychological power over their self-definition, without fully recognizing that the Pluto principle is part of their own psychological architecture. The developmental work is integrating Pluto's depth, power, and transformation as genuinely interior qualities.`,
    friendship: `The most transformative and occasionally most difficult friendships are those that involve genuine power dynamics. People who hold a kind of psychological power over the person's self-definition or who force a confrontation with something that was not previously visible.`,
    romantic: `Partners who carry a significant Plutonian quality, who seem to hold power, who force confrontations with hidden dimensions of the self, or who introduce genuine power dynamics, can be among the most transformative and most challenging relationship experiences.`,
    feed: `Pluto's transit is illuminating both ends of the identity-and-power axis in this connection today. The power dynamics and the deeper hidden forces at work between these charts are more visible right now than usual, and what becomes visible in that clarity is both significant and irreversible.`,
    sonic: `The Sun's clear, purposeful melodic direction keeps encountering Pluto's enormous subterranean force from across the compositional space in the opposition. The surface and the depth pulling in opposite directions across the full range of the musical space. Listen for the quality of music where something purposeful keeps encountering something of enormous depth from outside its own frame, where the surface direction and the underground power are in dialogue that transforms both.`,
  },

  PLUTO_MOON_CONJUNCTION: {
    key: 'PLUTO_MOON_CONJUNCTION', pair: 'PLUTO_MOON', aspect: 'conjunction', intensity: 'Extreme',
    core: `Pluto, the principle of transformation through depth, the destruction of what is no longer genuinely alive, and the encounter with the most primal compulsive unconscious forces, fuses with the Moon, the keeper of emotional instinct, memory, interior safety, and the body's fundamental need for nourishment and comfort. When these two occupy the same degree, the emotional world and the deepest transformative unconscious forces become one system. This is among the most psychologically intense configurations a natal chart can carry. The Moon's natural emotional instinct has been fused with Pluto's compulsive, depth-driving, transformative force. The emotional interior of this person is not merely deep. It is connected to the most primal dimensions of the unconscious. What this person feels, they feel absolutely. What they lose, they grieve completely. What they love, they love with a totality that can be overwhelming.`,
    behavioral: `The emotional attachment system has been fused with the transformative underworld archetype, producing an emotional interior that does not simply feel but is shaped by the full depth of the unconscious emotional field, including its most primal, compulsive, and power-driven dimensions. The result is extraordinary emotional depth, genuine psychological insight into the hidden emotional lives of others, and a capacity for emotional transformation, both their own and in the people they are close to, that others may find both healing and sometimes overwhelming. The shadow requires honest naming: the intensity can express as emotional control, as possessiveness, as an inability to allow the emotional field to remain simple or uncomplicated when Pluto's depth is always pulling everything into deeper and darker territory.`,
    friendship: `Friends experience a person of extraordinary emotional depth and genuine psychological perceptiveness who can be profoundly supportive in genuine crisis and occasionally difficult to sustain in ordinary relational ease, because Pluto's depth does not naturally rest in the shallows.`,
    romantic: `Partners often describe the most intense and transformative emotional experiences of their lives in relationship with this person, and also some of the most challenging. The depth is real. The transformation is real. The intensity is real. What the relationship asks of both people is correspondingly large.`,
    feed: `Pluto's transit is pressing on the deepest emotional foundations of this connection right now. Something in the emotional substrate between these two charts is being fundamentally altered today, and what it reveals about what has been hidden beneath the surface of this relationship is both significant and irreversible.`,
    sonic: `The Moon's emotional instinct and Pluto's transformative depth are the same sound in the conjunction. The modal harmonic language of emotional memory is saturated with Pluto's chromatic density and subterranean pressure. The breathing rhythmic quality of the Moon is driven by Pluto's relentless inevitable pulse. The melodic quality moves downward not toward darkness as absence but toward darkness as substance, as the most dense and pressurized and emotionally real territory available. Listen for the quality of music where you feel something in your body before you can name what you are feeling, where the emotional depth is real and also genuinely subterranean, genuinely below the level of ordinary emotional experience.`,
  },

  PLUTO_MOON_SEXTILE: {
    key: 'PLUTO_MOON_SEXTILE', pair: 'PLUTO_MOON', aspect: 'sextile', intensity: 'Medium',
    core: `Pluto, transformation, depth, and the regenerative unconscious, and the Moon, emotional instinct, interior need, and the body's requirement for safety, are in a 60-degree relationship of easy, productive cooperation. The person has genuine access to Pluto's transformative emotional depth without the compulsive intensity that the conjunction produces. They can engage with the deepest dimensions of emotional experience as genuine resources rather than as forces that perpetually overwhelm the emotional safety system.`,
    behavioral: `The Moon can feel with Pluto's depth available as a genuine resource without the compulsive intensity. The result is real emotional depth, genuine insight into hidden emotional dynamics, and a capacity for emotional transformation that serves the self and others rather than overwhelming them.`,
    friendship: `Emotionally perceptive at depth, genuinely trustworthy with the most difficult emotional material, and capable of sustaining transformative relationships.`,
    romantic: `Partners find a quality of genuine emotional depth and transformative capacity that makes the relationship feel substantive and genuinely supportive through real difficulty.`,
    feed: `Today's transit is gently opening the channel between emotional depth and transformative insight in this connection. There is a quality of genuine emotional power and psychological depth available between these charts right now.`,
    sonic: `The Moon's emotional instinct is given Pluto's depth without the compulsive overwhelm in the sextile. The harmonic language is modally warm and also genuinely deep, emotionally felt at the surface and substantial underneath. Listen for the quality of music where something emotionally instinctive also sounds genuinely profound, where the feeling and the depth beneath it are in natural agreement.`,
  },

  PLUTO_MOON_SQUARE: {
    key: 'PLUTO_MOON_SQUARE', pair: 'PLUTO_MOON', aspect: 'square', intensity: 'Extreme',
    core: `Pluto, the principle of transformation through depth, the destruction of what is no longer genuinely alive, and compulsive unconscious force, meets the Moon, emotional instinct, interior safety, and the body's fundamental need for comfort and nourishment, at a 90-degree angle of profound, sustained, and genuinely life-shaping tension. This is among the most psychologically challenging aspect configurations in the natal chart, and it deserves to be received with both honesty and care. Pluto compels the transformation of what the Moon most deeply needs: safety, familiarity, and the continuity of emotional memory. The Moon seeks the known. Pluto destroys the known. The Moon needs to feel safe. Pluto operates in the territory where safety cannot be guaranteed.`,
    behavioral: `The part of the psyche that simply needs to feel safe and held has been subjected to Pluto's demand for transformation before that safety is granted. Whether this originated in a literal experience of emotional upheaval in early life or is simply the natal architecture of the configuration, the behavioral result tends to be consistent. This person may carry cycles of establishing emotional ground and then experiencing its compulsive transformation, may find it genuinely difficult to know what they actually feel versus what they are being asked to become, and may develop either significant emotional stoicism or significant emotional intensity as a result. The power that emerges from genuine Pluto-Moon square integration is extraordinary: the emotional depth, the capacity for genuine compassionate accompaniment of others through their own difficult transformations, the earned wisdom of someone who has been to the emotional depths and returned.`,
    friendship: `Friends experience a person of extraordinary emotional depth and genuine compassionate presence in genuine crisis who may find ordinary relational ease genuinely difficult because Pluto's depth is always pulling the emotional field toward its most significant rather than its most comfortable dimensions.`,
    romantic: `Partners often describe the most emotionally significant and most demanding relationship of their lives. The depth is real. The transformation is real. The difficulty is also real. The relationship that can hold all of this becomes one of the most genuinely important experiences either person has.`,
    feed: `Pluto's transit is pressing on the deepest emotional foundations in this connection right now. Something in the emotional substrate between these charts is being compulsively transformed today in a way that is neither comfortable nor optional, and what emerges from that transformation will be more authentic than what it is replacing.`,
    sonic: `The Moon's breathing, returning quality is being compressed from below by Pluto's enormous subterranean weight in the square. The emotional surface is trying to maintain its familiar breathing rhythm and the depth beneath it is working on it continuously from below. The rhythm has the Moon's organic breath under Pluto's relentless pressure. Listen for the quality of music where something emotionally instinctive is also under enormous pressure from a depth far below its natural level, where the familiar emotional ground and the transformative force working on it from below are both completely audible and in genuine sustained tension.`,
  },

  PLUTO_MOON_TRINE: {
    key: 'PLUTO_MOON_TRINE', pair: 'PLUTO_MOON', aspect: 'trine', intensity: 'Medium',
    core: `Pluto, transformation, depth, and the regenerative unconscious, and the Moon, emotional instinct, interior need, and the body's requirement for safety, are in the same elemental family, separated by 120 degrees. The trine means these two forces are naturally aligned. Pluto's transformative depth and the Moon's emotional instinct move in the same direction without the compulsive intensity of harder aspects. The person has natural access to profound emotional depth, genuine insight into hidden emotional dynamics, and a capacity for emotional transformation as integrated qualities of their emotional character.`,
    behavioral: `The Moon can feel with Pluto's depth as a natural quality of the emotional field rather than as a compulsive force working against the need for safety. The result is extraordinary emotional depth, genuine psychological insight, and a capacity for sustaining and supporting genuine emotional transformation that is both real and integrated rather than overwhelming.`,
    friendship: `Emotionally powerful in their depth, genuinely trustworthy with the most difficult material, and capable of being present through genuine transformation without the compulsive intensity of harder Pluto aspects.`,
    romantic: `Partners find a quality of emotional depth and transformative capacity that makes the relationship feel genuinely substantive, the kind of relationship that grows more significant over time rather than less.`,
    feed: `The current sky is amplifying the natural alignment between emotional depth and transformative capacity in this connection. The genuine psychological depth and emotional power that runs between these charts is more present and more accessible right now.`,
    sonic: `The Moon's emotional instinct moves through Pluto's deep subterranean harmonic space without being overwhelmed by it in the trine. The emotional surface and the transformative depth are in natural agreement. The harmonic language is modally warm and also genuinely deep. Listen for the quality of music where something emotionally instinctive is also genuinely profound, where the feeling and the depth beneath it are the same quality.`,
  },

  PLUTO_MOON_OPPOSITION: {
    key: 'PLUTO_MOON_OPPOSITION', pair: 'PLUTO_MOON', aspect: 'opposition', intensity: 'Very high',
    core: `Pluto, transformation through depth, the unconscious, and the regenerative destruction of what is no longer alive, stands at full polarity with the Moon, emotional instinct, interior safety, and the body's fundamental need for comfort. The opposition tends to externalize. The person encounters Pluto's transformative, power-oriented, depth-driving principle through emotionally significant others and through life circumstances, through relationships that introduce genuine power dynamics into the emotional field, through people who carry a significant Plutonian quality, or through emotional events that force a fundamental transformation of the established interior emotional structure.`,
    behavioral: `The emotional ground the Moon has established keeps encountering situations and people that bring the full weight of Pluto's transformative force to bear on it from outside, through power dynamics in emotional relationships, through losses or crises that force fundamental emotional transformation, or through people who seem to hold a kind of power over the person's emotional interior. The developmental work is integrating the Plutonian capacity for emotional depth, power, and transformation as interior resources rather than forces encountered only through external circumstances.`,
    friendship: `The most emotionally transformative and occasionally most challenging friendships are those that involve genuine emotional power dynamics. People who bring Plutonian depth and force into contact with the Moon's need for safety.`,
    romantic: `Partners who carry a significant Plutonian quality can introduce the most profound and most demanding emotional transformations, relationships that leave both people genuinely changed.`,
    feed: `Pluto's transit is illuminating both ends of the emotional-power axis in this connection today. The hidden emotional forces and power dynamics at work between these charts are more visible right now than usual, and what becomes visible at this depth is significant.`,
    sonic: `The Moon's breathing, cycling, emotionally grounded quality keeps encountering Pluto's enormous subterranean force from across the compositional space in the opposition. Listen for the quality of music where something emotionally familiar keeps encountering something of enormous depth from outside, where the emotional surface and the underground transformation are in dialogue that leaves neither unchanged.`,
  },

  PLUTO_VENUS_CONJUNCTION: {
    key: 'PLUTO_VENUS_CONJUNCTION', pair: 'PLUTO_VENUS', aspect: 'conjunction', intensity: 'Extreme',
    core: `Pluto, the principle of transformation through depth, the destruction of what is no longer genuinely alive, and the encounter with the most primal compulsive unconscious forces, fuses with Venus, the planet governing love, aesthetic sensibility, relational value, and the capacity to draw beauty and connection toward oneself. When these two occupy the same degree, love and transformation become one system. This person does not experience love as something warm, gentle, and sustaining. They experience love as the most transformative encounter available to a human being. The result is a person whose love is genuine, deep, and total, and whose relational life is characterized by encounters of genuine psychological intensity that transform everyone involved.`,
    behavioral: `Venus reaches toward connection and beauty. Pluto ensures that any genuine connection will involve the full depth of the unconscious, including its most hidden, compulsive, and power-driven dimensions. This person does not love lightly. Every genuine attachment is felt at the level of absolute necessity. They do not let go easily, because Pluto's compulsive force makes the experience of love loss genuinely primal rather than merely sad. The shadow requires explicit naming: the same depth that makes this person's love transformative can express as possessiveness, jealousy, emotional control, or the use of intimate knowledge gained through love as a form of power over the beloved.`,
    friendship: `Friends experience extraordinary depth of genuine care and a quality of relational intensity that makes the friendship feel significant, and also occasionally demanding in the way that all genuinely Plutonian connections are demanding.`,
    romantic: `Partners often describe the most intensely transformative relationship of their lives. The love is real and total. The depth is genuine. The power dynamic requires conscious navigation. And the person who emerges from a genuine Pluto-Venus love relationship is not the same person who entered it.`,
    feed: `Pluto's transit is pressing on the deepest foundations of love and connection in this connection right now. Something that was hidden beneath the surface of how each person understands what this relationship means is becoming visible today, and what surfaces at this depth is both significant and irreversible.`,
    sonic: `Venus's warmth and aesthetic care are expressed through Pluto's subterranean register in the conjunction. The harmonic language is warm and also dark, the voice leading is graceful and also moving toward a depth that has no floor. The rhythm has Venus's grace under Pluto's relentless inevitable pressure. The beauty is real and it is being drawn downward into something far more primal than beauty alone. Listen for the quality of music where something genuinely beautiful is also unmistakably descending toward something vast and dark and genuinely transformative, where the warmth and the depth are the same sound, and the descent is both inevitable and profound.`,
  },

  PLUTO_VENUS_SEXTILE: {
    key: 'PLUTO_VENUS_SEXTILE', pair: 'PLUTO_VENUS', aspect: 'sextile', intensity: 'Medium',
    core: `Pluto, transformation, depth, and the regenerative unconscious, and Venus, love, aesthetic sensibility, and relational warmth, are in a 60-degree relationship of easy, productive cooperation. The person has genuine access to Pluto's transformative relational depth without the compulsive intensity the conjunction produces. They can love with genuine depth and bring real transformative capacity to their relationships without the power dynamics that the harder aspects introduce.`,
    behavioral: `Venus can express love with Pluto's depth and psychological insight available as genuine resources. The result is real relational depth, genuine insight into the hidden dynamics of love, and a capacity for transformative relational care.`,
    friendship: `Genuinely deep in their care, trustworthy with difficult relational material, and capable of sustaining transformative connections.`,
    romantic: `Partners find a quality of genuine relational depth and transformative care that makes the relationship feel substantive and meaningful over time.`,
    feed: `Today's transit is opening the productive channel between love and transformative depth in this connection. There is a quality of genuine relational power and psychological depth available between these charts right now.`,
    sonic: `Venus's warmth is given Pluto's depth without the compulsive intensity in the sextile. The harmonic language is warm and also genuinely deep. Listen for the quality of music where something beautiful also sounds genuinely profound, where the warmth and the depth are supporting each other.`,
  },

  PLUTO_VENUS_SQUARE: {
    key: 'PLUTO_VENUS_SQUARE', pair: 'PLUTO_VENUS', aspect: 'square', intensity: 'Very high',
    core: `Pluto, the principle of transformation through depth and the destruction of what is no longer genuinely alive, meets Venus, love, beauty, relational warmth, and the desire for sustaining connection, at a 90-degree angle of profound, sustained, compulsive tension. Pluto compels the transformation of the relational field. Venus builds toward warm, beautiful, sustained connection. Pluto destroys the surface beauty to reveal the depth beneath it. Venus seeks pleasure, warmth, and aesthetic harmony. Pluto is drawn to what is hidden, compulsive, and genuinely powerful rather than merely pleasant. The 90-degree angle means neither force simply yields, and the person experiences a recurring, often overwhelming tension between the Venus desire for genuine warmth and sustained relational connection and Pluto's compulsive insistence that what is beautiful on the surface must be tested against what is real in the depths.`,
    behavioral: `Pluto's transformative compulsion operates on Venus's most fundamental relational needs, for warmth, beauty, aesthetic harmony, and the sustained pleasure of genuine connection, with a force that does not respect the Venus requirement for gentleness. Relationships for this person are not merely warm or pleasant experiences. They are genuine descents, confrontations with what is hidden, and transformations of both people involved. The shadow requires explicit naming: the compulsive dimension of Pluto's force can express in the relational domain as possessiveness, jealousy, the use of intimate knowledge as power, or an inability to allow the beloved their genuine freedom because Pluto's compulsive attachment does not release easily.`,
    friendship: `Friends experience both extraordinary depth of genuine care and the intensity that Pluto introduces into all genuine connections. The friendship matters completely and the relational dynamics it generates can be genuinely complex.`,
    romantic: `Partners experience the most intensely demanding relational configuration in the library. Love that is absolutely genuine and also absolutely intense, that transforms both people involved, and that requires conscious navigation of genuine power dynamics to sustain.`,
    feed: `Pluto's transit is pressing on the deepest and most compulsive foundations of love in this connection right now. What is genuinely real versus what is merely beautiful, what is alive versus what is being maintained past its genuine end, is more visible today than it has been, and what surfaces at this depth cannot be ignored.`,
    sonic: `Venus reaches toward beautiful harmonic destinations. Pluto pulls everything toward the depths before the beautiful arrival can be completed in the square. The harmonic language has Venus's warmth saturated by Pluto's chromatic density, beauty under subterranean pressure. Listen for the quality of music where something genuinely beautiful is also being continuously pulled toward something vast and dark and transformative, where the warmth and the depth are in sustained compelling tension.`,
  },

  PLUTO_VENUS_TRINE: {
    key: 'PLUTO_VENUS_TRINE', pair: 'PLUTO_VENUS', aspect: 'trine', intensity: 'Medium',
    core: `Pluto and Venus are in the same elemental family, separated by 120 degrees. Love and transformative depth are not in tension here. They inform each other. The person's capacity for genuine warmth and their natural orientation toward relational depth and psychological power are harmoniously integrated. They can love with genuine depth and bring real transformative capacity to their relationships without the compulsive intensity that harder aspects produce.`,
    behavioral: `Venus can express love with Pluto's depth as a natural quality rather than as a compulsive force. The result is genuine, warm, relationally generous love that also has real psychological depth and genuine transformative capacity without the power dynamics of harder aspects.`,
    friendship: `Genuinely deep in their care, psychologically perceptive, and capable of sustained transformative connection.`,
    romantic: `Partners find a quality of love that is both genuinely warm and genuinely profound, relationship that deepens rather than simply continues over time.`,
    feed: `The current sky is amplifying the natural alignment between love and transformative depth in this connection. The warmth and genuine psychological power that flows between these charts is more present and more accessible right now.`,
    sonic: `Venus's aesthetic warmth is expressed through Pluto's deep subterranean register without being overwhelmed in the trine. The beautiful harmonic language of Venus with Pluto's genuine depth beneath it in natural agreement. Listen for the quality of music where something beautiful is also genuinely deep, where the warmth and the transformative depth are the same quality.`,
  },

  PLUTO_VENUS_OPPOSITION: {
    key: 'PLUTO_VENUS_OPPOSITION', pair: 'PLUTO_VENUS', aspect: 'opposition', intensity: 'Very high',
    core: `Pluto, transformation through depth, the unconscious, and the regenerative destruction of what is no longer alive, stands at full polarity with Venus, love, beauty, and relational warmth. The opposition tends to externalize. The person encounters Pluto's transformative, power-oriented, depth-driving principle through partners and relationships, through loves that carry genuine depth and power, through people who seem to hold a kind of psychological power over the relational world, or through relational circumstances that force a fundamental transformation of what love means and what it is worth.`,
    behavioral: `Venus's warmth and relational beauty encounters Pluto's transformative force from outside, through partners who carry Plutonian depth and power, through loves that introduce genuine power dynamics into the relational field, or through the experience of love loss as a genuinely primal and transformative event. The developmental work is integrating Pluto's depth and transformative power as interior relational resources.`,
    friendship: `The most transformative friendships are those that carry genuine depth, genuine power dynamics, and the quality of relationship that leaves both people genuinely changed.`,
    romantic: `Partners who carry Plutonian depth and power can introduce the most profound and most demanding relational transformations, encounters with love that transforms at its root.`,
    feed: `Pluto's transit is illuminating both ends of the love-and-power axis in this connection today. The hidden power dynamics and transformative forces at work in this relationship are more visible right now than usual, and what becomes visible at this depth is both significant and irreversible.`,
    sonic: `Venus's rich, beautiful harmonic warmth keeps encountering Pluto's enormous subterranean force from across the compositional space in the opposition. Listen for the quality of music where something beautiful keeps encountering something of enormous depth from outside, where the warmth and the transformative power are in dialogue that changes both.`,
  },

  PLUTO_MARS_CONJUNCTION: {
    key: 'PLUTO_MARS_CONJUNCTION', pair: 'PLUTO_MARS', aspect: 'conjunction', intensity: 'Extreme',
    core: `Pluto, the transpersonal principle of transformation through depth, the destruction of what is no longer genuinely alive, and the encounter with the most primal compulsive unconscious forces, fuses with Mars, the planet governing raw drive, assertion, the instinct to pursue and defend, and the force that moves the person toward what they want and away from what threatens them. When these two occupy the same degree, drive and the most primal transformative power become one system. The Mars impulse toward pursuit and assertion has been fused with Pluto's compulsive, depth-driving, power-oriented transformative force. What results is perhaps the most intensely powerful drive configuration available in the natal chart: a person whose assertive force is not merely strong but is driven from the deepest levels of the unconscious, whose will operates with a quality of necessity and compulsion that makes ordinary human assertion seem comparatively lightweight.`,
    behavioral: `The person does not experience their drive as merely personal. It feels like something is working through them, something larger and darker and more necessary than ordinary desire. The result is formidable, even frightening power when the drive is activated. The ability to pursue goals with an intensity and persistence that others cannot match, to survive encounters that would destroy less deeply powered configurations, and a quality of personal force that others feel as genuinely significant presence. The shadow requires full naming: the same compulsive power that makes this person formidable can express as controlling behavior, as the use of power over others rather than power in service of genuine goals, as an inability to release what has been pursued once the genuine goal has been reached, and as a quality of ruthlessness in the exercise of the drive that requires the most rigorous conscious discipline to keep in genuine service of ethical purpose.`,
    friendship: `Friends experience a person of extraordinary drive and genuine power who can be a formidable ally and whose presence is never quite neutral. The Pluto-Mars force field is simply too significant to be genuinely invisible.`,
    romantic: `Partners often describe the experience of being in relationship with someone whose will and drive carry a quality of genuine inevitability, whose pursuit is total, whose passion is genuine, and whose power requires the partner to have a strong enough center of their own to remain genuinely themselves within the relational field.`,
    feed: `Pluto's transit is activating the deepest drive forces in this connection right now. Something in the power dynamics and the most primal assertive forces between these charts is more active and more close to the surface today than usual, and how that power is directed matters significantly.`,
    sonic: `Mars's physical, driving force and Pluto's subterranean necessity are the same sound in the conjunction. The driving Martian pulse under Pluto's enormous subterranean weight, the incisive Martian energy saturated with Pluto's chromatic density, the directional Martian force driven from depths far below conscious intention. The rhythm is both physically driving like Mars and relentlessly inevitable like Pluto, unstoppable in a way that exceeds mere force. Listen for the quality of music where the rhythm arrives with such inevitability and such subterranean weight that resistance seems genuinely futile, where the force is both physical and deeply underground, both assertive and compulsive.`,
  },

  PLUTO_MARS_SEXTILE: {
    key: 'PLUTO_MARS_SEXTILE', pair: 'PLUTO_MARS', aspect: 'sextile', intensity: 'Medium',
    core: `Pluto, transformation, depth, and the regenerative unconscious, and Mars, drive, assertion, and the force that converts desire into action, are in a 60-degree relationship of easy, productive cooperation. The person has genuine access to Pluto's transformative depth and power as resources that sustain and deepen the Mars drive without the compulsive intensity the conjunction produces. The drive operates with genuine depth behind it and sufficient conscious access to direct it strategically.`,
    behavioral: `Mars can pursue with Pluto's depth and power available as a resource without being compulsively driven by them. The result is formidable, strategically accessible drive supported by genuine psychological depth.`,
    friendship: `Formidably reliable in their commitments, genuinely powerful in their support, and capable of sustaining effort through genuine difficulty.`,
    romantic: `Partners find a quality of genuine depth of drive and commitment that makes the relationship feel substantive and reliably supported.`,
    feed: `Today's transit is opening the productive channel between deep drive and strategic power in this connection. There is a quality of genuine formidable purpose and transformative direction available between these charts right now.`,
    sonic: `Mars's drive is supported by Pluto's depth without the compulsive overwhelm in the sextile. Listen for the quality of music where something driven also sounds genuinely powerful from within, where the assertive force and the subterranean depth are in natural agreement.`,
  },

  PLUTO_MARS_SQUARE: {
    key: 'PLUTO_MARS_SQUARE', pair: 'PLUTO_MARS', aspect: 'square', intensity: 'Extreme',
    core: `Pluto, the principle of transformation through depth and the compulsive unconscious force that destroys what is no longer alive, meets Mars, raw drive, assertion, and the force that moves the person toward what they want, at a 90-degree angle of profound, sustained, compulsive tension. Pluto compels the transformation of the assertive function itself. Mars knows what it wants. Pluto insists that the wanting is shaped by unconscious forces far deeper than the conscious drive can access or control. Mars pursues. Pluto makes the pursuit compulsive, makes the target seem absolutely necessary, and makes the experience of obstruction feel like a confrontation with the forces that govern life and death rather than merely an obstacle to an ordinary goal.`,
    behavioral: `Mars's natural drive has been given a Plutonian quality of unconscious compulsion. This person does not merely want things. They are driven toward them with a force that exceeds ordinary conscious motivation and that cannot simply be reduced or redirected through ordinary willpower. The behavioral consequences are significant: cycles of intense, compulsive pursuit followed by encounters with the shadow dimensions of the drive, with what the compulsive pursuit was actually in service of at the unconscious level, that force genuine confrontation with the power dynamics the drive has created. The development task is the most demanding in the library: bringing the Plutonian dimension of the drive into genuine conscious awareness and redirecting it from compulsive unconscious expression toward genuinely conscious, ethical, purposeful use of the enormous power this configuration carries.`,
    friendship: `Friends experience a person of formidable drive and genuine power whose intensity can be a remarkable resource and whose compulsive dimension requires conscious navigation to sustain healthy relational dynamics.`,
    romantic: `Partners experience one of the most intensely demanding relational configurations. The drive and passion are completely genuine, the power dynamic requires the most conscious attention, and the transformation that the relationship produces in both people is genuinely significant.`,
    feed: `Pluto's transit is pressing on the deepest and most compulsive drive forces in this connection right now. The hidden power dynamics and the most primal assertive forces at work between these charts are more visible today than usual, and what becomes visible at this depth cannot simply be put back below.`,
    sonic: `Pluto's extreme chromatic density, subterranean inevitability, and relentless pulse are in extreme tension with Mars's requirement for strategic precision and clear directional force in the square. The site of the conflict is the rhythm: Mars's driving downbeat is constantly in tension with Pluto's relentless inevitability, producing a pulse that feels both driven and compelled simultaneously. Enormous force present but unable to move purely according to strategic plan. Listen for the quality of music where something driven is also compelled from depths far beyond ordinary motivation, where the force and the compulsion are both completely present and in sustained tension with each other.`,
  },

  PLUTO_MARS_TRINE: {
    key: 'PLUTO_MARS_TRINE', pair: 'PLUTO_MARS', aspect: 'trine', intensity: 'Medium',
    core: `Pluto and Mars are in the same elemental family, separated by 120 degrees. Drive and transformative depth are not in tension here. They inform each other. The person's assertive function is naturally supported by Pluto's depth and power as integrated qualities rather than as forces in compulsive tension. The drive is formidable and its orientation toward genuinely significant rather than merely ordinary goals is natural.`,
    behavioral: `Mars can pursue with genuine depth and power as natural qualities of the drive rather than as compulsive forces. The result is formidable, strategically grounded drive with genuine transformative capacity and sufficient conscious access.`,
    friendship: `Formidably reliable, genuinely powerful in their commitments, and capable of pursuing shared goals with the full depth of Plutonian motivation behind them.`,
    romantic: `Partners find a quality of genuine depth of drive and transformative passion that makes the relationship feel both substantive and alive.`,
    feed: `The current sky is amplifying the natural alignment between drive and transformative depth in this connection. The genuine power and depth of purpose available between these charts is more naturally directed right now.`,
    sonic: `Mars's energetic drive is expressed through Pluto's deep subterranean register without the compulsive overwhelm in the trine. The physical force and the transformative depth in natural agreement. Listen for the quality of music where something physically driven is also genuinely powerful from within, where the force and the depth are the same quality.`,
  },

  PLUTO_MARS_OPPOSITION: {
    key: 'PLUTO_MARS_OPPOSITION', pair: 'PLUTO_MARS', aspect: 'opposition', intensity: 'Very high',
    core: `Pluto, transformation through depth, the unconscious, and the regenerative destruction of what is no longer alive, stands at full polarity with Mars, raw drive, assertion, and the force that moves toward what is wanted. The opposition tends to externalize. The person encounters Pluto's transformative, power-oriented, compulsive principle through external forces, through power struggles with others, through opponents who carry a Plutonian quality of depth and compulsion, or through circumstances that force the Mars drive into confrontation with forces far more powerful than ordinary strategic opposition.`,
    behavioral: `The Mars drive's strategic approach keeps encountering Pluto's transformative power from outside. The developmental work is integrating Pluto's depth and power as genuine interior resources that direct the Mars drive rather than forces encountered only through external power struggles.`,
    friendship: `The most transformative and occasionally most difficult collaborative relationships are those that involve genuine power dynamics, where Plutonian depth and compulsive force meet the Mars drive in ways that require conscious navigation.`,
    romantic: `Partners who carry genuine Plutonian power can introduce the most significant transformations of the Mars drive, encounters with force that changes what the drive is in service of.`,
    feed: `Pluto's transit is illuminating both ends of the drive-and-power axis in this connection today. The hidden power dynamics and compulsive forces at work between these charts are more visible right now than usual, and the depth of what is being negotiated between these two people deserves full conscious attention.`,
    sonic: `Mars's physical, incisive directional force keeps encountering Pluto's enormous subterranean power from across the compositional space in the opposition. Listen for the quality of music where something driven keeps encountering something of enormous transformative power from the outside, where the strategic force and the compulsive depth are in dialogue that changes both.`,
  },

} as const;
