/**
 * Astradio Insight Library — Neptune Aspects to Personal Planets (Batch 2)
 *
 * 20 objects: NEPTUNE × SUN, MOON, VENUS, MARS × 5 aspects
 * Place at: vnext/projection/insight-library/insight-library-aspects-neptune.ts
 */

import type { AspectInsight } from './insight-library-types';

export const NEPTUNE_ASPECT_INSIGHTS: Readonly<Record<string, AspectInsight>> = {

  NEPTUNE_SUN_CONJUNCTION: {
    key: 'NEPTUNE_SUN_CONJUNCTION', pair: 'NEPTUNE_SUN', aspect: 'conjunction', intensity: 'Very high',
    core: `Neptune, the transpersonal principle of dissolution, transcendence, the blurring of boundaries between self and other, spiritual longing, and the oceanic feeling that precedes and follows individual consciousness, fuses with the Sun, the seat of conscious identity and the purposeful drive toward self-expression. When these two occupy the same degree, identity and dissolution become one system. This person does not experience the ego's boundaries as firmly fixed. The self is always, at some level, in the process of dissolving into something larger than its individual form. What this produces is a person of extraordinary imaginative depth, genuine spiritual sensitivity, and creative capacity that accesses dimensions of experience that more boundaried ego structures cannot reach. It also produces a person for whom the question of who they actually are, separate from everyone and everything around them, can be genuinely difficult to answer.`,
    behavioral: `The ego's boundaries between self and world, between personal identity and collective experience, between the actual and the imagined, are constitutionally permeable rather than firmly drawn. The gifts are real: transcendent experience, creative and empathic capacity, spiritual depth. So is the shadow. The same porosity that enables transcendent experience also makes the ego vulnerable to boundary dissolution in ways that can be genuinely disorienting. The person may have difficulty distinguishing between what they actually feel and what they are absorbing from the emotional field around them, between who they actually are and who others need them to be, between genuine spiritual experience and the projections of an imagination that has no firm boundary against the world.`,
    friendship: `Friends experience a person with extraordinary empathic sensitivity and imaginative depth alongside a quality of personal elusiveness. This person is genuinely present and also somehow not quite fully defined, as if the full picture keeps dissolving slightly at its edges.`,
    romantic: `Partners often describe the experience of falling in love with someone who feels like the deepest possible version of what they were looking for, and then periodically wondering whether what they are in love with is the person or their own most beautiful projection of the person. Both are real questions. The Neptune-Sun person needs partners with enough groundedness to help them maintain contact with consensual reality.`,
    feed: `Neptune's transit is dissolving the edges of the identity structures in this connection right now. What each person thought they knew clearly about who they are in relation to the other is becoming more fluid today, and what becomes visible in that fluidity is worth attending to with both openness and discernment.`,
    sonic: `The Sun's natural clarity and purposefulness dissolve into Neptune's atmospheric register in the conjunction. The melodic lines begin with solar purpose and then lose their edges, blending into the harmonic texture rather than arriving at a clearly defined destination. The rhythm has the Sun's underlying consistency but Neptune has dissolved the hard edges of the beat. The harmonic language is major but refracted through Neptune's whole-tone ambiguity, familiar tonality seen through sea water. Listen for the quality of music where something purposeful seems to be moving forward and then discovers it is in open water, where the direction is real but the destination keeps dissolving before arrival, and the space itself becomes the content.`,
  },

  NEPTUNE_SUN_SEXTILE: {
    key: 'NEPTUNE_SUN_SEXTILE', pair: 'NEPTUNE_SUN', aspect: 'sextile', intensity: 'Low-medium',
    core: `Neptune, dissolution, transcendence, spiritual longing, and the blurring of boundaries, and the Sun, conscious identity and purposeful self-expression, are in a 60-degree relationship of easy, productive cooperation. The sextile places these two forces in compatible territories where Neptune's imaginative and spiritual depth and the Sun's purposeful self-expression can draw on each other without the identity dissolution that the conjunction produces. The person has genuine access to Neptune's imaginative, spiritual, and transcendent dimensions without losing the ego ground that allows them to function in the world.`,
    behavioral: `The Sun can draw on Neptune's imaginative depth and spiritual sensitivity as a genuine creative and empathic resource without being dissolved by it. The result is genuine imaginative richness, real spiritual sensitivity, and a quality of empathic attunement to others that is genuinely perceptive, alongside enough ego structure to remain grounded, to distinguish between their own experience and what they absorb from others, and to function effectively in the practical dimensions of life.`,
    friendship: `Genuinely empathic, imaginatively rich in their perspective, and spiritually attuned without the quality of elusiveness that harder Neptune aspects can produce.`,
    romantic: `Partners find a quality of genuine imaginative depth and empathic attunement that makes the relationship feel spiritually resonant without the boundary confusion that the Neptune-Sun conjunction can introduce.`,
    feed: `Today's transit is gently opening the channel between spiritual depth and purposeful expression in this connection. There is a quality of genuine imaginative resonance available between these charts right now that is worth fully receiving.`,
    sonic: `The Sun's directional clarity is supported by Neptune's imaginative harmonic depth without being dissolved by it in the sextile. The melodic lines have the Sun's purposeful direction and are colored by Neptune's atmospheric harmonic ambiguity. Listen for the quality of music where something purposeful moves through genuinely atmospheric harmonic space, where the direction is clear and the medium through which it moves has genuine spiritual depth.`,
  },

  NEPTUNE_SUN_SQUARE: {
    key: 'NEPTUNE_SUN_SQUARE', pair: 'NEPTUNE_SUN', aspect: 'square', intensity: 'High',
    core: `Neptune, dissolution, transcendence, the blurring of boundaries, and the oceanic principle, meets the Sun, conscious identity and the drive toward purposeful, clear self-expression, at a 90-degree angle of genuine, sustained tension. Neptune dissolves the ego's attempts at clear self-definition. The Sun builds identity. Neptune makes that identity permeable. The Sun seeks clarity about who it is. Neptune ensures that the question of who it is remains genuinely open. The 90-degree angle means neither force simply yields, and the person experiences a recurring tension between the Sun's legitimate need for coherent identity and Neptune's equally powerful insistence that the self is always more fluid, more permeable, and more mysterious than any fixed definition can contain.`,
    behavioral: `The Sun's natural drive toward stable, purposeful self-expression keeps encountering Neptune's insistence that the established identity is always only a partial truth, that there is something larger, more fluid, and more mysterious behind the surface the ego has constructed. This produces a person who periodically finds that the identity they have carefully constructed becomes permeable, that the self they thought they knew becomes unclear, and that a period of genuine formlessness precedes the emergence of the next more expanded version of who they are. The Neptune-Sun square is associated with significant creative and spiritual development precisely because of this recurring cycle of identity dissolution and re-formation.`,
    friendship: `Friends experience a person whose identity seems to move through periods of unusual clarity and periods of genuine dissolution. Someone who can be fully present and also periodically in the middle of a process of self-revision that makes them temporarily less available.`,
    romantic: `Partners may find this person's periodic identity dissolutions genuinely challenging. The person they were relating to becomes temporarily unclear, and the relationship has to hold that uncertainty while the next version of the self precipitates.`,
    feed: `Neptune's transit is pressing on the tension between self-clarity and self-dissolution in this connection right now. Something about how each person understands their own identity within this relationship is becoming less clearly defined today, and what becomes visible in that increased fluidity is significant.`,
    sonic: `The Sun's melodic lines set off with solar purpose and are gradually absorbed into Neptune's atmospheric harmonic medium in the square. The phrase loses its edges as it moves, the destination it was heading toward becoming less clearly defined as the harmonic atmosphere grows denser. The rhythm has the Sun's underlying consistency being dissolved by Neptune's atmospheric quality. Listen for the quality of music where something purposeful moves into genuinely dissolving harmonic space, where the direction becomes less certain as the music develops, and the formlessness itself begins to carry its own meaning.`,
  },

  NEPTUNE_SUN_TRINE: {
    key: 'NEPTUNE_SUN_TRINE', pair: 'NEPTUNE_SUN', aspect: 'trine', intensity: 'Low-medium',
    core: `Neptune, dissolution, transcendence, and the blurring of boundaries, and the Sun, conscious identity and purposeful self-expression, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces are naturally aligned. Neptune's imaginative and spiritual depth and the Sun's purposeful self-expression move in the same direction without the dissolution of harder aspects. The person has natural access to Neptune's transcendent, imaginative, and empathic dimensions as an integrated quality of their identity rather than as a force that periodically dissolves it.`,
    behavioral: `The Sun can express itself through Neptune's imaginative and spiritual register naturally, without the ego boundary dissolution that the conjunction produces or the recurring identity crisis that the square introduces. The result is genuine creative imagination, real spiritual sensitivity, and a quality of empathic attunement that is both perceptive and grounded. Someone for whom the transcendent dimensions of experience are naturally accessible rather than threatening.`,
    friendship: `Genuinely imaginative, spiritually attuned, and empathically perceptive in ways that make their presence feel both grounded and somewhat larger than ordinary.`,
    romantic: `Partners find a quality of genuine imaginative depth and spiritual resonance that makes the relationship feel meaningful at a level beyond the ordinary.`,
    feed: `The current sky is amplifying the natural integration of imaginative depth and purposeful expression in this connection. The spiritual resonance and creative quality that runs between these charts is more present and more accessible right now.`,
    sonic: `The Sun's purposeful melodic direction moves through Neptune's imaginative atmospheric register without dissolution in the trine. The harmonic language is major but seen through Neptune's characteristic harmonic depth, familiar tonality with an atmospheric quality that gives it genuine spiritual resonance. Listen for the quality of music where something purposeful also sounds genuinely deep, where the direction is clear and the harmonic space it moves through has a quality of spiritual translucence.`,
  },

  NEPTUNE_SUN_OPPOSITION: {
    key: 'NEPTUNE_SUN_OPPOSITION', pair: 'NEPTUNE_SUN', aspect: 'opposition', intensity: 'High',
    core: `Neptune, dissolution, transcendence, and the blurring of boundaries between self and other, stands at full polarity with the Sun, conscious identity and the drive toward purposeful self-expression. At 180 degrees, these two forces are in dialogue across an axis of maximum tension between individual definition and oceanic dissolution. The opposition tends to externalize. The person encounters Neptune's dissolving, transcendent principle through other people and through life circumstances, through relationships that introduce a quality of boundary dissolution, or through the experience of being idealized or confused with something other than who they actually are.`,
    behavioral: `The ego's clear self-definition keeps encountering situations, people, or circumstances that make that self-definition temporarily less clear, that introduce the oceanic feeling, the merging, the beautiful confusion of where the self ends and the other begins. The developmental work is integrating the Neptunian capacity for transcendence, compassion, and imaginative depth as an interior quality rather than something that must always be encountered through the dissolving pressure of the external world.`,
    friendship: `The most spiritually significant and potentially disorienting friendships are often those that introduce a quality of boundary dissolution, where the friendship has a quality of something larger than ordinary human connection.`,
    romantic: `Partners who carry a significant Neptune quality, who are idealized, who introduce a quality of oceanic merging, or who make it difficult to maintain clear ego boundaries, can be among the most transcendent and most confusing relationship experiences.`,
    feed: `Neptune's transit is illuminating both ends of the identity-dissolution axis in this connection today. How each person's presence is dissolving and expanding the other's sense of self is more visible between these charts right now, and the question of what is genuinely real here deserves careful attention.`,
    sonic: `The Sun's clear, forward-moving melodic statements keep encountering Neptune's atmospheric, boundary-dissolving harmonic medium from across the compositional space in the opposition. The direction is real and the dissolution is also real, and neither can simply ignore the other. Listen for the quality of music where something purposeful keeps encountering something that dissolves its edges from outside, where the clarity and the oceanic formlessness are in dialogue across a real distance.`,
  },

  NEPTUNE_MOON_CONJUNCTION: {
    key: 'NEPTUNE_MOON_CONJUNCTION', pair: 'NEPTUNE_MOON', aspect: 'conjunction', intensity: 'Very high',
    core: `Neptune, the transpersonal principle of dissolution, transcendence, spiritual longing, and the oceanic feeling, fuses with the Moon, the keeper of emotional instinct, memory, interior safety, and the body's fundamental need for nourishment and comfort. When these two occupy the same degree, emotional experience and dissolution become one system. This is among the most emotionally porous configurations a natal chart can carry. The Moon's natural emotional instinct has been fused with Neptune's dissolving principle. The result is a person whose emotional interior is in constant, gentle, undefended contact with the emotional field of the world around them. What others feel, this person feels. Where others suffer, this person aches. Where others experience beauty, this person is moved.`,
    behavioral: `The emotional attachment system has been opened to the collective rather than remaining bounded by the personal. The gifts are extraordinary: compassionate capacity, genuine spiritual sensitivity, a depth of emotional resonance that others experience as genuinely healing. The challenge is equally real. This person must consciously develop the capacity to distinguish between what they actually feel and what they are absorbing from the emotional atmosphere around them. The Moon-Neptune conjunction person can be chronically unable to locate their own emotional ground because it is perpetually mixed with the emotional ground of everyone they are close to.`,
    friendship: `Friends experience a person of extraordinary empathic depth and genuine compassionate presence alongside a quality of emotional boundlessness that can make it difficult to know where this person's emotional experience ends and their absorption of others' experience begins.`,
    romantic: `Partners often describe the experience of feeling profoundly emotionally understood and also, over time, uncertain whether the person they are with has a sufficiently stable emotional self to sustain genuine mutual relationship rather than compassionate merging.`,
    feed: `Neptune's transit is dissolving the emotional boundaries in this connection right now. What each person feels is becoming less clearly their own and more part of a shared emotional field between these charts today. What flows in that shared space is worth attending to with both openness and care.`,
    sonic: `The Moon's emotional depth and Neptune's atmospheric dissolution are indistinguishable in the conjunction. The harmonic language is modal and whole-tone simultaneously, the rhythm breathes and dissolves at its edges simultaneously, and the melodic quality is the Moon's instinctive returning motion blurred into Neptune's tendency to disappear into the harmonic medium. Listen for the quality of music where you cannot locate yourself inside or outside the sound, where the emotional content and the atmospheric medium are the same thing, and the distinction between what is feeling and what is being felt dissolves completely.`,
  },

  NEPTUNE_MOON_SEXTILE: {
    key: 'NEPTUNE_MOON_SEXTILE', pair: 'NEPTUNE_MOON', aspect: 'sextile', intensity: 'Low-medium',
    core: `Neptune, dissolution, transcendence, and compassionate merging, and the Moon, emotional instinct, interior need, and the body's requirement for safety, are in a 60-degree relationship of easy, productive cooperation. The person has genuine access to Neptune's compassionate, spiritually sensitive, imaginative dimension of emotional experience without losing the Moon's instinctive emotional grounding.`,
    behavioral: `The Moon can feel with Neptune's depth and compassion available as a resource without the ego boundary dissolution that the conjunction produces. The result is genuine empathic sensitivity, real compassionate attunement, and a quality of emotional depth that others find both genuinely perceptive and grounded enough to be reliably present.`,
    friendship: `Genuinely empathic, compassionately attuned, and emotionally deep without the boundary confusion that harder Neptune-Moon aspects can produce.`,
    romantic: `Partners find a quality of genuine emotional depth and compassionate attunement that makes the relationship feel emotionally spacious and spiritually resonant.`,
    feed: `Today's transit is gently opening the channel between emotional depth and compassionate attunement in this connection. The quality of genuine feeling and empathic resonance available between these charts right now is worth fully receiving.`,
    sonic: `The Moon's emotional instinct is colored by Neptune's atmospheric depth without being dissolved by it in the sextile. The harmonic language is warm and gently atmospheric, emotionally felt and also translucent. Listen for the quality of music where something deeply feeling also sounds genuinely spacious, where the emotional warmth and the atmospheric depth are supporting each other.`,
  },

  NEPTUNE_MOON_SQUARE: {
    key: 'NEPTUNE_MOON_SQUARE', pair: 'NEPTUNE_MOON', aspect: 'square', intensity: 'High',
    core: `Neptune, dissolution, transcendence, and the blurring of boundaries, meets the Moon, emotional instinct, interior safety, and the body's fundamental need for comfort and nourishment, at a 90-degree angle of profound, sustained tension. Neptune dissolves the Moon's attempts at emotional stability and self-protection. The Moon seeks familiarity, safety, and the firm interior ground of its own emotional self. Neptune makes that ground permeable, then translucent, then uncertain. The 90-degree angle means neither force simply yields, and the person experiences a recurring tension between the Moon's genuine need for interior emotional safety and Neptune's insistence that the emotional self is always more fluid, more connected to the collective, and more mysterious than any fixed emotional configuration can contain.`,
    behavioral: `The Moon's natural drive toward emotional familiarity and interior safety keeps encountering Neptune's insistence that the emotional self is not as clearly bounded as the Moon requires it to be. The feelings it is experiencing may not be entirely its own. The emotional ground it has established may be more permeable than it appears. This produces a person whose emotional life is characterized by recurring cycles of establishing emotional ground and then experiencing the dissolution of that ground. The Neptune-Moon square person may turn to various forms of escapism or idealizing fantasy as the Moon's need for safety meets Neptune's tendency to make the actual emotional field uncertain.`,
    friendship: `Friends experience a person with deep emotional resonance and compassionate attunement alongside a quality of emotional instability or boundary permeability that can make the friendship emotionally complex to navigate.`,
    romantic: `Partners may find this person's emotional world genuinely challenging to be in sustained relationship with. The emotional ground keeps shifting as Neptune's dissolving principle repeatedly makes the Moon's emotional self-definition less certain.`,
    feed: `Neptune's transit is pressing on the tension between emotional safety and emotional dissolution in this connection right now. Something in the emotional ground between these charts is becoming more permeable today, and what flows through that increased permeability deserves careful, grounded attention.`,
    sonic: `The Moon's breathing, returning quality keeps being drawn into Neptune's atmospheric dissolution in the square. The emotional phrase attempts to find its way back to familiar ground and discovers that the ground has become translucent, that what felt solid before now seems to have depth and uncertainty beneath it. Listen for the quality of music where something emotionally familiar keeps being drawn into genuinely atmospheric, boundary-dissolving harmonic space, where the instinct toward emotional safety keeps encountering something that makes the floor translucent.`,
  },

  NEPTUNE_MOON_TRINE: {
    key: 'NEPTUNE_MOON_TRINE', pair: 'NEPTUNE_MOON', aspect: 'trine', intensity: 'Low-medium',
    core: `Neptune, dissolution, transcendence, and compassionate merging, and the Moon, emotional instinct, interior need, and the body's requirement for safety, are in the same elemental family, separated by 120 degrees. The trine means these two forces are naturally aligned. Neptune's compassionate, spiritually attuned, boundary-dissolving quality and the Moon's emotional instinct move in the same direction without the tension of harder aspects. The person has natural access to genuine emotional depth, compassionate attunement, and spiritual emotional sensitivity as integrated qualities of their emotional character.`,
    behavioral: `The Moon can feel with Neptune's depth and compassion as natural qualities of the emotional field itself rather than as forces that dissolve the emotional ground from beneath. The result is genuine empathic attunement, real compassionate depth, and a quality of emotional resonance that is both perceptive and grounded.`,
    friendship: `Genuinely compassionate, emotionally deep, and spiritually attuned in ways that make their presence feel quietly sustaining and genuinely understanding.`,
    romantic: `Partners find a quality of emotional depth and compassionate attunement that makes the relationship feel emotionally meaningful at levels beyond the ordinary.`,
    feed: `The current sky is amplifying the natural integration of emotional depth and compassionate attunement in this connection. The quality of genuine feeling and spiritual resonance that moves between these charts is more present and more accessible right now.`,
    sonic: `The Moon's emotional instinct and Neptune's atmospheric depth flow in natural agreement in the trine. The harmonic language is modally rich and gently atmospheric, the rhythm breathes and also dissolves gently at its edges. Listen for the quality of music where something deeply feeling is also genuinely spacious and atmospheric, where the emotional depth and the spiritual translucence are the same quality.`,
  },

  NEPTUNE_MOON_OPPOSITION: {
    key: 'NEPTUNE_MOON_OPPOSITION', pair: 'NEPTUNE_MOON', aspect: 'opposition', intensity: 'High',
    core: `Neptune, dissolution, transcendence, and the blurring of boundaries, stands at full polarity with the Moon, emotional instinct, interior safety, and the body's fundamental need for comfort. The opposition tends to externalize. The person encounters Neptune's dissolving, boundary-blurring principle through emotionally significant others and through life circumstances, through relationships that introduce a quality of emotional merging, through people who carry a significant Neptunian quality, or through situations that make the established emotional self-definition temporarily uncertain.`,
    behavioral: `The emotional boundaries the Moon establishes keep encountering situations or people that make those boundaries permeable. Relationships where the Moon's emotional self becomes mixed with the other's, compassionate encounters that dissolve the protective boundaries the Moon normally maintains, or idealizations of emotionally significant others that make it difficult to see them clearly. The developmental work is integrating the Neptunian capacity for emotional transcendence, compassion, and spiritual depth as interior resources that the Moon can access without requiring external encounters to dissolve its protective boundaries.`,
    friendship: `The most emotionally significant and spiritually resonant friendships often involve people who introduce a quality of emotional boundary dissolution, where the friendship has a quality of emotional merging that is both deeply sustaining and occasionally disorienting.`,
    romantic: `Partners who carry a significant Neptunian quality, who are idealized, who introduce emotional merging, or who make the Moon's emotional boundaries permeable, can be among the most transcendent and most confusing relationship experiences.`,
    feed: `Neptune's transit is illuminating both ends of the emotional-dissolution axis in this connection today. How each person's emotional presence is making the other's emotional boundaries more permeable is more visible between these charts right now, and what flows in that shared emotional space deserves both openness and discernment.`,
    sonic: `The Moon's breathing, cyclical, emotionally grounded quality keeps encountering Neptune's atmospheric, boundary-dissolving harmonic medium from across the compositional space in the opposition. Listen for the quality of music where something emotionally instinctive keeps being drawn toward something atmospherically boundless from across a real distance, where the emotional ground and the oceanic dissolution are in dialogue.`,
  },

  NEPTUNE_VENUS_CONJUNCTION: {
    key: 'NEPTUNE_VENUS_CONJUNCTION', pair: 'NEPTUNE_VENUS', aspect: 'conjunction', intensity: 'Very high',
    core: `Neptune, the transpersonal principle of dissolution, transcendence, spiritual longing, and the blurring of boundaries between self and other, fuses with Venus, the planet governing love, aesthetic sensibility, relational value, and the capacity to draw beauty and connection toward oneself. When these two occupy the same degree, love and transcendence become one system. This person does not experience love as a bounded, ordinary human experience. They experience love as an encounter with the divine, with the infinite, with something that dissolves the separation between self and beloved into an oceanic experience of unity. What results is a person capable of an extraordinarily beautiful quality of love, deeply compassionate, genuinely selfless, aesthetically refined to the point of almost unbearable sensitivity, and also a person for whom the gap between the beloved as imagined and the beloved as they actually are can produce a specific kind of heartbreak that is unlike any other.`,
    behavioral: `Love is always partly an experience of yearning toward something beyond what is actually present. Venus reaches toward connection. Neptune ensures that what is reached for always retains a quality of the infinite that no actual person can fully embody. The love object is always partly a vessel for the Neptune projection, for the ideal of transcendent union, beauty, and compassionate merging that Neptune carries. The behavioral consequence is a recurring cycle of idealization and disillusionment. This person falls in love with genuine depth and beauty, loves with genuine selflessness and compassionate attunement, and then, as the Neptune projection meets the actual human being, experiences a quality of disappointment that is not about the other person's failure but about the structural gap between what Neptune projects and what any actual human being can be. The development task is not suppressing the Neptune capacity for transcendent love. It is learning to love the actual person alongside the projection.`,
    friendship: `Friends experience extraordinary compassionate warmth and genuine aesthetic attunement alongside a quality of idealization that can occasionally make the friendship carry more spiritual weight than any ordinary human connection quite can.`,
    romantic: `Partners often describe the experience of being loved by this person as the most beautiful experience of their lives, and also, over time, the experience of being unable to fully meet the transcendent quality of what this person's love requires. Both the beauty and the difficulty are real.`,
    feed: `Neptune's transit is dissolving the boundaries between love and transcendence in this connection right now. What each person feels about the other is becoming more idealized, more merged, and more spiritually resonant today than it usually is. What becomes visible in that heightened register is worth receiving with both openness and grounded discernment.`,
    sonic: `Venus's natural harmonic warmth is dissolved by Neptune into something that no longer has hard tonal edges in the conjunction. The beautiful chords are present and also floating, the voice leading is graceful and also gradually losing its harmonic floor. The rhythm has Venus's graceful quality dissolved by Neptune's atmospheric formlessness. The music moves with beauty and without ground simultaneously. Listen for the quality of music that sounds like the most beautiful thing you have ever heard and also like you cannot quite locate yourself inside it, where the beauty is real and the dissolution of the self inside that beauty is also real.`,
  },

  NEPTUNE_VENUS_SEXTILE: {
    key: 'NEPTUNE_VENUS_SEXTILE', pair: 'NEPTUNE_VENUS', aspect: 'sextile', intensity: 'Low-medium',
    core: `Neptune, dissolution, transcendence, and spiritual longing, and Venus, love, aesthetic sensibility, and relational warmth, are in a 60-degree relationship of easy, productive cooperation. The person has genuine access to Neptune's transcendent, spiritually attuned, aesthetically refined dimension of relational experience without losing the relational ground that allows them to sustain genuine connection with actual people.`,
    behavioral: `Venus can express love with Neptune's compassionate depth and aesthetic refinement available as genuine resources without the idealization pattern that the conjunction produces. The result is genuine aesthetic sensitivity, real compassionate attunement, and a quality of relational beauty that others find both genuinely lovely and sufficiently grounded.`,
    friendship: `Genuinely warm with a quality of aesthetic and spiritual refinement that makes their presence feel both beautiful and real.`,
    romantic: `Partners find a quality of genuine aesthetic beauty and compassionate attunement that makes the relationship feel both warm and spiritually resonant.`,
    feed: `Today's transit is gently opening the channel between love and transcendent beauty in this connection. There is a quality of genuine aesthetic and spiritual resonance available between these charts right now.`,
    sonic: `Venus's beauty is given Neptune's atmospheric depth without the dissolution of harder aspects in the sextile. The harmonic language is warm and also gently translucent. Listen for the quality of music where something beautiful also sounds genuinely deep, where the warmth and the atmospheric quality are supporting each other.`,
  },

  NEPTUNE_VENUS_SQUARE: {
    key: 'NEPTUNE_VENUS_SQUARE', pair: 'NEPTUNE_VENUS', aspect: 'square', intensity: 'High',
    core: `Neptune, dissolution, transcendence, and the blurring of what is real and what is imagined, meets Venus, love, beauty, relational warmth, and the desire for genuine sustained connection, at a 90-degree angle of profound, sustained tension. Neptune insists that love is a transcendent, boundary-dissolving experience that points toward the infinite. Venus insists that love is a warm, aesthetically beautiful, genuinely relational experience between two real people. These requirements are not naturally compatible. The 90-degree angle means neither force simply yields, and the person experiences a recurring tension between the Venus desire for genuine, sustained, warm relational connection with an actual person and Neptune's insistence that love always points beyond the actual toward the ideal.`,
    behavioral: `This person is aware, at some level, that they are projecting the Neptune ideal onto Venus objects, and also aware that the Venus need for genuine, warm, sustained connection with an actual person is not being fully met by the idealized image. The development task is developing the capacity to love what is actually present, to bring Neptune's compassion and spiritual depth into contact with the actual person rather than with the image of the person, while also honoring the genuine beauty that Neptune's vision makes visible.`,
    friendship: `Friends experience extraordinary empathic warmth alongside a quality of idealization that can make the friendship feel like it is carrying a weight of projected transcendence that makes ordinary human friendship feel inadequate by comparison.`,
    romantic: `Partners experience one of the most complex relational configurations. The love is genuinely beautiful and genuinely transcendent, and the gap between the idealized beloved and the actual person is a recurring source of both creative longing and genuine heartbreak.`,
    feed: `Neptune's transit is pressing on the tension between love's transcendent quality and love's relational reality in this connection right now. The gap between the ideal of what this connection could be and the reality of what it is is more visible today, and both dimensions are worth attending to.`,
    sonic: `Venus reaches toward beautiful, resolved harmonic destinations. Neptune dissolves the harmonic ground before the arrival can fully occur in the square. The rhythm has Venus's graceful quality being dissolved by Neptune's atmospheric formlessness. The music is trying to be both beautiful and boundless simultaneously, and the tension between those two imperatives is the primary emotional content. Listen for the quality of music where something is trying to be both genuinely beautiful and genuinely transcendent at the same time, where the warmth keeps being drawn into the infinite and the infinite keeps finding itself wanting the warmth.`,
  },

  NEPTUNE_VENUS_TRINE: {
    key: 'NEPTUNE_VENUS_TRINE', pair: 'NEPTUNE_VENUS', aspect: 'trine', intensity: 'Low-medium',
    core: `Neptune and Venus are in the same elemental family, separated by 120 degrees. Love and transcendence are not in tension here. They inform each other. The person's capacity for genuine warmth and their natural orientation toward spiritual beauty and compassionate merging are harmoniously integrated. They can love with genuine transcendent depth without the idealization cycle that the conjunction or square produces.`,
    behavioral: `Venus can express love with Neptune's compassionate depth and aesthetic refinement as integrated natural qualities rather than as forces in tension. The result is genuine relational warmth expressed with real spiritual beauty and compassionate attunement.`,
    friendship: `Genuinely warm, aesthetically refined, and compassionately attuned in ways that make their relational presence feel both beautiful and spiritually real.`,
    romantic: `Partners find a quality of love that is both genuinely warm and genuinely transcendent, relationship that feels both emotionally present and spiritually meaningful.`,
    feed: `The current sky is amplifying the natural integration of love and transcendent beauty in this connection. The warmth and spiritual quality that flows between these charts is more present and more accessible right now.`,
    sonic: `Venus's aesthetic warmth is expressed through Neptune's atmospheric register without dissolution in the trine. The harmonic language is both warm and gently translucent, the beauty real and also has depth. Listen for the quality of music where something is genuinely beautiful and also genuinely atmospheric, where the warmth and the depth are the same quality.`,
  },

  NEPTUNE_VENUS_OPPOSITION: {
    key: 'NEPTUNE_VENUS_OPPOSITION', pair: 'NEPTUNE_VENUS', aspect: 'opposition', intensity: 'High',
    core: `Neptune, dissolution, transcendence, and the longing for what lies beyond ordinary reality, stands at full polarity with Venus, love, beauty, and relational warmth. The opposition tends to externalize. The person encounters Neptune's idealized, dissolving, transcendent quality through partners and relationships that introduce a quality of projected transcendence, through people who seem to embody the ideal, through loves that feel fated or spiritually significant, or through relationships that introduce a quality of beautiful confusion about what is real and what is projected.`,
    behavioral: `Venus's warm, relational attachment keeps encountering Neptune's idealizing, boundary-dissolving principle from outside. The developmental work is integrating the Neptunian capacity for transcendent love and aesthetic beauty as an interior resource, learning to bring that depth into contact with actual people rather than requiring extraordinary external Neptunian experiences to access it.`,
    friendship: `The most spiritually significant friendships often carry a quality of idealization or transcendent projection, where the friendship has a quality of something larger than ordinary human connection.`,
    romantic: `Partners who seem to embody the ideal, who are idealized, mysterious, or who introduce a quality of boundary dissolution, can be among the most transcendent and most confusing relationship experiences.`,
    feed: `Neptune's transit is illuminating both ends of the love-and-transcendence axis in this connection today. How each person's presence is activating the other's capacity for idealization and transcendent longing is more visible between these charts right now.`,
    sonic: `Venus's rich, beautiful harmonic warmth keeps encountering Neptune's atmospheric dissolution from across the compositional space in the opposition. The beauty is real and the formlessness is also real, and they are pulling in opposite directions. Listen for the quality of music where something beautiful keeps being dissolved by something boundless from outside, where the warmth keeps encountering the infinite.`,
  },

  NEPTUNE_MARS_CONJUNCTION: {
    key: 'NEPTUNE_MARS_CONJUNCTION', pair: 'NEPTUNE_MARS', aspect: 'conjunction', intensity: 'Very high',
    core: `Neptune, the transpersonal principle of dissolution, transcendence, the blurring of boundaries, and spiritual longing, fuses with Mars, the planet governing raw drive, assertion, the instinct to pursue and defend, and the force that moves the person toward what they want. When these two occupy the same degree, drive and dissolution become one system. The Mars impulse toward clear, direct, strategic pursuit has been dissolved by Neptune's permeating quality. The drive is real but its direction is not always clear, its targets are not always visible in the ordinary sense, and its relationship to conventional strategic reality is genuinely uncertain. What this produces is a person whose drive is oriented toward the transcendent, the imagined, the compassionate, or the creatively visionary rather than toward ordinary tangible targets.`,
    behavioral: `Mars's natural clarity of purpose has been dissolved by Neptune into something that pursues the indefinite, the spiritual, the imaginative, or the compassionate rather than the clearly defined. This person can work with extraordinary dedication toward creative, spiritual, or compassionate goals that others may not be able to see clearly enough to pursue. They may also struggle with the kind of direct, assertive, strategic action that conventional life requires when it involves purely tangible, ordinary targets. The Neptune-Mars person's drive works best when it is in the service of something that transcends ordinary self-interest.`,
    friendship: `Friends experience a person with genuine compassionate energy and creative dedication who may be less reliably available for the kind of direct, strategic, practically-oriented action that ordinary collaborative projects require.`,
    romantic: `Partners experience a person whose drive and energy are oriented toward something beyond ordinary relational goals, whose passion is real and whose direction is not always immediately legible in conventional terms.`,
    feed: `Neptune's transit is dissolving the edges of the drive in this connection right now. What each person is pursuing in relation to the other is becoming less clearly defined today, and what becomes visible in that increased fluidity about direction and purpose is worth attending to carefully.`,
    sonic: `Mars's physical, incisive energy is present in the conjunction but its edges are not hard. The driving pulse is real but it moves through water rather than through air. The rhythm has Mars's underlying force with Neptune's dissolving quality. The beat is present and its edges are uncertain. The melodic lines want to be short and incisive like Mars but are drawn into Neptune's tendency to blur into the harmonic environment. Listen for the quality of music where something physically driven is also genuinely formless, where the force is present and the direction is atmospheric rather than clearly defined.`,
  },

  NEPTUNE_MARS_SEXTILE: {
    key: 'NEPTUNE_MARS_SEXTILE', pair: 'NEPTUNE_MARS', aspect: 'sextile', intensity: 'Low-medium',
    core: `Neptune, dissolution, transcendence, and imaginative depth, and Mars, drive, assertion, and the force that converts desire into action, are in a 60-degree relationship of easy, productive cooperation. The person's drive is naturally oriented toward creative, compassionate, or spiritually meaningful goals without the loss of strategic direction that the conjunction produces.`,
    behavioral: `Mars provides the energy. Neptune provides the orientation toward what is genuinely worth that energy, toward goals that transcend ordinary self-interest. The result is genuine drive expressed through creative, compassionate, or spiritually significant pursuits rather than conventional strategic targets.`,
    friendship: `Energizing in creative and compassionate collaborative contexts, and reliably oriented toward what is genuinely worth pursuing.`,
    romantic: `Partners find a quality of genuine creative passion and compassionate investment that makes the relationship feel meaningful.`,
    feed: `Today's transit is opening the channel between drive and creative or compassionate purpose in this connection. The energy and imaginative direction available between these charts right now is more aligned with something genuinely meaningful than usual.`,
    sonic: `Mars's drive is oriented by Neptune's imaginative depth without being dissolved by it in the sextile. Listen for the quality of music where something driven also sounds genuinely atmospheric and purposeful in a non-ordinary sense, where the force and the transcendent direction are supporting each other.`,
  },

  NEPTUNE_MARS_SQUARE: {
    key: 'NEPTUNE_MARS_SQUARE', pair: 'NEPTUNE_MARS', aspect: 'square', intensity: 'High',
    core: `Neptune, dissolution, transcendence, and the blurring of what is real and what is imagined, meets Mars, raw drive, assertion, and the force that wants to move toward clearly defined targets, at a 90-degree angle of genuine, sustained tension. Neptune dissolves Mars's strategic clarity. Mars knows what it wants and how to pursue it. Neptune makes the target uncertain, the path unclear, and the relationship between effort and outcome unpredictable. The 90-degree angle means neither force simply yields, and the person experiences a recurring tension between the Mars drive's need for clear targets and strategic clarity and Neptune's insistence that what is actually worth pursuing exceeds what ordinary strategic reality can clearly define.`,
    behavioral: `Mars commits to a pursuit. Neptune dissolves the target, the path, or the conviction that the ordinary strategic approach is the right one. The person may experience cycles of energetic commitment followed by a loss of conviction about the direction, not because the drive has failed but because Neptune's dissolving quality has made the target less clearly real. The development task is distinguishing between Neptune's genuine insight that some conventional strategic pursuits are not worth the Mars energy, and Neptune's tendency to dissolve all clear targets indiscriminately as part of its transcendent longing.`,
    friendship: `Friends experience a person with genuine energy and compassionate drive who may periodically find their strategic direction dissolving in ways that are disorienting to collaborative projects.`,
    romantic: `Partners experience a person whose drive and energy are real and whose direction is periodically unclear in ways that require the relationship to accommodate genuine strategic uncertainty.`,
    feed: `Neptune's transit is pressing on the tension between drive and strategic clarity in this connection right now. Something about what each person is actually pursuing in relation to the other is becoming less clearly defined today, and that increased ambiguity is itself revealing something important.`,
    sonic: `Mars wants to drive toward a defined target. Neptune dissolves the target before arrival in the square. The rhythm has Mars's physical drive being dissolved by Neptune's atmospheric quality. The force is present and the direction keeps becoming uncertain. Listen for the quality of music where something driven keeps losing its strategic direction in atmospheric dissolution, where the force is real and the clarity of what it is pursuing keeps being absorbed by something larger and more formless.`,
  },

  NEPTUNE_MARS_TRINE: {
    key: 'NEPTUNE_MARS_TRINE', pair: 'NEPTUNE_MARS', aspect: 'trine', intensity: 'Low-medium',
    core: `Neptune and Mars are in the same elemental family, separated by 120 degrees. Drive and transcendent purpose are not in tension here. They inform each other. The person's assertive function is naturally oriented toward creative, compassionate, or spiritually significant goals without the loss of strategic direction that the conjunction or square produces. The drive is genuine and its orientation toward what is beyond ordinary self-interest is also genuine.`,
    behavioral: `Mars can pursue what matters with Neptune's depth of purpose available as an integrated quality. The result is genuine drive expressed through creative, spiritual, or compassionate pursuits with enough directional clarity to actually reach what they are pursuing.`,
    friendship: `Genuinely energizing in creative and compassionate contexts, and reliably oriented toward what is worth pursuing.`,
    romantic: `Partners find a quality of creative passion and compassionate investment that makes the relationship feel genuinely meaningful.`,
    feed: `The current sky is amplifying the natural alignment between drive and transcendent purpose in this connection. The energy and creative or compassionate direction available between these charts is more naturally integrated right now.`,
    sonic: `Mars's energetic drive is expressed through Neptune's atmospheric register without dissolution in the trine. The force is present and its direction is creative and atmospheric rather than purely conventional. Listen for the quality of music where something driven also sounds genuinely transcendent in its purpose, where the force and the depth of what it is serving are the same quality.`,
  },

  NEPTUNE_MARS_OPPOSITION: {
    key: 'NEPTUNE_MARS_OPPOSITION', pair: 'NEPTUNE_MARS', aspect: 'opposition', intensity: 'High',
    core: `Neptune, dissolution, transcendence, and the blurring of what is real and what is imagined, stands at full polarity with Mars, raw drive, assertion, and the force that moves toward what is wanted. The opposition tends to externalize. The person encounters Neptune's dissolving, transcendent principle through external forces, through situations that make the Mars drive's targets uncertain, through people who introduce a quality of imaginative dissolution into the person's strategic plans, or through circumstances that consistently seem to redirect the Mars drive toward something other than what it was pursuing.`,
    behavioral: `The Mars drive's strategic approach keeps encountering Neptune's dissolving principle from outside. The developmental work is integrating the Neptunian capacity for creative, compassionate, and spiritually oriented purpose as an interior quality that guides the Mars drive rather than requiring external Neptunian encounters to redirect it.`,
    friendship: `The most creatively and compassionately significant collaborations often involve people who introduce a quality of transcendent purpose or imaginative dissolution into the person's strategic approach.`,
    romantic: `Partners who carry a significant Neptunian quality, who dissolve conventional strategic certainty or introduce imaginative depth, can redirect the Mars drive in significant and occasionally disorienting ways.`,
    feed: `Neptune's transit is illuminating both ends of the drive-and-dissolution axis in this connection today. How each person's presence is dissolving or redirecting the other's strategic drive is more visible between these charts right now.`,
    sonic: `Mars's physical, incisive directional force keeps encountering Neptune's atmospheric, dissolving harmonic medium from across the compositional space in the opposition. Listen for the quality of music where something driven keeps encountering something that dissolves its strategic edges from outside, where the force and the dissolution are in unresolved dialogue.`,
  },

} as const;
