/**
 * Astradio Insight Library — Saturn Aspects to Personal Planets (Batch 2)
 *
 * 20 objects: SATURN × SUN, MOON, VENUS, MARS × 5 aspects
 * Place at: vnext/projection/insight-library/insight-library-aspects-saturn.ts
 */

import type { AspectInsight } from './insight-library-types';

export const SATURN_ASPECT_INSIGHTS: Readonly<Record<string, AspectInsight>> = {

  SATURN_SUN_CONJUNCTION: {
    key: 'SATURN_SUN_CONJUNCTION', pair: 'SATURN_SUN', aspect: 'conjunction', intensity: 'High',
    core: `Saturn, the principle of structure, limitation, time, and earned authority, sits fused with the Sun, the seat of conscious identity and the purposeful drive toward self-expression. Saturn is not a cruel planet. It is a serious one. It makes things real by making them difficult, and when it fuses with the Sun at birth, the ego's development is shaped from the beginning by Saturn's particular form of demand. This person did not grow up feeling exempt from consequence. They grew up feeling that things had to be earned. Over time, and Saturn always works over time, that early weight builds into something genuinely rare: a self that has been tested, that knows its own limits, and that carries a quiet authority that more effortlessly expressive charts simply do not develop.`,
    behavioral: `The Saturn principle has been internalized so deeply into the ego that this person carries their own inner authority figure as part of the self. They are their own most demanding critic, their own most exacting judge of whether what they have produced or become is genuinely sufficient. The Sun's natural desire for recognition and expression is always being filtered through Saturn's test of whether that expression has truly been earned. In youth this often reads as seriousness, heaviness, or an inability to simply enjoy things without the shadow of responsibility making itself felt. In maturity, and this aspect genuinely improves with age in a way that few do, it produces a person of real weight and genuine authority. The risk is chronic self-suppression. The internalized Saturn can become so demanding that the Sun's legitimate need for joy, play, and spontaneous self-expression is indefinitely deferred in favor of more dutiful pursuits.`,
    friendship: `Friends experience this person as reliable, serious, and genuinely dependable. Someone whose word means something because they do not give it lightly. The warmth is real but measured. They do not perform enthusiasm they do not feel.`,
    romantic: `Partners often describe a sense of being in relationship with someone who takes the commitment very seriously, which is deeply sustaining when reciprocated and quietly suffocating when the partner needs more lightness. The development task is learning that joy is not a reward for completed duty but a legitimate need of the Sun itself.`,
    feed: `Saturn's transit is pressing directly on the identity structure of this connection. What is genuinely solid between these two charts is being tested right now, and what holds will hold for a long time.`,
    sonic: `Saturn's dense, structurally weighted minor harmony and measured deliberate cadence shape the Sun's natural brightness completely in the conjunction. The Sun's purposeful melodic statements are delivered at Saturn's pace: restrained, fully weighted at every step, reaching less far than they might but meaning every inch of what they do reach. The rhythm has the Sun's consistency but Saturn's gravity. Each beat carries more than its nominal value. The harmonic language is major but dark, the Sun's natural brightness compressed into something that sounds like light working through resistance. Listen for the quality of a melody that knows exactly where it is going and moves there with complete deliberateness, earning each step.`,
  },

  SATURN_SUN_SEXTILE: {
    key: 'SATURN_SUN_SEXTILE', pair: 'SATURN_SUN', aspect: 'sextile', intensity: 'Low-medium',
    core: `Saturn, structure, limitation, time, and earned authority, and the Sun, conscious identity and purposeful self-expression, are in a 60-degree relationship of easy, productive cooperation. The sextile does not fuse these forces as the conjunction does. It places them in neighboring territories that can draw on each other without generating weight. Saturn's discipline and the Sun's expressive drive are in natural dialogue here. The person's identity and their relationship to responsibility and long-term development are not at war. They are in conversation.`,
    behavioral: `The sextile creates a well-functioning reality principle. The ego's drive for self-expression and the internalized sense of structure and responsibility are in productive communication rather than in conflict. The Sun generates the creative and expressive impulse. Saturn evaluates it for structural viability and long-term sustainability without killing it. The result is a person with natural organizational capacity and a reliable sense of personal authority that does not require constant external validation.`,
    friendship: `Reliable, consistent, and genuinely trustworthy. Their commitments mean something. Not the most spontaneous presence, but the one you call when something actually matters.`,
    romantic: `Partners find a quality of seriousness and genuine investment in this person that makes the relationship feel substantial. The warmth is real and the commitment is meant.`,
    feed: `Today's transit is moving through the productive channel between structure and self-expression in this connection. What each person is building toward individually is touching how they show up for each other right now.`,
    sonic: `Saturn's measured deliberate cadence and structural harmonic weight support the Sun's expressive drive without compressing it in the sextile. The rhythm has the Sun's consistent forward motion and Saturn's measured weight in easy dialogue, purposeful without being heavy. The harmonic language moves between the Sun's major brightness and Saturn's structural depth in a way that feels grounded rather than oppressive. Listen for the quality of music that moves with both purpose and gravity, where the forward motion feels earned and the direction feels reliable.`,
  },

  SATURN_SUN_SQUARE: {
    key: 'SATURN_SUN_SQUARE', pair: 'SATURN_SUN', aspect: 'square', intensity: 'Very high',
    core: `Saturn, the principle of structure, limitation, and the testing of what is genuinely load-bearing, meets the Sun, conscious identity and the drive toward purposeful self-expression, at a 90-degree angle of profound, sustained tension. This is one of the most significant aspect configurations a natal chart can carry. The Sun wants to express, to be seen, to become. Saturn refuses to grant easy passage toward any of those things. The square places these two forces in a permanent state of mutual challenge: every act of self-expression the Sun attempts is evaluated by Saturn's standards of worthiness, discipline, and genuine competence. Neither force yields.`,
    behavioral: `Saturn sets standards that the Sun's natural self-expression consistently falls short of, producing a cycle of effort, self-critique, renewed effort, and occasional hard-won satisfaction that never quite settles into ease. The father archetype that Saturn represents in its demanding, evaluating, authority-conferring function is in tension with the hero-ego of the Sun, which is trying to establish its own legitimacy. The compensatory patterns vary: some Saturn-Sun square people become relentless achievers driven by the internalized demand. Others collapse under it and develop a profound ambivalence about pursuing visibility or authority at all. The gift, and it is a genuine gift despite the cost, is that people who have worked through the Saturn-Sun square carry an earned authority that no easier configuration produces.`,
    friendship: `Friends experience a quality of seriousness and personal responsibility that can feel both reassuring and occasionally heavy. This person takes their commitments seriously and expects the same from others, sometimes more than others are prepared to give.`,
    romantic: `Partners often encounter a person who finds it genuinely difficult to receive love without feeling they must earn it first. The development task is understanding that the Sun's legitimate need for warmth and appreciation does not require Saturn's permission.`,
    feed: `Saturn's transit is pressing directly on the self-expression and identity structures in this connection right now. What each person is being asked to prove, to build, or to let go of is touching the core of what this relationship means.`,
    sonic: `Saturn's dense, slow, structurally weighted harmonic language is in genuine friction with the Sun's drive toward clear, purposeful, bright-tonal forward motion. The Sun's melodic lines move with purpose and are being compressed from beneath by Saturn's enormous structural weight. Moments of solar clarity are interrupted by Saturnian density. The rhythm moves forward with the Sun's intent and is measured against Saturn's demand that every step be earned. Listen for the quality of music where something is clearly trying to move forward and is meeting genuine structural resistance at every step, where the forward motion is real and the weight is also real, and the music earns its progress bar by measure.`,
  },

  SATURN_SUN_TRINE: {
    key: 'SATURN_SUN_TRINE', pair: 'SATURN_SUN', aspect: 'trine', intensity: 'Low-medium',
    core: `Saturn, structure, discipline, time, and the principle of earned authority, and the Sun, conscious identity and the purposeful drive toward self-expression, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces recognize each other's legitimacy and work in the same direction without the friction of harder aspects or the weight of the conjunction. The person's ego and their relationship to responsibility, structure, and long-term commitment are naturally integrated. Saturn's discipline feels like part of who they are, not like something imposed from outside.`,
    behavioral: `The internalized Saturn principle and the ego's expressive drive are drawing from the same elemental well rather than competing for resources. The ambition is directed and realistic. The discipline is genuine rather than performed. The authority they project comes from actual competence rather than from status-seeking. The trine's shadow is that the ease of this integration can mean the person never fully encounters the depth of Saturn's demand. The crucible experience that produces hard-won wisdom through years of testing is simply not as available here.`,
    friendship: `Reliable, consistent, and quietly authoritative. Their word means something. Their presence in a difficult situation is genuinely stabilizing.`,
    romantic: `Partners find a quality of genuine dependability and quiet authority that makes the relationship feel grounded. The challenge may be accessing the Sun's more playful, spontaneous dimensions, which the Saturn trine can mute.`,
    feed: `The current sky is moving through the natural authority structure in this connection. What each person brings as genuine competence and reliability is touching the quality of this relationship right now in a way that is worth noticing.`,
    sonic: `Saturn and the Sun are in the same elemental family in the trine. The Sun's purposeful melodic direction is expressed with Saturn's measured gravity without friction between purpose and discipline. The rhythm is purposeful and grounded simultaneously, moving with the Sun's directional logic and Saturn's deliberateness in natural cooperation. The harmonic language is major with depth rather than brightness, the Sun's natural tonality given structural weight by Saturn's presence. Listen for the quality of music that feels both certain and unhurried, where the direction is clear and the pace is exactly what the music requires and no more.`,
  },

  SATURN_SUN_OPPOSITION: {
    key: 'SATURN_SUN_OPPOSITION', pair: 'SATURN_SUN', aspect: 'opposition', intensity: 'High',
    core: `Saturn, the principle of structure, limitation, time, and the testing of what is genuinely load-bearing, stands at full polarity with the Sun, conscious identity and the drive toward purposeful self-expression and recognition. At 180 degrees, the Sun asserts its right to express and to be seen. Saturn challenges whether that expression has been sufficiently earned and whether the ego's claims to authority are genuinely solid. Where the conjunction fuses these forces into the person's own identity and the square creates a permanent internal friction, the opposition tends to place this dynamic in the relational field. This person tends to encounter Saturn's testing principle through other people, through authority figures, demanding partners, or critical external structures, more than through their own internalized self-critique alone.`,
    behavioral: `Because Saturn and the Sun are at opposite poles, the ego tends to experience Saturn's demanding, limiting, authority-testing function as something that comes from outside rather than from within. This means the person may repeatedly encounter critical authority figures, demanding partners, or external structures that seem to be blocking their legitimate self-expression, without fully recognizing that the Saturn principle is part of their own psychological architecture. The person who successfully navigates this opposition develops a remarkable quality of tested authority, because they have had to prove themselves repeatedly rather than having the path smoothed by internal Saturnian structure from the beginning.`,
    friendship: `Friends may notice a pattern of this person positioning themselves against authority or structure in their lives, not out of rebellion for its own sake but because the Saturn principle has not yet been fully internalized and is still being processed through external encounter.`,
    romantic: `Partners who carry genuine structure, authority, or high personal standards can activate this opposition's dynamic significantly. The relationship becomes a site of Saturn's testing. The most productive partnerships are those where the partner's Saturn reflects something the person is ready to integrate rather than simply resist.`,
    feed: `Saturn's transit is illuminating both ends of the identity-authority axis in this connection today. What each person is being asked to be accountable for, and to whom, is more visible between these charts today than it usually is.`,
    sonic: `The Sun and Saturn in opposition produce a composition where purposeful identity and structural weight are in dialogue across maximum distance. The Sun's bright, major-tonal, forward-moving melodic statements are answered by Saturn's dense, minor-tonal, deliberate structural gravity pulling from across the compositional space. The rhythm alternates between the Sun's assertive forward pulse and Saturn's measured, heavy cadence. The music cannot fully commit to either forward brightness or weighted gravity because each is constantly answered by the other. Listen for the quality of music where something is clearly trying to move forward and something is clearly applying weight to that movement, where the dialogue between brightness and gravity is the actual emotional content.`,
  },

  SATURN_MOON_CONJUNCTION: {
    key: 'SATURN_MOON_CONJUNCTION', pair: 'SATURN_MOON', aspect: 'conjunction', intensity: 'Very high',
    core: `Saturn, the principle of structure, limitation, emotional sobriety, and the force that tests what is genuinely load-bearing, fuses with the Moon, the keeper of emotional instinct, memory, interior safety, and the body's fundamental need for nourishment and comfort. This is not a comfortable configuration in early life. The Moon's natural impulse toward fluid emotional expression, instinctive nurturing, and unrestricted feeling is filtered through Saturn's requirement for discipline, control, and structural adequacy. What it does not produce is emotional numbness. It produces a person for whom emotional experience carries weight and seriousness that others around them may not feel as acutely. What they feel, they feel deeply. What they commit to emotionally, they commit to with the full authority of Saturn's structural permanence.`,
    behavioral: `Saturn's internalized demand for structural adequacy has been applied to the domain of feeling itself, meaning this person evaluates their own emotional responses with the same rigorous scrutiny they bring to everything else. This creates an emotional interior that is both deeply feeling and deeply controlled. This person is not cold. They are emotionally reliable in the most structural sense. They do not have easy access to spontaneous emotional expression or uncomplicated warmth, but when they commit to someone emotionally, that commitment is genuine, durable, and not easily withdrawn. The psychological cost is a chronic difficulty with emotional vulnerability. The person may experience their own feelings as something that must be managed, contained, or proven worthy before expression is permitted.`,
    friendship: `Friends experience this person as dependable and genuinely caring in a quiet, structural way. They show up consistently, they remember what matters, and their support is real even when it is not demonstratively warm. The emotional reserve is not coldness. It is Saturn's discipline applied to the Moon's domain.`,
    romantic: `Partners often need patience with the emotional availability this person can offer, not because the feelings are not there but because Saturn has built significant structure around the Moon's expression. The relationships that unlock this person are those patient enough to earn the Moon's trust through demonstrated structural reliability.`,
    feed: `Saturn's transit is pressing on the emotional foundation of this connection right now. What each person genuinely needs to feel secure in this relationship is being tested, and what is real here will become clearer today.`,
    sonic: `Saturn's dense, structurally weighted minor harmony and measured deliberate cadence shape the Moon's entire emotional register in the conjunction. The Moon's natural fluid, breathing quality is organized by Saturn's structural demand into something contained, measured, and weighted. The harmonic language is modal but dark, the Moon's natural emotional ambiguity given structural density by Saturn's presence. The rhythm breathes like the Moon but with Saturn's weight: the inhalation and exhalation are measured, deliberate, not free. Listen for the quality of music where something deeply feeling is also deeply contained, where the emotional depth is unmistakable but the expression of it is restrained and deliberate.`,
  },

  SATURN_MOON_SEXTILE: {
    key: 'SATURN_MOON_SEXTILE', pair: 'SATURN_MOON', aspect: 'sextile', intensity: 'Low-medium',
    core: `Saturn, structure, discipline, emotional sobriety, and the principle of earned trust, and the Moon, emotional instinct, interior need, and the body's requirement for safety and nourishment, are in a 60-degree relationship of easy, productive cooperation. The sextile places these two forces in compatible territories where Saturn's organizing discipline and the Moon's emotional intelligence can support each other without the heaviness that harder aspects create. Saturn provides the container. The Moon fills it.`,
    behavioral: `The Moon's emotional instinct and Saturn's structural discipline are in productive dialogue. The Moon generates the feeling, and Saturn provides the containment and organizational framework that allows those feelings to be processed, expressed, and acted upon without overwhelming the system. The result is genuine emotional reliability: they can be present for others in difficulty without being destabilized, can make and keep emotional commitments without the ambivalence that less integrated Saturn-Moon configurations produce, and can process grief, disappointment, and vulnerability without requiring external scaffolding to do so.`,
    friendship: `Emotionally reliable, quietly nurturing, and genuinely trustworthy with what is shared. Not the most effusive presence, but the one whose emotional support is consistently real.`,
    romantic: `Partners find a quality of emotional steadiness and genuine commitment that makes the relationship feel secure. The warmth deepens over time rather than being most present at the beginning.`,
    feed: `Today's transit is moving through the emotional reliability channel in this connection. The trust and structural care that runs between these charts is being gently activated right now, and it is worth noticing what that feels like.`,
    sonic: `Saturn's organizing discipline and the Moon's emotional intelligence support each other in the sextile without the compression that harder aspects create. The rhythm has the Moon's organic breathing quality and Saturn's measured weight in easy dialogue, the emotional pulse present and also held. The harmonic language is modally warm with structural depth, the Moon's emotional color given a grounded foundation by Saturn's presence. Listen for the quality of music where something emotionally present also feels structurally held, where the feeling is real and the container for it is reliable.`,
  },

  SATURN_MOON_SQUARE: {
    key: 'SATURN_MOON_SQUARE', pair: 'SATURN_MOON', aspect: 'square', intensity: 'Very high',
    core: `Saturn, the principle of structure, emotional sobriety, and the testing of what is genuinely load-bearing, meets the Moon, the principle of emotional instinct, interior safety, and the body's fundamental need for comfort and nourishment, at a 90-degree angle of profound, sustained tension. This is one of the most psychologically significant configurations in the natal chart, and it deserves to be treated with the seriousness it carries. Saturn tests the Moon's emotional world with the same unflinching scrutiny it applies to everything else. The Moon needs to feel safe enough to be vulnerable. Saturn questions whether the safety has been sufficiently earned.`,
    behavioral: `The part of the psyche that the Moon governs, the part that simply needs to feel safe and held, has been subjected to Saturn's demand for structural adequacy before that safety is granted. Whether this originated in a literal experience of conditional emotional availability in early life or is simply the natal architecture of the configuration, the behavioral result tends to be consistent. This person has a profound difficulty trusting that emotional need is legitimate without prior justification, that vulnerability will be met with care rather than judgment, and that the inner world is safe to inhabit without constant self-monitoring. Some Saturn-Moon square people develop a kind of emotional stoicism, carrying their interior world in isolation and presenting a composed exterior that others rarely penetrate. Others develop chronic emotional anxiety, caught in the gap between what is needed and what feels permitted. In both cases the development task is the same: learning that the Moon's needs are not a burden that must be earned away but a legitimate dimension of the human interior that Saturn, properly integrated, can protect rather than suppress.`,
    friendship: `Friends may notice a quality of emotional self-sufficiency that makes this person seem less in need of support than they actually are. They are often better at providing care than receiving it.`,
    romantic: `Partners need genuine patience and demonstrated reliability over time to reach the Moon that is behind Saturn's structural wall. The person who earns this person's emotional trust receives something of extraordinary depth and durability in return.`,
    feed: `Saturn's transit is pressing directly on the emotional security structures in this connection right now. What each person genuinely needs to feel safe in this relationship is under examination, and what is solid here is about to become clearer.`,
    sonic: `Saturn's dense, structurally weighted minor harmony and measured deliberate cadence are in profound friction with the Moon's need for fluid emotional expression, familiar harmonic territory, and the breathing rhythm of its own natural cycling. The Moon's breathing, returning quality is compressed from above by Saturn's structural demand. The rhythm is the Moon's organic breath working against Saturn's measured weight, the breathing present but labored, carrying more than it wants to carry. Listen for the quality of music where something very clearly feels something and is also very clearly working hard to contain what it is feeling, where the emotional depth and the structural restraint are both unmistakable and in genuine sustained tension.`,
  },

  SATURN_MOON_TRINE: {
    key: 'SATURN_MOON_TRINE', pair: 'SATURN_MOON', aspect: 'trine', intensity: 'Low-medium',
    core: `Saturn, structure, discipline, emotional sobriety, and the principle of earned trust, and the Moon, emotional instinct, interior need, and the body's requirement for safety, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means Saturn's organizing discipline and the Moon's emotional intelligence move in the same direction without the friction that harder aspects create. The person's emotional interior has a natural structural quality. Feelings are real and deeply felt, and they are also contained, organized, and expressed in ways that serve rather than destabilize the person and those around them.`,
    behavioral: `The affect system and the structural containment system are drawing from the same elemental source, which means emotional experience flows naturally into appropriate expression without requiring the effortful containment that harder Saturn-Moon aspects demand. The Moon generates feeling. Saturn provides the natural container and organizational framework without constricting the feeling itself. The result is genuine emotional maturity and reliable self-regulation. Not the performed composure of someone suppressing their interior world, but the genuine steadiness of someone whose emotional system and structural system are working together.`,
    friendship: `Emotionally steady, genuinely nurturing, and reliable in the quiet structural way that Saturn gives. Their care is real and their consistency is remarkable.`,
    romantic: `Partners find a quality of emotional dependability and quiet depth that makes the relationship feel genuinely safe over time. The warmth is not effusive but it is absolutely real.`,
    feed: `The current sky is amplifying the emotional stability running between these charts. The quiet, structural care that holds this connection together is more present and more noticeable right now than it is as a background condition.`,
    sonic: `The Moon's emotional instinct and Saturn's structural discipline flow in natural agreement in the trine. The rhythm has the Moon's organic breathing quality and Saturn's measured gravity in natural cooperation. The harmonic language is modally warm and also structurally deep, the Moon's emotional color given a foundation by Saturn's presence that feels supportive rather than constraining. Listen for the quality of music where something emotionally deep also feels completely held, where the depth and the safety of the container are the same quality.`,
  },

  SATURN_MOON_OPPOSITION: {
    key: 'SATURN_MOON_OPPOSITION', pair: 'SATURN_MOON', aspect: 'opposition', intensity: 'High',
    core: `Saturn, the principle of structure, limitation, emotional sobriety, and the testing of what is genuinely load-bearing, stands at full polarity with the Moon, emotional instinct, interior safety, and the body's fundamental need for comfort and nourishment. At 180 degrees, the Moon needs to feel safe, held, and emotionally received. Saturn challenges whether the safety being sought is genuinely earned, whether the need being expressed is genuinely justified, and whether the emotional world is as real and legitimate as it feels. This opposition tends to externalize rather than staying as interior dialogue. The person encounters Saturn's emotional testing principle through relationships and external circumstances rather than entirely through their own internalized self-critique.`,
    behavioral: `The Moon's need for emotional safety and nourishment keeps encountering Saturnian resistance in the external environment: partners who are emotionally withholding, structures that demand performance before care is granted, life circumstances that consistently require emotional self-sufficiency before comfort is available. The developmental work is integrating the Saturn principle, understanding that the structure, discipline, and emotional sobriety that Saturn demands are part of the person's own psychological architecture, not obstacles placed there by others.`,
    friendship: `May notice a pattern of attracting emotionally unavailable or demanding relationships, not through poor judgment but through the archetypal dynamic of the opposition seeking its missing pole in the external world.`,
    romantic: `The most significant developmental work for this configuration happens in long-term partnership, where the Saturn pole of the opposition can be encountered, examined, and gradually integrated rather than simply projected.`,
    feed: `Saturn's transit is illuminating both ends of the emotional security axis in this connection today. What is being asked for and what is being withheld between these charts is more visible right now than usual, and naming it directly is the move.`,
    sonic: `The Moon and Saturn in opposition produce a composition where emotional instinct and structural demand are in dialogue across maximum distance. The Moon's breathing, modally ambiguous, memory-cycling emotional quality is answered by Saturn's dense, weighted, structurally measured gravity from across the compositional space. The rhythm alternates between the Moon's organic tide-like breath and Saturn's heavy measured cadence in a pattern that feels like emotional need meeting structural resistance repeatedly. Listen for the quality of music where something is clearly feeling something and something is clearly weighing that feeling against a structural standard, where the emotional content and the structural discipline are in unresolved dialogue from opposite ends.`,
  },

  SATURN_VENUS_CONJUNCTION: {
    key: 'SATURN_VENUS_CONJUNCTION', pair: 'SATURN_VENUS', aspect: 'conjunction', intensity: 'Very high',
    core: `Saturn, the principle of structure, limitation, time, earned authority, and the force that tests what is genuinely durable, fuses with Venus, the planet governing love, aesthetic sensibility, relational value, and the capacity to draw beauty and connection toward oneself. When these two share the same degree, love and structure become one system. This person does not experience love as something that simply happens. They experience it as something that must be earned, built, and proven durable before it can be fully trusted or expressed. What results is someone who loves seriously, who commits with the full weight of Saturn's permanence, and who builds relationships the way architects build structures: slowly, deliberately, with attention to what will actually hold.`,
    behavioral: `The relational attachment system has been fused with the internalized authority and structure principle, meaning this person's capacity for love is gated by Saturn's evaluation of whether the relationship is structurally sound, whether the other person is genuinely reliable, and whether the love being offered is something that will endure. This is not avoidance born of fear exactly. It is avoidance born of Saturn's genuine wisdom that premature emotional investment in unstable structures is a form of irresponsibility. The person is slow to open relationally, their warmth deepens significantly over time, and their commitment, once genuinely given, is among the most durable that any configuration produces.`,
    friendship: `Friends are earned rather than made easily. But the friendships this person builds carry real weight and real durability. They are the friend whose loyalty does not waver when circumstances change.`,
    romantic: `Partners who need immediate warmth and effortless relational ease will find this configuration difficult. Partners who can invest in something that builds over time will find that what develops is genuinely extraordinary: a love that has been tested and has held.`,
    feed: `Saturn's transit is pressing on the love and commitment structures in this connection right now. What is genuinely real between these two charts is being tested for durability today, and what holds under that pressure is worth paying very close attention to.`,
    sonic: `Venus's natural warmth and aesthetic pleasure are expressed through Saturn's register in the conjunction. The harmonic language is beautiful but serious, the rich Venusian seventh-chord color given structural density by Saturn's minor gravity. The rhythm has Venus's graceful quality but Saturn's measured weight: the grace is deliberate, earned, not spontaneous. The melodic lines are beautiful but restrained, reaching toward beauty within the range that has been structurally permitted. Listen for the quality of music where something is genuinely beautiful and also genuinely heavy, where the aesthetic warmth is real but it carries weight, where the beauty has been built rather than discovered.`,
  },

  SATURN_VENUS_SEXTILE: {
    key: 'SATURN_VENUS_SEXTILE', pair: 'SATURN_VENUS', aspect: 'sextile', intensity: 'Low-medium',
    core: `Saturn, structure, discipline, time, and the principle of earned trust, and Venus, love, aesthetic sensibility, and the capacity for relational warmth, are in a 60-degree relationship of easy, productive cooperation. Love and structure are not at war here. They work together. The person's relational life has a natural quality of reliability and aesthetic care. They take their relationships seriously without the oppressive weight of the conjunction, and they build them with intention without the anxiety of the square.`,
    behavioral: `The desire system and the structural reality principle are in productive dialogue. Venus generates the warmth and relational desire, and Saturn provides the organizational framework and long-term orientation that gives that warmth somewhere real to land. The ambition is directed and realistic. The aesthetic dimension of Venus is also supported here: Saturn's appreciation for craft, precision, and what endures over time combines naturally with Venus's eye for beauty to produce a person with genuine aesthetic sensibility and a preference for quality over quantity in all things.`,
    friendship: `Reliable, warm in a measured way, and genuinely invested in the people they choose to be close to. Their friendships are carefully chosen and carefully maintained.`,
    romantic: `Partners find a quality of genuine care and structural commitment that makes the relationship feel both warm and solid. The investment deepens naturally over time.`,
    feed: `Today's transit is moving through the productive channel between love and structure in this connection. What is being built between these charts with genuine care and deliberate attention is touching the quality of this relationship right now.`,
    sonic: `Saturn's organizing wisdom supports Venus's relational warmth and aesthetic sensibility without compressing them in the sextile. The harmonic language is warm and colorful with structural grounding, Venusian beauty given a foundation by Saturn's presence that makes it feel durable rather than ephemeral. The rhythm is graceful and measured simultaneously, Venus's flowing ease and Saturn's deliberateness in natural dialogue. Listen for the quality of music where something is beautiful and also feels built to last, where the aesthetic warmth and the structural reliability are both present and supporting each other.`,
  },

  SATURN_VENUS_SQUARE: {
    key: 'SATURN_VENUS_SQUARE', pair: 'SATURN_VENUS', aspect: 'square', intensity: 'Very high',
    core: `Saturn, the principle of structure, limitation, time, and the testing of what is genuinely durable, meets Venus, the principle of love, beauty, relational warmth, and the magnetic pull toward connection and pleasure, at a 90-degree angle of sustained, significant tension. Saturn tests love for structural soundness. Venus reaches toward warmth and beauty as immediate, legitimate experiences of value. These two forces do not naturally agree. Saturn says: prove that this love will last, that this relationship is built on something real, that the pleasure being sought will not simply evaporate. Venus says: the warmth is real now, the beauty is present now, the connection matters now. The square means this argument never fully resolves.`,
    behavioral: `Saturn demands that love prove its durability before it is trusted. Venus experiences that demand as a barrier to the warmth and connection that it knows is already real. The behavioral result is a recurring approach-withdrawal pattern in relationships that is different in origin from the Venus-Mars square's approach-withdrawal. Where the Venus-Mars square produces friction between desire and pursuit, the Saturn-Venus square produces friction between warmth and the fear of structural failure. This person may find themselves drawn into relationships and then pulling back as Saturn's evaluating function begins its assessment. The development task is learning to trust that love is not exempt from difficulty, that Venus and Saturn can coexist in a relationship, and that the love worth building is the one that can hold both.`,
    friendship: `May find it difficult to allow friendships to be simply easy and warm. The Saturn function keeps evaluating whether the relationship is built on something solid enough to merit full investment.`,
    romantic: `Partners experience a person who clearly wants connection and warmth and who simultaneously keeps creating distance between themselves and that connection. The path through is demonstrated reliability over time rather than explanation.`,
    feed: `Saturn's transit is pressing directly on the tension between love and structure in this connection right now. What each person needs to feel safe enough to be genuinely warm is under examination today, and what this reveals is significant.`,
    sonic: `Venus's rich consonant beauty and graceful relational warmth are in significant friction with Saturn's structural weight and measured deliberate cadence in the square. Venus wants the harmonic language to be beautiful and warm. Saturn demands it be structurally adequate first. The harmonic language cycles between Venus's rich, colorful warmth and Saturn's structural minor density, beauty and gravity in unresolved tension. The melodic lines want to go somewhere beautiful and are measured against Saturn's demand for structural justification before each phrase is permitted to reach its destination. Listen for the quality of music where something is trying to be warm and beautiful and is meeting structural resistance at every step.`,
  },

  SATURN_VENUS_TRINE: {
    key: 'SATURN_VENUS_TRINE', pair: 'SATURN_VENUS', aspect: 'trine', intensity: 'Low-medium',
    core: `Saturn, structure, discipline, time, and the principle of what endures, and Venus, love, aesthetic sensibility, and the capacity for relational warmth, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means Saturn's organizing wisdom and Venus's relational warmth move in the same direction without the friction of harder aspects. Love and structure are not in tension here. They inform each other. The person builds their relationships with genuine care and aesthetic attention, and the structures they create in love are beautiful precisely because they are solid.`,
    behavioral: `The love-and-beauty system and the structural-reality principle are drawing from the same elemental source and moving in compatible directions. Venus's desire for warmth and connection is not being tested by Saturn's demand for structural proof. It is being supported by Saturn's organizational wisdom and long-term orientation. The result is a person who can love with both warmth and wisdom simultaneously. Aesthetically, the trine produces a refined, enduring sensibility. These people tend to have large aesthetic appetites, appreciation for cultural breadth, and a quality of aesthetic generosity that makes their environments and relationships feel genuinely beautiful.`,
    friendship: `These friendships are carefully chosen, genuinely warm, and notably durable. The investment is real and the reliability is structural.`,
    romantic: `Partners find a quality of love that is both genuinely warm and genuinely solid, affection that does not require the relationship to be in a honeymoon state to be fully present.`,
    feed: `The current sky is moving through this connection's love-and-structure harmony. What has been built between these charts with genuine care and long-term intention is more visible and more available right now than usual.`,
    sonic: `Venus's aesthetic warmth and Saturn's structural depth are in natural agreement in the trine. The harmonic language is warm and colorful with genuine structural grounding, Venusian beauty given Saturn's durability without any tension between them. The rhythm is graceful and measured in natural cooperation, flowing ease and deliberate weight as one quality. The melodic lines are beautiful and within a structurally trustworthy range, reaching toward beauty with the assurance that the foundation will hold. Listen for the quality of music where something beautiful also feels like it will still be beautiful tomorrow and next year, where the warmth and the reliability are the same quality.`,
  },

  SATURN_VENUS_OPPOSITION: {
    key: 'SATURN_VENUS_OPPOSITION', pair: 'SATURN_VENUS', aspect: 'opposition', intensity: 'High',
    core: `Saturn, the principle of structure, limitation, time, and the testing of what is genuinely durable, stands at full polarity with Venus, the principle of love, beauty, relational warmth, and the magnetic pull toward connection and pleasure. At 180 degrees, Saturn says that love must be proven, structured, and tested for durability. Venus says that love is its own justification and that warmth and beauty are legitimate values in themselves. This opposition tends to externalize the tension. The person may encounter the Saturn principle through partners who are withholding, demanding, or structurally rigid, or through life circumstances that consistently create barriers between themselves and the connection and warmth they genuinely desire.`,
    behavioral: `The loving, warmth-seeking Venus self keeps encountering Saturnian coldness, withholding, or structural demand in partners, or the structured, responsible Saturnian self keeps encountering partners who are relationally demanding, expecting more warmth than Saturn currently permits. The development task is integrating both poles: understanding that the capacity for genuine love and the wisdom of structural reality are both part of the self, and that the most enduring love is the one that can hold both Venus's warmth and Saturn's integrity simultaneously.`,
    friendship: `May notice a pattern of friendships where the warmth they seek is not quite available, or where their own structural demands create distance that Venus then experiences as loneliness.`,
    romantic: `The most significant relational development for this configuration happens through partnerships where the Saturn-Venus tension can be consciously examined, where the question of how love and structure coexist can be actively worked rather than simply enacted.`,
    feed: `Saturn's transit is illuminating both ends of the love-and-structure axis in this connection today. What is being asked for and what feels withheld between these charts is more visible right now, and that visibility is an opening.`,
    sonic: `Venus and Saturn in opposition produce a composition where aesthetic warmth and structural weight are in dialogue across maximum distance. Venus's rich, warm, beautiful harmonic language is answered by Saturn's dense, minor, structurally weighted gravity from across the compositional space. The rhythm alternates between Venus's graceful flowing ease and Saturn's measured deliberate cadence in a pattern that feels like warmth meeting resistance repeatedly. Listen for the quality of music where something warm keeps meeting something structurally demanding, where the beauty is real and the weight is also real, and the two keep encountering each other without fully reconciling.`,
  },

  SATURN_MARS_CONJUNCTION: {
    key: 'SATURN_MARS_CONJUNCTION', pair: 'SATURN_MARS', aspect: 'conjunction', intensity: 'Very high',
    core: `Saturn, the principle of structure, limitation, discipline, and the force that tests what is genuinely load-bearing, fuses with Mars, the planet governing raw drive, assertion, the instinct to pursue and defend, and the force that moves a person toward what they want and away from what threatens them. When these two occupy the same degree, drive and structure become one unified system. The Mars impulse toward immediate assertion and direct pursuit is filtered through Saturn's demand for strategic discipline, long-term thinking, and proven structural soundness before commitment. The result, over time, is one of the most formidable configurations in the natal chart: disciplined force that does not waste itself on targets that cannot be reached.`,
    behavioral: `Mars provides the force and the willingness to engage. Saturn provides the strategy, the patience, and the structural discipline that determines when and where that force is deployed. The person's assertive drive and the reality principle are fused, which means this person's Mars never fires ahead of Saturn's structural assessment of whether the target is worth the energy and whether the approach is likely to succeed. The psychological cost is significant suppression of the Mars drive in the short term. The immediate, reactive, impulsive dimension of Mars is consistently overridden by Saturn's demand for strategic assessment, which can produce a chronic sense of frustration or compressed energy that finds no adequate outlet. When the energy does release, it tends to do so with the full accumulated weight of everything Saturn has been holding in reserve.`,
    friendship: `Reliable and formidable in their commitments. When they are on your side, they are genuinely on your side, with the full weight of Mars's force and Saturn's strategic loyalty.`,
    romantic: `Partners need to understand that the passion here is real and significant. It is simply organized rather than impulsive. What they receive is not the spontaneous fire of an unaspected Mars but the directed, durable commitment of a Mars that has been shaped by Saturn.`,
    feed: `Saturn's transit is pressing on where drive and discipline meet in this connection right now. The force that each person brings to this relationship is being organized by something larger today, and what gets directed matters.`,
    sonic: `Mars's physical force and Saturn's structural weight are the same sound in the conjunction. The driving Martian rhythm is measured by Saturn's deliberate cadence: the pulse is both powerful and controlled simultaneously. The harmonic language has Mars's directional clarity and Saturn's structural density, not beautiful but formidable. The melodic lines are short and incisive like Mars but held within the range that Saturn's strategic assessment permits. Listen for the quality of music where power and restraint are the same quality, where the force is unmistakable and the control over that force is equally unmistakable.`,
  },

  SATURN_MARS_SEXTILE: {
    key: 'SATURN_MARS_SEXTILE', pair: 'SATURN_MARS', aspect: 'sextile', intensity: 'Low-medium',
    core: `Saturn, structure, discipline, strategic intelligence, and the principle of earned mastery, and Mars, raw drive, assertion, and the force that converts desire into action, are in a 60-degree relationship of easy, productive cooperation. The sextile places these two forces in compatible elemental territories where Saturn's organizing discipline and Mars's energetic drive can support each other without the weight or frustration that harder aspects create. The person has reliable access to both force and direction simultaneously.`,
    behavioral: `Mars provides the energy and the impulse to pursue. Saturn provides the organizational framework and long-term orientation that ensures that energy is directed effectively rather than wasted on targets that cannot be reached or approaches that cannot succeed. The result is reliable, directed drive. Not the explosive power of the conjunction or the frustrated intensity of the square, but a consistent, well-organized capacity for sustained effort toward chosen goals.`,
    friendship: `Someone you want on your team when something actually matters. Their support is organized, reliable, and backed by genuine effort.`,
    romantic: `Partners find a quality of committed, directed energy in this person that makes the relationship feel genuinely supported. The passion is real and the effort is strategic.`,
    feed: `Today's transit is moving through the productive channel between drive and structure in this connection. The organized, directed energy that each person brings to this relationship is more available and more aligned right now than usual.`,
    sonic: `Saturn's organizing discipline and Mars's energetic drive are in productive dialogue in the sextile. The rhythm has Mars's physical energy and Saturn's measured deliberateness in natural agreement, the drive real and also strategically organized. The harmonic language is direct and structurally grounded, not beautiful but purposeful and reliable. Listen for the quality of music where something powerful is also strategically organized, where the energy and the structure supporting it are in natural agreement.`,
  },

  SATURN_MARS_SQUARE: {
    key: 'SATURN_MARS_SQUARE', pair: 'SATURN_MARS', aspect: 'square', intensity: 'Very high',
    core: `Saturn, the principle of structure, limitation, discipline, and the testing of what is genuinely load-bearing, meets Mars, the planet of raw drive, assertion, and the force that moves the person toward desire and away from threat, at a 90-degree angle of fundamental, sustained tension. Saturn says: wait, assess, organize, determine whether this target is strategically sound before committing force. Mars says: the target is there, the energy is available, the time is now. These two imperatives are structurally incompatible in their natural timing and orientation. The square means neither fully overrides the other, and the person carries a permanent friction between their impulse to assert and their internalized demand for strategic adequacy before that assertion is permitted.`,
    behavioral: `In some people, Saturn wins the argument: the Mars drive is so consistently overridden by Saturn's structural demands that the person develops a chronic pattern of suppressed drive, accumulating a pressure that eventually releases in ways that feel disproportionate to the immediate trigger. In others, Mars wins: the drive fires ahead of Saturn's strategic assessment, producing action that is forceful but poorly timed or structurally unsound, followed by Saturn's exacting post-mortem examination of what went wrong. In most people the pattern alternates between these poles, producing a life characterized by significant effort, periodic frustration, strategic setbacks that become lessons, and the eventual development of a disciplined force that emerges from having had to learn, through repeated experience, exactly when to move and when to wait. The gift of the Saturn-Mars square is genuine: when this aspect is integrated, the result is not the impulsive power of an unaspected Mars but the precisely directed, strategically deployed, durably sustained force of a Mars that has been fully disciplined by Saturn.`,
    friendship: `Can be challenging to be around when the suppressed Mars energy is looking for an outlet, but extraordinary to have on your side when the strategic moment arrives and the full directed force becomes available.`,
    romantic: `Partners experience a person with significant contained drive whose expression can feel unpredictable, not because the drive isn't real but because the Saturn-Mars negotiation is ongoing and the results are not always legible from the outside.`,
    feed: `Saturn's transit is pressing directly on the friction point between drive and structure in this connection right now. The tension between what each person wants to pursue and the constraints they are operating within is elevated today, and how that tension is handled will matter.`,
    sonic: `Saturn's structural weight and deliberate cadence are in profound friction with Mars's physical drive and immediate directional energy in the square. The site of the primary conflict is the rhythm: Mars's driving downbeat is constantly in tension with Saturn's measured cadence, producing a pulse that feels both powerful and constrained simultaneously. The harmonic language has Mars's directional force compressed by Saturn's structural weight, enormous energy present but unable to move freely. Listen for the quality of music where enormous force is being held under enormous structural pressure, where the power is completely audible and the restraint is equally audible, and the tension between them is the primary emotional content.`,
  },

  SATURN_MARS_TRINE: {
    key: 'SATURN_MARS_TRINE', pair: 'SATURN_MARS', aspect: 'trine', intensity: 'Low-medium',
    core: `Saturn, structure, discipline, strategic intelligence, and the principle of earned mastery, and Mars, raw drive, assertion, and the force that converts desire into action, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means Saturn's organizing discipline and Mars's energetic drive move in the same direction without the friction or compression that harder aspects create. The person has natural access to both force and direction as integrated qualities of their assertive function. The drive is organized not because Saturn had to discipline it into submission but because the two forces are naturally aligned.`,
    behavioral: `The drive and the discipline, the force and the strategy, are functioning as a unified system. Mars provides the energy and the willingness to engage. Saturn provides the natural patience, structural assessment, and long-term orientation that ensures the energy is deployed effectively. There is no ongoing internal argument about when to move and when to wait. The ambition is directed and realistic. The discipline is genuine rather than performed. The authority they project comes from actual competence.`,
    friendship: `Reliable, quietly formidable, and genuinely effective when something needs to be done. Their support is organized and backed by real capacity.`,
    romantic: `Partners find a quality of directed commitment and organized passion that makes the relationship feel both energized and structurally sound.`,
    feed: `The current sky is amplifying the natural alignment between drive and discipline in this connection. The organized force that runs between these charts is more available and more directed right now than it is as a baseline.`,
    sonic: `Saturn's structural discipline and Mars's energetic drive flow in natural agreement in the trine. The rhythm is powerful and controlled simultaneously, a natural confident forward motion where the pulse and the melodic direction are in complete agreement. The harmonic language is direct and structurally grounded, Mars's force given Saturn's strategic intelligence without either compromising the other. Listen for the quality of music where power and control are the same quality, where the force is real and the structure supporting it is also real, and neither is working against the other.`,
  },

  SATURN_MARS_OPPOSITION: {
    key: 'SATURN_MARS_OPPOSITION', pair: 'SATURN_MARS', aspect: 'opposition', intensity: 'High',
    core: `Saturn, the principle of structure, limitation, strategic discipline, and the testing of what is genuinely load-bearing, stands at full polarity with Mars, the planet of raw drive, assertion, immediate pursuit, and the force that wants to move without waiting for structural permission. At 180 degrees, Saturn says: stop, assess, organize. Mars says: move, now, directly. The opposition tends to externalize this tension. The person encounters the Saturnian principle of structure and strategic constraint through external authority, opposition from the environment, or the perceived blocking of their Mars drive by forces outside themselves.`,
    behavioral: `The person may either strongly identify with the Mars pole, experiencing themselves as someone whose drive is consistently blocked, frustrated, or constrained by external authority, or strongly identify with the Saturn pole, developing a powerful strategic and organizational capacity while projecting the raw Mars drive onto others who seem impulsive, reckless, or aggressive. Whichever end of the opposition is less consciously owned becomes the shadow dimension of the assertive function. Claiming both the capacity for direct, immediate assertion and the wisdom of strategic restraint as authentic expressions of the self is what the opposition is asking for.`,
    friendship: `May notice a pattern of being in friction with authority or with people who embody either impulsive force or rigid structure, both of which are aspects of the Saturn-Mars axis being encountered in the relational field.`,
    romantic: `Partners who embody one end of the Saturn-Mars axis can activate this configuration's dynamic significantly. The relationship becomes a site of working out the assertive-constraint tension.`,
    feed: `Saturn's transit is illuminating both ends of the drive-and-structure axis in this connection today. What is being pursued and what is creating resistance between these charts is more visible right now than usual, and the visibility is the point.`,
    sonic: `Mars and Saturn in opposition produce a composition where driving force and structural weight are in dialogue across maximum distance. Mars's physical, incisive directional energy is answered by Saturn's dense, measured, structurally weighty authority from across the compositional space. The rhythm alternates between Mars's driving downbeat force and Saturn's measured deliberate cadence in a pattern that feels like momentum meeting resistance repeatedly. Listen for the quality of music where something is clearly trying to move forward and something is clearly applying structural resistance to that movement, where the force and the constraint are in unresolved but generative dialogue from opposite ends of the musical space.`,
  },

} as const;
