/**
 * Astradio Insight Library — Sign Archetypes
 *
 * 12 standalone sign archetypes: Aries through Pisces
 *
 * Keys: SIGN_{SIGN} (e.g., SIGN_ARIES, SIGN_TAURUS)
 * Place at: vnext/projection/insight-library/insight-library-signs.ts
 *
 * v2 Phase 5A: Foundational sign meanings authored as standalone archetypes
 * describing singular chart contexts (A), not cross-chart comparisons (A + B).
 * Each entry contains 6 natal fields only. No synastry fields, as these describe
 * what a sign means in a chart rather than between charts.
 *
 * Authoring rule: core and behavioral fields use chart-bearer attribution 
 * ("the person," "this chart-bearer") and avoid partnership-coded language.
 * Role-specific framing lives in friendship and romantic fields where contextually
 * licensed.
 */

import type { SignInsight } from './insight-library-types';

export const SIGN_INSIGHTS: Readonly<Record<string, SignInsight>> = {

  SIGN_ARIES: {
    key: 'SIGN_ARIES',
    sign: 'ARIES',
    element: 'fire',
    modality: 'cardinal',
    title: 'Aries',
    core: `Aries is the archetype of initiation, the principle of new beginnings, and the capacity to move toward what is wanted without waiting for permission or guarantee of success. As the first sign of the zodiac, Aries represents the moment when potential becomes action, when thought converts to movement, when the self asserts its existence by doing rather than by contemplating. Aries is cardinal fire: it is the spark that starts the blaze, the impulse that launches the project, the courage to be first even when being first means being alone. The Aries signature in a chart describes a dimension of the psyche that is oriented toward initiation rather than completion, toward beginning rather than sustaining, toward the act of willing something into existence rather than the work of maintaining it afterward. Psychologically, Aries is the warrior archetype in its purest form—not the soldier who follows orders, but the pioneer who strikes out into unknown territory because the urge to move forward is stronger than the need for safety. Aries does not deliberate endlessly. It does not wait for consensus. It acts, and it learns from the consequences of action rather than from theoretical preparation. The Aries impulse is directness, speed, and the refusal to be slowed by complexity or caution. It is the part of the self that knows desire and pursuit as a single motion, that experiences hesitation as a form of death, and that would rather fail quickly than succeed slowly.`,
    behavioral: `Behaviorally, Aries expresses as decisiveness, physical courage, and impatience with delay. A person with strong Aries emphasis moves quickly, speaks directly, and commits to action before all variables are known. They are the ones who volunteer first, who raise their hand before the question is fully asked, who start the project immediately rather than spending weeks planning. This is not recklessness—it is a different relationship to risk. Aries understands that perfect information is never available, that waiting for certainty is a form of paralysis, and that momentum itself is a resource that must be claimed early or not at all. The Aries approach to obstacles is to go through them rather than around them. Complexity is simplified. Options are narrowed. The path forward is chosen and pursued with singular focus. The psychological challenge for Aries is learning to tolerate the middle phase of any endeavor—the part that is no longer new and exciting but not yet complete and victorious. Aries is built for beginnings. The sustained effort required for mastery can feel like imprisonment unless the Aries energy learns to find the small battles within the larger campaign. At its best, Aries is the capacity for genuine courage: the willingness to act when action is required, to take the first step even when the destination is unclear, and to trust that forward motion itself is generative.`,
    friendship: `In friendship, Aries brings energy, directness, and the willingness to initiate. The Aries friend is the one who suggests the adventure, who takes charge when the group is stuck in indecision, who acts as the catalyst that gets everyone moving. They are honest to the point of bluntness, loyal in crisis, and uninterested in subtle social games. What you see is what you get. The Aries friend needs the bond to allow for spontaneity and action—friendships that are purely contemplative or that require endless processing feel suffocating. They need to do things together, not just talk about doing things. The friendship thrives when it includes shared physical activity, shared challenges, or shared projects that have clear beginnings and endpoints. Aries can be impatient with friends who cannot make decisions, who need extensive emotional processing before committing, or who take offense at directness. The friendships that last are those that can match Aries's energy without being overwhelmed by it, that can receive blunt honesty as care rather than cruelty, and that understand that Aries's occasional absence is not neglect but the natural rhythm of someone who moves quickly through many commitments.`,
    romantic: `In romance, Aries brings passion, directness, and the thrill of pursuit. The Aries romantic is not subtle—they know what they want and they move toward it with clarity. The chase itself is energizing. The uncertainty of new connection is exhilarating. The partner experiences being wanted in a way that is unambiguous and physically present. The challenge for Aries in long-term partnership is sustaining interest once the initial conquest is complete. Aries is built for the dramatic early phase, and the quieter work of sustained intimacy can feel like settling unless the partnership continues to generate new challenges. The partner who works well with Aries maintains their own autonomy, does not require constant emotional processing, and participates in keeping the relationship active rather than expecting it to settle into passive coexistence. Aries in romance is not incapable of commitment, but the commitment must feel chosen repeatedly rather than assumed. The relationship needs edges, friction, renewal. Partnerships that honor Aries create space for independence, welcome direct confrontation as a form of engagement, and understand that passion and peace are not the same thing.`,
    feed: `Aries energy is active in the current sky. The impulse to begin something new, to act decisively, and to move forward without waiting for perfect conditions is stronger right now. This is a time for courage, for initiation, for claiming what is wanted rather than waiting to be given permission.`,
    sonic: `Aries contributes a sharp, bright attack, a driving forward pulse, and melodic gestures that are short, incisive, and declarative. The rhythm is fast and emphatic, with strong downbeats that propel the music forward. The harmonic language is simple and direct—often power chords or unadorned triads, nothing ornate or ambiguous. The melodic phrases are angular and energetic, leaping rather than stepwise, reaching upward and outward rather than dwelling. Aries's sound is hot and immediate, not soft or sustained. Listen for the quality of music where every element is moving forward at speed, where the pulse creates urgency, where the overall effect is one of action and momentum. Aries's sonic character is initiation, directness, and the sound of something that has already begun.`,
  },

  SIGN_TAURUS: {
    key: 'SIGN_TAURUS',
    sign: 'TAURUS',
    element: 'earth',
    modality: 'fixed',
    title: 'Taurus',
    core: `Taurus is the archetype of embodiment, the principle of sensory presence, and the capacity to value what is tangible, enduring, and genuinely pleasurable. As fixed earth, Taurus represents the moment when energy settles into form, when the abstract becomes concrete, when what was initiated must now be held and cultivated. The Taurus signature in a chart describes a dimension of the psyche that is oriented toward stability rather than change, toward preservation rather than transformation, toward the accumulation and enjoyment of resources rather than the constant pursuit of new frontiers. Psychologically, Taurus is the archetype of the gardener, the steward, the builder of enduring value. It is not interested in speed or novelty. It is interested in quality, in sustainability, in creating conditions where beauty and comfort can be maintained over time. Taurus knows the world through the body and the senses. It does not trust what cannot be touched, tasted, seen, heard, smelled. Abstract principles must be translated into lived experience or they remain unconvincing. Taurus is the part of the self that knows rest is as important as action, that pleasure is a legitimate human need rather than a guilty indulgence, and that some forms of value cannot be rushed into existence but must be grown slowly.`,
    behavioral: `Behaviorally, Taurus expresses as steadiness, patience, and resistance to unnecessary change. A person with strong Taurus emphasis moves deliberately, commits slowly, and holds position with remarkable endurance once commitment has been made. They are the ones who finish what others start, who remain loyal when others have moved on, who build slowly and solidly rather than quickly and shoddily. Taurus does not respond well to pressure. Attempts to rush Taurus into decisions or actions produce stubbornness rather than compliance. The Taurus relationship to change is conservative in the root sense: what is working should be preserved; what is broken should be fixed rather than discarded; what is new must prove itself worthy before displacing what already exists. The psychological challenge for Taurus is learning when to let go rather than clinging to what is familiar simply because it is familiar. Taurus at its worst becomes ossified, unable to adapt when circumstances genuinely require change. But at its best, Taurus is the capacity for genuine sustainability: the ability to create conditions that endure, to honor the body's needs without apology, and to find deep pleasure in the sensory richness of ordinary life.`,
    friendship: `In friendship, Taurus brings loyalty, reliability, and the creation of physical comfort. The Taurus friend is the one whose home always feels welcoming, who remembers what you like to eat and makes sure it's available, who shows up consistently without drama. They are steady rather than exciting, grounded rather than adventurous, and genuinely committed to the people they claim as their own. The Taurus friend needs the bond to feel stable and reciprocal. They invest slowly but deeply, and they expect that investment to be honored rather than taken for granted. Friendships that are emotionally volatile or that require constant crisis management exhaust Taurus. The friendship thrives when it includes shared sensory pleasure—good food, comfortable environments, physical activities that are pleasant rather than punishing. Taurus can be hurt by friends who disappear during difficult times or who treat the friendship as disposable when more exciting options appear. The friendships that last are those that honor Taurus's need for stability, that reciprocate care in tangible rather than purely verbal ways, and that understand that Taurus's resistance to change is not inflexibility but commitment.`,
    romantic: `In romance, Taurus brings sensuality, devotion, and the desire to build something enduring. The Taurus romantic is not interested in casual connection. They move slowly into partnership, assessing whether the bond has genuine substance before fully committing, but once committed, they are remarkably steadfast. Physical affection is central—Taurus expresses love through touch, through creating beautiful shared environments, through the provision of comfort and pleasure. The challenge for Taurus in partnership is the fear of loss that can produce possessiveness. Taurus wants to hold what it has built, and the partner's autonomy can feel threatening if Taurus confuses love with ownership. The partner who works well with Taurus honors their need for physical affection and stability, participates in creating shared material comfort, and understands that Taurus's loyalty is a gift rather than a given. Partnerships that honor Taurus create beauty together, honor the body's needs without shame, and treat commitment as something demonstrated through consistent action rather than declared once and forgotten.`,
    feed: `Taurus energy is active in the current sky. The pull toward stability, the need for sensory pleasure, and the capacity to value what is tangible and enduring are all stronger right now. This is a time for slowing down, for enjoying what is already present, for building rather than chasing.`,
    sonic: `Taurus contributes rich, warm harmonic voicings, slow harmonic rhythm, and melodic lines that are singable and grounded. The rhythm is steady and unhurried, with a quality of settled ease rather than forward drive. The harmonic language is consonant and full—major chords with warm color tones, voicings that emphasize the lower register, nothing harsh or dissonant. The melodic phrases move through stepwise motion, staying close to the tonic, returning to familiar ground rather than reaching into new territory. Taurus's sound is warm and physical, not airy or abstract. Listen for the quality of music where the body can settle, where the rhythm invites swaying rather than rushing, where the overall effect is one of comfort and sensory pleasure. Taurus's sonic character is embodiment, steadiness, and the sound of being fully present in physical form.`,
  },

  SIGN_GEMINI: {
    key: 'SIGN_GEMINI',
    sign: 'GEMINI',
    element: 'air',
    modality: 'mutable',
    title: 'Gemini',
    core: `Gemini is the archetype of connection, the principle of exchange, and the capacity to perceive and communicate patterns across diverse information streams. As mutable air, Gemini represents the moment when fixed structures become fluid, when single perspectives multiply into many, when the mind learns by moving between different frames of reference rather than committing to one. The Gemini signature in a chart describes a dimension of the psyche that is oriented toward multiplicity rather than unity, toward variety rather than depth, toward the pleasure of learning and communicating rather than the work of mastering any single domain. Psychologically, Gemini is the archetype of the messenger, the translator, the connector who moves between worlds and makes exchange possible. It is not interested in arriving at final answers. It is interested in the process of inquiry itself, in the pleasure of noticing patterns, in the social exchange that happens when ideas are shared. Gemini knows the world through language and relationship. It does not experience ideas as solitary possessions but as conversational currency, something that gains value by being circulated rather than hoarded. Gemini is the part of the self that can hold multiple perspectives simultaneously without needing them to resolve into a single truth, that finds boredom more painful than confusion, and that treats curiosity as its primary operating system.`,
    behavioral: `Behaviorally, Gemini expresses as mental agility, conversational fluency, and restlessness. A person with strong Gemini emphasis is quick-witted, socially adept, and capable of shifting between different contexts with ease. They are the ones who can talk to anyone, who make connections between seemingly unrelated ideas, who learn new things rapidly and then move on to the next topic before achieving mastery. Gemini does not commit easily to single paths. The world is too full of interesting options, and choosing one means foreclosing on all the others. This can manifest as dilettantism—surface-level engagement with many subjects rather than deep expertise in one—or as genuine versatility, where the capacity to synthesize across domains creates unique value. The psychological challenge for Gemini is learning to tolerate depth and commitment when variety and novelty are more naturally appealing. Gemini can become scattered, unable to finish what it starts because the next interesting thing has already appeared. But at its best, Gemini is the capacity for genuine synthesis: the ability to see connections that others miss, to translate between different languages and contexts, and to keep the mind alive through ongoing learning.`,
    friendship: `In friendship, Gemini brings conversation, humor, and intellectual stimulation. The Gemini friend is the one who always has something interesting to say, who introduces people to each other, who keeps the group engaged with new ideas and perspectives. They are witty, curious, and genuinely interested in others—not in a deep emotional sense necessarily, but in the sense of wanting to understand how different people think. The Gemini friend needs the bond to remain mentally engaging. Friendships that settle into predictable routines or that are emotionally heavy without intellectual exchange feel suffocating. They need to talk, to share ideas, to laugh. The friendship thrives when it includes ongoing conversation, shared learning, and the freedom to be inconsistent without being judged. Gemini can be experienced as superficial by friends who value emotional depth over intellectual connection, and they can frustrate friends who need reliability and follow-through. The friendships that last are those that honor Gemini's need for variety, that receive their conversational energy as a gift rather than as avoidance, and that understand that Gemini's occasional flakiness is not malice but the natural consequence of a mind that is always tracking multiple commitments.`,
    romantic: `In romance, Gemini brings playfulness, communication, and the need for mental connection. The Gemini romantic needs to be able to talk to their partner, to share ideas, to laugh together. Physical chemistry alone is not sufficient—if the conversation becomes dull, the relationship feels empty regardless of other forms of compatibility. The challenge for Gemini in long-term partnership is the pull toward novelty when the relationship settles into familiar patterns. Gemini is built for the discovery phase, and the work of sustained intimacy can feel repetitive unless the partnership continues to generate new material. The partner who works well with Gemini remains interesting, participates in ongoing conversation and learning, and does not interpret Gemini's need for variety as a sign that the relationship is insufficient. Partnerships that honor Gemini create space for intellectual exchange, welcome curiosity as a form of engagement, and understand that commitment for Gemini is demonstrated through continued interest rather than through unchanging devotion.`,
    feed: `Gemini energy is active in the current sky. The desire to learn, to communicate, and to make connections across different domains is stronger right now. This is a time for conversation, for curiosity, for allowing the mind to move freely rather than forcing it into narrow focus.`,
    sonic: `Gemini contributes quick, articulate melodic phrases, rapid harmonic changes, and a conversational texture where ideas are exchanged between voices. The rhythm is light and fast, with frequent syncopation and rhythmic variation. The harmonic language is restless, modulating between keys and modes with agility, never settling in one place for long. The melodic lines are bright and quick, often in call-and-response patterns, passing motifs back and forth between instruments. Gemini's sound is transparent and nimble, not heavy or sustained. Listen for the quality of music where the content is being thought through in real time, where ideas are being tested and revised, where the overall effect is one of intellectual playfulness and ongoing discovery. Gemini's sonic character is curiosity, conversation, and the pleasure of pattern recognition.`,
  },

  SIGN_CANCER: {
    key: 'SIGN_CANCER',
    sign: 'CANCER',
    element: 'water',
    modality: 'cardinal',
    title: 'Cancer',
    core: `Cancer is the archetype of nurturance, the principle of emotional safety, and the capacity to create sanctuary in a world that is often hostile to vulnerability. As cardinal water, Cancer represents the moment when the self recognizes its need for protection and takes action to secure it, when emotional instinct becomes the organizing principle rather than a secondary concern. The Cancer signature in a chart describes a dimension of the psyche that is oriented toward care—both giving it and receiving it—toward the creation of home as a felt experience rather than a physical location, and toward the preservation of what is emotionally precious. Psychologically, Cancer is the archetype of the mother, the container, the one who holds space for others' vulnerability. It is not interested in conquest or expansion. It is interested in safety, in belonging, in the conditions that allow the tender parts of the self to exist without being destroyed. Cancer knows the world through feeling and memory. It does not trust what cannot be felt. Rational arguments must translate into emotional truth or they remain abstract and unconvincing. Cancer is the part of the self that knows care is not weakness, that emotional safety is a legitimate need rather than a childish demand, and that some things are worth protecting even when protection requires withdrawal from the world.`,
    behavioral: `Behaviorally, Cancer expresses as emotional attunement, protective instinct, and caution around new people and situations. A person with strong Cancer emphasis notices what others are feeling before it is spoken, creates environments that feel safe and welcoming, and invests deeply in the people and places they claim as home. They are the ones who remember important dates, who check in when you're going through difficulty, who create the emotional infrastructure that allows others to relax their vigilance. Cancer does not trust easily. New people are assessed for safety before being allowed into the inner circle. Vulnerability is shared selectively, with those who have proven they will not weaponize it. The psychological challenge for Cancer is learning to distinguish between legitimate emotional self-protection and defensive withdrawal that prevents genuine connection. Cancer at its worst becomes so defended that no one can reach the tender interior. But at its best, Cancer is the capacity for genuine nurturance: the ability to create emotional safety for others, to hold space for vulnerability without judgment, and to build homes—literal and metaphorical—where people can rest.`,
    friendship: `In friendship, Cancer brings emotional depth, loyalty, and the creation of sanctuary. The Cancer friend is the one who makes their home available, who creates the conditions where you can be honest about how you're actually doing, who remembers the small details that matter. They are protective of the people they love, sometimes to the point of being possessive. The Cancer friend needs the bond to feel emotionally safe and reciprocal. They give care generously but need to know it is valued rather than taken for granted. Friendships that are purely intellectual or that do not include genuine emotional exchange feel empty. The friendship thrives when it includes time in private, comfortable settings where vulnerability is possible, and when care is mutual rather than one-directional. Cancer can be hurt by friends who are emotionally unavailable or who treat emotional intimacy as optional. The friendships that last are those that honor Cancer's need for emotional safety, that reciprocate care in tangible ways, and that understand that Cancer's occasional withdrawal is not rejection but self-protection.`,
    romantic: `In romance, Cancer brings devotion, emotional intimacy, and the desire to create home together. The Cancer romantic needs to feel emotionally safe with their partner before they can be fully open. They move slowly into trust, assessing whether the relationship can hold their vulnerability, but once they trust, they invest completely. Emotional attunement is central—Cancer needs a partner who notices their emotional state, who responds to it with care rather than dismissiveness, and who participates in creating a shared life that feels like sanctuary. The challenge for Cancer in partnership is the tendency to give care even when it is not reciprocated, hoping that generosity will eventually earn the love they need. The partner who works well with Cancer honors their emotional rhythms, creates genuine emotional safety, and participates in building a home that feels like refuge. Partnerships that honor Cancer create space for emotional intimacy, honor vulnerability as strength, and treat care as a mutual commitment rather than as something one person provides while the other consumes.`,
    feed: `Cancer energy is active in the current sky. The need for emotional safety, the desire to care for what is precious, and the pull toward home and sanctuary are all stronger right now. This is a time for tending to emotional needs, for creating safety, for honoring what nourishes.`,
    sonic: `Cancer contributes gentle, flowing melodic lines, modal harmonic warmth, and a rhythm that ebbs and flows like tides. The harmonic language is soft and emotionally resonant—often modal rather than purely major or minor, with suspensions and color tones that create emotional depth. The rhythm is organic and breathing, not metronomic, with a quality of gentle rocking or swaying. The melodic phrases are lyrical and tender, moving through stepwise motion, returning to familiar ground. Cancer's sound is warm and enveloping, not sharp or aggressive. Listen for the quality of music where you feel held, where the emotional register is more important than structural clarity, where the overall effect is one of comfort and emotional safety. Cancer's sonic character is nurturance, emotional depth, and the sound of being home.`,
  },

  SIGN_LEO: {
    key: 'SIGN_LEO',
    sign: 'LEO',
    element: 'fire',
    modality: 'fixed',
    title: 'Leo',
    core: `Leo is the archetype of self-expression, the principle of creative vitality, and the capacity to shine without apology. As fixed fire, Leo represents the moment when the spark becomes a sustained flame, when individual presence is claimed and maintained, when the self becomes visible not through conquest but through radiance. The Leo signature in a chart describes a dimension of the psyche that is oriented toward creative self-actualization, toward the joy of being seen and celebrated, and toward the generous sharing of one's light with others. Psychologically, Leo is the archetype of the sovereign, the performer, the one who understands that genuine self-expression is a gift to the world rather than an act of narcissism. It is not interested in blending in. It is interested in being recognized for what it uniquely offers, in creating beauty and joy, and in inspiring others through the example of living boldly. Leo knows the world through the heart and through creative expression. It does not trust what cannot be felt or made. Abstract principles must be embodied, performed, brought into visible form or they remain incomplete. Leo is the part of the self that knows dignity is claimed through self-respect rather than earned through others' approval, that creativity is not optional but essential, and that the courage to be seen is as important as any other form of bravery.`,
    behavioral: `Behaviorally, Leo expresses as confidence, generosity, and the need for recognition. A person with strong Leo emphasis is visible, charismatic, and capable of commanding attention simply by being themselves. They are the ones who take center stage without apology, who create moments of drama and celebration, who make ordinary experiences feel special through the force of their presence. Leo does not hide. It assumes that what it has to offer is valuable and presents it with confidence. This can be experienced as arrogance by those who mistake Leo's self-assurance for inflation, but genuine Leo is more generous than grandiose—it wants others to shine as well, not to diminish them but to create a world where everyone's light is celebrated. The psychological challenge for Leo is learning to tolerate being overlooked or unappreciated without collapsing into resentment. Leo needs to be seen, and when recognition is withheld, it can become either desperate for attention or withdrawn into hurt pride. But at its best, Leo is the capacity for genuine creative courage: the willingness to put oneself forward, to create beauty and joy for its own sake, and to inspire others through example.`,
    friendship: `In friendship, Leo brings warmth, loyalty, and the creation of celebration. The Leo friend is the one who makes ordinary gatherings feel like events, who celebrates others' successes with genuine enthusiasm, who is fiercely protective of the people they love. They are generous with their time and resources, dramatic in their affections, and genuinely committed to making the people around them feel special. The Leo friend needs the bond to include recognition and appreciation. They give generously but need to know their contributions are valued. Friendships that take Leo's loyalty for granted or that fail to reciprocate enthusiasm feel one-sided. The friendship thrives when it includes moments of celebration, mutual admiration, and the freedom to be dramatic without being mocked. Leo can be hurt by friends who are emotionally withholding or who treat Leo's need for appreciation as vanity. The friendships that last are those that honor Leo's generosity, that reciprocate warmth and celebration, and that understand that Leo's confidence is an invitation to shine together rather than a demand for exclusive attention.`,
    romantic: `In romance, Leo brings passion, romance, and the desire to create a love story worth telling. The Leo romantic is not subtle or casual—they want grand gestures, dramatic declarations, and a partnership that feels significant. Being loved by Leo means being treated as special, celebrated, and worthy of devotion. Physical affection is generous, verbal affirmations are frequent, and the relationship itself becomes a creative project. The challenge for Leo in long-term partnership is the need for ongoing romance when the relationship settles into routine. Leo is built for the heightened moments, and the quieter work of daily intimacy can feel like settling unless the partnership continues to generate celebration. The partner who works well with Leo appreciates their generosity, reciprocates romantic gesture and verbal affirmation, and participates in keeping the relationship alive through ongoing creative engagement. Partnerships that honor Leo create beauty together, celebrate each other's successes without jealousy, and treat love as performance in the best sense—something worth doing beautifully.`,
    feed: `Leo energy is active in the current sky. The desire to be seen, to create, and to express the self without apology is stronger right now. This is a time for confidence, for generosity, for allowing the heart to lead rather than hiding its light.`,
    sonic: `Leo contributes bold, declarative melodic statements, rich harmonic fullness, and a rhythm that is regal and confident. The harmonic language is major and expansive—full chords in broad voicings, often using the entire range of available pitch space. The rhythm is steady and noble, with a quality of processional grandeur rather than rushing. The melodic phrases are singable and memorable, stated with confidence and clarity, reaching upward and outward. Leo's sound is warm and generous, not sparse or restrained. Listen for the quality of music where the self-expression is unambiguous, where the harmonic richness creates a sense of abundance, where the overall effect is one of radiance and celebration. Leo's sonic character is confidence, generosity, and the sound of creative vitality.`,
  },

  SIGN_VIRGO: {
    key: 'SIGN_VIRGO',
    sign: 'VIRGO',
    element: 'earth',
    modality: 'mutable',
    title: 'Virgo',
    core: `Virgo is the archetype of discernment, the principle of refinement, and the capacity to notice what is imperfect and work toward making it functional. As mutable earth, Virgo represents the moment when the tangible world is not accepted as it is but is instead analyzed, categorized, and improved. The Virgo signature in a chart describes a dimension of the psyche that is oriented toward practical service, toward the craft of making things work better, and toward the humility that comes from recognizing that perfection is asymptotic—always approachable but never fully achieved. Psychologically, Virgo is the archetype of the healer, the craftsperson, the editor who understands that excellence emerges through iteration rather than inspiration. It is not interested in grand visions. It is interested in the thousand small adjustments that convert a rough draft into a finished work, that turn chaos into order, that make daily life more functional and less painful. Virgo knows the world through attention to detail. It notices what others overlook—the gap between stated intention and actual execution, the inefficiency that everyone else has learned to tolerate, the small flaw that undermines the larger structure. Virgo is the part of the self that knows useful work is sacred, that care for the body and the immediate environment is not trivial but essential, and that criticism is a form of care when it is offered in service of improvement rather than as judgment.`,
    behavioral: `Behaviorally, Virgo expresses as precision, competence, and self-criticism. A person with strong Virgo emphasis is skilled, reliable, and capable of producing work that is both functional and refined. They are the ones who notice what needs fixing, who organize chaos into systems, who can be counted on to deliver quality rather than just completing the task. Virgo does not tolerate sloppiness in themselves or others. Standards are high, and the gap between what is and what could be is always visible. This can manifest as perfectionism—the inability to release work because it is never quite good enough—or as genuine excellence, where the capacity to refine produces results of unusual quality. The psychological challenge for Virgo is learning to distinguish between useful discernment and destructive self-criticism. Virgo sees flaws everywhere, including in the self, and without compassion this becomes a form of internal violence. But at its best, Virgo is the capacity for genuine service: the ability to make things work better, to care for the body and the world with practical intelligence, and to offer criticism that genuinely helps rather than simply identifying what is wrong.`,
    friendship: `In friendship, Virgo brings competence, practical help, and the willingness to show up in tangible ways. The Virgo friend is the one who helps you move, who edits your resume, who notices when you're struggling and offers concrete assistance. They are not effusive in their affections, but their care is real and demonstrated through action. The Virgo friend needs the bond to feel useful and reciprocal. They give practical support generously but need to know their contributions are valued. Friendships that are purely emotional or that do not include practical exchange feel ungrounded. The friendship thrives when it includes shared work or shared problem-solving, and when competence is mutual rather than one-directional. Virgo can be hurt by friends who are chronically disorganized or who expect Virgo to fix everything without reciprocation. The friendships that last are those that honor Virgo's need to be useful, that reciprocate practical care, and that understand that Virgo's criticism is offered in service of improvement rather than as judgment.`,
    romantic: `In romance, Virgo brings devotion, practical care, and the desire to make the partnership function well. The Virgo romantic shows love through acts of service—cooking, organizing, taking care of the details that make life easier. They are not naturally demonstrative with words or grand gestures, but their care is visible in the small daily acts of maintenance and improvement. The challenge for Virgo in partnership is the tendency to focus on what is wrong rather than what is working, to criticize the partner in ways that feel like rejection rather than help. The partner who works well with Virgo receives their practical care as love, tolerates their need for order and routine, and participates in making the relationship function smoothly. Partnerships that honor Virgo create shared systems and routines, honor the body's needs through healthy habits, and treat practical competence as a legitimate form of intimacy. Virgo in romance is not cold—it is care expressed through function rather than through feeling.`,
    feed: `Virgo energy is active in the current sky. The capacity to notice what needs refinement, to organize what is chaotic, and to serve what is useful are all stronger right now. This is a time for precision, for improvement, for making things work better through small, careful adjustments.`,
    sonic: `Virgo contributes clean, precise melodic lines, careful voice leading, and harmonic language that is functional rather than decorative. The rhythm is accurate and controlled, not loose or approximate, with a quality of measured precision. The harmonic language is clear and economical—nothing extraneous, every note serving a purpose, voicings that are efficient rather than lush. The melodic phrases are well-crafted and refined, moving through logical progressions, nothing wasted. Virgo's sound is clean and transparent, not thick or cluttered. Listen for the quality of music where every element has been considered, where the structure is elegant because it is efficient, where the overall effect is one of competence and refinement. Virgo's sonic character is precision, discernment, and the craft of making things work well.`,
  },

  SIGN_LIBRA: {
    key: 'SIGN_LIBRA',
    sign: 'LIBRA',
    element: 'air',
    modality: 'cardinal',
    title: 'Libra',
    core: `Libra is the archetype of balance, the principle of relationship, and the capacity to perceive beauty in symmetry and harmony. As cardinal air, Libra represents the moment when the self recognizes it exists in relation to others, when individual perspective must be balanced against other perspectives, when fairness and aesthetic coherence become organizing principles. The Libra signature in a chart describes a dimension of the psyche that is oriented toward partnership, toward the creation of harmony and beauty, and toward the negotiation of competing needs without losing the essential quality of graceful equilibrium. Psychologically, Libra is the archetype of the diplomat, the artist, the one who understands that relationship is not the subordination of self to other but the co-creation of something neither could produce alone. It is not interested in domination or isolation. It is interested in the dance between autonomy and connection, in the aesthetic pleasure of well-balanced composition, and in the social intelligence that makes cooperation possible. Libra knows the world through relationship and aesthetic perception. It does not trust what is ugly or what is solitary. Truth must be beautiful and must be arrived at through dialogue or it remains partial and unconvincing. Libra is the part of the self that knows we are incomplete alone, that beauty is a form of intelligence, and that fairness is not weakness but the foundation of sustainable social life.`,
    behavioral: `Behaviorally, Libra expresses as social grace, indecisiveness, and the need for partnership. A person with strong Libra emphasis is charming, diplomatic, and capable of seeing multiple sides of any question. They are the ones who mediate conflicts, who create beautiful environments, who make social situations feel pleasant and balanced. Libra does not decide quickly. Every choice requires weighing options, considering others' perspectives, and attempting to find the solution that offends no one and preserves harmony. This can manifest as chronic indecision—the inability to choose because every option has legitimate merit—or as genuine fairness, where the capacity to hold multiple perspectives produces decisions that are genuinely just. The psychological challenge for Libra is learning to tolerate necessary conflict when harmony is not actually available. Libra can suppress its own needs in service of keeping the peace, creating resentment that eventually destabilizes the very harmony it was trying to preserve. But at its best, Libra is the capacity for genuine partnership: the ability to balance self and other without losing either, to create beauty that serves life, and to negotiate conflict in ways that preserve relationship.`,
    friendship: `In friendship, Libra brings grace, fairness, and the creation of social harmony. The Libra friend is the one who makes sure everyone is included, who mediates when tensions arise, who creates the conditions where the group can function smoothly. They are considerate, thoughtful about how their actions affect others, and genuinely committed to fairness. The Libra friend needs the bond to feel balanced and reciprocal. They give consideration and expect it in return. Friendships that are one-sided or that involve chronic conflict feel exhausting. The friendship thrives when it includes aesthetic pleasure—beauty, art, good conversation in pleasant settings—and when fairness is mutual. Libra can be hurt by friends who are selfish or who create unnecessary drama. The friendships that last are those that honor Libra's need for balance, that reciprocate consideration, and that understand that Libra's avoidance of conflict is not dishonesty but a legitimate preference for harmony.`,
    romantic: `In romance, Libra brings partnership, romance, and the desire to create beauty together. The Libra romantic is built for relationship—they do not thrive alone, and partnership is central to their sense of identity. They are attentive to their partner's needs, committed to fairness, and invested in creating a relationship that is aesthetically and emotionally beautiful. The challenge for Libra in partnership is the tendency to accommodate excessively, suppressing their own needs in order to keep the peace until resentment builds. The partner who works well with Libra honors their need for harmony but also creates space for honest disagreement, participates in making decisions together, and shares their commitment to creating beauty in the partnership. Partnerships that honor Libra create aesthetic pleasure together, negotiate conflict fairly, and treat relationship itself as the central project rather than as a means to other ends.`,
    feed: `Libra energy is active in the current sky. The pull toward partnership, the desire for fairness and beauty, and the capacity to see multiple perspectives are all stronger right now. This is a time for balance, for collaboration, for creating harmony rather than forcing resolution.`,
    sonic: `Libra contributes balanced, symmetrical melodic phrases, elegant harmonic progressions, and a rhythm that is graceful and measured. The harmonic language is beautiful and consonant—carefully voiced chords that resolve smoothly, nothing harsh or abrupt. The rhythm is flowing and balanced, neither rushed nor dragging. The melodic phrases are lyrical and well-proportioned, moving through graceful intervals, creating a sense of symmetry and aesthetic pleasure. Libra's sound is refined and beautiful, not rough or aggressive. Listen for the quality of music where every element is in balance, where the harmonic progressions create a sense of rightness and completion, where the overall effect is one of beauty and grace. Libra's sonic character is balance, partnership, and the pleasure of aesthetic coherence.`,
  },

  SIGN_SCORPIO: {
    key: 'SIGN_SCORPIO',
    sign: 'SCORPIO',
    element: 'water',
    modality: 'fixed',
    title: 'Scorpio',
    core: `Scorpio is the archetype of transformation, the principle of depth, and the capacity to face what is hidden, denied, or feared. As fixed water, Scorpio represents the moment when emotional intensity is not diffused but concentrated, when the psyche turns its full attention to what lies beneath the surface, when power is recognized as something to be claimed rather than avoided. The Scorpio signature in a chart describes a dimension of the psyche that is oriented toward penetration rather than surface engagement, toward the confrontation with shadow material, and toward the experience of death and rebirth as an ongoing psychological process. Psychologically, Scorpio is the archetype of the shaman, the depth psychologist, the one who understands that genuine transformation requires descent into what is uncomfortable, painful, or taboo. It is not interested in pleasant surfaces. It is interested in what is real, even when reality is ugly or terrifying. Scorpio knows the world through intensity and through power dynamics. It does not trust what is superficial or what is claimed without evidence. Truth must be tested through crisis or it remains theoretical. Scorpio is the part of the self that knows some forms of growth require destruction of what came before, that power must be acknowledged and negotiated rather than denied, and that intimacy without depth is not intimacy at all.`,
    behavioral: `Behaviorally, Scorpio expresses as intensity, secrecy, and the need for control. A person with strong Scorpio emphasis is emotionally powerful, perceptive about hidden motives, and capable of sustained focus on what matters to them. They are the ones who see beneath the surface, who ask the questions others are afraid to ask, who will not accept evasion or deflection. Scorpio does not reveal itself easily. Trust is earned slowly and tested rigorously. Vulnerability is shared only when safety has been established, and even then it is given incrementally. This can manifest as paranoia—the inability to trust anyone fully—or as genuine discernment, where the capacity to read people accurately protects against real danger. The psychological challenge for Scorpio is learning to tolerate powerlessness when control is not actually available. Scorpio fears betrayal and loss, and the attempt to prevent these through total control can produce the very abandonment it was trying to avoid. But at its best, Scorpio is the capacity for genuine transformation: the willingness to face what is terrifying, to allow what is dead to die, and to trust that renewal is possible even after complete breakdown.`,
    friendship: `In friendship, Scorpio brings loyalty, depth, and the willingness to face difficulty. The Scorpio friend is the one who sees the parts of you others miss, who can hold your darkest material without flinching, who will stand by you through crisis when others have disappeared. They are fiercely protective of the people they trust, and they expect that loyalty to be reciprocated. The Scorpio friend needs the bond to be emotionally real and exclusive. They do not do casual connection. Friendships that stay on the surface or that include too many people feel diluted and unsatisfying. The friendship thrives when it includes genuine emotional intimacy, when secrets can be shared safely, and when both people are willing to face uncomfortable truths together. Scorpio can be hurt by betrayal—real or perceived—and they do not forgive easily. The friendships that last are those that honor Scorpio's need for depth and loyalty, that reciprocate intensity, and that understand that Scorpio's secrecy is protection rather than dishonesty.`,
    romantic: `In romance, Scorpio brings passion, depth, and the desire for complete union. The Scorpio romantic is not interested in casual connection or surface-level intimacy. They want to know their partner completely, to merge at every level—physical, emotional, psychological. Sexual intimacy is central and is experienced as a form of transformation rather than simply as physical pleasure. The challenge for Scorpio in partnership is the fear of betrayal that can produce possessiveness and attempts at control. Scorpio wants total access and total loyalty, and the partner's autonomy can feel threatening. The partner who works well with Scorpio honors their need for depth and exclusivity, tolerates their intensity without being overwhelmed, and participates in the ongoing work of facing shadow material together. Partnerships that honor Scorpio create genuine intimacy, face power dynamics directly, and treat transformation as the central purpose of the relationship.`,
    feed: `Scorpio energy is active in the current sky. The pull toward depth, the capacity to face what is hidden, and the need to transform what is no longer viable are all stronger right now. This is a time for intensity, for truth-telling, for allowing necessary death and regeneration.`,
    sonic: `Scorpio contributes dense harmonic textures, chromatic melodic movement, and a rhythm that is inexorable and driving. The harmonic language is dark and complex—thick voicings in low registers, minor keys with added tensions, dissonances that create a sense of unease. The rhythm is relentless, moving forward with a sense of fate or inevitability. The melodic phrases are chromatic and descending, moving through half-steps, creating tension that does not easily resolve. Scorpio's sound is heavy and intense, not light or transparent. Listen for the quality of music where the emotional register is depth and power, where the harmonic density creates a sense of weight and gravity, where the overall effect is one of confrontation and transformation. Scorpio's sonic character is intensity, depth, and the sound of something that cannot be avoided.`,
  },

  SIGN_SAGITTARIUS: {
    key: 'SIGN_SAGITTARIUS',
    sign: 'SAGITTARIUS',
    element: 'fire',
    modality: 'mutable',
    title: 'Sagittarius',
    core: `Sagittarius is the archetype of exploration, the principle of meaning-making, and the capacity to see beyond immediate circumstances toward larger possibilities. As mutable fire, Sagittarius represents the moment when the flame becomes mobile rather than fixed, when the quest for understanding propels the self outward into unfamiliar territory, when direct experience becomes the teacher rather than abstract theory. The Sagittarius signature in a chart describes a dimension of the psyche that is oriented toward expansion, toward the search for truth and meaning, and toward the optimistic belief that life is an adventure worth undertaking. Psychologically, Sagittarius is the archetype of the philosopher, the traveler, the one who understands that wisdom comes through encounter with what is foreign and that growth requires leaving the safety of the known. It is not interested in staying put. It is interested in what lies beyond the horizon, in the synthesis of diverse experiences into coherent meaning, and in the freedom to follow curiosity wherever it leads. Sagittarius knows the world through exploration and belief. It does not trust what has not been experienced directly. Abstract principles must be tested in the field or they remain suspect. Sagittarius is the part of the self that knows life without meaning is not worth living, that truth is found through inquiry rather than received as doctrine, and that the courage to leave home is as important as the ability to create one.`,
    behavioral: `Behaviorally, Sagittarius expresses as enthusiasm, restlessness, and the need for freedom. A person with strong Sagittarius emphasis is optimistic, adventurous, and capable of finding meaning in difficult experiences. They are the ones who travel, who seek out new perspectives, who remain curious even when others have become cynical. Sagittarius does not commit easily to narrow paths. The world is full of possibilities, and choosing one means foreclosing on exploration of the others. This can manifest as chronic restlessness—the inability to settle because something more interesting is always just beyond reach—or as genuine philosophical breadth, where the capacity to synthesize across diverse experiences produces wisdom. The psychological challenge for Sagittarius is learning to commit to depth when breadth is more naturally appealing. Sagittarius can become a perpetual beginner, sampling many things without mastering any. But at its best, Sagittarius is the capacity for genuine wisdom: the ability to learn from experience, to find meaning in suffering, and to maintain optimism without denying reality.`,
    friendship: `In friendship, Sagittarius brings enthusiasm, humor, and the invitation to expand. The Sagittarius friend is the one who suggests the road trip, who introduces new ideas and perspectives, who makes you laugh even when things are difficult. They are generous, honest to the point of bluntness, and genuinely interested in your growth. The Sagittarius friend needs the bond to allow for freedom and exploration. Friendships that are possessive or that require constant presence feel suffocating. They need friends who can match their energy for adventure, who can handle blunt honesty, and who understand that Sagittarius's occasional absence is not neglect but the natural rhythm of someone who moves through many commitments. The friendship thrives when it includes shared exploration—whether physical travel or intellectual inquiry—and when both people support each other's growth rather than trying to keep each other small. Sagittarius can frustrate friends who need reliability and depth. The friendships that last are those that honor Sagittarius's need for freedom, that receive their honesty as care, and that participate in the ongoing quest for meaning.`,
    romantic: `In romance, Sagittarius brings passion, honesty, and the desire to explore life together. The Sagittarius romantic needs a partner who is interesting, who shares their enthusiasm for growth and discovery, and who does not try to contain their expansive energy. They are direct in their affections, generous with their enthusiasm, and committed to the idea that partnership should expand both people rather than limiting them. The challenge for Sagittarius in long-term partnership is the fear of being trapped. Sagittarius needs freedom even within commitment, and a partner who is possessive or who requires constant togetherness feels like imprisonment. The partner who works well with Sagittarius maintains their own autonomy, participates in shared adventures, and understands that Sagittarius's need for space is not a rejection of the relationship. Partnerships that honor Sagittarius create room for individual exploration alongside shared growth, welcome honesty even when it is uncomfortable, and treat the relationship as an ongoing adventure rather than as a settled arrangement.`,
    feed: `Sagittarius energy is active in the current sky. The desire to explore, to find meaning, and to expand beyond current limitations is stronger right now. This is a time for optimism, for taking risks, for following curiosity rather than staying safely within the known.`,
    sonic: `Sagittarius contributes expansive melodic gestures, adventurous harmonic movement, and a rhythm that is energetic and forward-driving. The harmonic language is exploratory—modulating to distant keys, visiting unexpected tonal centers, not staying in one place for long. The rhythm is lively and optimistic, with a sense of forward momentum and adventure. The melodic phrases are wide-ranging, leaping through large intervals, reaching outward and upward. Sagittarius's sound is bright and open, not contained or restrained. Listen for the quality of music where the sense is one of possibility and expansion, where the harmonic journey takes unexpected turns, where the overall effect is one of enthusiasm and discovery. Sagittarius's sonic character is exploration, optimism, and the sound of the quest for meaning.`,
  },

  SIGN_CAPRICORN: {
    key: 'SIGN_CAPRICORN',
    sign: 'CAPRICORN',
    element: 'earth',
    modality: 'cardinal',
    title: 'Capricorn',
    core: `Capricorn is the archetype of mastery, the principle of enduring achievement, and the capacity to build structures that outlast the individual who built them. As cardinal earth, Capricorn represents the moment when tangible ambition is claimed, when the self commits to long-term goals that require sustained discipline, when legacy becomes more important than immediate comfort. The Capricorn signature in a chart describes a dimension of the psyche that is oriented toward authority and responsibility, toward the slow accumulation of genuine competence, and toward the understanding that some forms of value can only be created through time and deliberate effort. Psychologically, Capricorn is the archetype of the elder, the master craftsperson, the one who understands that excellence is not a shortcut but a mountain that must be climbed step by step. It is not interested in flash or novelty. It is interested in what endures, in what can be relied upon when everything else has failed, and in the dignity that comes from accepting responsibility rather than avoiding it. Capricorn knows the world through structure and through time. It does not trust what is easy or what arrives without effort. Mastery must be earned through repetition and failure or it is not genuine. Capricorn is the part of the self that knows genuine achievement requires sacrifice, that authority must be earned rather than claimed, and that legacy is built through daily discipline rather than through singular heroic acts.`,
    behavioral: `Behaviorally, Capricorn expresses as ambition, discipline, and emotional restraint. A person with strong Capricorn emphasis is goal-oriented, responsible, and capable of sustained effort toward long-term objectives. They are the ones who plan carefully, who work steadily toward mastery, who can delay gratification indefinitely in service of larger goals. Capricorn does not waste energy on pursuits that will not yield lasting results. Every action is strategic. Every commitment is assessed for whether it serves the long-term vision. This can manifest as coldness—the suppression of feeling in service of achievement—or as genuine strength, where the capacity for discipline produces results of unusual quality and endurance. The psychological challenge for Capricorn is learning to allow warmth and spontaneity when everything in the psyche is organized around control and achievement. Capricorn can become so focused on the climb that it forgets to enjoy the view. But at its best, Capricorn is the capacity for genuine mastery: the willingness to do the work that others will not do, to build slowly and solidly, and to accept responsibility as a form of power rather than as a burden.`,
    friendship: `In friendship, Capricorn brings reliability, loyalty, and the willingness to be a stabilizing force. The Capricorn friend is the one who shows up consistently, who can be counted on in crisis, who offers practical advice rather than empty reassurance. They are serious, sometimes to the point of being heavy, and they do not do casual connection well. The Capricorn friend needs the bond to feel substantive and enduring. They invest slowly but deeply, and they expect that investment to be honored. Friendships that are flighty or emotionally volatile feel unstable and exhausting. The friendship thrives when it includes mutual respect, shared goals or projects, and the recognition that Capricorn's seriousness is not coldness but commitment. Capricorn can be experienced as emotionally distant by friends who need constant warmth. The friendships that last are those that honor Capricorn's need for structure and responsibility, that reciprocate loyalty, and that understand that Capricorn's restraint is protection rather than indifference.`,
    romantic: `In romance, Capricorn brings commitment, stability, and the desire to build something enduring. The Capricorn romantic does not enter partnership lightly—they assess whether the relationship has genuine potential before investing fully, but once committed, they are remarkably steadfast. They show love through provision and reliability rather than through grand romantic gestures. The challenge for Capricorn in partnership is the difficulty accessing and expressing vulnerability. Capricorn's defenses are strong, and the partner may experience them as emotionally unavailable even when Capricorn is genuinely devoted. The partner who works well with Capricorn honors their need for respect and competence, participates in building shared goals and structures, and creates safety for emotional vulnerability without demanding it prematurely. Partnerships that honor Capricorn build enduring achievement together, honor responsibility as a form of love, and treat commitment as demonstrated through sustained action.`,
    feed: `Capricorn energy is active in the current sky. The pull toward long-term goals, the capacity for discipline and structure, and the willingness to accept responsibility are all stronger right now. This is a time for ambition, for building, for committing to what endures.`,
    sonic: `Capricorn contributes austere harmonic voicings, slow deliberate rhythm, and melodic lines that are grounded and serious. The harmonic language is spare and economical—simple triads without ornament, voicings that emphasize the bass register, nothing frivolous. The rhythm is measured and controlled, with long note values and a sense of gravity. The melodic phrases are restrained, moving through small intervals, staying within defined limits. Capricorn's sound is solid and weighty, not light or playful. Listen for the quality of music where structure and discipline are more important than beauty, where every element has been considered and nothing is wasted, where the overall effect is one of endurance and seriousness. Capricorn's sonic character is mastery, responsibility, and the architecture of lasting achievement.`,
  },

  SIGN_AQUARIUS: {
    key: 'SIGN_AQUARIUS',
    sign: 'AQUARIUS',
    element: 'air',
    modality: 'fixed',
    title: 'Aquarius',
    core: `Aquarius is the archetype of the collective, the principle of equality, and the capacity to see systems rather than individuals. As fixed air, Aquarius represents the moment when thought solidifies into ideology, when individual perspective is subordinated to collective good, when innovation serves liberation rather than personal advancement. The Aquarius signature in a chart describes a dimension of the psyche that is oriented toward the future, toward the dismantling of hierarchies that no longer serve, and toward the understanding that genuine freedom requires structural change rather than individual escape. Psychologically, Aquarius is the archetype of the revolutionary, the humanitarian, the one who understands that we are all interconnected and that injustice anywhere diminishes us everywhere. It is not interested in personal power. It is interested in the distribution of power, in the creation of systems that serve collective flourishing, and in the intellectual frameworks that make liberation thinkable. Aquarius knows the world through ideas and through social structures. It does not trust what serves only the individual. Truth must be universal and must serve the common good or it is suspect. Aquarius is the part of the self that knows we are fundamentally equal, that hierarchy is constructed rather than natural, and that the future does not have to replicate the past.`,
    behavioral: `Behaviorally, Aquarius expresses as intellectual independence, social concern, and emotional detachment. A person with strong Aquarius emphasis is original, humanitarian, and capable of seeing patterns that others miss. They are the ones who challenge conventions, who advocate for collective good, who think in terms of systems rather than personal relationships. Aquarius does not conform easily. Traditional authority is questioned rather than obeyed. Social norms are examined rather than absorbed. This can manifest as alienation—the experience of being perpetually outside conventional social structures—or as genuine innovation, where the capacity to think independently produces insights that transform collective understanding. The psychological challenge for Aquarius is learning to tolerate the messiness of individual human emotion when abstract principles are cleaner and more satisfying. Aquarius can become so committed to ideals that actual people become inconvenient. But at its best, Aquarius is the capacity for genuine vision: the ability to see what could be rather than what is, to work toward collective liberation, and to treat equality as a structural requirement rather than as a nice sentiment.`,
    friendship: `In friendship, Aquarius brings intellectual stimulation, egalitarianism, and connection to larger communities. The Aquarius friend is the one who introduces you to new people and ideas, who treats everyone as equal regardless of social status, who organizes around causes rather than just talking about them. They are loyal in their own way—not through emotional intensity but through showing up for what matters. The Aquarius friend needs the bond to feel intellectually engaging and socially meaningful. Friendships that are purely personal or that do not include larger purpose feel narrow. They need friends who can engage with ideas, who share their social concerns, and who understand that Aquarius's emotional distance is not coldness but a different way of relating. The friendship thrives when it includes shared intellectual or social pursuits, when both people are treated as equals, and when the bond connects to something larger than just the two individuals. Aquarius can frustrate friends who need emotional intimacy. The friendships that last are those that honor Aquarius's need for intellectual freedom and social purpose, that don't demand constant emotional processing, and that participate in collective work.`,
    romantic: `In romance, Aquarius brings friendship, intellectual connection, and the desire for an egalitarian partnership. The Aquarius romantic needs a partner who is interesting intellectually, who shares their social values, and who does not expect traditional romantic scripts. They are not naturally demonstrative with emotion or physical affection—they show love through intellectual engagement, through supporting the partner's autonomy, and through working together toward shared ideals. The challenge for Aquarius in long-term partnership is the difficulty with emotional intimacy when intellectual connection feels safer and more natural. The partner who works well with Aquarius honors their need for independence, engages with them intellectually, and participates in their commitment to larger social good. Partnerships that honor Aquarius treat both people as equals, create space for individual freedom within commitment, and understand that love for Aquarius is demonstrated through respect for autonomy and shared purpose rather than through traditional romance.`,
    feed: `Aquarius energy is active in the current sky. The capacity to see systems clearly, to imagine alternative futures, and to work toward collective good are all stronger right now. This is a time for intellectual independence, for challenging what is unjust, for connecting individual action to collective liberation.`,
    sonic: `Aquarius contributes unusual harmonic choices, unexpected rhythmic patterns, and a quality of intellectual clarity and detachment. The harmonic language is innovative—using unconventional chord progressions, exploring dissonances that create interest rather than resolution, refusing to settle into predictable patterns. The rhythm is complex and often syncopated, creating a sense of intellectual engagement rather than physical groove. The melodic phrases are angular and unpredictable, avoiding singable or conventional contours. Aquarius's sound is bright and clear but emotionally cool, not warm or sensual. Listen for the quality of music where ideas are being explored, where the structure challenges expectations, where the overall effect is one of intellectual stimulation and innovation. Aquarius's sonic character is originality, equality, and the sound of thinking independently.`,
  },

  SIGN_PISCES: {
    key: 'SIGN_PISCES',
    sign: 'PISCES',
    element: 'water',
    modality: 'mutable',
    title: 'Pisces',
    core: `Pisces is the archetype of dissolution, the principle of compassion, and the capacity to experience the interconnection of all beings. As mutable water, Pisces represents the moment when boundaries between self and world become permeable, when the psyche opens to dimensions of experience that transcend ordinary reality, when empathy becomes so complete it approaches identification. The Pisces signature in a chart describes a dimension of the psyche that is oriented toward transcendence, toward the mystical or spiritual dimensions of experience, and toward the understanding that suffering is universal and that compassion is the only sane response. Psychologically, Pisces is the archetype of the mystic, the artist, the healer who understands that genuine connection requires the temporary dissolution of ego boundaries. It is not interested in logic or structure. It is interested in what is felt, imagined, dreamed, and intuited. Pisces knows the world through empathy and imagination. It does not trust what is rigid or what insists on clear categories. Reality is fluid, permeable, and more mysterious than rational mind can capture. Pisces is the part of the self that knows we are not separate, that the suffering of others is not fundamentally different from one's own suffering, and that the material world is not all that exists.`,
    behavioral: `Behaviorally, Pisces expresses as sensitivity, adaptability, and difficulty with boundaries. A person with strong Pisces emphasis is empathic to the point of absorbing others' emotional states, imaginative to the point where fantasy and reality blur, and capable of profound compassion. They are the ones who sense what is not being said, who respond to emotional undercurrents, who can hold space for suffering without trying to fix it immediately. Pisces does not maintain clear boundaries easily. The self is porous, permeable to others' emotions, moods, and expectations. This can manifest as chronic overwhelm—the inability to distinguish one's own feelings from those absorbed from the environment—or as genuine spiritual sensitivity, where the capacity to feel with others produces extraordinary compassion. The psychological challenge for Pisces is learning to ground and protect the self when permeability leaves one vulnerable to psychic overwhelm. Pisces can become lost in fantasy, addiction, or escapism when ordinary reality feels too harsh. But at its best, Pisces is the capacity for genuine compassion: the ability to feel with others without losing the self, to access transcendent states that renew rather than escape, and to bring imaginative vision into form that serves collective healing.`,
    friendship: `In friendship, Pisces brings compassion, imagination, and the capacity to meet others in their suffering. The Pisces friend is the one who sees beneath the surface, who does not judge, who offers forgiveness and acceptance even when it is not deserved. They are gentle, adaptable, and willing to sacrifice their own needs to preserve the bond. The Pisces friend needs the friendship to allow for emotional fluidity and creative expression. Friendships that are rigid or that demand constant clarity feel harsh. They need friends who can meet them in the realm of feeling and imagination, who do not weaponize their vulnerability, and who understand that Pisces's adaptability is not dishonesty but genuine fluidity. The friendship thrives when it includes shared creative or spiritual pursuits, when empathy is mutual, and when Pisces is not expected to be the only one who accommodates. Pisces can be hurt by friends who are emotionally harsh or who take advantage of their giving nature. The friendships that last are those that honor Pisces's sensitivity, that reciprocate compassion, and that create safety for their permeable boundaries.`,
    romantic: `In romance, Pisces brings devotion, imagination, and the desire for union that transcends the personal. The Pisces romantic is not interested in practical partnership alone—they want the relationship to feel sacred, to carry a quality of destiny or spiritual significance. They are self-sacrificing to a fault, often giving far more than they receive, hoping that their devotion will eventually be matched. The challenge for Pisces in partnership is the tendency to idealize the partner, to see potential rather than reality, and to accommodate to the point of self-erasure. The partner who works well with Pisces honors their sensitivity, participates in creating beauty and meaning together, and helps ground their vision in practical reality without dismissing it. Partnerships that honor Pisces create space for transcendence alongside embodiment, protect Pisces's permeable boundaries rather than exploiting them, and treat compassion as a mutual commitment rather than as something only Pisces provides.`,
    feed: `Pisces energy is active in the current sky. The capacity to feel deeply, to imagine alternative realities, and to experience interconnection with all beings is stronger right now. This is a time for compassion, for creative vision, for allowing the boundaries between self and world to soften.`,
    sonic: `Pisces contributes harmonic ambiguity, fluid rhythmic motion, and melodic lines that drift and dissolve. The harmonic language is suspended and unresolved—chords that float without clear tonal center, modal harmonies that shift between major and minor without committing. The rhythm is fluid and undefined, without sharp metric pulse, creating a sense of timelessness and drift. The melodic phrases are elusive and wandering, often obscured by layers of reverb and texture. Pisces's sound is soft, diffuse, and oceanic, not sharp or defined. Listen for the quality of music where boundaries dissolve, where you cannot tell where one element ends and another begins, where the overall effect is one of dreamlike immersion and transcendence. Pisces's sonic character is compassion, imagination, and the sound of dissolution into something larger than the self.`,
  },

} as const;
