/**
 * Astradio Insight Library — Personal Planet Pair Aspects (Batch 1)
 *
 * 30 objects: SUN_MOON, SUN_VENUS, SUN_MARS, MOON_VENUS, MOON_MARS, VENUS_MARS
 * × 5 aspect types (conjunction, sextile, square, trine, opposition)
 *
 * Keys: canonical derived strings from buildAspectKey()
 * Place at: vnext/projection/insight-library/insight-library-aspects-personal.ts
 */

import type { AspectInsight } from './insight-library-types';

export const PERSONAL_ASPECT_INSIGHTS: Readonly<Record<string, AspectInsight>> = {

  SUN_MOON_CONJUNCTION: {
    key: 'SUN_MOON_CONJUNCTION', pair: 'SUN_MOON', aspect: 'conjunction', intensity: 'Background',
    core: `The Sun, the seat of conscious will and purposeful identity, sits fused with the Moon, the keeper of emotional memory, instinctive need, and interior safety. Where a conjunction occurs, two planets operate as one undivided system. Here that means the sense of who you are and what you feel are not two separate conversations. They run along the same current. The conscious self does not experience itself as separate from the emotional self. What this person wants, they feel. What they feel, they identify with completely. This produces a powerful coherence of self that others often read as certainty, presence, or magnetism. Born near the new moon, this is a person at the beginning of a lunar cycle, oriented toward initiation rather than reflection.`,
    behavioral: `Because the Sun's ego-drive and the Moon's emotional instinct are fused rather than separate, this person's psychological decision-making runs on a single track rather than two competing ones. The persona and the interior feeling-self are unusually integrated. There is very little shadow material created by the tension between who they present as and who they feel themselves to be. Full commitment follows: when the Sun decides to move toward something, the Moon's emotional body is already on board, so the follow-through is total. There is no private second-guessing that contradicts the public self. The fusion also means the Moon's vulnerability is fully exposed at the level of identity. Emotional wounding is not cushioned by any psychological distance between feeling and self. A slight to their work, their choices, or their affections can register as an existential threat because what they feel and who they are genuinely cannot be separated.`,
    friendship: `Friends experience this person as consistent and fully present. What they say they want, they want. There is no gap between stated feelings and actual emotional state.`,
    romantic: `Partners feel the full force of this person's attention when they are loved. Relational wounds hit at the level of identity, because for this person feeling hurt and feeling threatened as a self are the same experience.`,
    feed: `The current sky is threading solar and lunar frequencies through this connection at the same pitch. A window of unusual alignment between intent and feeling is open right now between these two charts.`,
    sonic: `The Sun contributes a clear, forward-moving tonal center and a steady assertive pulse. The Moon contributes modal harmonic color and a breathing, tide-like rhythmic quality underneath. In the conjunction these two voices are fused rather than distinct. The result is a single unified sound where the Sun's purposeful melodic statements are felt from the inside, colored by the Moon's emotional register rather than simply projected outward. The rhythm has the Sun's regularity but the Moon's organic quality of breath. The harmonic language is major but with modal inflections that give the consonance an interior warmth, resolved but felt. Listen for the quality of a melody that knows exactly where it is going and also feels completely at home arriving there.`,
  },

  SUN_MOON_SEXTILE: {
    key: 'SUN_MOON_SEXTILE', pair: 'SUN_MOON', aspect: 'sextile', intensity: 'Low',
    core: `The Sun, conscious will and purposeful identity, and the Moon, emotional instinct and the interior need for safety, are in a 60-degree relationship of easy, compatible exchange. The sextile places them in neighboring territories that understand each other's language. The person's sense of purpose and their emotional nature are not in conflict. They communicate readily, each available to support the other when called upon.`,
    behavioral: `The sextile between the Sun's ego-function and the Moon's emotional instinct creates what psychologists would recognize as good ego-affect integration. The rational, goal-oriented self and the emotional feeling-self are in productive dialogue rather than opposition. The gap between what they intend to do and how they actually feel about doing it is small and manageable. What they notice is reliability: this person's stated feelings tend to match their actual emotional state, their commitments tend to stick, and their capacity to be present under stress is notably higher than in people whose Sun and Moon are in harder relationship.`,
    friendship: `Reliable, emotionally available without being overwhelming. Easy to be around because their inner life isn't constantly broadcasting friction.`,
    romantic: `Partners find them stable and consistent. The ease of this aspect means they don't generate unnecessary drama from internal conflict.`,
    feed: `Today's transit field is gently opening the channel between how each person directs themselves and what each needs emotionally. There is easier access between these two charts than usual right now.`,
    sonic: `The Sun contributes its steady, purposeful pulse and clear melodic direction. The Moon contributes modal harmonic warmth and an organic, breathing rhythmic quality. In the sextile these two voices cooperate rather than fuse. The Sun's forward-moving melodic lines are supported by the Moon's emotional harmonic coloring without being absorbed by it. The harmonic language moves between major and modal passages naturally, as if the music is alternating between thinking and feeling without effort. Listen for the quality of a melody that moves with purpose and also sounds emotionally at home.`,
  },

  SUN_MOON_SQUARE: {
    key: 'SUN_MOON_SQUARE', pair: 'SUN_MOON', aspect: 'square', intensity: 'Medium',
    core: `The Sun, the principle of conscious identity and willful becoming, meets the Moon, the principle of emotional memory, instinctive need, and interior safety, at a 90-degree angle of sustained tension. The square does not resolve easily because both forces are genuinely strong and neither naturally yields to the other. The Sun pushes toward what it wants to achieve. The Moon pulls toward what it needs to feel secure. These two imperatives are not aligned. The person experiences a real and recurring friction between their conscious goals and their emotional requirements, not as a character flaw but as an ongoing negotiation that is also the engine of significant psychological depth.`,
    behavioral: `The Sun's goal-orientation and the Moon's emotional self-protection are in a 90-degree conflict that neither can resolve by simply overriding the other. This manifests as a pattern where the person pursues something with genuine conviction only to find afterward that the emotional self was not consulted and is now quietly registering its objections through dissatisfaction, restlessness, or a sense of hollowness that doesn't match the outward achievement. The Moon's instinct for self-protection can also override the Sun's ambition at critical moments, producing hesitations or retreats that puzzle others who see only the capable, driven exterior. The development work this aspect demands is the capacity to deliberately slow down the Sun's decisiveness long enough to take a genuine read from the Moon before committing.`,
    friendship: `Friends may notice inconsistency between stated goals and actual emotional responses. This person might say they're fine when they're not, not dishonestly, but because the Sun has genuinely overridden the signal the Moon is sending.`,
    romantic: `Partners need patience with the internal processing this person requires. The square creates genuine richness and depth. They are rarely psychologically shallow, but emotional availability requires intentional cultivation rather than automatic access.`,
    feed: `The current sky is pressing on the tension between directional will and emotional need in this connection. Something that usually hums beneath the surface between these two charts is asking to be named today.`,
    sonic: `The Sun pushes its melody forward with purposeful assertion. The Moon pulls the harmonic language toward modal ambiguity and emotional cycling. In the square these two sonic characters are in genuine friction. The Sun's clear, resolving harmonic language is interrupted by the Moon's suspended, unresolved harmonic coloring, and the Moon's organic rhythmic breath is cut across by the Sun's assertive pulse. The result is a composition where moments of clear melodic direction are followed by passages of harmonic uncertainty. The music makes a statement and then the emotional undertow questions it. Listen for the quality of a melody that begins with confidence and then encounters harmonic weather it did not plan for, and has to find its way through rather than around.`,
  },

  SUN_MOON_TRINE: {
    key: 'SUN_MOON_TRINE', pair: 'SUN_MOON', aspect: 'trine', intensity: 'Low',
    core: `The Sun, conscious will and the drive toward purposeful self-expression, and the Moon, emotional instinct, memory, and the body's need for safety, are separated by 120 degrees, placing them in the same elemental family. The trine means these two forces do not experience each other as foreign. The Sun's direction and the Moon's instinct are oriented toward compatible ends, using the same emotional vocabulary, reaching naturally toward similar conclusions.`,
    behavioral: `The trine between the Sun's ego-function and the Moon's feeling-function creates what psychologists would describe as a well-integrated emotional identity. The Sun's capacity for purposeful action and the Moon's instinct for emotional self-care are not competing for psychological resources, which means very little energy is lost to internal conflict. Feelings match stated intentions, mood tends to support rather than undermine goals, and the capacity for recovery after difficulty is strong. The psychological shadow is that without inner tension as a developmental driver, the person may remain at a level of psychological development that is comfortable but not particularly deep.`,
    friendship: `Warm, consistent, easy to be with. Friends return to them because the relationship doesn't cost much emotional labor.`,
    romantic: `Partners often cite this person's steadiness as central to what makes the relationship sustainable.`,
    feed: `Today's transits are amplifying the natural coherence running between these two charts. What flows easily in this connection is flowing more easily right now, and there is something worth hearing in that.`,
    sonic: `The Sun contributes its warm, purposeful melodic direction and clear major tonality. The Moon contributes its modal harmonic richness and organic rhythmic breath. In the trine these two forces do not need to negotiate. The Sun's melodic statements are naturally colored by the Moon's emotional warmth without any friction between the two. The harmonic language is both resolved and emotionally rich simultaneously, major tonality with modal depth, purposeful progression with organic breathing rhythm underneath. Listen for the quality of music that feels both emotionally true and directionally certain at the same time, where the melody and the harmonic coloring behind it seem to have been made for each other.`,
  },

  SUN_MOON_OPPOSITION: {
    key: 'SUN_MOON_OPPOSITION', pair: 'SUN_MOON', aspect: 'opposition', intensity: 'Medium-high',
    core: `The Sun, conscious identity, willful direction, and the ego's drive to define itself, stands opposite the Moon, emotional memory, instinctive need, and the interior self that feels and seeks safety, across a 180-degree axis of full polarity. Born near the full moon, this person was born into a moment of maximum tension between the two luminaries. The opposition holds these forces apart and in constant awareness of each other. The Sun knows the Moon is there. The Moon feels the Sun's pull. Neither can simply ignore the other.`,
    behavioral: `The psychological mechanism of the Sun-Moon opposition is what Jung mapped as the tension between the ego and the unconscious, but in this chart that tension is unusually conscious and unusually relational. Where the square produces internal friction that stays mostly inside, the opposition tends to externalize. This person processes the tension between their conscious will and their emotional nature through relationship, projection, and dialogue with others. The person who seems intensely driven one week and entirely oriented toward home and emotional processing the next is not being erratic. Both poles are entirely real. Other people become essential for this person's psychological integration in a way that is less true for other configurations.`,
    friendship: `Friends are often important sounding boards for this person's internal dialogue. The friendship carries weight because it serves a function that goes beyond companionship.`,
    romantic: `Partnership is a primary arena of psychological growth. The partner functions as the external anchor for the internal polarity.`,
    feed: `The current sky is illuminating both ends of this connection's axis at once. The pull between outward direction and interior feeling is more visible between these two charts today than it usually is, and more workable.`,
    sonic: `The Sun and Moon in opposition produce a composition built on call and response. The two sonic identities are at maximum distance from each other and in constant dialogue across that distance. The Sun's assertive, forward-moving melodic statements are answered by the Moon's cycling, memory-driven, modally ambiguous responses. The rhythm alternates between the Sun's steady pulse and the Moon's organic, breathing quality. Neither fully dominates for long. The harmonic language moves between major resolution and modal suspension in a cycling pattern that feels like two voices in genuine conversation. Listen for the quality of music where a clear statement is made and then a feeling responds to it.`,
  },

  SUN_VENUS_CONJUNCTION: {
    key: 'SUN_VENUS_CONJUNCTION', pair: 'SUN_VENUS', aspect: 'conjunction', intensity: 'Background',
    core: `The Sun, the seat of conscious identity and the purposeful drive to define and express the self, fuses with Venus, the planet governing the capacity to love, aesthetic sensibility, relational value, and what the person finds beautiful and worthy of desire. When these two share the same degree, identity and value become one system. This person's sense of who they are is inseparable from what they love and what they find beautiful. Their aesthetic choices, their affections, and their relational life are not decorative additions to the self but expressions of identity itself. To be appreciated is not merely pleasant for this person. It is confirming at a deep level.`,
    behavioral: `The ego has been shaped in and through the experience of love and beauty rather than as something separate from it. The person's identity formation has been heavily mediated by the Venusian principle: what they find beautiful, who appreciates them, and how they are received relationally are not external validations of a pre-formed self but are actually constitutive of the self. The Sun's natural drive toward self-expression takes a Venusian form, expressing through charm, aesthetic refinement, and relational generosity rather than through assertion or competition. The psychological cost is a heightened sensitivity to aesthetic and relational rejection. Criticism of what they love or create or how they connect is not processed as feedback about a peripheral aspect of the self. It lands at the core of identity.`,
    friendship: `Generous, attentive, genuinely interested in the wellbeing of people they care about. They remember details. They create warmth deliberately.`,
    romantic: `Love is their primary medium of self-expression. When they are in love, it is total and visible. The challenge is distinguishing between genuine resonance and the validation that feels like resonance, both of which feel identical internally until they don't.`,
    feed: `The current sky is activating the place where identity and love overlap in this connection. How this person understands themselves is directly touching how they value this relationship right now, and that carries weight today.`,
    sonic: `The Sun contributes its warm, purposeful melodic direction and clear tonal center. Venus contributes rich consonant harmony, beautiful voice leading, and a sensory melodic warmth. In the conjunction these two voices fuse into a single unified sound. The Sun's directional clarity is expressed entirely through Venus's aesthetic register. The result is a composition of unusual melodic beauty with genuine structural purpose behind it. The phrases know where they are going and they arrive somewhere beautiful. The harmonic language is major with rich seventh-chord color, resolved but luxurious. Listen for the quality of a melody that moves with purpose and sounds genuinely beautiful at every step, where the direction and the beauty are the same thing.`,
  },

  SUN_VENUS_SEXTILE: {
    key: 'SUN_VENUS_SEXTILE', pair: 'SUN_VENUS', aspect: 'sextile', intensity: 'Low',
    core: `The Sun, conscious identity and willful self-expression, and Venus, the capacity for love, beauty, and relational attunement, are in a 60-degree relationship of easy, compatible exchange. The sextile places these two forces in neighboring elemental territories where they can communicate and cooperate without strain. The person's sense of self and their relational nature are not in competition. The Sun's need to express and define itself and Venus's pull toward connection and beauty share enough common ground that each supports the other without either being diminished.`,
    behavioral: `The sextile produces social competence that is genuine rather than performed. This person can read the emotional temperature of a room and respond to it without losing their own center, can express genuine warmth without becoming emotionally porous, and can be in relationship without the anxiety of merger that afflicts configurations where Venus and the Sun are more tensely aspected. The absence of friction between these two principles also means they tend to attract positive regard without particularly engineering it.`,
    friendship: `Easy, warm, low maintenance. Not dramatic. Reliable affection that doesn't demand reciprocal intensity.`,
    romantic: `Partners appreciate that this person knows how to be in relationship without consuming it. Present without being consuming.`,
    feed: `Today's transit field is easing the passage between self-expression and relational warmth in this connection. Contact between these charts has less internal friction than usual right now.`,
    sonic: `The Sun provides the directional architecture and Venus decorates that architecture with genuine aesthetic warmth. The melodic lines have purpose and also sound beautiful. The harmony is resolved with rich color tones that make the resolution feel like arrival at somewhere pleasant rather than merely somewhere correct. Listen for the quality of music where something purposeful is also beautiful, where the structural logic and the aesthetic pleasure are pointing in the same direction without either having to compromise.`,
  },

  SUN_VENUS_SQUARE: {
    key: 'SUN_VENUS_SQUARE', pair: 'SUN_VENUS', aspect: 'square', intensity: 'Medium',
    core: `The Sun, the principle of individual identity and purposeful becoming, meets Venus, the principle of love, relational harmony, and the magnetic draw toward beauty and connection, at a 90-degree angle of ongoing tension. The Sun wants to define and express the self on its own terms. Venus wants to attune, attract, and harmonize with others. These are not naturally compatible impulses. The square means neither force simply yields, and the person experiences a real and recurring pull between their individual ambitions and the accommodations that genuine relationship requires.`,
    behavioral: `The psychological tension is between the ego's need for autonomous self-definition and the Venusian imperative toward relational harmony and mutual attunement. The behavioral result is a pattern psychologists would recognize as approval-seeking with underlying resentment: the person accommodates and smooths because Venus is genuinely strong here and harmony genuinely matters, but the suppressed Sun eventually reasserts itself, sometimes through withdrawal, sometimes through an unexpected burst of self-assertion that surprises people who had experienced only the Venusian accommodation.`,
    friendship: `Warm and generous but may withdraw when the friendship starts requiring more than they currently have available. The withdrawal isn't rejection. It's the Sun reasserting its need for autonomous space after Venus has been running the show.`,
    romantic: `Partners may feel the push-pull of someone who genuinely wants closeness but flinches when it threatens the self. This creates a dynamic that requires direct conversation about what each person actually needs rather than assuming natural alignment.`,
    feed: `A transit is pressing on the negotiation point between individual drive and relational pull in this connection. What each person actually needs from the other is closer to the surface today than it usually is.`,
    sonic: `The Sun's assertive, purposeful melodic direction and Venus's beautiful, harmonically rich relational warmth are in friction in the square. The Sun pushes its melody forward toward its intended destination. Venus pulls the harmonic language toward aesthetic dwelling, wanting to stay in the beautiful harmony rather than progress to the next structural destination. Listen for the quality of music where something directional and something beautiful keep interrupting each other, where the melody sets off with confidence and then the harmonic beauty makes it linger when it should move, or moves when it should linger.`,
  },

  SUN_VENUS_TRINE: {
    key: 'SUN_VENUS_TRINE', pair: 'SUN_VENUS', aspect: 'trine', intensity: 'Low',
    core: `The Sun, conscious identity and the drive to define and express the self, and Venus, the capacity for love, beauty, and relational warmth, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces do not experience each other as competing demands. The person's sense of self and their relational nature speak the same language. The Sun's need to express itself finds a natural channel through the warmth and beauty that Venus governs. Charm is not a performance for this person. It is structural.`,
    behavioral: `The ego's self-expression and the Venusian capacity for love and beauty are drawing from the same elemental well rather than competing for resources. The social grace, the aesthetic sensibility, and the relational warmth are not performances layered over a different, more guarded interior. They are genuine expressions of how the ego actually functions. The shadow of this trine is that without inner tension as a developmental driver, the person is not forced to examine their relational patterns or confront the ways in which their desire for harmony might be avoiding rather than resolving difficulty.`,
    friendship: `These are the friendships people return to because they feel genuinely easy. Not absent of depth, but not emotionally costly. The warmth is reliable and unperformed.`,
    romantic: `Partners often describe a sense that being loved by this person feels natural, not effortful or strategic. The risk is that this ease can reduce urgency to grow relationally, since growth requires some friction and this aspect provides very little.`,
    feed: `The current sky is moving through the warmth center of this connection. The ease and genuine affection that runs between these two charts is more available and more noticeable right now than it is as a baseline.`,
    sonic: `The Sun and Venus are in the same elemental family in the trine. The Sun's purposeful melodic direction is expressed through Venus's aesthetic register without any friction between purpose and beauty. The harmonic language is major with rich color tones, resolved with warmth. The melody arrives somewhere beautiful because that is where it was always heading. Listen for the quality of music where you feel both the structure and the beauty at the same time, where what is purposeful and what is lovely are the same thing.`,
  },

  SUN_VENUS_OPPOSITION: {
    key: 'SUN_VENUS_OPPOSITION', pair: 'SUN_VENUS', aspect: 'opposition', intensity: 'Medium',
    core: `The Sun, individual identity and autonomous will, stands at full polarity with Venus, the principle of love, relational attunement, beauty, and the magnetic pull toward union with others. At 180 degrees, these two forces are on opposite ends of the same axis, each fully aware of the other but pulling in different directions. Independence and intimacy can feel like opposing gravitational forces for this person, not because they don't want both, but because the 180-degree tension makes it genuinely difficult to hold both at once.`,
    behavioral: `The Sun's individuation drive and Venus's attachment drive pull in opposite directions, which means the person experiences the approach of genuine closeness as a threat to the autonomous self, and the experience of autonomy as a form of loneliness that the Venus nature cannot sustain. The behavioral expression of this is a cycle of reaching toward intimacy and then pulling back toward independence, a rhythm that is entirely genuine on both ends but which can read as ambivalence or mixed signals to partners and close friends.`,
    friendship: `Significant friendships. Not casual. They invest fully or barely at all. The opposition doesn't do comfortable middle distances.`,
    romantic: `Partnership is a central arena of growth. The people who last as partners are those who can hold their own ground while remaining in genuine contact.`,
    feed: `Today's transits are lighting the axis between autonomy and closeness in this connection. The real distance between what each person needs from themselves and from each other is visible right now in a way worth examining.`,
    sonic: `The Sun and Venus in opposition produce a composition where two distinct sonic identities are in dialogue across maximum distance. The Sun's assertive, purposeful melodic statements are answered by Venus's rich, beautiful, harmonically warm responses, but the two voices are pulling in different directions. The Sun moves the composition forward. Venus wants it to dwell in beauty. Listen for the quality of music where something purposeful and something beautiful are in conversation but not agreement, where the music cannot decide whether to progress or to luxuriate, and that indecision itself becomes the emotional content.`,
  },

  SUN_MARS_CONJUNCTION: {
    key: 'SUN_MARS_CONJUNCTION', pair: 'SUN_MARS', aspect: 'conjunction', intensity: 'Medium-high',
    core: `The Sun, the principle of conscious identity and the purposeful drive toward self-definition, fuses with Mars, the planet governing raw drive, assertion, the instinct to pursue, and the force that moves a person toward what they want and away from what threatens them. When these two occupy the same degree, identity and drive become one unified force. This person does not experience themselves as someone who has drive. They experience drive as the expression of who they are. There is very little gap between decision and action, between desire and pursuit.`,
    behavioral: `The Sun-Mars conjunction creates a highly activated ego-will complex. The ego's identity function and Mars's aggressive, goal-seeking function are so fused that the person experiences their drive to pursue, compete, and assert as an expression of their core identity rather than as a tool the self deploys. Opposition to this person's actions or goals is not processed as feedback about the action. It is processed as a threat to the self. This produces the characteristic quality of force that people around this conjunction notice: not necessarily aggression, but a quality of energetic presence and directness that asserts itself even when the person is trying to be quiet.`,
    friendship: `Activating presence. Friends feel galvanized. The directness can be bracing for those who prefer more circuitous communication, but there is never any question about where this person stands.`,
    romantic: `Passionate and fully present. The same force that makes them magnetic early in relationship can become pressure if the partner doesn't have enough grounding to receive it without feeling consumed.`,
    feed: `The current sky is activating where force and identity converge in this connection. The energy running between these two charts is at a higher voltage right now than usual, and that charge is looking for direction.`,
    sonic: `The Sun contributes its assertive, purposeful melodic direction and clear forward pulse. Mars contributes its driving physical pulse, cutting tonal edge, and short incisive melodic gestures. In the conjunction these two voices are fused. The Sun's purposeful melodic statements are delivered with Mars's physical, driving energy. The rhythm is strong and assertive, the Sun's consistency amplified by Mars's physical downbeat weight. The harmonic language is clear and unambiguous, major tonality expressed with Mars's preference for open, powerful voicings. Listen for the quality of music where every element is moving forward and nothing is hesitating, where the melodic statement, the harmonic clarity, and the rhythmic drive are all pointing in the same direction at the same time with the same force.`,
  },

  SUN_MARS_SEXTILE: {
    key: 'SUN_MARS_SEXTILE', pair: 'SUN_MARS', aspect: 'sextile', intensity: 'Low',
    core: `The Sun, conscious identity and willful self-direction, and Mars, drive, assertion, and the force that converts desire into action, are in a 60-degree relationship of easy, functional cooperation. The sextile places these two forces in compatible elemental territories where they can draw on each other without generating friction. The Sun sets direction. Mars provides the energy to move in that direction. Neither undermines the other's function.`,
    behavioral: `The sextile between the Sun's identity-function and Mars's drive-function creates a stable, reliable relationship between intention and action. The person decides, and the energy to pursue that decision is available without requiring a significant internal negotiation first. This is not the explosive force of the conjunction. The Mars here is functional rather than fused into the identity. But it is consistently accessible. The result is productive reliability: they can sustain effort over time, recover from setbacks without a significant crash, and direct their energy toward chosen goals without it bleeding off into unfocused restlessness.`,
    friendship: `Good to have on your team. Shows up and follows through without drama about the effort involved.`,
    romantic: `Steady engagement. Their desire is present without being destabilizing.`,
    feed: `Today's transit field is moving through the productive channel between drive and direction in this connection. Momentum between these two charts is easier to access right now than it typically is.`,
    sonic: `The Sun provides the directional architecture and Mars provides the energetic fuel to move through that architecture without friction. The rhythm has the Sun's regularity and Mars's physical energy simultaneously, without either forcing the other. The melodic lines are purposeful and also energetically alive. Listen for the quality of music that moves with both purpose and energy, where the direction is clear and the forward momentum feels natural rather than forced.`,
  },

  SUN_MARS_SQUARE: {
    key: 'SUN_MARS_SQUARE', pair: 'SUN_MARS', aspect: 'square', intensity: 'High',
    core: `The Sun, the principle of conscious identity and purposeful direction, meets Mars, the planet of raw drive, assertion, and the force that moves the person toward desire and away from threat, at a 90-degree angle of genuine, sustained tension. Both of these forces are strong. The Sun insists on its chosen direction. Mars insists on its own momentum. The square means neither naturally yields, and the person's sense of who they are and the direction of their energy do not automatically agree.`,
    behavioral: `The Sun-Mars square creates a psychological configuration where the ego's goal-setting function and the Mars drive are perpetually in each other's way. The ego plans. Mars charges ahead of the plan. Or the ego is ready to move and Mars has already burned the available energy on something else. The Mars energy here is real and significant. This is not a low-drive person. But it has a quality of pressure that seeks release rather than direction. The development task is the cultivation of the directed will: the capacity to feel the full force of the Mars drive and then deliberately choose when and where to deploy it, rather than being driven by it reactively. The square is also a source of real power. When identity and drive are pointed at the same target, the output is formidable.`,
    friendship: `Activating, sometimes abrasive. The directness can feel aggressive to those who don't understand that it isn't personal. But this is also the friend who shows up fully in a crisis, when there's something real to fight for.`,
    romantic: `The Mars square creates heat. There is genuine passion here. But the friction between self and drive means conflict can arise even when unintended. Relationships that can hold vigorous honest exchange do far better than those requiring constant smoothness.`,
    feed: `A transit is pressing directly on the friction point between assertive drives in this connection. The tension that usually runs beneath the surface between these two charts is closer to the top today and will not be easy to ignore.`,
    sonic: `The Sun's purposeful melodic direction and Mars's driving, assertive force are in genuine friction in the square. The Sun wants to move toward its chosen destination with strategic clarity. Mars wants to move now, with maximum force, regardless of whether the strategic moment has arrived. The rhythm is high-energy but slightly at cross-purposes with the melodic direction. Listen for the quality of music where the energy and the direction are both strong but not perfectly synchronized, where the drive is real but the strategic clarity is delayed, and the music has to work through that friction rather than resolve it cleanly.`,
  },

  SUN_MARS_TRINE: {
    key: 'SUN_MARS_TRINE', pair: 'SUN_MARS', aspect: 'trine', intensity: 'Low-medium',
    core: `The Sun, conscious identity and the ego's purposeful drive toward self-expression, and Mars, the planet of assertion, drive, and the force that converts intention into action, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means the Sun's direction and Mars's energy move together without internal argument. The person does not have to manage the relationship between who they are and how they pursue what they want. The two inform each other naturally. Confidence is structural here rather than compensatory.`,
    behavioral: `The Sun-Mars trine produces a well-integrated assertive function. The ego's identity and the Mars drive are drawing from the same elemental source, which means assertion does not require the ego to override internal resistance or manage a competing impulse first. The warrior archetype that Mars represents has been integrated into the ego's repertoire as a natural tool rather than a disruptive force. The trine's shadow is subtler: because the Mars energy flows so easily through the ego's channels, this person may underestimate how much force they are actually applying in situations that call for restraint.`,
    friendship: `Reliable, energizing without being overwhelming. Good to have in your corner when something actually needs to be done.`,
    romantic: `Confident engagement. They pursue without hesitating but don't confuse pursuit with possession.`,
    feed: `The current sky is amplifying the natural forward motion available in this connection. Initiative and shared energy between these two charts are aligned right now in a way that doesn't happen on an ordinary day.`,
    sonic: `The Sun and Mars are in the same elemental family in the trine. The Sun's purposeful melodic direction is expressed through Mars's energetic, driving force without friction between strategy and momentum. The rhythm is strong and consistent, a natural, confident forward motion where the pulse and the melodic direction are in complete agreement. The harmonic language is clear and direct, moving with the Sun's purposeful logic and Mars's preference for unambiguous harmonic statements. Listen for the quality of music that moves with both clarity and physical energy, where the direction is never in doubt and the momentum supporting it never flags.`,
  },

  SUN_MARS_OPPOSITION: {
    key: 'SUN_MARS_OPPOSITION', pair: 'SUN_MARS', aspect: 'opposition', intensity: 'High',
    core: `The Sun, the conscious self and the principle of identity and purposeful direction, stands in full polarity with Mars, the planet of raw drive, assertion, and the force that presses toward desire and against opposition. At 180 degrees, these two forces are fully aware of each other and fully in tension. The Sun defines the self. Mars pushes outward with force. When these two oppose each other, the person may find that their own drive is experienced as something that belongs to others. They may encounter aggression, competition, or pressure from external sources and not recognize it as a reflection of their own unexpressed Mars.`,
    behavioral: `The psychological mechanism of the Sun-Mars opposition is one of the clearest natal signatures for projection. Because the Mars drive and the Sun's identity-function are at opposite poles, the ego tends to disown the Mars energy. This means the person may genuinely not experience themselves as aggressive, competitive, or forceful, and yet they consistently encounter people who are exactly those things. When the Mars is integrated, the opposition becomes a source of significant energy, because both the Sun's strategic intelligence and Mars's forceful drive become available to the same conscious self.`,
    friendship: `May attract combative friends or find themselves consistently in the role of challenger or rival without understanding why. The friendships that last are those that can hold honest friction without fracturing.`,
    romantic: `At its best, produces a relationship of genuine vitality and honest confrontation. At its most difficult, produces power struggles between two people who can't locate the source of the friction.`,
    feed: `Today's transits are lighting the axis where these two charts' drives meet. What is usually a background dynamic of assertion and response between these people is now in the foreground, and what happens here matters.`,
    sonic: `The Sun and Mars in opposition produce a composition where two strong sonic identities are at maximum distance, each asserting its own character across the full width of the musical space. The Sun's purposeful, strategic melodic statements are met by Mars's short, driving, incisive responses, not harmonizing but answering with force. The rhythm alternates between the Sun's consistent, organized pulse and Mars's driving downbeat emphasis in a pattern that feels like two strong wills negotiating. Listen for the quality of music where two forces are in conversation but neither is yielding, where the energy is high and the direction is contested.`,
  },

  MOON_VENUS_CONJUNCTION: {
    key: 'MOON_VENUS_CONJUNCTION', pair: 'MOON_VENUS', aspect: 'conjunction', intensity: 'Background',
    core: `The Moon, the planet governing emotional instinct, interior need, memory, and the body's fundamental requirement for safety and nourishment, fuses with Venus, the planet governing love, aesthetic value, relational attunement, and the capacity to draw connection toward oneself. When these two occupy the same degree, what the person emotionally needs and what they love are not separate experiences. They are the same experience. Comfort and affection arrive through the same channel. Safety and love feel like the same thing.`,
    behavioral: `The Moon-Venus conjunction creates a psychological configuration where the emotional attachment system and the relational love system are operating as a single integrated structure rather than as two distinct functions. To feel loved is to feel safe, and to feel emotionally unsafe is to feel unloved, even when the external relational reality is more complex. This fusion produces remarkable relational warmth and genuine attunement to others' emotional states. It also produces a significant psychological vulnerability: because emotional safety and the experience of being loved are the same signal, any disruption to the relational field registers simultaneously as emotional threat and relational loss.`,
    friendship: `These people create the warmth that holds groups together. They remember how everyone is doing. They check in. The risk is over-extension. They may give more than the friendship actually requires and then feel depleted.`,
    romantic: `Love is emotional sustenance for this person, not merely experience. The relationship that nourishes them has real emotional attunement at its center, not just affection as a gesture, but actual meeting.`,
    feed: `The current sky is moving through the place where emotional need and relational warmth are fused in this connection. What passes between these two people today carries more feeling than usual, and it is worth paying attention to.`,
    sonic: `The Moon contributes its modal harmonic ambiguity, breathing rhythmic instinct, and memory-driven emotional cycling. Venus contributes its rich consonant harmony, beautiful voice leading, and sensory melodic warmth. In the conjunction these two voices are fused. The harmonic language is modal with rich Venusian color tones, both emotionally ambiguous and acoustically beautiful simultaneously. The rhythm breathes like the Moon but moves with Venus's graceful ease. Listen for the quality of music where something feels emotionally true and also sounds genuinely beautiful, where the feeling in the sound and the beauty of the sound are indistinguishable from each other.`,
  },

  MOON_VENUS_SEXTILE: {
    key: 'MOON_VENUS_SEXTILE', pair: 'MOON_VENUS', aspect: 'sextile', intensity: 'Low',
    core: `The Moon, governing emotional instinct, interior need, and the drive toward safety and nourishment, and Venus, governing love, beauty, and relational attunement, are in a 60-degree relationship of easy, compatible exchange. The Moon's need for emotional safety and Venus's pull toward love and connection are not at odds. They can communicate and support each other without strain.`,
    behavioral: `The sextile creates what psychologists would recognize as a securely attached relational style, not because of developmental history necessarily, but because the natal architecture provides a baseline of good coordination between the emotional self-protection instinct and the drive toward connection. The Moon can feel what it feels without Venus immediately overriding it with the need for relational harmony. Venus can reach toward connection without the Moon immediately retreating into protective withdrawal. The result is a quiet, reliable emotional competence that others experience as warmth without pressure.`,
    friendship: `Easy to be with. Emotionally reliable. The warmth is available without being pressuring.`,
    romantic: `Partners feel received without being consumed. Warmth without the undercurrent of need that makes some people emotionally exhausting to love.`,
    feed: `Today's transit field is opening easy access to the warmth channel running between these charts. Emotional generosity is more available between these two people right now than it is on an average day.`,
    sonic: `The Moon's emotional instinct and Venus's aesthetic warmth are in easy dialogue in the sextile. The harmonic language is warm and emotionally resonant without being ambiguous, the Moon's modal coloring and Venus's rich chord voicings complementing each other naturally. The rhythm has the Moon's organic breathing quality and Venus's graceful ease simultaneously. Listen for the quality of music where something feels emotionally present and also beautiful, where the warmth in the sound and the aesthetic pleasure of the sound are supporting each other.`,
  },

  MOON_VENUS_SQUARE: {
    key: 'MOON_VENUS_SQUARE', pair: 'MOON_VENUS', aspect: 'square', intensity: 'Medium',
    core: `The Moon, the principle of emotional instinct, interior safety, and the body's deep need for comfort and familiarity, meets Venus, the principle of love, aesthetic desire, and the pull toward beauty and relational connection, at a 90-degree angle of genuine, ongoing tension. The Moon seeks what is safe, known, and emotionally nourishing. Venus seeks what is beautiful, desirable, and relationally alive. These two imperatives do not always point in the same direction.`,
    behavioral: `The tension here is between the attachment system's need for safety and the desire system's pull toward beauty, novelty, and relational aliveness. The Moon says this doesn't feel safe enough. Venus says but look how beautiful it is. Neither is wrong. The person's relational history often carries a recurring theme: choosing between emotionally safe relationships that Venus finds dull, and relationally exciting connections that the Moon finds threatening. The development task is building the capacity to hold both criteria simultaneously, to ask not just whether something is safe and not just whether it is beautiful, but whether it is genuinely both.`,
    friendship: `Warm but inconsistent. May pull back when the friendship starts feeling emotionally costly. The withdrawal isn't rejection. It's the Moon reasserting its requirement for safety after Venus has pushed it toward more exposure than it can comfortably sustain.`,
    romantic: `Partners may notice approach-avoidance: drawn close when emotional safety is felt, more distant when vulnerability increases. The square is not a barrier to love. It is a map of what love needs to feel like to be sustainable for this particular person.`,
    feed: `A transit is activating the tension between emotional safety and relational desire in this connection. Something about what each person needs from the other is asking to be examined today, and the timing is right to do it.`,
    sonic: `The Moon's modal harmonic ambiguity, breathing rhythm, and memory-driven emotional cycling are in friction with Venus's rich consonant beauty, graceful flow, and aesthetic melodic warmth. The Moon's harmonic language wants to stay in suspended, emotionally ambiguous territory. Venus wants to resolve into beauty. Listen for the quality of music where something emotionally raw is also being shaped into beauty, where the feeling and the aesthetic form are in productive tension with each other, neither fully winning.`,
  },

  MOON_VENUS_TRINE: {
    key: 'MOON_VENUS_TRINE', pair: 'MOON_VENUS', aspect: 'trine', intensity: 'Low',
    core: `The Moon, emotional instinct, interior need, and the body's requirement for safety and nourishment, and Venus, love, aesthetic sensibility, and the capacity for relational warmth, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces recognize each other as kin. The Moon's need for emotional safety and Venus's pull toward love and beauty are oriented in compatible directions. They do not compete for psychological resources.`,
    behavioral: `The Moon-Venus trine creates a natural integration of the attachment system and the love system. The emotional self-protection instinct and the relational desire function are drawing from the same elemental source and moving in the same direction. The person can give affection without depleting themselves, can receive love without needing it to continuously confirm their safety, and creates warmth in relational contexts with a naturalness that others experience as genuine care.`,
    friendship: `The person others return to. Reliably warm, not dramatic, genuinely interested in the lives of people they care about.`,
    romantic: `Partners describe a quality of being genuinely held in this relationship, not suffocatingly, but with real and consistent emotional safety.`,
    feed: `The current sky is amplifying the warmth infrastructure running between these charts. What is usually a quiet, sustaining ease between these two people is more noticeable and more available right now than it is as a baseline.`,
    sonic: `The Moon and Venus are in the same elemental family in the trine. The harmonic language is modally rich and also acoustically beautiful simultaneously, modal color tones voiced with Venus's careful attention to voice leading. The rhythm breathes and flows at the same time. The melodic lines have the Moon's instinctive, returning quality and Venus's careful attention to the aesthetic beauty of each interval. Listen for the quality of music where what sounds most beautiful also feels most emotionally true, where the feeling and the form are the same thing.`,
  },

  MOON_VENUS_OPPOSITION: {
    key: 'MOON_VENUS_OPPOSITION', pair: 'MOON_VENUS', aspect: 'opposition', intensity: 'Medium',
    core: `The Moon, the principle of emotional instinct, interior safety, and the need for privacy and self-protection, stands at full polarity with Venus, the principle of love, outward relational attunement, and the desire for beautiful, sustaining connection with others. At 180 degrees, these two forces are in constant dialogue across an axis of genuine tension. The Moon retreats inward toward safety. Venus reaches outward toward love. Full emotional safety can feel like it requires a degree of protective withdrawal that works against the openness that love requires.`,
    behavioral: `The person cycles between states of emotional generosity and openness, when the Venus end of the axis is dominant, and states of protective withdrawal and interior focus, when the Moon reasserts its need for safety. The development task is making the cycle conscious: learning to recognize when a withdrawal is the Moon's legitimate need for emotional restoration versus an avoidance of genuine relational contact, and learning to communicate the rhythm to partners rather than enacting it silently.`,
    friendship: `The friendship that matters to this person matters completely. They require friendships that can hold the rhythm of presence and withdrawal without interpreting the withdrawal as rejection.`,
    romantic: `Partners often describe the experience of feeling deeply loved and then suddenly unreachable, alternating with enough regularity to create genuine confusion. Both states are real and the withdrawal is protective rather than rejecting.`,
    feed: `Today's transits are lighting both ends of the emotional axis in this connection. The real distance between needing safety and wanting closeness is present between these two charts right now in a way that is worth naming directly.`,
    sonic: `The Moon and Venus in opposition produce a composition where emotional instinct and relational warmth are in dialogue across maximum distance. The Moon's breathing, cycling emotional quality is answered by Venus's rich consonant beauty, graceful flow, and aesthetically shaped melodic warmth. The harmonic language cycles between the Moon's emotionally suspended, unresolved quality and Venus's acoustically beautiful, resolved warmth. Listen for the quality of music where something is being felt from inside and also being made beautiful from outside, where the interior emotional world and the outward aesthetic presentation are in dialogue rather than agreement.`,
  },

  MOON_MARS_CONJUNCTION: {
    key: 'MOON_MARS_CONJUNCTION', pair: 'MOON_MARS', aspect: 'conjunction', intensity: 'High',
    core: `The Moon, the principle of emotional instinct, interior feeling, and the body's immediate, pre-cognitive responses to the world, fuses with Mars, the planet governing raw drive, assertive force, and the instinct to pursue and defend. When these two occupy the same degree, feeling and action become one motion. The Moon does not have time to process what it feels before Mars has already responded to it. Emotion and impulse arrive simultaneously as a single unified force.`,
    behavioral: `The Moon-Mars conjunction creates what might be described as an undifferentiated affect-action system. The emotional experience and the behavioral response to that experience have not been separated by psychological structures that would normally create a pause between feeling and doing. This is not a pathology. It produces extraordinary emotional immediacy, real passion, and fierce protective instincts. What it requires is the conscious development of affect regulation: the capacity to feel the full intensity of the Moon's emotional signal and the full force of Mars's reactive drive while also creating enough internal space for the reflective mind to briefly participate before the behavior occurs.`,
    friendship: `Fiercely loyal. They will show up when it matters. They will also have strong opinions about how you should handle your situation. The protectiveness is genuine and not always wanted.`,
    romantic: `High emotional intensity. Partners who can match that intensity without being destabilized by it find it extraordinarily alive.`,
    feed: `The current sky is activating where feeling and action are fused in this connection. The emotional temperature running between these two charts is higher than usual right now, and what is felt is likely to become what is said or done.`,
    sonic: `The Moon's emotional instinct and Mars's action-drive are fused rather than sequential in the conjunction. The breathing, instinctive rhythmic quality of the Moon is driven by Mars's physical downbeat force, producing a pulse that feels both emotional and unstoppable. The harmonic language is modal with moments of Martian dissonance. The feeling is dark and strong and does not wait for harmonic resolution to express itself. Listen for the quality of music where you feel something before you understand what you are feeling, where the emotion arrives at the speed of action.`,
  },

  MOON_MARS_SEXTILE: {
    key: 'MOON_MARS_SEXTILE', pair: 'MOON_MARS', aspect: 'sextile', intensity: 'Low',
    core: `The Moon, emotional instinct, interior feeling, and the body's immediate responses, and Mars, drive, assertion, and the force that converts feeling into action, are in a 60-degree relationship of easy, functional cooperation. The Moon can feel what it feels. Mars can act on those feelings without the process becoming overwhelming or misdirected.`,
    behavioral: `The sextile between the Moon's emotional instinct and Mars's action-drive creates a psychological configuration where the affect system and the behavioral response system are in productive dialogue rather than either fused or in conflict. The Moon generates the emotional signal. Mars receives it and converts it into appropriate action without either amplifying it to the point of overwhelm or bypassing it in favor of reactive force. The result is a reliable emotional courage: the person can feel something clearly, assess it briefly, and act on it without being consumed by the feeling or paralyzed by the gap between emotion and response.`,
    friendship: `Reliable and present. Will show up without drama. Emotionally engaged without being intense about it.`,
    romantic: `Emotionally present and willing to act on that presence. Not passive in their affections.`,
    feed: `Today's transit field is moving through the cooperative channel between emotional instinct and responsive drive in this connection. What needs to happen between these two people has a clearer, more direct path available right now.`,
    sonic: `The Moon's emotional instinct and Mars's responsive drive are in easy sequential communication in the sextile. The Moon generates the feeling and Mars converts it into appropriate action without either overwhelming the other. The rhythm has the Moon's organic quality and Mars's physical energy in natural dialogue. Listen for the quality of music where something is felt and then responded to in natural sequence, where the emotional content and the energetic response feel proportionate and honest.`,
  },

  MOON_MARS_SQUARE: {
    key: 'MOON_MARS_SQUARE', pair: 'MOON_MARS', aspect: 'square', intensity: 'High',
    core: `The Moon, the principle of emotional instinct, interior need, and the body's requirement for safety and comfort, meets Mars, the planet of raw drive, assertive force, and the instinct to pursue and defend, at a 90-degree angle of genuine, sustained tension. Both forces are strong and neither naturally yields. The Moon needs to feel safe before it moves. Mars wants to move before it has checked whether safety exists. The person experiences a recurring friction between their emotional reactions and their impulse to act on those reactions.`,
    behavioral: `The Moon-Mars square creates a psychological configuration where the affect system and the action system compete for priority rather than operating in sequence. The Moon generates the emotional signal and rather than being processed into a considered response, it immediately activates the Mars drive, which fires the behavioral response before the reflective mind has been consulted. This is the natal architecture of high emotional reactivity. The feelings are real, the convictions are genuine, the loyalty is fierce. The development task is building the pause-and-appraise capacity: not suppressing the Moon's feeling or Mars's drive, but creating enough psychological space between them for the reflective function to briefly participate before the behavioral response fires.`,
    friendship: `Intense. Can be the most loyal friend or the most difficult, often in the same week. The emotional investment is real. So is the reactivity. So is the fierce, genuine care.`,
    romantic: `High heat, high friction, high investment. Partners often describe the experience as the most alive relationship they've had and also one of the most demanding. The passion is not performance. Neither is the friction.`,
    feed: `A transit is pressing on the friction point where emotional reactivity and assertive drive meet in this connection. The voltage running between these two charts is elevated right now, and how that energy is handled today will leave a mark.`,
    sonic: `The Moon's breathing, modal, memory-instinct harmonic quality is in genuine friction with Mars's driving, physical, dissonant force. The Moon wants to feel before it moves. Mars has already moved before the Moon has finished feeling. The rhythm is high-energy and slightly chaotic, the Moon's organic breath and Mars's driving downbeat competing for rhythmic priority. Listen for the quality of music where emotion and action are both present but not synchronized, where you feel the musical equivalent of wanting to feel something fully before responding and simultaneously having already responded before the feeling arrived.`,
  },

  MOON_MARS_TRINE: {
    key: 'MOON_MARS_TRINE', pair: 'MOON_MARS', aspect: 'trine', intensity: 'Low-medium',
    core: `The Moon, emotional instinct, interior feeling, and the body's immediate responses to the world, and Mars, drive, assertion, and the force that converts feeling into action, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means the Moon's feeling and Mars's response move in the same direction without requiring negotiation between them. Emotional experience flows naturally into appropriate action. The person does not have to fight themselves to act on what they feel.`,
    behavioral: `The Moon-Mars trine creates emotional courage in its most integrated form: the capacity to feel something fully, trust the feeling, and act from it without the excessive second-guessing that comes from the Moon and Mars being in harder relationship. The Mars drive is not overriding the Moon's emotional signal, and the Moon is not suppressing the Mars impulse. They are cooperating, with the result that this person's behavioral responses to emotional situations tend to be appropriately scaled, direct, and honest without being reactive in the destabilizing sense.`,
    friendship: `Someone who will be honest about how they feel and who expects and respects the same honesty. Loyal and genuinely active in their care for people who matter to them.`,
    romantic: `Emotionally present and willing to pursue what they feel. Partners feel clearly wanted.`,
    feed: `The current sky is amplifying the emotional courage available between these charts. Honest expression and direct response between these two people are more accessible and more natural right now than they are on an ordinary day.`,
    sonic: `The Moon and Mars are in the same elemental family in the trine. The emotional instinct and Mars's responsive drive flow in natural sequence without friction between them. The rhythm has the Moon's organic breathing quality and Mars's physical energy in natural agreement. The harmonic language is modally warm with enough Martian directional clarity to feel emotionally honest rather than simply beautiful. Listen for the quality of music where emotion and action feel like one thing, where the feeling and the response to that feeling are the same musical motion.`,
  },

  MOON_MARS_OPPOSITION: {
    key: 'MOON_MARS_OPPOSITION', pair: 'MOON_MARS', aspect: 'opposition', intensity: 'High',
    core: `The Moon, the principle of emotional instinct, interior safety, and the need to feel before acting, stands at full polarity with Mars, the planet of raw drive, outward assertion, and the force that moves without waiting for emotional permission. At 180 degrees, these two forces pull in opposite directions across the same axis. The Moon retreats inward to feel and process. Mars presses outward to act and assert. Both movements are real. Both are part of the same person.`,
    behavioral: `The Moon-Mars opposition produces a characteristic oscillation that is different in kind from the square's friction. Where the square produces a collision between two forces both trying to operate in the same psychological space at the same time, the opposition produces a pendulum. The Moon and Mars take turns being dominant. The opposition also has a strong projection tendency: the Mars end of the axis, when not consciously owned, may be experienced as something that belongs to others. The person who does not experience themselves as aggressive may repeatedly encounter aggression from their environment without understanding that the unowned Mars is being broadcast.`,
    friendship: `Complex and significant. Not casual. Both the emotional investment and the potential for friction run high.`,
    romantic: `At its best, produces a relationship of genuine encounter and real meeting. At its most difficult, produces emotional standoffs where neither side can reach the other. The path through is naming the cycle rather than simply enacting it.`,
    feed: `Today's transits are lighting both ends of the feeling-action axis in this connection. The oscillation between emotional depth and assertive force between these two charts is more visible right now and more worth examining than usual.`,
    sonic: `The Moon and Mars in opposition produce a composition where emotional instinct and physical drive are in dialogue across maximum distance and fundamental contrast. The Moon's breathing, cyclical emotional quality is answered by Mars's driving, incisive force, two sonic identities that represent opposite psychological principles. The rhythm alternates between the Moon's organic tide-like breath and Mars's heavy measured cadence in a pattern that feels like emotional need meeting assertive force repeatedly. Listen for the quality of music where something emotionally familiar keeps encountering something physically driven from across a distance.`,
  },

  VENUS_MARS_CONJUNCTION: {
    key: 'VENUS_MARS_CONJUNCTION', pair: 'VENUS_MARS', aspect: 'conjunction', intensity: 'High',
    core: `Venus, the planet governing love, aesthetic desire, relational attunement, and the magnetic capacity to draw beauty and connection toward oneself, fuses with Mars, the planet governing raw drive, pursuit, assertion, and the force that moves the person actively toward what they want. When these two occupy the same degree, desire and the impulse to pursue that desire become a single unified motion. This person does not experience significant distance between wanting something and reaching for it. Attraction is immediate and total. Love and desire are not separate registers. They arrive together.`,
    behavioral: `The Venus-Mars conjunction creates a psychological configuration where the desire system and the pursuit system are operating as one fused impulse rather than as two sequential steps. The distinction between attraction and approach has been collapsed. The behavioral expression of this fusion is magnetic presence in the fullest sense, not just passive attractiveness but an active, visible charge in how this person engages with what and whom they find compelling. The psychological challenge is the difficulty of distinguishing between genuine connection and the energy of pursuit itself, when the two are felt as identical.`,
    friendship: `Warm, direct, and sensorially present. Their friendships have a quality of aliveness, presence that registers even in small interactions.`,
    romantic: `This is the aspect of full romantic engagement, love that includes desire, desire that carries genuine affection. Partners feel genuinely wanted, not merely chosen.`,
    feed: `The current sky is activating where desire and pursuit are unified in this connection. The magnetic charge running between these two charts is more present and more immediate today than it typically is, and it has something to say.`,
    sonic: `Venus contributes its rich consonant harmony, beautiful voice leading, and graceful melodic warmth. Mars contributes its driving physical pulse, cutting tonal edge, and directional melodic force. In the conjunction these two voices are fused. Venus's natural warmth and aesthetic care are expressed at Mars's energetic register: the harmonic language is rich, warm, and driven. The rhythm is both graceful and driven simultaneously. Listen for the quality of music where something beautiful moves with complete irresistible forward momentum, where the aesthetic pleasure and the physical drive are the same force.`,
  },

  VENUS_MARS_SEXTILE: {
    key: 'VENUS_MARS_SEXTILE', pair: 'VENUS_MARS', aspect: 'sextile', intensity: 'Low',
    core: `Venus, governing love, aesthetic desire, and the magnetic pull toward beauty and relational connection, and Mars, governing drive, assertion, and the force that converts desire into active pursuit, are in a 60-degree relationship of easy, functional cooperation. Venus generates the desire. Mars provides the energy and direction to act on it. Neither undermines the other's function.`,
    behavioral: `The sextile between Venus's desire-function and Mars's pursuit-function creates a psychological configuration where wanting and reaching for what is wanted are in smooth sequential relationship. Venus generates the attraction, and Mars receives that signal and converts it into appropriate approach without either amplifying it into compulsion or bypassing it in favor of reactive assertion. The result is a well-calibrated romantic and social drive. The person knows what they want, has the energy and confidence to move toward it, and does so without the internal friction that makes pursuit feel either desperate or effortful.`,
    friendship: `Easy, warm, socially capable. A natural quality of warmth and confident engagement without pressure.`,
    romantic: `Naturally engaging. The balance between genuine warmth and confident pursuit feels unforced.`,
    feed: `Today's transit field is easing the flow between attraction and approach in this connection. What each person wants from the other has a more direct, lower-friction path available between these charts right now.`,
    sonic: `Venus generates the desire and Mars converts it into approach in the sextile, the two cooperating naturally without friction between them. The rhythm is graceful and energetic simultaneously. The harmonic language is warm and colorful with enough directional clarity to feel alive rather than merely beautiful. Listen for the quality of music where something beautiful moves toward you and you move toward it at the same time, where desire and approach are in natural, unforced sequence.`,
  },

  VENUS_MARS_SQUARE: {
    key: 'VENUS_MARS_SQUARE', pair: 'VENUS_MARS', aspect: 'square', intensity: 'Medium-high',
    core: `Venus, the principle of love, harmony, beauty, and the desire to draw connection toward oneself through magnetic attunement, meets Mars, the planet of assertion, direct pursuit, competition, and the force that moves outward without waiting, at a 90-degree angle of genuine, sustained tension. Venus wants to attract. Mars wants to pursue. Venus moves toward harmony. Mars moves toward conquest. Venus waits to be met. Mars presses forward. These are not naturally compatible strategies for the same goal, and the square means the person experiences a recurring friction between their desire for relational beauty and the way their drive actually moves.`,
    behavioral: `The psychological tension here is between the receptive and assertive poles of the erotic drive. In the square these two modes compete for priority. The behavioral result is the approach-withdrawal pattern the Venus-Mars square is well known for producing. The person is genuinely attracted, moves toward connection, and then the Mars drive either asserts itself too forcefully and triggers the Venus instinct for retreat, or the Venus pull toward harmony suppresses the Mars drive into passivity until it reasserts itself as sudden unexpected assertion. The square also produces what is perhaps its most constructive gift: creative tension. Some of the most charged, alive, and genuinely passionate creative and relational work emerges from exactly this configuration.`,
    friendship: `Warm and direct in turns. Can generate friction without consciously intending to.`,
    romantic: `Significant charge and genuine heat. Partners experience real passion alongside moments of tension that seem to emerge without warning. The development task is understanding the pattern so it can be worked with consciously rather than endlessly repeated.`,
    feed: `A transit is pressing on the point where desire and pursuit are in tension in this connection. The push-pull dynamic that runs through this relationship is closer to the surface today than usual, and what surfaces is worth listening to.`,
    sonic: `Venus's rich consonant beauty, graceful flow, and aesthetic melodic warmth are in genuine friction with Mars's driving physical pulse and directional force. Venus wants the music to stay in beautiful harmonic territory. Mars wants to drive it forward. Venus's graceful rhythmic flow is disrupted by Mars's hard downbeat emphasis. The harmonic language cycles between Venus's rich, colorful dwelling and Mars's directional, forward-moving clarity. Listen for the quality of music where something beautiful keeps being interrupted by something driven, and something driven keeps being softened by something beautiful.`,
  },

  VENUS_MARS_TRINE: {
    key: 'VENUS_MARS_TRINE', pair: 'VENUS_MARS', aspect: 'trine', intensity: 'Low-medium',
    core: `Venus, governing love, aesthetic desire, and the magnetic capacity to attract beauty and connection, and Mars, governing drive, assertion, and the force that converts desire into active pursuit, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces move in the same direction without internal argument. Venus's desire and Mars's drive to pursue that desire are naturally aligned.`,
    behavioral: `The Venus-Mars trine creates a psychological configuration where the receptive desire system and the assertive pursuit system are drawing from the same elemental source and functioning as a unified system. Venus generates the attraction, and Mars receives that signal and converts it into appropriate approach. There is no ongoing internal argument about when to move and when to wait. The assessment and the action are naturally synchronized. The person can want things and people and move toward them with natural grace.`,
    friendship: `Easy warmth. Good social presence. Not effortful. The warmth is genuine rather than performed.`,
    romantic: `Partners feel genuinely desired and pursued without feeling pressured. The balance between warmth and confident pursuit is natural.`,
    feed: `The current sky is amplifying the natural ease between wanting and reaching in this connection. The grace that runs between these charts is more available today, and something in this dynamic is worth opening right now.`,
    sonic: `Venus and Mars are in the same elemental family in the trine. Venus's aesthetic warmth and Mars's energetic drive flow in natural sequence without friction between desire and pursuit. The rhythm is graceful and energetic simultaneously, the flowing ease of Venus and the physical forward motion of Mars in complete natural agreement. The harmonic language is warm, colorful, and directionally alive. The melodic lines are both singable and purposeful, reaching with grace. Listen for the quality of music where something beautiful moves with complete natural confidence, where the grace and the drive are the same thing.`,
  },

  VENUS_MARS_OPPOSITION: {
    key: 'VENUS_MARS_OPPOSITION', pair: 'VENUS_MARS', aspect: 'opposition', intensity: 'High',
    core: `Venus, the principle of love, harmony, relational attunement, and the desire to attract and be met, stands at full polarity with Mars, the planet of raw drive, outward assertion, direct pursuit, and the force that presses rather than waits. At 180 degrees, these two forces are fully aware of each other and fully in tension across the same axis. Venus pulls toward softness, receptivity, and mutual meeting. Mars pushes toward assertion, pursuit, and direct force. The person lives inside this polarity, the push and pull between receptivity and assertion, between attracting and pursuing, between the desire for harmony and the drive toward confrontation.`,
    behavioral: `The psychological mechanism of the Venus-Mars opposition is a structural version of the contrasexual polarity conflict. The receptive, relational, beauty-oriented dimension of the psyche and the assertive, goal-oriented, competitive drive are at 180 degrees, fully aware of each other, unable to ignore each other, and unable to simply merge. The behavioral expression in relational life is a characteristic oscillation between extreme receptivity and extreme assertion, or projection of one end of the polarity onto others. The person who does not own their Mars may find themselves repeatedly attracted to aggressively assertive partners while experiencing themselves as purely relational and accommodating.`,
    friendship: `Their most significant friendships often have an element of productive friction. They do not gravitate naturally toward purely peaceful, low-charge connections.`,
    romantic: `This is the aspect of intense romantic life. Not necessarily smooth, but alive, charged, and significant. Partners feel the full spectrum of this person's relational range because the opposition carries both the softness of Venus and the force of Mars in full measure.`,
    feed: `Today's transits are lighting both ends of the desire axis in this connection. The polarity between receptivity and assertion running between these two charts is more charged right now than it usually is, and what that tension is generating deserves a full listen.`,
    sonic: `Venus and Mars in opposition produce a composition where aesthetic warmth and physical drive are in dialogue across maximum distance. Venus's rich, warm, beautiful harmonic language is answered by Mars's driving, directionally forceful energy, two sonic identities pulling in different directions. The rhythm alternates between Venus's graceful, flowing ease and Mars's hard driving pulse in a pattern that generates significant charge. The harmonic language cycles between Venus's colorful, consonant warmth and Mars's directional, power-chord force. Listen for the quality of music where something beautiful and something driven are in unresolved but generative tension, where the aesthetic pleasure and the physical momentum keep answering each other in a way that never fully resolves but generates continuous energy.`,
  },

} as const;
