/**
 * Astradio Insight Library — Jupiter Aspects to Personal Planets (Batch 2)
 *
 * 20 objects: JUPITER × SUN, MOON, VENUS, MARS × 5 aspects
 * Place at: vnext/projection/insight-library/insight-library-aspects-jupiter.ts
 */

import type { AspectInsight } from './insight-library-types';

export const JUPITER_ASPECT_INSIGHTS: Readonly<Record<string, AspectInsight>> = {

  JUPITER_SUN_CONJUNCTION: {
    key: 'JUPITER_SUN_CONJUNCTION', pair: 'JUPITER_SUN', aspect: 'conjunction', intensity: 'High',
    core: `Jupiter, the principle of expansion, meaning, abundance, and the force that carries a person toward something genuinely larger than their current limits, fuses with the Sun, the seat of conscious identity and the purposeful drive toward self-expression. When these two occupy the same degree, identity and expansion become one system. This person does not experience themselves as someone who seeks growth. They experience growth as an expression of who they are. The ego's natural drive toward self-definition has been shaped by Jupiter's generosity, optimism, and drive toward meaning and scale. What results is a person who moves through the world with a quality of largeness, not arrogance necessarily, but a genuinely expanded sense of what is possible, what they are capable of, and what they are entitled to reach for. Jupiter's shadow is present here too. The same force that expands can inflate, and the ego shaped by Jupiter can become so confident in its own scale that it loses contact with the legitimate limits that Saturn would impose.`,
    behavioral: `The ego has been enlarged by Jupiter's expansive force and genuinely believes in a larger version of itself than the immediate evidence might support. This is not delusion. Jupiter's faith in potential has a self-fulfilling quality, and people with this conjunction genuinely do tend to attract opportunity, receive generosity from the world, and expand into the space that their confidence creates. This person naturally assumes that things will work out, that they will be received well, that the world is fundamentally generous toward them. That assumption tends to be accurate often enough to reinforce itself, which is Jupiter's gift. The shadow is the difficulty this person has with genuine limitation. The Saturn experiences that are part of every life, the real reckoning with what is not possible, the humility that comes from encountering a boundary that Jupiter's expansion cannot dissolve, can be genuinely difficult to metabolize.`,
    friendship: `Friends experience this person as generous, expansive, and genuinely encouraging. Someone who makes their world feel larger simply by being in it. The challenge is that this person's natural optimism can sometimes bypass the genuine difficulty of what a friend is experiencing, wrapping real pain in enthusiasm before it has been fully heard.`,
    romantic: `Partners often describe a quality of abundance in this relationship, a sense that being with this person opens up possibilities that did not exist before. The shadow is that Jupiter's confidence in expansion can crowd out the space a partner needs to be their own distinct person.`,
    feed: `Jupiter's transit is amplifying the expansive force in this connection right now. What each person believes is possible between these two charts is being enlarged today, and what opens up from that enlarged perspective is worth exploring.`,
    sonic: `The Sun's purposeful melodic statements are enlarged by Jupiter's generosity in the conjunction. The phrases reach further than expected, the harmonic territory covered is more expansive, the dynamic range is wider. The rhythm has the Sun's consistent forward motion expressed through Jupiter's sense of abundant time, steady and confident with a quality of spaciousness around each beat. The harmonic language is major and generous, big open voicings that fill the acoustic space, modulations that expand the tonal territory beyond what a simpler version of this material would require. Listen for the quality of music where everything is slightly larger than expected, where the melodic phrases reach further and the harmonies open wider than the modest beginning suggested was possible.`,
  },

  JUPITER_SUN_SEXTILE: {
    key: 'JUPITER_SUN_SEXTILE', pair: 'JUPITER_SUN', aspect: 'sextile', intensity: 'Low-medium',
    core: `Jupiter, the principle of expansion, meaning, abundance, and growth, and the Sun, conscious identity and purposeful self-expression, are in a 60-degree relationship of easy, productive cooperation. The sextile places these two forces in compatible elemental territories where Jupiter's expansive generosity and the Sun's expressive purpose can draw on each other without the inflation that the conjunction can produce. The person's sense of identity and their natural orientation toward growth, meaning, and possibility are in easy dialogue.`,
    behavioral: `The ego's drive for self-expression and the Jupiterian faith in growth and possibility are in productive communication rather than in fusion or tension. The Sun can pursue its goals with Jupiter's expansive faith available as a resource rather than as an automatic assumption, and Jupiter's generosity can animate the Sun's purpose without inflating the ego beyond what the situation actually supports. The result is genuine confidence appropriately calibrated to actual circumstances. They believe things will work out because they have enough experience of Jupiter's gifts to trust the principle, but they also maintain enough contact with reality to adjust when the expansion meets a genuine limit.`,
    friendship: `Easy to be around, naturally generous in their assumptions about others, and genuinely encouraging without the quality of inflation that harder Jupiter-Sun aspects can produce.`,
    romantic: `Partners find a quality of optimistic investment in this person that makes the relationship feel full of possibility. The warmth is real and the faith in growth is genuine.`,
    feed: `Today's transit is opening the productive channel between expansion and self-expression in this connection. There is a quality of genuine possibility available between these two charts right now that is worth stepping into.`,
    sonic: `The Sun's directional clarity is supported by Jupiter's expansive faith in the sextile, producing melodic lines that reach with confidence and harmonic language that covers more territory than expected without losing its sense of direction. The rhythm has the Sun's consistency and Jupiter's sense of abundant spacious time in easy dialogue. Listen for the quality of music where something purposeful also sounds genuinely generous, where the direction is clear and the harmonic space around it is wider than necessary.`,
  },

  JUPITER_SUN_SQUARE: {
    key: 'JUPITER_SUN_SQUARE', pair: 'JUPITER_SUN', aspect: 'square', intensity: 'Medium-high',
    core: `Jupiter, the principle of expansion, meaning, abundance, and growth, meets the Sun, conscious identity and the drive toward purposeful self-expression, at a 90-degree angle of genuine, productive tension. Jupiter says: reach further, aim higher, the possibilities are larger than you think. The Sun's ego hears this and responds with genuine enthusiasm. But the 90-degree angle means the expansion Jupiter encourages and the purposeful, structured self-expression the Sun requires are not naturally aligned. Jupiter's generosity can exceed what the Sun's identity can actually sustain and deliver. The result is a person with genuine ambition, real vision, and a recurring gap between the scale at which they conceive their projects and the scale at which they can actually execute them.`,
    behavioral: `This is the tension between vision and execution, between the inspiring version of what could be and the disciplined, step-by-step process that would actually produce it. This person conceives at Jupiter's scale and executes at the Sun's scale, and the gap between those two scales is the source of both their considerable ambition and their periodic frustration. The Jupiter-Sun square also produces what is perhaps its most recognizable expression: the person who is excellent at inspiring others, at communicating vision, at generating enthusiasm for what could be, and who sometimes struggles with the unglamorous structural work that converts vision into reality. The development task is not suppressing Jupiter's expansive vision but developing the Sun's capacity to pursue that vision through structured, sustained, step-by-step execution rather than through repeated cycles of inspiration and incompletion.`,
    friendship: `Friends experience a person who is genuinely inspiring and occasionally over-promising. Someone whose enthusiasm for what is possible can be more available than the follow-through that converts that enthusiasm into actual delivery.`,
    romantic: `Partners often experience this person as someone who makes the relationship feel large and full of possibility, and who sometimes struggles with the mundane structural work that long-term partnership requires. The vision is genuine. The execution requires conscious cultivation.`,
    feed: `Jupiter's transit is pressing on the tension between vision and delivery in this connection right now. What each person believes is possible between these charts and what is actually being built are both more visible today, and the gap between them is the productive territory.`,
    sonic: `Jupiter's expansive harmonic generosity and wide-ranging melodic ambition are in friction with the Sun's purposeful, structured, directional clarity in the square. Jupiter pushes the harmonic language toward ever-wider territory. The Sun's structural purpose tries to maintain directional coherence. The melodic lines aspire to Jupiter's large intervallic leaps but land in harmonic territory the Sun's structural logic has not fully prepared. Listen for the quality of music where something is clearly reaching for something larger than it has yet achieved, where the ambition and the capacity are both real and both slightly mismatched.`,
  },

  JUPITER_SUN_TRINE: {
    key: 'JUPITER_SUN_TRINE', pair: 'JUPITER_SUN', aspect: 'trine', intensity: 'Low-medium',
    core: `Jupiter, expansion, meaning, abundance, and the principle of growth, and the Sun, conscious identity and the purposeful drive toward self-expression, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces recognize each other as kin and move in the same direction without the friction of harder aspects or the inflation of the conjunction. The person's sense of identity and their natural orientation toward growth and possibility are harmoniously integrated. The Sun's purpose is genuinely supported by Jupiter's abundance, and Jupiter's expansiveness finds its most productive expression through the Sun's clear self-definition.`,
    behavioral: `The ego's drive for self-expression and the Jupiterian faith in growth and possibility are drawing from the same elemental source and moving in compatible directions. The Sun can pursue its goals with Jupiter's expansive faith genuinely available as a sustaining resource, and Jupiter's generosity is given genuine direction by the Sun's purposeful structure. The ambition is both real and appropriately scaled. Jupiter's vision and the Sun's structured execution are in natural agreement rather than tension. The psychological shadow of the trine is the complacency that ease produces: because the Sun and Jupiter are naturally aligned, the person may not develop the depth of resilience that comes from working through genuine failure or confronting a genuine limit that Jupiter could not dissolve.`,
    friendship: `Naturally generous, genuinely encouraging, and easy to be around. Friends experience a quality of warmth and expansive goodwill that makes the relationship feel sustaining.`,
    romantic: `Partners find a quality of genuine abundance and optimistic investment in this person that makes the relationship feel both warm and full of possibility.`,
    feed: `The current sky is amplifying the natural abundance available in this connection. What each person brings to this relationship in terms of genuine generosity and expansive possibility is more present and more accessible right now than usual.`,
    sonic: `The Sun and Jupiter are in the same elemental family in the trine. The Sun's purposeful melodic direction is expressed through Jupiter's generous, expansive register without any friction between direction and scale. The harmonic language is major and wide-ranging, the Sun's clear tonality given Jupiter's large, open voicings and willingness to modulate into generous harmonic territory. The melodic lines have the Sun's purposeful forward direction and Jupiter's tendency toward wide intervallic leaps. Listen for the quality of music that moves with both purpose and genuine generosity, where the direction is clear and the scale is naturally large, and neither quality is working against the other.`,
  },

  JUPITER_SUN_OPPOSITION: {
    key: 'JUPITER_SUN_OPPOSITION', pair: 'JUPITER_SUN', aspect: 'opposition', intensity: 'Medium',
    core: `Jupiter, the principle of expansion, meaning, abundance, and growth beyond current limits, stands at full polarity with the Sun, conscious identity and the drive toward purposeful self-expression. At 180 degrees, the Sun defines and consolidates the self. Jupiter expands beyond it. The opposition tends to externalize this tension. The person may encounter Jupiter's expansive, meaning-seeking principle through other people, through teachers, philosophers, travelers, or people of a different cultural or belief background, who expand the person's world in ways the ego alone could not generate.`,
    behavioral: `The ego's consolidating, self-defining function and Jupiter's expansive, meaning-seeking principle are at opposite poles, which means the person tends to find their growth through encounter with otherness rather than through interior development alone. Jupiter's principle of meaning and expansion is partly located in the not-self, encountered through relationships, cultural exposure, philosophical challenge, and travel rather than through introspection. This person is genuinely expanded by their encounters with different people, ideas, and worldviews. Their identity becomes larger through contact with what lies beyond it rather than through protecting what is already there. The shadow is a tendency to place Jupiter's principle entirely outside the self, seeking meaning, wisdom, and expansive perspective exclusively through others rather than developing the interior capacity for philosophical self-reflection and autonomous meaning-making.`,
    friendship: `Friendships with people of different backgrounds, belief systems, or cultural orientations are often the most expansive and significant. The encounter with genuine difference is what activates the Jupiter-Sun axis most productively.`,
    romantic: `Partners who represent a genuinely different worldview, cultural background, or philosophical orientation can be deeply activating for this person. The relationship becomes a site of identity expansion through encounter with the genuinely other.`,
    feed: `Jupiter's transit is illuminating both ends of the identity-expansion axis in this connection today. What each person's worldview and sense of possibility are doing to the other's sense of who they are is more visible between these charts right now, and more worth exploring.`,
    sonic: `The Sun and Jupiter in opposition produce a composition where purposeful directional clarity and expansive, wide-ranging generosity are in dialogue across maximum distance. The Sun's clear, forward-moving melodic statements are answered by Jupiter's large, harmonically expansive responses, two sonic identities pulling in different directions, one toward structured purposefulness and the other toward ever-wider harmonic territory. Listen for the quality of music where something purposeful keeps being expanded beyond its intended scale by something generous, where the direction is real but the harmonic territory keeps opening wider than the structural logic requires.`,
  },

  JUPITER_MOON_CONJUNCTION: {
    key: 'JUPITER_MOON_CONJUNCTION', pair: 'JUPITER_MOON', aspect: 'conjunction', intensity: 'High',
    core: `Jupiter, the principle of expansion, meaning, abundance, and growth beyond current limits, fuses with the Moon, the keeper of emotional instinct, memory, interior safety, and the body's fundamental need for nourishment and comfort. When these two occupy the same degree, emotional experience and the principle of abundance become one system. This person does not experience emotional life as bounded or rationed. The Moon's natural capacity for feeling is expanded by Jupiter's generosity into something that fills the available space and then fills more. The emotional world is generous, expansive, and oriented toward meaning. What feels good tends to feel very good. What feels difficult tends to feel very difficult. The emotional register runs at Jupiter's scale, and that scale is genuinely large.`,
    behavioral: `The Moon's natural emotional instinct has been expanded by Jupiter's principle of abundance into a feeling world that is more generous, more expressive, and more attuned to meaning than the Moon alone would produce. Emotional experiences are not simply felt but are simultaneously interpreted for their larger significance. Every emotional encounter carries the potential for philosophical or spiritual resonance. The result is a person with enormous emotional generosity, a natural gift for empathy and emotional attunement, and a capacity for genuine warmth that others find deeply sustaining. The shadow is the difficulty this person has with emotional limits. They may give more than the situation requires, assume that emotional problems can be resolved through generosity and optimism alone, or experience their own emotional lows as disproportionately vast because Jupiter's scale amplifies both directions.`,
    friendship: `Friends experience an extraordinary quality of emotional generosity and genuine warmth. Someone who makes them feel genuinely held and genuinely seen at Jupiter's scale. The challenge is that this person's emotional abundance can sometimes make it difficult for friends to bring genuinely difficult material, because the expansive optimism can feel like it bypasses rather than receives the depth of the difficulty.`,
    romantic: `Partners often describe a quality of being emotionally held at a scale that no previous relationship quite matched. The shadow is that Jupiter's emotional expansiveness can crowd out the nuances. The partner's more quietly expressed emotional needs may not register at the scale Jupiter requires.`,
    feed: `Jupiter's transit is amplifying the emotional generosity available in this connection right now. What flows between these two charts in terms of genuine warmth and emotional abundance is more present today than it is as a baseline, and what that opens up is worth receiving.`,
    sonic: `The Moon's emotional depth and Jupiter's generosity are fused in the conjunction. The harmonic language is modally rich and also harmonically generous, the Moon's emotional ambiguity given Jupiter's large, open voicings that fill the acoustic space with feeling. The rhythm breathes like the Moon but with Jupiter's sense of abundant unhurried time. The melodic lines have the Moon's instinctive, returning quality at Jupiter's scale, curving back toward the familiar but covering enormous harmonic distance in doing so. Listen for the quality of music where something emotionally instinctive is also emotionally vast, where the feeling registers not just as personal but as large, as meaningful, as the emotional equivalent of a wide horizon.`,
  },

  JUPITER_MOON_SEXTILE: {
    key: 'JUPITER_MOON_SEXTILE', pair: 'JUPITER_MOON', aspect: 'sextile', intensity: 'Low-medium',
    core: `Jupiter, expansion, meaning, abundance, and the principle of growth, and the Moon, emotional instinct, interior need, and the body's requirement for safety and nourishment, are in a 60-degree relationship of easy, productive cooperation. The sextile places these two forces in compatible elemental territories where Jupiter's expansive generosity and the Moon's emotional intelligence can support each other without the amplification that the conjunction produces.`,
    behavioral: `The Moon can feel what it feels with Jupiter's sustaining faith in the significance of that feeling available as a resource, and Jupiter's expansiveness is informed by the Moon's genuine emotional wisdom rather than operating independently of it. The result is natural emotional warmth, a genuine interest in the emotional lives of others, and a quality of empathetic generosity that does not deplete itself because Jupiter's abundance sustains it.`,
    friendship: `Warm, emotionally generous, and genuinely interested in the wellbeing of people they care about. The support is real and the emotional availability is reliable without being overwhelming.`,
    romantic: `Partners find a quality of genuine emotional warmth and sustaining generosity that makes the relationship feel nourishing. The care is real and it comes from an abundant rather than scarce emotional resource.`,
    feed: `Today's transit is gently opening the emotional generosity channel in this connection. What flows between these charts in terms of genuine warmth and emotional care is more easily available right now than it typically is.`,
    sonic: `The Moon's emotional instinct is supported by Jupiter's expansive faith without being overwhelmed by it in the sextile. The harmonic language is modally warm and also harmonically generous, the Moon's emotional ambiguity given Jupiter's open voicings without the fusion of the conjunction. Listen for the quality of music where something emotionally present also sounds genuinely generous, where the feeling is real and the harmonic space around it is wider than necessary.`,
  },

  JUPITER_MOON_SQUARE: {
    key: 'JUPITER_MOON_SQUARE', pair: 'JUPITER_MOON', aspect: 'square', intensity: 'Medium',
    core: `Jupiter, the principle of expansion, meaning, abundance, and growth, meets the Moon, the principle of emotional instinct, interior safety, and the body's fundamental need for comfort, at a 90-degree angle of genuine, productive tension. Jupiter says: feel it fully, let the emotional experience be as large as it wants to be, find the meaning in what you feel. The Moon's natural emotional instinct hears this and expands. But the 90-degree angle means Jupiter's expansion and the Moon's genuine need for emotional safety and containment are not naturally compatible. The feeling that Jupiter encourages the Moon to amplify is not always the feeling the Moon needs to have contained and processed safely.`,
    behavioral: `Jupiter wants the emotional field to be vast and meaningful. The Moon needs it to be safe and contained. The square means neither fully yields, and the person carries a recurring tension between emotional experiences that feel enormous and potentially overwhelming, and the Moon's instinct that enormous feelings require careful management. The result is a rich, meaningful emotional life that periodically exceeds its own containment. This person feels things very fully, finds great meaning in emotional experience, and occasionally generates emotional weather that is larger than the people around them can comfortably receive. The development task is developing the Moon's capacity for emotional self-regulation alongside Jupiter's natural emotional abundance, learning to feel at Jupiter's scale while also maintaining the Moon's instinctive wisdom about what the emotional field can safely hold.`,
    friendship: `Friends experience a person with enormous emotional warmth and genuine empathy who occasionally requires more emotional space than the friendship can easily provide, not out of neediness but out of Jupiter's amplification of the Moon's already-full emotional register.`,
    romantic: `Partners often describe a relationship with extraordinary emotional depth and richness alongside periods where the emotional weather is significantly larger than the immediate situation seems to warrant.`,
    feed: `Jupiter's transit is pressing on the tension between emotional depth and emotional containment in this connection right now. What each person feels about this relationship is being amplified today, and the scale of what surfaces is worth sitting with rather than managing.`,
    sonic: `Jupiter's expansive harmonic generosity and wide-ranging melodic reach are in genuine friction with the Moon's instinct for emotional containment, safe harmonic territory, and measured rhythmic breath. Jupiter pushes the emotional harmonic language toward ever-larger territory. The Moon's instinct is to return to the familiar and safe. The harmonic language cycles between the Moon's modally ambiguous emotional suspension and Jupiter's generous, wide-voiced harmonic expansiveness. Listen for the quality of music where something emotionally instinctive is being consistently enlarged beyond its natural scale, where the feeling and the space it is being given are in creative tension with each other.`,
  },

  JUPITER_MOON_TRINE: {
    key: 'JUPITER_MOON_TRINE', pair: 'JUPITER_MOON', aspect: 'trine', intensity: 'Low-medium',
    core: `Jupiter, expansion, meaning, abundance, and the principle of growth, and the Moon, emotional instinct, interior need, and the body's requirement for safety and nourishment, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces recognize each other as kin and move in the same direction without friction. Jupiter's abundance sustains the Moon's emotional generosity without amplifying it beyond what the emotional field can safely hold.`,
    behavioral: `The Moon can feel what it feels with Jupiter's genuine faith in the significance of emotional experience available as a sustaining resource, and Jupiter's expansiveness is grounded by the Moon's emotional wisdom without being constrained by it. The result is natural emotional warmth, a genuine gift for empathy and attunement, and an emotional generosity that sustains itself because Jupiter's abundance is its source. The trine's shadow is the complacency that ease produces. This person may not develop the emotional resilience that comes from having to work through genuine emotional difficulty.`,
    friendship: `Warm, sustaining, and emotionally generous without being overwhelming. Friends experience a quality of genuine care that is reliably available.`,
    romantic: `Partners find a quality of emotional nourishment in this relationship that makes it feel genuinely sustaining. The warmth is real and it comes from an abundant source.`,
    feed: `The current sky is amplifying the natural emotional abundance running between these charts. The warmth and genuine care that moves between these two people is more available and more noticeable right now than it is as a baseline.`,
    sonic: `The Moon's emotional instinct and Jupiter's expansive generosity flow in natural agreement in the trine. The harmonic language is modally rich and also harmonically generous, the Moon's emotional color given Jupiter's open voicings without any tension between containment and expansion. The melodic lines have the Moon's instinctive returning quality and Jupiter's wide intervallic reach in natural cooperation. Listen for the quality of music where something emotionally instinctive is also emotionally generous, where the feeling is present at a natural, sustaining scale without either shrinking or overflowing.`,
  },

  JUPITER_MOON_OPPOSITION: {
    key: 'JUPITER_MOON_OPPOSITION', pair: 'JUPITER_MOON', aspect: 'opposition', intensity: 'Medium',
    core: `Jupiter, the principle of expansion, meaning, abundance, and growth beyond current limits, stands at full polarity with the Moon, emotional instinct, interior safety, and the body's fundamental need for comfort and nourishment. At 180 degrees, the Moon seeks safety, familiarity, and emotional containment. Jupiter seeks expansion, meaning, and growth beyond what is currently comfortable. The opposition tends to externalize. The person may encounter Jupiter's expansive principle through emotionally significant others who introduce them to new emotional territories, philosophical frameworks, or cultural perspectives that expand the Moon's emotional world beyond what it would have reached on its own.`,
    behavioral: `The Moon contracting toward the familiar while Jupiter, encountered through others, through travel, through philosophical or cultural exposure, expands the emotional field beyond what the Moon finds immediately comfortable. This person's emotional world is significantly enlarged by encounters with different emotional cultures, philosophical frameworks, and ways of being that their own Moon's instinctive conservatism would not have generated. The shadow is a tendency to seek the Jupiter-Moon expansion externally rather than developing the interior capacity to expand the Moon's emotional world through deliberate cultivation of philosophical depth and emotional generosity.`,
    friendship: `The most expansive friendships are often with people whose emotional world or cultural background is significantly different. The encounter with different emotional realities activates the Jupiter end of the opposition productively.`,
    romantic: `Partners who carry a genuinely different emotional culture or philosophical perspective often provide the Jupiterian expansion that this person's Moon cannot generate on its own.`,
    feed: `Jupiter's transit is illuminating both ends of the emotional-expansion axis in this connection today. What each person's emotional world and sense of meaning are doing to the other's interior life is more visible between these charts right now, and what that reveals is worth exploring.`,
    sonic: `The Moon and Jupiter in opposition produce a composition where emotional instinct and expansive generosity are in dialogue across maximum distance. The Moon's breathing, modally ambiguous, memory-cycling quality is answered by Jupiter's large, harmonically generous, wide-ranging expansiveness from across the compositional space. The rhythm alternates between the Moon's careful organic breathing and Jupiter's sense of abundant, expansive time. Listen for the quality of music where something emotionally familiar keeps encountering something emotionally expansive from across a distance, where the instinctive emotional quality and the generous scale keep answering each other.`,
  },

  JUPITER_VENUS_CONJUNCTION: {
    key: 'JUPITER_VENUS_CONJUNCTION', pair: 'JUPITER_VENUS', aspect: 'conjunction', intensity: 'High',
    core: `Jupiter, the principle of expansion, meaning, abundance, and growth beyond current limits, fuses with Venus, the planet governing love, aesthetic sensibility, relational value, and the capacity to draw beauty and connection toward oneself. When these two occupy the same degree, love and abundance become one system. This person experiences love, beauty, and relational life at Jupiter's scale: generously, expansively, with a natural faith that the relational world is fundamentally abundant. This is one of the most naturally fortunate relationship configurations in the natal chart, and it carries one of the clearest Jupiter shadows: the same force that makes love generous can make it excessive, and the same faith that makes relational abundance feel natural can make genuine relational limits feel like a personal affront.`,
    behavioral: `This person believes in love at Jupiter's scale: in its redemptive capacity, its abundance, its power to expand what is possible for everyone it touches. The result is extraordinary natural charm, genuine relational warmth that others find almost magnetically attractive, and a capacity for generosity in relationship that can feel genuinely inexhaustible. The aesthetic dimension of Venus is amplified by Jupiter's expansiveness into a refined and wide-ranging sensibility. These people tend to have large aesthetic appetites, appreciation for cultural breadth, and a quality of aesthetic generosity that makes their environments and relationships feel genuinely beautiful. The shadow is the difficulty this configuration has with relational limits. The same Jupiter faith that makes love feel abundant can make it difficult to accept that some love cannot be made larger, some relationships cannot be made more beautiful, and some relational limits are genuine rather than failures of faith.`,
    friendship: `Friends experience a quality of warmth and genuine relational generosity that makes being in this person's orbit feel genuinely sustaining. The charm is real, the care is genuine, and the aesthetic quality of their friendship is unusually high.`,
    romantic: `Partners often describe the experience of being loved at a scale they had not previously encountered, a quality of warmth, generosity, and relational abundance that expands their sense of what love can be. The shadow is that Jupiter's expansive relational faith can make genuine relational difficulty feel like a betrayal of the principle rather than simply an ordinary challenge.`,
    feed: `Jupiter's transit is amplifying the love and relational abundance available in this connection right now. What flows between these two charts in terms of genuine warmth, generosity, and aesthetic pleasure is more present today than it is as a baseline, and that is worth fully receiving.`,
    sonic: `Venus's natural warmth and aesthetic care are expressed at Jupiter's scale in the conjunction. The harmonic language is rich, warm, and vast, generous chord voicings that fill the acoustic space with beauty, modulations that expand the tonal territory into regions of genuine harmonic luxury. The rhythm is graceful and spacious simultaneously. The melodic lines are long, beautiful, and wide-ranging, reaching toward beauty at Jupiter's scale. Listen for the quality of music where something is so genuinely beautiful that it fills the entire acoustic space, where the warmth and the scale are both present and both completely natural.`,
  },

  JUPITER_VENUS_SEXTILE: {
    key: 'JUPITER_VENUS_SEXTILE', pair: 'JUPITER_VENUS', aspect: 'sextile', intensity: 'Low-medium',
    core: `Jupiter, expansion, meaning, abundance, and Venus, love, aesthetic sensibility, and relational warmth, are in a 60-degree relationship of easy, productive cooperation. The sextile places these two forces in compatible territories where Jupiter's generous expansiveness and Venus's relational warmth can support each other without the amplification of the conjunction. Venus's warmth is supported by Jupiter's faith in relational possibility, and Jupiter's expansiveness finds its most graceful expression through Venus's aesthetic sensibility.`,
    behavioral: `Venus can express warmth and beauty with Jupiter's generous faith available as a sustaining resource, and Jupiter's expansiveness is given genuine aesthetic form through Venus's careful attention to beauty and relational quality. The result is natural charm, genuine relational warmth, and a quality of aesthetic generosity that others find genuinely pleasant to be around. The relational life has a natural quality of abundance and beauty without the quality of excess that harder Jupiter-Venus aspects can produce.`,
    friendship: `Charming, warm, and genuinely generous in their relational care. Easy to be around and naturally pleasant in their aesthetic sensibility.`,
    romantic: `Partners find a quality of genuine warmth and relational generosity that makes the relationship feel both beautiful and sustaining.`,
    feed: `Today's transit is gently opening the channel between love and abundance in this connection. There is a quality of genuine relational warmth and aesthetic pleasure available between these two charts right now that is worth stepping into.`,
    sonic: `Venus's beauty is supported by Jupiter's abundance without being overwhelmed by it in the sextile. The harmonic language is warm and generous, Venusian beauty with Jupiter's wider tonal reach. Listen for the quality of music where something beautiful also sounds genuinely generous, where the aesthetic warmth and the harmonic expansiveness are supporting each other.`,
  },

  JUPITER_VENUS_SQUARE: {
    key: 'JUPITER_VENUS_SQUARE', pair: 'JUPITER_VENUS', aspect: 'square', intensity: 'Medium',
    core: `Jupiter, the principle of expansion, meaning, and abundance, meets Venus, love, beauty, and relational warmth, at a 90-degree angle of genuine, productive tension. Jupiter says: let the love be larger, let the beauty be more, let the relational world be as abundant as it wants to be. Venus's natural relational instinct hears this and reaches. But the 90-degree angle means Jupiter's expansive principle and Venus's requirement for genuine relational quality and aesthetic care are not naturally compatible. Quantity and quality are Jupiter and Venus's respective orientations, and the square means neither naturally yields to the other.`,
    behavioral: `Jupiter wants the love to be vast. Venus knows that love is deepened by care rather than scale. The square means neither fully prevails, and the person carries a recurring tension between the expansive, generous, large-scale relational vision that Jupiter provides and the Venus requirement for genuine relational quality that does not simply scale with ambition. This produces a person with an enormous capacity for warmth and a genuine love for beauty who periodically overextends in the relational domain: promising more than can be genuinely delivered, loving more people than can be genuinely held, or pursuing beauty at a scale that exceeds what the relational or aesthetic field can actually sustain.`,
    friendship: `Warm and genuinely generous, with a quality of relational abundance that can occasionally exceed what any single friendship can actually contain. The care is real. The scale sometimes needs calibration.`,
    romantic: `Partners often experience a relationship with extraordinary warmth and relational vision alongside a quality of over-promise that the daily reality of partnership cannot always match.`,
    feed: `Jupiter's transit is pressing on the tension between love's scale and love's depth in this connection right now. What each person is offering and what can actually be received and sustained between these charts is more visible today, and both dimensions matter.`,
    sonic: `Jupiter's expansive harmonic generosity and wide-ranging reach are in genuine friction with Venus's requirement for genuine aesthetic care and relational quality in the square. Jupiter pushes the harmonic language toward ever-wider territory. Venus insists that each harmonic choice be genuinely beautiful rather than simply expansive. The rhythm alternates between Venus's graceful, carefully shaped flow and Jupiter's sense of abundant, unhurried spaciousness. Listen for the quality of music where something is trying to be both beautiful and enormous at the same time, where the aesthetic care and the expansive scale are in productive creative tension.`,
  },

  JUPITER_VENUS_TRINE: {
    key: 'JUPITER_VENUS_TRINE', pair: 'JUPITER_VENUS', aspect: 'trine', intensity: 'Low-medium',
    core: `Jupiter, expansion, meaning, and abundance, and Venus, love, aesthetic sensibility, and relational warmth, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces are naturally aligned. Jupiter's expansive generosity and Venus's aesthetic warmth move in the same direction without friction. Love and abundance are not in tension here. They reinforce each other.`,
    behavioral: `The desire system and the meaning-making principle are drawing from the same elemental source, which means the person can love generously without the anxiety of scarcity, can appreciate beauty with a wide and genuinely educated aesthetic sensibility, and can engage in relationship with a quality of warmth and faith that sustains itself because Jupiter's abundance is its source. The wide-ranging curiosity and genuine generosity of Jupiter combined with Venus's careful aesthetic attention produces people with extraordinary taste: broad, cultured, genuinely appreciative of beauty across many forms.`,
    friendship: `Naturally charming, genuinely warm, and aesthetically generous. Friends experience a quality of care and relational abundance that is reliably sustaining.`,
    romantic: `Partners find a quality of love that is both warm and genuinely abundant, a relationship that feels beautiful and also feels like it has room to grow.`,
    feed: `The current sky is amplifying the natural beauty and relational abundance available in this connection. The warmth and genuine aesthetic pleasure that flows between these charts is more present and more accessible right now than it is as a baseline.`,
    sonic: `Venus's aesthetic warmth and Jupiter's expansive generosity flow in natural agreement in the trine. The beauty is genuine and the scale is naturally large without tension between them. The harmonic language is warm, rich, and wide-ranging, Venusian beauty at Jupiter's generous scale. Listen for the quality of music where something is both genuinely beautiful and genuinely abundant, where the warmth fills the acoustic space naturally without either shrinking or overflowing.`,
  },

  JUPITER_VENUS_OPPOSITION: {
    key: 'JUPITER_VENUS_OPPOSITION', pair: 'JUPITER_VENUS', aspect: 'opposition', intensity: 'Medium',
    core: `Jupiter, expansion, meaning, and growth beyond current limits, stands at full polarity with Venus, love, beauty, and relational warmth. At 180 degrees, these two forces are in dialogue across an axis of fundamental tension between relational depth and relational breadth, between the quality that genuine love requires and the scale that Jupiter always reaches for. The opposition tends to externalize. The person may encounter Jupiter's expansive principle through partners or relationships that expand their relational world beyond what their Venus alone would have generated.`,
    behavioral: `Venus's instinct for genuine relational quality and aesthetic depth keeps encountering Jupiter's expansive principle from across a distance. Through partners who carry a genuinely different relational culture, through love that takes the person beyond their previous relational horizon, or through aesthetic encounters that expand their sense of what beauty can be. The developmental work is integrating the Jupiterian capacity for relational abundance and philosophical perspective on love as a genuinely interior resource rather than something that must always be supplied from outside.`,
    friendship: `The most expansive and significant friendships often involve people whose relational world or cultural background significantly differs from the person's own.`,
    romantic: `Partners who expand the person's relational world, who carry a genuinely different perspective on love, beauty, or human possibility, often provide the most significant developmental experiences.`,
    feed: `Jupiter's transit is illuminating both ends of the love-and-abundance axis in this connection today. What each person's sense of relational possibility is doing to the other's experience of this connection is more visible between these charts right now, and what that reveals is worth sitting with.`,
    sonic: `Venus and Jupiter in opposition produce a composition where aesthetic warmth and expansive generosity are in dialogue across maximum distance. Venus's rich, carefully shaped beauty is answered by Jupiter's wide-ranging, harmonically generous expansiveness, two sonic identities pulling in different directions, one toward relational quality and depth and the other toward relational scale and breadth. Listen for the quality of music where something beautiful keeps encountering something vast from across a distance, where the aesthetic care and the expansive scale keep answering each other.`,
  },

  JUPITER_MARS_CONJUNCTION: {
    key: 'JUPITER_MARS_CONJUNCTION', pair: 'JUPITER_MARS', aspect: 'conjunction', intensity: 'High',
    core: `Jupiter, the principle of expansion, meaning, abundance, and growth beyond current limits, fuses with Mars, the planet governing raw drive, assertion, the instinct to pursue and defend, and the force that moves the person toward what they want. When these two occupy the same degree, drive and expansion become one unified force. This person does not experience drive as bounded or rationed. The Mars impulse toward pursuit and assertion is enlarged by Jupiter's generosity and faith into something that operates at genuinely large scale. The ambition is real, the drive is physical and present, and Jupiter's faith amplifies both into a quality of energetic expansiveness that others find either inspiring or overwhelming depending on how it is meeting them.`,
    behavioral: `The assertive function and the meaning-making principle are fused, producing a person for whom drive is not merely instrumental but is experienced as meaningful, as pointing toward something larger than the immediate target. The result is formidable energy, genuine courage, a natural faith that the force they bring to any endeavor will be sufficient, and a quality of expansive ambition that can inspire significant followings or create significant friction depending on the wisdom with which it is directed. The shadow of the Jupiter-Mars conjunction is the classic inflation of the warrior archetype: the drive becomes so large and so imbued with a sense of righteous purpose that the legitimate limits and the legitimate needs of others in the field of the person's ambition are no longer fully visible.`,
    friendship: `Friends experience a person with formidable energy and genuine expansive enthusiasm who can be genuinely galvanizing and also occasionally overwhelming in the scale at which their drive operates.`,
    romantic: `Partners often experience this person's energy as initially exciting and eventually demanding. The Jupiter-Mars drive fills the relational space in ways that require a partner with their own strong center to receive without being consumed.`,
    feed: `Jupiter's transit is amplifying the drive and expansive ambition available in this connection right now. The force that each person brings to this relationship is running at a higher scale today than usual, and where that force gets directed matters significantly.`,
    sonic: `Mars's physical drive is amplified by Jupiter's expansiveness in the conjunction into something that fills the acoustic space with forward momentum. The rhythm is driving and spacious simultaneously, the energy physical and also somehow vast. The harmonic language has Mars's directional force given Jupiter's wide, generous voicings. The power chords are open and resonant rather than compressed. The melodic lines are short and incisive like Mars but reach toward Jupiter's large intervallic ambitions. Listen for the quality of music where something physically driven is also enormous in scale, where the force and the expansiveness are the same quality.`,
  },

  JUPITER_MARS_SEXTILE: {
    key: 'JUPITER_MARS_SEXTILE', pair: 'JUPITER_MARS', aspect: 'sextile', intensity: 'Low-medium',
    core: `Jupiter, expansion, meaning, and abundance, and Mars, drive, assertion, and the force that converts desire into action, are in a 60-degree relationship of easy, productive cooperation. The sextile places these two forces in compatible elemental territories where Jupiter's expansive faith and Mars's energetic drive can support each other without the amplification of the conjunction. The person's drive and their natural orientation toward growth and meaning are in easy dialogue.`,
    behavioral: `Mars provides the energy and the directional impulse. Jupiter provides the faith in the significance of where that energy is being directed. The result is reliable drive, genuine confidence in the capacity to pursue what matters, and a quality of energetic optimism that sustains itself through difficulty because Jupiter's faith in growth is available as a sustaining resource even when the Mars drive meets genuine resistance.`,
    friendship: `Energizing, genuinely supportive of others' ambitions, and reliable in their own commitments. The drive is real and the faith in growth is genuine.`,
    romantic: `Partners find a quality of genuine energetic investment and expansive ambition in this person that makes the relationship feel forward-moving and full of possibility.`,
    feed: `Today's transit is opening the productive channel between drive and expansive possibility in this connection. The momentum available between these charts right now is more aligned with genuine growth than it typically is.`,
    sonic: `Mars's drive is supported by Jupiter's expansive faith in the sextile, producing energy that is both physical and meaningful. Listen for the quality of music where something driven also sounds genuinely large in its ambitions, where the forward momentum and the harmonic expansiveness are supporting each other.`,
  },

  JUPITER_MARS_SQUARE: {
    key: 'JUPITER_MARS_SQUARE', pair: 'JUPITER_MARS', aspect: 'square', intensity: 'Medium-high',
    core: `Jupiter, the principle of expansion, meaning, abundance, and growth, meets Mars, raw drive, assertion, and the force that moves the person toward what they want, at a 90-degree angle of genuine, productive tension. Jupiter says: pursue it further, the ambition should be larger, the force should be greater. Mars hears this and amplifies. But the 90-degree angle means Jupiter's expansive amplification and Mars's strategic requirement for precision and appropriate force are not naturally compatible. Jupiter's encouragement of larger scale does not always produce more effective force. Sometimes it produces more force than the situation can accommodate, directed at targets that were not chosen with sufficient strategic precision.`,
    behavioral: `Jupiter amplifies the Mars drive beyond what any single situation strictly requires. This person brings more energy, more ambition, and more force to their pursuits than is always strategically optimal. The result is a person with formidable drive and genuine ambition who periodically overreaches: pursuing targets at a scale that exceeds the available resources, bringing more force to situations than they can absorb, or moving faster than the strategic situation warrants because Jupiter's faith that things will expand removes the natural checks that Mars's strategic wisdom would otherwise apply. The development task is developing Jupiter's wisdom alongside its enthusiasm, learning to pursue at a scale that is genuinely sustainable rather than simply the largest scale that can be imagined.`,
    friendship: `Energizing and inspiring, with a quality of drive and ambition that can galvanize others. The challenge is that the Jupiter-Mars square's tendency toward overreach can occasionally produce commitments that the person cannot fully sustain.`,
    romantic: `Partners experience a person with formidable energy and genuine expansive ambition who occasionally overextends in ways that require recalibration. The drive is real and so is the need for strategic discipline to sustain it.`,
    feed: `Jupiter's transit is pressing on the tension between drive and strategic wisdom in this connection right now. The force that each person is bringing to this relationship is running larger than usual today, and how that force is directed will determine what it produces.`,
    sonic: `Jupiter's expansive harmonic generosity and wide-ranging melodic ambition are in genuine friction with Mars's requirement for strategic precision and directed force in the square. Jupiter pushes the Mars drive toward ever-larger targets and ever-greater force. Mars's strategic instinct resists the lack of precision that Jupiter's expansiveness introduces. The rhythm is powerful and slightly ungainly, Mars's driving pulse given Jupiter's spacious, abundant timing in a way that produces enormous energy without always producing equally enormous precision. Listen for the quality of music where something enormously energetic is also slightly beyond its own optimal scale, where the drive and the ambition are both real and both running slightly ahead of the strategy that would make them most effective.`,
  },

  JUPITER_MARS_TRINE: {
    key: 'JUPITER_MARS_TRINE', pair: 'JUPITER_MARS', aspect: 'trine', intensity: 'Low-medium',
    core: `Jupiter, expansion, meaning, and abundance, and Mars, drive, assertion, and the force that converts desire into action, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces are naturally aligned. Jupiter's expansive faith and Mars's energetic drive move in the same direction without friction. Drive and expansion are not in tension here. They reinforce each other.`,
    behavioral: `The person can pursue what matters with both genuine force and genuine faith that the pursuit is significant. Mars provides the energy. Jupiter provides the sustaining conviction that the energy is being directed toward something worth reaching. The combination produces a quality of energetic optimism that is both genuinely motivating and genuinely effective. The ambition is real, the drive is real, and the faith in growth that sustains both through difficulty is also real.`,
    friendship: `Energizing, reliable in their commitments, and genuinely supportive of others' ambitions. The energy is real and it is oriented toward growth.`,
    romantic: `Partners find a quality of genuine drive and expansive ambition that makes the relationship feel forward-moving and purposeful.`,
    feed: `The current sky is amplifying the natural alignment between drive and expansive purpose in this connection. The energy and ambition available between these charts right now are more naturally directed toward meaningful growth than they usually are.`,
    sonic: `Mars's energetic drive and Jupiter's expansive faith flow in natural agreement in the trine. The rhythm is powerful and spacious simultaneously, Mars's physical drive given Jupiter's abundant sense of time in natural cooperation. Listen for the quality of music where something physically driven is also genuinely ambitious in scale, where the force and the expansiveness are the same quality moving in the same direction.`,
  },

  JUPITER_MARS_OPPOSITION: {
    key: 'JUPITER_MARS_OPPOSITION', pair: 'JUPITER_MARS', aspect: 'opposition', intensity: 'Medium',
    core: `Jupiter, the principle of expansion, meaning, abundance, and growth beyond current limits, stands at full polarity with Mars, raw drive, assertion, immediate pursuit, and the force that wants to move without waiting. At 180 degrees, these two forces are in dialogue across an axis of fundamental tension between the strategic precision Mars requires and the expansive faith Jupiter encourages. The opposition tends to externalize. The person may encounter Jupiter's expansive principle through others who represent a genuinely larger worldview, more expansive ambition, or a different philosophical orientation toward what is worth pursuing.`,
    behavioral: `The Mars drive's requirement for strategic precision and appropriate force keeps encountering Jupiter's expansive principle from across a distance, through people who operate at a larger scale of ambition or who carry a genuinely different philosophical orientation toward what is worth pursuing. The developmental work is integrating the Jupiterian capacity for expansive faith and meaningful purpose as a genuinely interior resource that directs the Mars drive rather than something that must always be supplied through encounter with others.`,
    friendship: `The most galvanizing friendships often involve people who operate at a larger scale of ambition or who carry a genuinely different philosophical orientation toward what is worth pursuing.`,
    romantic: `Partners who represent a genuinely different philosophy of pursuit or a larger scale of ambition can be deeply activating for this person's Mars-Jupiter axis.`,
    feed: `Jupiter's transit is illuminating both ends of the drive-and-expansion axis in this connection today. What each person's ambition and sense of expansive purpose are doing to the other's drive is more visible between these charts right now, and what that dynamic is generating is worth examining.`,
    sonic: `Mars and Jupiter in opposition produce a composition where energetic drive and expansive faith are in dialogue across maximum distance. Mars's physical, incisive, directionally precise force is answered by Jupiter's wide-ranging, harmonically generous expansiveness from across the compositional space. The rhythm alternates between Mars's driving downbeat force and Jupiter's spacious, abundant sense of time. Listen for the quality of music where something driven keeps encountering something vast from across a distance, where the force and the scale keep answering each other without fully resolving.`,
  },

} as const;
