/**
 * Astradio Insight Library — Mercury Aspects (Phase 3A scope)
 *
 * Mercury aspect entries authored as net-new content during v2 Phase 3.
 * Unlike Phase 2 retrofit work (which added synastry fields to pre-existing
 * natal entries), Phase 3 entries are full 14-field blocks authored from
 * scratch under the locked authoring rule from Phase 2A revision: shared
 * synastry blocks (core_synastry, behavioral_synastry) use chart-bearer
 * attribution, no partnership-coded language, no second-person pronouns.
 * Role-specific framing is reserved for friendship_synastry and
 * romantic_synastry where contextually licensed.
 *
 * Phase 3A scope (50 entries total in this file):
 *   Phase 3A1 — Mercury × Personal pairs (25 entries):
 *     - SUN_MERCURY × 5 aspects
 *     - MOON_MERCURY × 5 aspects
 *     - MERCURY_VENUS × 5 aspects
 *     - MERCURY_MARS × 5 aspects
 *     - MERCURY_MERCURY × 5 aspects (synastry-only, no natal occurrence;
 *       natal fields describe the conceptual register of the geometry)
 *   Phase 3A2 — Mercury × Outer pairs (25 entries):
 *     - SATURN_MERCURY × 5 aspects
 *     - JUPITER_MERCURY × 5 aspects
 *     - URANUS_MERCURY × 5 aspects
 *     - NEPTUNE_MERCURY × 5 aspects
 *     - PLUTO_MERCURY × 5 aspects
 *
 * Note on natal field authoring for synastry-only aspects: SUN_MERCURY
 * reaches conjunction natally (Mercury's max elongation from Sun is ~28°);
 * sextile/square/trine/opposition do not occur natally. Natal fields for
 * these entries describe the geometric register conceptually rather than
 * as an active natal manifestation, matching how Phase 2 personal.ts
 * handles the analogous SUN_VENUS_SEXTILE/SQUARE/TRINE/OPPOSITION
 * configurations that are similarly bounded by orbital geometry.
 *
 * Phase 3A1a (this batch): SUN_MERCURY × 5 entries as the methodology pilot.
 *
 * Place at: vnext/projection/insight-library/insight-library-aspects-mercury.ts
 */

import type { AspectInsight } from './insight-library-types';

export const MERCURY_ASPECT_INSIGHTS: Readonly<Record<string, AspectInsight>> = {
  SUN_MERCURY_CONJUNCTION: {
    key: 'SUN_MERCURY_CONJUNCTION', pair: 'SUN_MERCURY', aspect: 'conjunction', intensity: 'Background',
    core: `The Sun, the seat of conscious identity and willful self-direction, fuses with Mercury, the planet governing the mind, perception, learning, and the function of articulation that converts inner experience into language and thought into form. Where a conjunction occurs, two planets operate as one undivided system. Here that means the sense of who this person is and the way they think and speak are not two separate registers. They run along the same current. The conscious self does not experience itself as separate from its own voice. What this person thinks, they identify with. How they articulate, they recognize as themselves. The mind is not a tool the self deploys; it is the self in motion. This produces a quality of intellectual presence that others read as alert, articulate, and characteristically self-defined through speech.`,
    behavioral: `Because the Sun's identity-function and Mercury's cognitive function are fused rather than distinct, this person's psychological self-recognition runs heavily through verbal and intellectual channels. Thinking is identity work. Speaking aloud, writing, and reasoning through a problem are not just methods of processing for this person; they are the means by which the self continually confirms its own shape. There is little distance between a thought arriving and that thought being attributed to the conscious self as something genuinely meant. The fusion also exposes the Mercury function to the Sun's full ego-investment. Criticism of how this person thinks, speaks, or perceives is not received as feedback about a peripheral skill. It registers at the level of identity. Being called wrong about a fact and being called wrong about who they are can feel indistinguishable. The development task is the slow recognition that thought is information about reality, not the report card on the self.`,
    friendship: `Friends experience this person as articulate, present, and quick to find words. Conversation is how they show up. The friendship lives partly in language.`,
    romantic: `Partners feel met when this person speaks. Verbal exchange is a form of intimacy here. Misunderstandings about words or meaning land harder than they would in less Mercury-identified people because language and self are the same territory.`,
    feed: `The current sky is threading solar and Mercurial frequencies through this connection at the same pitch. A window is open right now where what each person thinks and how each understands themselves are aligned and audible between these two charts.`,
    sonic: `The Sun contributes a clear, forward-moving tonal center and a steady purposeful pulse. Mercury contributes quick melodic articulation, contrapuntal motion, and rapid figure-work that traces the harmonic outline with light incisive notes. In the conjunction these two voices are fused. The Sun's directional clarity is delivered through Mercury's articulate, intricate, fast-moving phrasing. The result is a single unified sound where every melodic statement is sharply enunciated and where the pulse and the figure-work share the same intent. The harmonic language is major and clear, voiced with Mercury's preference for transparency over weight. Listen for the quality of a melody that thinks aloud, where the line and the articulation of the line are the same thing, and where what is being said and the act of saying it cannot be pulled apart.`,
    core_synastry: `When one chart's Sun meets another's Mercury at conjunction, the Sun-bearer's conscious identity arrives at the precise frequency of how the Mercury-bearer perceives, thinks, and articulates. The Mercury-bearer reads the Sun-bearer with unusual clarity, often putting words to who the Sun-bearer is in a way the Sun-bearer recognizes as accurate before they had managed it themselves. The Sun-bearer, in turn, finds their natural way of being received as something the Mercury-bearer can name, describe, and reflect back. This is one of the most immediately legible resonances in synastry, often felt as the experience of being understood without having had to explain.`,
    behavioral_synastry: `In practice, the Mercury-bearer notices things about the Sun-bearer that the Sun-bearer has not yet noticed about themselves: turns of phrase the Sun-bearer uses without meaning to, patterns in how the Sun-bearer makes decisions, recurrences in what the Sun-bearer cares about. This perception is offered easily, and the Sun-bearer often experiences it as recognition rather than analysis. The Sun-bearer's identity gives the Mercury-bearer's mind a real subject to engage with. The shadow is asymmetric: the Mercury-bearer can come to know the Sun-bearer faster than the Sun-bearer comes to know the Mercury-bearer, because the Sun-bearer's identity is the thing being articulated rather than the thing doing the articulating. Both chart-bearers benefit from the Mercury-bearer remaining a real interlocutor rather than becoming the Sun-bearer's mirror.`,
    friendship_synastry: `In a friendship, this conjunction produces the friend who can describe the Sun-bearer to themselves. The Mercury-bearer is the one who remembers what the Sun-bearer said three years ago and quotes it back when it becomes relevant; the Sun-bearer is the one whose presence gives the Mercury-bearer's mind something genuinely worth turning over. These friendships often involve a great deal of conversation that neither friend would describe as small talk. The work is making sure the Mercury-bearer is also seen, not only the one doing the seeing.`,
    romantic_synastry: `In a romantic pairing, this conjunction produces the experience of feeling articulated by the other. The Sun-bearer encounters the Mercury-bearer as someone whose words for the relationship and for the Sun-bearer are unusually accurate; the Mercury-bearer encounters the Sun-bearer as someone whose presence gives every conversation a real subject. Verbal intimacy runs unusually high in partnerships with this aspect, and the relationship often deepens through extended conversation more than through other channels. The sustaining work is making sure the Sun-bearer also learns to articulate the Mercury-bearer rather than simply being articulated by them.`,
  },

  SUN_MERCURY_SEXTILE: {
    key: 'SUN_MERCURY_SEXTILE', pair: 'SUN_MERCURY', aspect: 'sextile', intensity: 'Low',
    core: `The Sun, conscious identity and the drive toward purposeful self-expression, and Mercury, the mind, perception, and the function of articulation that turns thought into form, are in a 60-degree relationship of easy, compatible exchange. The sextile places these two forces in neighboring territories where they understand each other's language. The person's sense of self and their cognitive life do not compete for psychological priority. Identity supports thought, and thought supports identity. The capacity to articulate who they are and what they perceive is available without internal friction.`,
    behavioral: `The sextile between the Sun's identity-function and Mercury's cognitive function creates a productive working relationship between the self and the mind. The conscious self uses thought as a tool rather than identifying with every passing perception, and the mind serves the self's articulation rather than running on tracks separate from it. The result is intellectual reliability without intellectual rigidity. This person can think out loud without the thinking destabilizing the self, and can hold a position firmly while remaining genuinely curious about contrary evidence. Their voice tends to sound like them rather than like someone playing a part. The shadow of the sextile is its own ease: without significant friction between identity and mind, this person may not develop unusual depth in either dimension, since both functions are competent enough that neither requires the kind of work that produces real range.`,
    friendship: `Easy to talk to. Reliably articulate without being performative. Friends find conversation with this person comfortable rather than effortful.`,
    romantic: `Partners appreciate that this person can usually find words for what they mean. The match between what they think and what they say is steady, and verbal exchange does not become a site of recurring misunderstanding.`,
    feed: `Today's transit field is gently opening the channel between conscious direction and articulated thought in this connection. There is easier access between what each person thinks and how each understands themselves than there is on an ordinary day.`,
    sonic: `The Sun contributes its steady purposeful pulse and clear melodic direction. Mercury contributes light articulate figure-work and quick contrapuntal motion. In the sextile these two voices cooperate without fusing. The Sun's directional melodic statements are accompanied by Mercury's clear, intricate articulation that traces the harmonic outline without obscuring it. The harmonic language is major and unambiguous, voiced with Mercury's clarity. The rhythm has the Sun's regularity and Mercury's lighter rhythmic surface working in natural cooperation. Listen for the quality of music that moves with both purpose and articulate intelligence, where the line knows where it is going and the articulation of every note along the way is precise.`,
    core_synastry: `When one chart's Sun meets another's Mercury at sextile, the Sun-bearer's natural self-expression and the Mercury-bearer's mind find a reliable channel of cooperation. The Mercury-bearer perceives the Sun-bearer accurately enough to be a useful interlocutor without producing the immediate identity-recognition the conjunction generates. The Sun-bearer's identity gives the Mercury-bearer's mind a genuine subject to engage; the Mercury-bearer's articulation gives the Sun-bearer language for what they were already becoming. The bond's intellectual register runs steady rather than electric.`,
    behavioral_synastry: `The Mercury-bearer reads the Sun-bearer well, with enough accuracy to be helpful and enough distance to remain a separate mind rather than a mirror. Conversations between the two chart-bearers tend to clarify rather than complicate, and decisions made together tend to be articulated honestly because each chart-bearer can describe what they actually want without misrepresentation. The aspect produces durable working compatibility in the verbal and intellectual domain without the immediacy of the conjunction. Both chart-bearers remain themselves, the contact between them is reliably productive, and shared thinking lands somewhere both can stand.`,
    friendship_synastry: `In a friendship, this sextile produces the friend conversations are easy with. The Mercury-bearer enjoys the Sun-bearer's company because the Sun-bearer gives them something real to think about; the Sun-bearer enjoys the Mercury-bearer's company because the Mercury-bearer's articulation is welcome rather than intrusive. These friendships are often the ones marked by ongoing genuine conversation across years and life phases.`,
    romantic_synastry: `In a romantic pairing, this sextile produces a relationship where verbal communication runs reliably well. The Mercury-bearer can describe what the relationship needs without it landing as criticism on the Sun-bearer's identity; the Sun-bearer can express what they want without the Mercury-bearer over-analyzing it. Partnerships with this aspect tend to weather difficulty better than those without strong Mercury contact, because the partners can actually talk about what is happening between them when difficulty arrives.`,
  },

  SUN_MERCURY_SQUARE: {
    key: 'SUN_MERCURY_SQUARE', pair: 'SUN_MERCURY', aspect: 'square', intensity: 'Medium',
    core: `The Sun, the principle of conscious identity and willful direction, meets Mercury, the mind, perception, and the function of articulation, at a 90-degree angle of sustained tension. The square does not resolve easily because identity and thought are both genuinely strong here and neither yields to the other. The Sun knows what it wants to be. Mercury notices things that complicate that picture. The person experiences a recurring friction between the self they consciously identify with and the perceptions, doubts, and articulations the mind produces about that self. This is not a flaw. It is a configuration that produces unusual self-awareness alongside unusual self-questioning.`,
    behavioral: `The Sun's drive toward unified self-definition and Mercury's tendency to notice nuance, contradiction, and contrary evidence are in 90-degree friction that neither can resolve by simply overriding the other. This produces a pattern recognizable as the smart self-doubter: a person whose intellectual capacity is real, who can analyze most situations clearly, and who turns that same capacity onto themselves with results that are not always kind. The internal critic is loud. Thoughts arrive faster than the self can absorb them, and the self ends up arguing with its own perception. The development task is learning to let Mercury be a tool rather than a tribunal: the mind notices things, including unflattering things, and the self decides what to do with the information rather than treating every perception as a verdict on identity.`,
    friendship: `May be self-deprecating or quick to second-guess. Friends sometimes see this person more clearly than this person sees themselves, and serve as a useful counterweight to the inner critic that runs louder here than is fair.`,
    romantic: `Partners may notice the gap between this person's actual capabilities and their self-assessment. The Mercury function turns inward more sharply than is warranted. Reassurance helps but does not finally resolve it; the work is internal.`,
    feed: `A transit is pressing on the friction point between identity and articulation in this connection. The gap between what each person consciously identifies with and what each perceives about themselves is closer to the surface today than usual, and there is something productive available in naming it.`,
    sonic: `The Sun pushes its melody forward with directional confidence. Mercury cuts across that confidence with quick contrapuntal lines that question, qualify, and complicate the harmonic landing. In the square these two sonic characters are in genuine friction. The Sun's clear major statements are interrupted by Mercury's incisive counter-figures, and Mercury's articulate intelligence keeps adding qualifications the Sun's pulse did not invite. The harmonic language moves between major resolution and quick chromatic passing motion that destabilizes the resolution before it fully lands. Listen for the quality of music where a clear statement is made and then a quick mind picks at it, where the melody and the commentary on the melody are happening at the same time and not always in agreement.`,
    core_synastry: `When one chart's Sun meets another's Mercury at square, the Sun-bearer's identity and the Mercury-bearer's perception find each other through friction. The Mercury-bearer's natural articulations of the Sun-bearer consistently miss in some small way: too pointed, too clinical, too quick, or focused on something the Sun-bearer was hoping would not be noticed. The Sun-bearer's identity, in turn, registers in the Mercury-bearer's awareness as something not quite matching the words available to describe it. Neither chart-bearer is doing anything wrong. The geometry produces real, structural mismatch between what one is and what the other can name.`,
    behavioral_synastry: `The Mercury-bearer's observations about the Sun-bearer often land with more weight than the Mercury-bearer intended, because what reads as a casual remark to the Mercury-bearer registers in the Sun-bearer's awareness as a description of self. The Sun-bearer's responses sometimes seem to the Mercury-bearer like overreaction, because the Mercury-bearer was simply thinking aloud. This produces a bond marked by recurring small misunderstandings about what was meant, what was heard, and what was actually being said. The work is real: the Mercury-bearer learning to register the weight their articulations carry, the Sun-bearer learning to receive observations as information rather than as verdicts on the self.`,
    friendship_synastry: `In a friendship, this square produces a bond marked by genuine intellectual engagement and recurring small misfires in conversation. The Mercury-bearer's quick observations sometimes land harder than intended; the Sun-bearer sometimes hears critique where description was offered. These friendships endure when both friends learn that the friction is the aspect's signature rather than evidence of bad faith, and develop the habit of repairing quickly when an exchange goes off-key.`,
    romantic_synastry: `In a romantic pairing, this square produces a relationship of substance where verbal exchanges carry unusual weight. The Mercury-bearer's words land on the Sun-bearer's identity rather than glancing off, and the Sun-bearer's responses can read to the Mercury-bearer as defensive when the Mercury-bearer was simply observing. Partnerships with this aspect develop genuine fluency in each other's communicative styles when both partners commit to the work, and the verbal intimacy that results is more honest than easier configurations produce.`,
  },

  SUN_MERCURY_TRINE: {
    key: 'SUN_MERCURY_TRINE', pair: 'SUN_MERCURY', aspect: 'trine', intensity: 'Low',
    core: `The Sun, conscious identity and the drive toward purposeful self-definition, and Mercury, the mind, perception, and the function of articulation that converts thought into form, are separated by 120 degrees, placing them in the same elemental family. The trine means these two forces do not experience each other as foreign. The conscious self and the thinking self are oriented toward compatible ends, drawing on the same elemental register, supporting each other without effort. This person's voice tends to sound like them. What they think and what they identify with run on the same current.`,
    behavioral: `The trine between the Sun's identity-function and Mercury's cognitive function creates a well-integrated articulating self. The mind serves the conscious will rather than running on a separate track, and the conscious will is articulate about its own ends rather than driving forward without intellectual self-awareness. This person can describe what they want, why they want it, and how they propose to pursue it without significant internal friction in any of those operations. The cognitive style tends to be clear without being cold, verbal without being verbose, and articulate without performing articulacy. The shadow of this trine is the same shadow it carries everywhere: ease can produce comfortable underdevelopment of either function, since neither identity nor mind is forced into the kind of contention that produces depth.`,
    friendship: `Reliable conversational presence. This person finds words easily and means what they say. Friends return to them because talking with them clarifies rather than complicates.`,
    romantic: `Partners often cite the ease of being understood by this person. They listen well and articulate accurately. The match between intent and expression is steady.`,
    feed: `The current sky is amplifying the natural coherence between identity and articulation in this connection. What runs easily between these two charts in the verbal and intellectual register is running more easily right now than it does on an ordinary day.`,
    sonic: `The Sun and Mercury are in the same elemental family in the trine. The Sun's directional clarity and Mercury's articulate figure-work flow together without friction between purpose and precision. The melodic lines have the Sun's purposeful direction and Mercury's clean articulation simultaneously. The harmonic language is clear, voiced with Mercury's preference for transparency. Every note is well-placed; every line knows where it is going; every articulation lands precisely where it was aiming. Listen for the quality of music that thinks aloud with grace, where the line and the articulation of the line are both clear and never at odds with each other.`,
    core_synastry: `When one chart's Sun meets another's Mercury at trine, the Sun-bearer's identity and the Mercury-bearer's mind find each other in the same elemental family, moving in compatible directions without effort. The Mercury-bearer perceives the Sun-bearer accurately as a default rather than as an achievement; the Sun-bearer's identity gives the Mercury-bearer a real subject to engage with, and the Mercury-bearer's articulations land where the Sun-bearer recognizes themselves rather than missing slightly. The bond runs intellectually warm without effort.`,
    behavioral_synastry: `The Mercury-bearer's observations about the Sun-bearer tend to be the kind the Sun-bearer recognizes immediately, and the Sun-bearer's responses give the Mercury-bearer real material to work with. Conversations clarify; shared thinking moves forward; decisions made together get articulated honestly because both chart-bearers can describe what they actually mean. The aspect produces sustained intellectual ease that does not need to be manufactured. The trine's limitation is that the same ease can let both chart-bearers stay at a comfortable level of mutual understanding without ever pushing into the harder territory where real depth lives.`,
    friendship_synastry: `In a friendship, this trine produces the friend conversations work with by default. The Mercury-bearer enjoys the Sun-bearer's company because the Sun-bearer's identity gives every exchange a real subject; the Sun-bearer enjoys the Mercury-bearer's company because the Mercury-bearer's articulation is welcome and accurate. These friendships often last across years because the underlying intellectual compatibility holds without effort.`,
    romantic_synastry: `In a romantic pairing, this trine produces a relationship marked by sustained verbal ease. The Mercury-bearer can describe what is happening between the two without it landing as criticism; the Sun-bearer can express what they want without the Mercury-bearer parsing it into something it was not. Partnerships with this aspect tend to weather difficulty well because the partners can actually talk to each other when difficulty arrives, and the conversation tends to clarify rather than complicate.`,
  },

  SUN_MERCURY_OPPOSITION: {
    key: 'SUN_MERCURY_OPPOSITION', pair: 'SUN_MERCURY', aspect: 'opposition', intensity: 'Medium',
    core: `The Sun, conscious identity, willful direction, and the ego's drive to define itself, stands opposite Mercury, the mind, perception, and the function of articulation, across a 180-degree axis of full polarity. The opposition holds these two forces apart and in constant awareness of each other. The Sun knows the mind is observing. Mercury knows the self is acting. Neither can ignore the other. The person experiences a structural distance between the self that does and the self that thinks about doing, with each pole fully visible to the other across the gap.`,
    behavioral: `The psychological mechanism of the Sun-Mercury opposition is the gap between action and articulation, made conscious. The person who acts and the person who narrates that action are not the same psychological agent in this configuration. They face each other. Where the conjunction fuses identity and mind into a single voice, the opposition holds them at maximum distance, which produces a characteristic capacity for self-observation alongside a characteristic difficulty trusting that the observer and the observed are the same person. This person often processes their own life through dialogue with others, because external interlocutors temporarily collapse the internal axis: someone else's articulation can be received without the suspicion that always attends the person's own self-description. The development task is learning to be both poles of the axis at once rather than alternating between them.`,
    friendship: `Friends are often important sounding boards. The articulation that happens in conversation does work for this person that internal monologue cannot finish on its own.`,
    romantic: `Partnership becomes a primary site of self-articulation. The partner's words for the relationship and for this person carry weight because they bridge an internal gap that this person cannot fully bridge alone.`,
    feed: `Today's transits are illuminating both ends of the identity-articulation axis in this connection. The space between what each person is and what each can say about themselves is more visible right now between these two charts than it usually is, and there is something to do with that visibility today.`,
    sonic: `The Sun and Mercury in opposition produce a composition built on call and response between two distinct voices. The Sun's purposeful, directional melodic statements are answered by Mercury's quick, articulate counter-lines from the opposite end of the musical space. The two voices are at maximum distance and in constant dialogue across that distance. Neither dominates for long; each comments on the other. The harmonic language alternates between the Sun's clear major resolutions and Mercury's quick chromatic passing motion that observes and qualifies the resolution from outside. Listen for the quality of music where action and observation are happening as two separate voices in conversation, where the doing and the watching the doing are both audible at the same time and never fully merge.`,
    core_synastry: `When one chart's Sun meets another's Mercury at opposition, the two charts face each other across the full width of the synastry axis. The Sun-bearer's identity sits at one pole; the Mercury-bearer's mind sits at the other. Each is fully visible to the other across the distance, and neither is hidden. The Mercury-bearer's perception of the Sun-bearer is unusually clear, sometimes uncomfortably so. The Sun-bearer's presence gives the Mercury-bearer's mind something to circle, describe, and articulate, sometimes more than the Sun-bearer asked for. The bond becomes a site where being and being-described meet across genuine distance.`,
    behavioral_synastry: `The Mercury-bearer often finds themselves narrating, observing, or articulating the Sun-bearer in ways neither chart-bearer fully chose. The Sun-bearer often finds themselves reflected in the Mercury-bearer's words, sometimes recognizing themselves and sometimes not. This produces a bond marked by significant verbal exchange where the stakes are higher than they appear: each conversation is partly the Mercury-bearer trying to put words to the Sun-bearer, and the Sun-bearer either claiming or refusing those words. Worked consciously, the polarity becomes one of the most generative configurations for mutual understanding. Worked unconsciously, the bond cycles between the Mercury-bearer over-articulating and the Sun-bearer feeling defined from outside.`,
    friendship_synastry: `In a friendship, this opposition produces the friend whose conversations carry weight. The Mercury-bearer becomes the one who can put words to what the Sun-bearer is going through; the Sun-bearer becomes the one who gives the Mercury-bearer's mind something genuinely worth articulating. These friendships often involve long, important conversations that neither friend would describe as casual, and they tend to deepen significantly when both friends accept that what is being exchanged is more than information.`,
    romantic_synastry: `In a romantic pairing, this opposition produces a relationship where verbal exchange carries unusual stakes. The Mercury-bearer's articulations of the Sun-bearer and of the relationship reach across distance and can land with significant force; the Sun-bearer's responses to those articulations shape what the relationship actually becomes. Partnerships with this aspect either develop genuine fluency in the dialogue between identity and articulation or break down into recurring arguments about what was meant, what was heard, and who has the right to describe whom. The middle path is the work, and partners who do it well report a relationship of unusual verbal honesty.`,
  },

  MOON_MERCURY_CONJUNCTION: {
    key: 'MOON_MERCURY_CONJUNCTION', pair: 'MOON_MERCURY', aspect: 'conjunction', intensity: 'Background',
    core: `The Moon, the principle of emotional instinct, interior need, memory, and the body's immediate, pre-cognitive responses to the world, fuses with Mercury, the planet governing the mind, perception, learning, and the function of articulation that converts inner experience into language. Where a conjunction occurs, two planets operate as one undivided system. Here that means the emotional self and the thinking self are not two separate registers. They run along the same current. What this person feels, they think about immediately. What they perceive, they process emotionally. The Moon's instinctive body-wisdom and Mercury's cognitive clarity are fused into a single integrated response mechanism.`,
    behavioral: `Because the Moon's affect-system and Mercury's cognitive function are fused rather than sequential, this person experiences a very short lag time between feeling something and naming it. Emotional intelligence in the specific sense of being able to articulate what is being felt runs very high here. The person can describe their interior state with precision, not because they have learned emotional vocabulary as a skill, but because the emotional experience and the cognitive articulation of that experience arrive together as a single motion. This produces psychological self-awareness that is immediate rather than reflective. The shadow is that the mind can over-process emotional signals before the body has had time to simply feel them, converting every emotional experience into a thought about the emotional experience before the experience itself has been fully absorbed.`,
    friendship: `Friends experience this person as emotionally articulate and psychologically present. They can name what they are feeling as it is happening, which makes conflict resolution and emotional repair unusually direct.`,
    romantic: `Partners appreciate that this person can describe their emotional state rather than expecting it to be inferred. The fusion of Moon and Mercury means verbal exchange about feelings is natural rather than effortful.`,
    feed: `The current sky is threading lunar and Mercurial frequencies through this connection at the same pitch. A window is open right now where what each person feels and how each articulates feeling are aligned between these two charts.`,
    sonic: `The Moon contributes its modal harmonic ambiguity, breathing rhythmic instinct, and memory-driven emotional cycling. Mercury contributes quick melodic articulation, contrapuntal motion, and rapid figure-work. In the conjunction these two voices are fused. The Moon's emotional cycling is articulated with Mercury's precision: every emotional shift is named, traced, and given clear melodic form. The harmonic language is modal with Mercury's transparent voicing, emotionally ambiguous but clearly articulated. The rhythm breathes like the Moon but is subdivided with Mercury's quick, precise surface motion. Listen for the quality of music where something is being felt and described at the same time, where the emotional content and the articulation of that content are the same gesture.`,
    core_synastry: `When one chart's Moon meets another's Mercury at conjunction, the Moon-bearer's emotional foundation lands at the precise frequency of how the Mercury-bearer perceives and articulates. The Mercury-bearer reads the Moon-bearer's emotional state with unusual clarity, often naming what the Moon-bearer is feeling before the Moon-bearer has fully registered it themselves. The Moon-bearer, in turn, finds their interior life articulated by the Mercury-bearer in words that feel accurate rather than intrusive. This is one of the most immediately emotionally legible resonances in synastry, often experienced as being emotionally understood without having to explain.`,
    behavioral_synastry: `In practice, the Mercury-bearer notices subtle shifts in the Moon-bearer's emotional weather and names them out loud in concrete terms—quieter than usual, still unsettled after a particular exchange, more settled than they were that morning. These observations tend to be accurate, and the Moon-bearer often experiences them as welcome rather than invasive, because what the Mercury-bearer names is what the Moon-bearer was beginning to feel but had not yet put into words. The shadow is that the Mercury-bearer can become the Moon-bearer's emotional narrator, doing the articulation work for both chart-bearers, and the Moon-bearer can become dependent on that narration rather than developing their own emotional vocabulary.`,
    friendship_synastry: `In a friendship, this conjunction produces the friend who can put words to emotional dynamics in the group or in the Moon-bearer's life that no one else is naming. The Mercury-bearer becomes the one who says, "That's what's actually happening here," and the Moon-bearer is the one whose emotional presence gives the Mercury-bearer something real to articulate. These friendships often involve long conversations where emotional states are examined closely and honestly.`,
    romantic_synastry: `In a romantic pairing, this conjunction produces the experience of feeling emotionally translated. The Mercury-bearer can describe what the Moon-bearer is feeling in ways the Moon-bearer recognizes as true, and the Moon-bearer's emotional openness gives the Mercury-bearer's mind real material to work with. Partnerships with this aspect tend to involve significant verbal processing of emotional states, and the relationship deepens through sustained emotional conversation. The work is making sure the Moon-bearer retains their own emotional voice rather than outsourcing all emotional articulation to the Mercury-bearer.`,
  },

  MOON_MERCURY_SEXTILE: {
    key: 'MOON_MERCURY_SEXTILE', pair: 'MOON_MERCURY', aspect: 'sextile', intensity: 'Low',
    core: `The Moon, emotional instinct, interior need, and the body's pre-cognitive responses, and Mercury, the mind, perception, and the function of articulation, are in a 60-degree relationship of easy, compatible exchange. The sextile places these two forces in neighboring territories where they can communicate without strain. The person's emotional life and their thinking life are not in competition. Feelings inform thoughts; thoughts help process feelings. The capacity to articulate emotional experience is available without the over-processing that can occur when these two are more tightly bound.`,
    behavioral: `The sextile between the Moon's affect-system and Mercury's cognitive function creates a productive working relationship between feeling and naming. The person can access their emotional state, think about it without immediately dissolving the feeling into analysis, and articulate what is happening with accuracy when articulation is needed. This is emotional intelligence in its most integrated, least effortful form: the person knows what they feel, can describe it when asked, and does not need constant verbal processing to maintain emotional equilibrium. The capacity to soothe through self-talk is real here, because the mind can speak to the emotional body in language the emotional body recognizes.`,
    friendship: `Emotionally reliable and easy to talk to. Can describe what they are feeling without making the conversation about them, and can listen to others' emotional states without needing to fix them immediately.`,
    romantic: `Partners appreciate the steady emotional availability. This person can articulate needs without drama and can receive their partner's emotional signals with both empathy and clarity.`,
    feed: `Today's transit field is gently opening the channel between emotional instinct and articulated thought in this connection. There is easier access between what each person feels and how each describes feeling than there is on an ordinary day.`,
    sonic: `The Moon's emotional instinct and Mercury's articulate precision are in easy sequential cooperation in the sextile. The Moon generates the emotional content and Mercury traces it with clear melodic articulation. The harmonic language is modally warm with Mercury's transparent voicing. The rhythm has the Moon's organic breathing quality and Mercury's quick subdivided surface in natural dialogue. Listen for the quality of music where something is felt and then clearly described, where the feeling and the naming of the feeling are in easy cooperation rather than fused or in tension.`,
    core_synastry: `When one chart's Moon meets another's Mercury at sextile, the Moon-bearer's emotional rhythms and the Mercury-bearer's perception find a productive channel between them. The Mercury-bearer can read the Moon-bearer's emotional cues with enough accuracy to be helpful without the immediate translation the conjunction produces. The Moon-bearer's emotional state gives the Mercury-bearer real information to work with, and the Mercury-bearer's articulation gives the Moon-bearer useful language for their own interior without overwhelming it. The bond's emotional register runs steady and clear.`,
    behavioral_synastry: `The Mercury-bearer notices the Moon-bearer's emotional shifts and can name them when asked, but does not narrate the Moon-bearer's interior continuously. The Moon-bearer trusts the Mercury-bearer's observations because they tend to be accurate without being invasive. This produces a connection where emotional conversations clarify rather than complicate, where the Moon-bearer can describe what they need and the Mercury-bearer can articulate what they are observing, and both chart-bearers feel heard. The aspect produces durable emotional communication without the intensity of the conjunction.`,
    friendship_synastry: `In a friendship, this sextile produces the friend emotional conversations work well with. The Mercury-bearer can listen to the Moon-bearer's emotional processing and reflect it back accurately; the Moon-bearer trusts the Mercury-bearer's observations without feeling exposed. These friendships are often marked by sustained emotional honesty that runs quietly rather than dramatically.`,
    romantic_synastry: `In a romantic pairing, this sextile produces a relationship where emotional communication runs reliably well. The Mercury-bearer can describe what is happening between the two without the Moon-bearer experiencing it as criticism; the Moon-bearer can express emotional needs without the Mercury-bearer over-analyzing them. Partnerships with this aspect tend to weather difficulty better than those without strong Moon-Mercury contact, because the partners can actually talk about what they are feeling when difficulty arrives.`,
  },

  MOON_MERCURY_SQUARE: {
    key: 'MOON_MERCURY_SQUARE', pair: 'MOON_MERCURY', aspect: 'square', intensity: 'Medium-high',
    core: `The Moon, the principle of emotional instinct, pre-cognitive bodily responses, and the need for interior safety, meets Mercury, the mind, perception, and the function of articulation, at a 90-degree angle of sustained tension. The square does not resolve easily because both forces are genuinely strong and neither yields to the other. The Moon wants to feel before it names. Mercury wants to name before the feeling has settled. The person experiences a recurring friction between their emotional life and their thinking life, not as pathology but as an ongoing negotiation between two equally legitimate modes of processing.`,
    behavioral: `The Moon's need to absorb emotional experience bodily and Mercury's drive to articulate and analyze that experience are in 90-degree friction that neither can resolve by overriding the other. This produces a characteristic pattern: the person feels something, the mind immediately begins analyzing the feeling, and the analysis interrupts the feeling before the body has had time to simply sit with it. Alternatively, the Moon resists the mind's attempt to put words to it, and the person ends up unable to articulate what they are feeling even when articulation would be useful. The development task is learning to let the Moon feel first and the Mercury function describe second, creating a deliberate pause between the emotional signal and the cognitive processing of that signal.`,
    friendship: `May struggle to describe what they are feeling in the moment, or may over-describe in ways that intellectualize the emotion rather than expressing it. Friends who can hold space for both the feeling and the thinking without forcing immediate clarity serve this person well.`,
    romantic: `Partners may notice the gap between this person's emotional state and their ability to articulate it. What is felt and what is said do not always match cleanly. Patience with the lag time between feeling and naming is required.`,
    feed: `A transit is pressing on the friction point between emotional instinct and articulated thought in this connection. The gap between what each person feels and what each can say about feeling is closer to the surface today than usual, and there is something productive available in naming it.`,
    sonic: `The Moon's emotional cycling and Mercury's quick articulate precision are in genuine friction in the square. The Moon wants the harmonic language to stay in suspended, emotionally ambiguous modal territory. Mercury wants to clarify the harmony through articulation. The Moon's organic breathing rhythm is cut across by Mercury's quick subdivided surface motion. The result is a composition where emotional content and analytical clarity keep interrupting each other. Listen for the quality of music where something is being felt and something is being thought about that feeling at the same time, and the two processes are not in agreement about timing.`,
    core_synastry: `When one chart's Moon meets another's Mercury at square, the Moon-bearer's emotional ground and the Mercury-bearer's articulation find each other through friction. The Mercury-bearer's observations about the Moon-bearer's emotional state tend to arrive too quickly, before the Moon-bearer has finished feeling what they are feeling. The Moon-bearer's emotional rhythms register in the Mercury-bearer's awareness as something that resists clear articulation, something ambiguous that the Mercury-bearer wants to clarify but cannot. Neither chart-bearer is doing anything wrong. The geometry produces real, recurring mismatch between the speed of feeling and the speed of naming.`,
    behavioral_synastry: `The Mercury-bearer often finds themselves trying to put words to the Moon-bearer's emotional state before the Moon-bearer is ready to have it named, and the Moon-bearer experiences the Mercury-bearer's articulations as premature or slightly off-key. The Moon-bearer's emotional signals, in turn, reach the Mercury-bearer as something harder to read than expected, and the Mercury-bearer's attempts to clarify through questions can feel to the Moon-bearer like pressure to explain before understanding has arrived. This produces a bond marked by recurring small frictions in emotional communication. The work is genuine: the Mercury-bearer learning to slow the speed of articulation, the Moon-bearer learning to tolerate the discomfort of naming feelings before they have fully settled.`,
    friendship_synastry: `In a friendship, this square produces a bond where genuine care coexists with recurring small misunderstandings about emotional states. The Mercury-bearer tries to help by naming what they observe; the Moon-bearer sometimes experiences that naming as intrusive. These friendships work when both friends accept that emotional communication will require more deliberate care than it does in easier configurations, and develop the habit of repairing when an exchange goes off-key.`,
    romantic_synastry: `In a romantic pairing, this square produces a relationship of substance where emotional communication requires real work. The Mercury-bearer's attempts to articulate what is happening emotionally can land on the Moon-bearer as analysis rather than empathy; the Moon-bearer's emotional states can read to the Mercury-bearer as opaque in ways that generate frustration. Partnerships with this aspect develop genuine fluency in each other's emotional language when both partners commit to the work, and the emotional intimacy that results is more honest than easier configurations produce.`,
  },

  MOON_MERCURY_TRINE: {
    key: 'MOON_MERCURY_TRINE', pair: 'MOON_MERCURY', aspect: 'trine', intensity: 'Low',
    core: `The Moon, emotional instinct, interior need, and the body's immediate responses, and Mercury, the mind, perception, and the function of articulation, are separated by 120 degrees, placing them in the same elemental family. The trine means these two forces do not experience each other as foreign. The emotional self and the thinking self are oriented toward compatible ends, drawing on the same elemental register. What this person feels and what they can say about feeling flow in the same direction. Emotional intelligence is structural here.`,
    behavioral: `The trine between the Moon's affect-system and Mercury's cognitive function creates a well-integrated emotional articulation capacity. The person can feel their feelings fully without the mind immediately dissolving them into analysis, and can think about their feelings clearly without the emotional body resisting the cognitive processing. This is emotional self-awareness that is both genuine and articulate. The person knows what they feel, can describe it when needed, and does not require extensive verbal processing to maintain emotional equilibrium. The shadow of this trine is its own ease: without friction between feeling and thinking, the person may not develop unusual depth in emotional life, since both functions are competent enough that neither requires the kind of developmental pressure that produces real range.`,
    friendship: `Emotionally present and easy to talk to. Can describe their interior state clearly and can receive others' emotional processing without needing to fix it or intellectualize it away.`,
    romantic: `Partners often cite the emotional reliability. This person can articulate needs, can sit with their partner's emotional states, and can engage in emotional repair without defensiveness.`,
    feed: `The current sky is amplifying the natural coherence between emotional instinct and articulated thought in this connection. What flows easily between these two charts in the emotional-communicative register is flowing more easily right now than it does on an ordinary day.`,
    sonic: `The Moon and Mercury are in the same elemental family in the trine. The emotional cycling and the articulate precision flow together without friction between feeling and naming. The harmonic language is modally rich with Mercury's transparent voicing, emotionally ambiguous and clearly articulated at the same time. The rhythm has the Moon's organic breathing quality and Mercury's quick surface articulation in natural agreement. Listen for the quality of music where something is felt and described with equal ease, where the emotional content and the clarity of articulation are moving in the same direction and never at odds.`,
    core_synastry: `When one chart's Moon meets another's Mercury at trine, the Moon-bearer's emotional foundation and the Mercury-bearer's mind find each other in the same elemental family, moving in compatible directions without effort. The Mercury-bearer reads the Moon-bearer's emotional rhythms with natural accuracy; the Moon-bearer's interior life gives the Mercury-bearer real material to articulate, and the articulations tend to land where the Moon-bearer recognizes themselves. The bond runs emotionally warm and verbally clear without needing to manufacture either quality.`,
    behavioral_synastry: `The Mercury-bearer's observations about the Moon-bearer's emotional state tend to be the kind the Moon-bearer recognizes immediately, and the Moon-bearer's emotional cues give the Mercury-bearer clear signals to work with. Emotional conversations clarify; decisions about the relationship get articulated honestly; misunderstandings repair easily because both chart-bearers can describe what actually happened. The aspect produces sustained emotional-communicative ease that does not need to be performed. The trine's limitation is that the same ease can let both chart-bearers stay at a comfortable level of emotional exchange without pushing into the harder territory where real depth lives.`,
    friendship_synastry: `In a friendship, this trine produces the friend emotional honesty works well with. The Mercury-bearer can articulate what they observe about the Moon-bearer's emotional life without it landing as intrusion; the Moon-bearer trusts the Mercury-bearer's observations because they tend to be accurate and offered in good faith. These friendships often last across years because the underlying emotional-communicative compatibility holds without effort.`,
    romantic_synastry: `In a romantic pairing, this trine produces a relationship marked by sustained emotional clarity. The Mercury-bearer can describe what is happening between the two without the Moon-bearer experiencing it as attack; the Moon-bearer can express emotional needs without the Mercury-bearer over-analyzing or defending. Partnerships with this aspect tend to be the ones friends describe as remarkably communicative, where both partners can actually talk about what they are feeling and be heard.`,
  },

  MOON_MERCURY_OPPOSITION: {
    key: 'MOON_MERCURY_OPPOSITION', pair: 'MOON_MERCURY', aspect: 'opposition', intensity: 'Medium-high',
    core: `The Moon, the principle of emotional instinct, interior feeling, and the body's pre-cognitive responses, stands opposite Mercury, the mind, perception, and the function of articulation, across a 180-degree axis of full polarity. The opposition holds these two forces apart and in constant awareness of each other. The Moon knows the mind is watching. Mercury knows the body is feeling. Neither can ignore the other. The person experiences a structural distance between the self that feels and the self that thinks about feeling, with each pole fully visible to the other across the gap.`,
    behavioral: `The psychological mechanism of the Moon-Mercury opposition is the gap between emotional experience and cognitive articulation, made fully conscious. The person who feels and the person who describes that feeling are not the same psychological agent in this configuration. They face each other. Where the conjunction fuses emotion and thought into immediate articulation, the opposition holds them at maximum distance, which produces a characteristic capacity for emotional self-observation alongside a characteristic difficulty trusting that the observer and the observed are the same person. This configuration often produces writers, therapists, and people who process their emotional lives through sustained verbal or written articulation, because the gap between feeling and naming creates a need for the articulation work that bridges it.`,
    friendship: `Friends are often important sounding boards. The articulation of emotional states that happens in conversation does work for this person that internal reflection cannot complete on its own.`,
    romantic: `Partnership becomes a primary site of emotional processing. The partner's words for what the Moon-bearer is feeling carry weight because they bridge an internal gap the Moon-bearer cannot fully bridge alone.`,
    feed: `Today's transits are illuminating both ends of the feeling-articulation axis in this connection. The space between what each person feels and what each can say about feeling is more visible right now between these two charts than it usually is, and there is something to do with that visibility today.`,
    sonic: `The Moon and Mercury in opposition produce a composition built on call and response between emotional instinct and articulate observation. The Moon's breathing, modal, memory-driven emotional cycling is answered by Mercury's quick, clear, articulate counter-lines from the opposite end of the musical space. The two voices are at maximum distance and in constant dialogue across that distance. Neither dominates for long; each observes and responds to the other. The harmonic language alternates between the Moon's emotionally suspended modal quality and Mercury's clarifying chromatic motion. Listen for the quality of music where feeling and naming are happening as two separate voices in conversation, where the emotion and the description of the emotion are both audible at the same time and never fully merge.`,
    core_synastry: `When one chart's Moon meets another's Mercury at opposition, the two charts face each other across the full width of the synastry axis. The Moon-bearer's emotional foundation sits at one pole; the Mercury-bearer's mind sits at the other. Each is fully visible to the other across the distance, and neither is hidden. The Mercury-bearer's perception of the Moon-bearer's emotional life is unusually sharp, sometimes uncomfortably so. The Moon-bearer's emotional presence gives the Mercury-bearer's mind something to observe, describe, and articulate, sometimes more than the Moon-bearer asked for. The bond becomes a site where feeling and being-described meet across genuine distance.`,
    behavioral_synastry: `The Mercury-bearer often finds themselves narrating the Moon-bearer's emotional states, observing patterns the Moon-bearer has not yet named, and articulating dynamics the Moon-bearer is still absorbing bodily. The Moon-bearer often finds themselves reflected in the Mercury-bearer's words, sometimes recognizing themselves and sometimes not. This produces a bond marked by significant emotional-verbal exchange where the stakes are higher than they appear: each conversation is partly the Mercury-bearer trying to put words to the Moon-bearer's interior, and the Moon-bearer either claiming or refusing those words. Worked consciously, the polarity becomes one of the most emotionally articulate configurations in synastry. Worked unconsciously, the bond cycles between the Mercury-bearer over-articulating and the Moon-bearer feeling described from outside rather than understood from inside.`,
    friendship_synastry: `In a friendship, this opposition produces the friend whose emotional observations carry weight. The Mercury-bearer becomes the one who can put words to what the Moon-bearer is going through; the Moon-bearer becomes the one who gives the Mercury-bearer's mind something genuinely worth articulating. These friendships often involve sustained emotional processing conversations that neither friend would describe as casual, and they tend to deepen significantly when both friends accept that what is being exchanged is emotional translation rather than simple companionship.`,
    romantic_synastry: `In a romantic pairing, this opposition produces a relationship where verbal processing of emotional states carries unusual stakes. The Mercury-bearer's articulations of the Moon-bearer's feelings and of the relationship reach across distance and can land with significant force; the Moon-bearer's responses to those articulations shape what the relationship actually becomes. Partnerships with this aspect either develop genuine fluency in the dialogue between feeling and naming or break down into recurring arguments about what was felt, what was meant, and who has the right to describe the emotional reality between them. The middle path is the work, and partners who do it well report a relationship of unusual emotional honesty.`,
  },

  MERCURY_VENUS_CONJUNCTION: {
    key: 'MERCURY_VENUS_CONJUNCTION', pair: 'MERCURY_VENUS', aspect: 'conjunction', intensity: 'Background',
    core: `Mercury, the planet governing the mind, perception, learning, and the function of articulation that converts thought into language, fuses with Venus, the planet governing love, aesthetic value, relational attunement, and what the person finds beautiful and worthy of desire. Where a conjunction occurs, two planets operate as one undivided system. Here that means the way this person thinks and the way they love are not two separate registers. They run along the same current. What they find beautiful, they want to understand. What they articulate, they shape toward beauty. The mind is an aesthetic instrument. Language is a medium of affection.`,
    behavioral: `Because Mercury's cognitive function and Venus's love-and-beauty function are fused rather than distinct, this person's intellectual life runs heavily through aesthetic and relational channels. Thinking is not a cold analytical operation for this person. It is a warm, appreciative, sensory engagement with the world. They notice beauty in ideas, elegance in arguments, grace in the way someone explains something. Conversely, their affections and aesthetic preferences are highly articulate: they can describe what they love and why they love it with precision. The fusion also means relational warmth is expressed primarily through verbal and intellectual channels. To be loved by this person is to be spoken to with care, listened to with genuine interest, and engaged with intellectually. The challenge is that criticism of how they think or speak can feel like rejection of their capacity to love, because for this person thinking beautifully and loving well are the same act.`,
    friendship: `Warm, conversational, genuinely interested in the lives and ideas of people they care about. These friendships run on sustained verbal exchange more than on shared activity.`,
    romantic: `Love is expressed through language for this person. Compliments are genuine. Conversations are a form of intimacy. Partners who are themselves articulate and who value verbal exchange thrive here.`,
    feed: `The current sky is threading Mercurial and Venusian frequencies through this connection at the same pitch. A window is open right now where what each person thinks and what each values are aligned between these two charts.`,
    sonic: `Mercury contributes quick melodic articulation, contrapuntal motion, and rapid transparent figure-work. Venus contributes rich consonant harmony, beautiful voice leading, and sensory melodic warmth. In the conjunction these two voices are fused. Mercury's articulate precision is delivered with Venus's acoustic beauty: every melodic gesture is both clear and lovely. The harmonic language is major with rich Venusian color tones, resolved and aesthetically warm. The rhythm has Mercury's quick subdivided surface and Venus's graceful flow as one unified motion. Listen for the quality of music where thinking and beauty are the same thing, where every articulated idea sounds inherently lovely and every beautiful phrase is also intelligently constructed.`,
    core_synastry: `When one chart's Mercury meets another's Venus at conjunction, the Mercury-bearer's mind arrives at the precise frequency of what the Venus-bearer experiences as beautiful, valuable, and worth drawing toward themselves. The Venus-bearer encounters the Mercury-bearer's way of thinking, speaking, and articulating not as information to process but as something aesthetically pleasing in itself. The Mercury-bearer, in turn, finds their natural mode of verbal expression received with appreciation that does not need to be earned. This is one of the most immediately conversationally attractive synastry configurations and one of the easiest to mistake for deeper compatibility than the geometry alone produces.`,
    behavioral_synastry: `The Venus-bearer tends to find the Mercury-bearer's voice, their turns of phrase, their way of explaining things genuinely charming in a way that feels almost prereflective, registered before any conscious decision about the bond has been made. The Mercury-bearer tends to find the Venus-bearer's appreciation flattering in a way that is genuinely warming, because the Venus-bearer's regard lands directly on the Mercury-bearer's articulation rather than glancing off it. The risk is that the recognition can carry the bond for longer than it should on its own, generating conversational warmth in the early phase that masks the question of whether either chart-bearer actually knows the other beyond the immediate aesthetic-verbal resonance.`,
    friendship_synastry: `In a friendship, this conjunction produces the friend conversations are genuinely enjoyable with. The Mercury-bearer's articulation is received by the Venus-bearer as pleasant to listen to; the Venus-bearer's warmth is received by the Mercury-bearer as welcome appreciation. These friendships tend to be marked by sustained verbal exchange, shared aesthetic interests, and the pleasure of each other's conversational company more than by intense emotional intimacy.`,
    romantic_synastry: `In a romantic pairing, this conjunction produces the experience of finding each other's voice beautiful. The Mercury-bearer is received by the Venus-bearer as someone whose way of speaking is inherently attractive; the Venus-bearer is received by the Mercury-bearer as someone whose appreciation makes articulation feel worthwhile. The relationship's early phase tends to be unusually warm and conversationally charged. The work is letting the relationship grow substance beyond the initial aesthetic-verbal recognition, because the geometry alone does not guarantee compatibility in domains the conjunction does not touch.`,
  },

  MERCURY_VENUS_SEXTILE: {
    key: 'MERCURY_VENUS_SEXTILE', pair: 'MERCURY_VENUS', aspect: 'sextile', intensity: 'Low',
    core: `Mercury, the mind, perception, and the function of articulation, and Venus, love, beauty, and relational attunement, are in a 60-degree relationship of easy, compatible exchange. The sextile places these two forces in neighboring territories where they can communicate and cooperate without strain. The person's thinking life and their aesthetic-relational life are not in competition. The mind appreciates beauty; beauty informs thought. Language can be a medium of warmth without requiring constant performance.`,
    behavioral: `The sextile between Mercury's cognitive function and Venus's aesthetic-relational function creates a productive working relationship between thought and affection. The person can think clearly without losing relational warmth, can express affection verbally without the articulation feeling forced or strategic, and can engage intellectually without the coldness that sometimes accompanies purely analytical thought. Social competence runs high here, not as performance but as natural integration of mental clarity and relational grace. The person knows how to say difficult things kindly, how to disagree without creating relational rupture, and how to use language to build rather than sever connection.`,
    friendship: `Easy, warm, conversationally graceful. Friends find this person pleasant to talk to and also substantive when substance is needed.`,
    romantic: `Partners appreciate that this person can articulate affection clearly and can engage in intellectual exchange without losing warmth. The balance between thinking clearly and relating warmly is natural.`,
    feed: `Today's transit field is gently opening the channel between articulated thought and relational warmth in this connection. There is easier access between what each person thinks and what each values than there is on an ordinary day.`,
    sonic: `Mercury's articulate precision and Venus's aesthetic warmth are in easy sequential cooperation in the sextile. Mercury provides the clear melodic articulation and Venus decorates that articulation with genuine beauty. The harmonic language is major with rich color tones, resolved and warm. The rhythm has Mercury's quick surface and Venus's graceful flow in natural dialogue. Listen for the quality of music where something is clearly said and also sounds beautiful, where the precision and the warmth are in easy cooperation rather than fused or in tension.`,
    core_synastry: `When one chart's Mercury meets another's Venus at sextile, the Mercury-bearer's articulation and the Venus-bearer's sense of beauty and warmth find a productive channel between them. The Venus-bearer finds the Mercury-bearer's way of speaking agreeable without finding it magnetic in the way the conjunction produces. The Mercury-bearer finds the Venus-bearer's appreciation pleasant without finding it identity-shaping. This is a productive geometry for sustained conversational connection because it provides genuine warmth without the early-phase intensity that can mask compatibility questions.`,
    behavioral_synastry: `The Venus-bearer enjoys the Mercury-bearer's conversational presence without being charmed in the overwhelming sense; the Mercury-bearer enjoys the Venus-bearer's appreciation without being dependent on it. This produces a bond where conversations tend to go well, where shared aesthetic interests can be explored verbally, and where decisions made together tend to land in territory both chart-bearers find pleasant. The aspect produces durable conversational ease without dramatic intensity, which makes it well-suited for sustained relational work.`,
    friendship_synastry: `In a friendship, this sextile produces the friend conversations are reliably pleasant with. The Mercury-bearer's articulation is welcome to the Venus-bearer; the Venus-bearer's warmth is welcome to the Mercury-bearer. These friendships tend to last because the underlying conversational compatibility holds without effort and shared interests can be explored verbally without pressure.`,
    romantic_synastry: `In a romantic pairing, this sextile produces a relationship where verbal exchange runs warm and clear. The Mercury-bearer's articulation is appreciated by the Venus-bearer; the Venus-bearer's warmth is articulated clearly by the Mercury-bearer. Partnerships with this aspect tend to function well as durable conversational partnerships rather than as sites of dramatic chemistry, with steady verbal intimacy rather than overwhelming early heat.`,
  },

  MERCURY_VENUS_SQUARE: {
    key: 'MERCURY_VENUS_SQUARE', pair: 'MERCURY_VENUS', aspect: 'square', intensity: 'Medium',
    core: `Mercury, the principle of mind, perception, and analytical articulation, meets Venus, the principle of love, beauty, relational harmony, and aesthetic desire, at a 90-degree angle of sustained tension. Mercury wants to clarify, analyze, and name things accurately. Venus wants to dwell in beauty, maintain harmony, and avoid saying things that create relational friction. These are not naturally compatible impulses. The square means neither force simply yields, and the person experiences a recurring pull between intellectual honesty and relational smoothness.`,
    behavioral: `The psychological tension here is between the mind's drive toward accurate articulation and the Venusian imperative toward relational harmony and aesthetic pleasure. The behavioral result is a characteristic pattern: the person notices something that needs to be said, the Venus function registers that saying it will create friction or break the aesthetic mood, and the person either suppresses the observation to preserve harmony or articulates it and then regrets the relational cost. Alternatively, the Venus drive toward warmth and connection produces language the Mercury function recognizes as imprecise or overly accommodating, and the person feels inauthentic in their own speech. The development task is learning that honesty and kindness are not opposing values, and that language can be both accurate and warm when both functions are held consciously.`,
    friendship: `May struggle between wanting to maintain conversational warmth and wanting to say what they actually think. Friends sometimes notice hedging or over-softening of opinions that diminishes the substance of what is being said.`,
    romantic: `Partners may experience this person as conflict-avoidant in conversation or as someone who says difficult things in ways that land harder than intended because the internal negotiation between truth and kindness has not been resolved before the words arrive.`,
    feed: `A transit is pressing on the friction point between analytical clarity and relational warmth in this connection. The gap between what each person thinks and how each values harmony is closer to the surface today than usual, and there is something productive available in naming it.`,
    sonic: `Mercury's quick articulate precision and Venus's rich aesthetic warmth are in genuine friction in the square. Mercury wants to clarify the harmonic language through analytical articulation. Venus wants to dwell in beautiful harmonic territory without being pulled toward analytical resolution. Mercury's quick subdivided rhythmic surface cuts across Venus's graceful flow. Listen for the quality of music where something is being said clearly and something is being made beautiful, and the two impulses keep interrupting each other, where the precision and the warmth are not in agreement about what the music should prioritize.`,
    core_synastry: `When one chart's Mercury meets another's Venus at square, the Mercury-bearer's mode of articulation and the Venus-bearer's pull toward harmony and beauty find each other through friction. The Mercury-bearer's directness often registers in the Venus-bearer's awareness as less kind or less aesthetically attuned than it should be. The Venus-bearer's relational smoothness often registers in the Mercury-bearer's awareness as insufficiently honest or precise. Neither chart-bearer is doing anything wrong; the geometry produces real, recurring friction between clarity and warmth.`,
    behavioral_synastry: `The Mercury-bearer says things that land in the Venus-bearer's awareness as more blunt than the Venus-bearer wanted to hear; the Venus-bearer responds with warmth that the Mercury-bearer reads as evasive or insufficiently substantive. This produces a bond where small conversational misfires accumulate until they are either addressed directly or until one chart-bearer's accommodation curdles into resentment. The work is honest negotiation about what each chart-bearer values in verbal exchange: the Mercury-bearer learning that kindness does not require imprecision, the Venus-bearer learning that honesty does not require harshness.`,
    friendship_synastry: `In a friendship, this square produces a bond where genuine affection coexists with recurring small frictions about conversational tone. The Mercury-bearer wants to say what they actually think; the Venus-bearer wants the conversation to stay pleasant. These friendships work when both friends learn to name the tension explicitly rather than expecting the other to intuit the right balance.`,
    romantic_synastry: `In a romantic pairing, this square produces a relationship where verbal intimacy requires real work. The Mercury-bearer's honesty can land as insufficient kindness to the Venus-bearer; the Venus-bearer's relational warmth can land as insufficient honesty to the Mercury-bearer. Partners who stay together through this aspect develop genuine fluency in language that is both accurate and warm, and the conversational intimacy that results is more honest than easier configurations produce.`,
  },

  MERCURY_VENUS_TRINE: {
    key: 'MERCURY_VENUS_TRINE', pair: 'MERCURY_VENUS', aspect: 'trine', intensity: 'Low',
    core: `Mercury, the mind, perception, and the function of articulation, and Venus, love, beauty, and relational attunement, are separated by 120 degrees, placing them in the same elemental family. The trine means these two forces do not experience each other as foreign. The thinking self and the loving self are oriented toward compatible ends, drawing on the same elemental register. What this person says and how they relate flow in the same direction. Warmth and clarity support each other naturally.`,
    behavioral: `The trine between Mercury's cognitive function and Venus's aesthetic-relational function creates a well-integrated conversational and relational style. The mind serves warmth and warmth serves clarity. The person can articulate difficult things with genuine kindness, can disagree without severing connection, and can use language to build intimacy rather than simply to convey information. Social grace is structural here rather than performed. The person knows how to make others feel welcome through conversation, how to listen in ways that make speaking feel safe, and how to express affection verbally in ways that land as genuine rather than strategic. The shadow of this trine is its own ease: without friction between thought and relational warmth, the person may not develop unusual depth in either intellectual or relational life, since both functions are competent enough that neither requires the kind of work that produces real range.`,
    friendship: `Warm, articulate, genuinely pleasant to be around. Conversations feel both substantive and easy. Friends return to this person because talking with them is reliably nourishing.`,
    romantic: `Partners often cite the conversational intimacy. This person can articulate affection clearly, can engage intellectually without losing warmth, and can navigate relational difficulty with both honesty and care.`,
    feed: `The current sky is amplifying the natural coherence between articulated thought and relational warmth in this connection. What flows easily between these two charts in the conversational-relational register is flowing more easily right now than it does on an ordinary day.`,
    sonic: `Mercury and Venus are in the same elemental family in the trine. Mercury's articulate precision and Venus's aesthetic warmth flow together without friction between clarity and beauty. The harmonic language is major with rich Venusian color tones, resolved and warm simultaneously. The rhythm has Mercury's quick surface articulation and Venus's graceful flow in natural agreement. Every melodic gesture is both clearly articulated and inherently lovely. Listen for the quality of music where thinking and beauty are moving in the same direction, where what is precisely said is also aesthetically warm, and the two qualities are never at odds.`,
    core_synastry: `When one chart's Mercury meets another's Venus at trine, the Mercury-bearer's articulation and the Venus-bearer's sense of warmth and beauty find each other in the same elemental family, moving in compatible directions without effort. The Venus-bearer finds the Mercury-bearer's way of speaking inherently pleasant; the Mercury-bearer's articulation gives the Venus-bearer's appreciation something real to settle on. Conversations between the two run warm and clear without needing to manufacture either quality.`,
    behavioral_synastry: `The Mercury-bearer's observations and articulations tend to be the kind the Venus-bearer finds pleasant to hear, and the Venus-bearer's warmth gives the Mercury-bearer's words a welcome reception. Conversations clarify; shared aesthetic interests get explored verbally with mutual enjoyment; decisions about the relationship get articulated with both honesty and care. The aspect produces sustained conversational ease that does not need to be performed. The trine's limitation is that the same ease can let both chart-bearers stay at a comfortable level of verbal exchange without pushing into harder territory where real depth lives.`,
    friendship_synastry: `In a friendship, this trine produces the friend conversations are genuinely nourishing with. The Mercury-bearer's articulation is received by the Venus-bearer as pleasant and substantive; the Venus-bearer's warmth is received by the Mercury-bearer as genuine appreciation. These friendships often last across years because the underlying conversational-relational compatibility holds without effort.`,
    romantic_synastry: `In a romantic pairing, this trine produces a relationship marked by sustained conversational warmth. The Mercury-bearer can articulate needs and observations with clarity that does not wound; the Venus-bearer can express affection with warmth that does not feel performed. Partnerships with this aspect tend to be the ones friends describe as remarkably communicative, where both partners can talk to each other with both honesty and kindness, and where verbal intimacy is a genuine strength of the relationship.`,
  },

  MERCURY_VENUS_OPPOSITION: {
    key: 'MERCURY_VENUS_OPPOSITION', pair: 'MERCURY_VENUS', aspect: 'opposition', intensity: 'Medium',
    core: `Mercury, the principle of mind, perception, analytical articulation, and the drive toward clarity, stands opposite Venus, the principle of love, beauty, relational harmony, and aesthetic desire, across a 180-degree axis of full polarity. The opposition holds these two forces apart and in constant awareness of each other. Mercury knows Venus is shaping the message. Venus knows Mercury is insisting on precision. Neither can ignore the other. The person experiences a structural distance between the self that speaks truthfully and the self that speaks beautifully, with each pole fully visible to the other across the gap.`,
    behavioral: `The psychological mechanism of the Mercury-Venus opposition is the gap between intellectual honesty and relational warmth, made fully conscious. The person who wants to say what is accurate and the person who wants to maintain harmony are not the same psychological agent in this configuration. They face each other. Where the conjunction fuses clarity and warmth into speech that is both honest and kind, the opposition holds them at maximum distance, which produces a characteristic oscillation between saying exactly what one thinks (Mercury dominant) and softening language to preserve connection (Venus dominant). The person may also project one pole: experiencing themselves as purely analytical while attracting relational partners who seem to prioritize harmony over honesty, or experiencing themselves as purely relational while surrounded by people who seem blunt.`,
    friendship: `Friendships that matter to this person often involve negotiation between honesty and kindness. They require friends who can hold both the person's directness and their relational sensitivity without forcing a choice between them.`,
    romantic: `Partnership becomes a primary site where the tension between speaking truthfully and speaking kindly gets worked out. Partners who can receive both the Mercury clarity and the Venus warmth without interpreting oscillation between them as inconsistency serve this person well.`,
    feed: `Today's transits are illuminating both ends of the clarity-warmth axis in this connection. The space between what each person thinks and what each values in relational exchange is more visible right now between these two charts than it usually is, and there is something to do with that visibility today.`,
    sonic: `Mercury and Venus in opposition produce a composition where analytical clarity and aesthetic warmth are in dialogue across maximum distance. Mercury's quick, precise articulation is answered by Venus's rich, beautiful harmonic warmth from the opposite end of the musical space. The two voices are at maximum distance and in constant awareness of each other. Mercury pushes toward clarity; Venus pulls toward beauty. The harmonic language alternates between Mercury's transparent, analytically clear voicing and Venus's rich, aesthetically warm color tones. Listen for the quality of music where what is being said precisely and what is being shaped beautifully are happening as two separate voices in conversation, where the honesty and the warmth are both audible at the same time and never fully merge.`,
    core_synastry: `When one chart's Mercury meets another's Venus at opposition, the two charts face each other across the full width of the synastry axis. The Mercury-bearer's clarity sits at one pole; the Venus-bearer's warmth sits at the other. Each is fully visible to the other across the distance, and neither is hidden. The Mercury-bearer's directness reaches the Venus-bearer with full force; the Venus-bearer's relational sensitivity reaches the Mercury-bearer as something the Mercury-bearer wants to honor without sacrificing clarity. The bond becomes a site where honesty and kindness find each other across genuine difference rather than blending into mutual accommodation.`,
    behavioral_synastry: `The Mercury-bearer's articulations often land in the Venus-bearer's awareness as more direct than the Venus-bearer expected, and the Venus-bearer's responses often land in the Mercury-bearer's awareness as softer than the Mercury-bearer finds substantive. This produces a bond where the two chart-bearers cycle between the Mercury-bearer feeling the Venus-bearer is evading and the Venus-bearer feeling the Mercury-bearer is harsh. Worked consciously, the polarity becomes one of the most conversationally honest configurations in synastry, because each chart-bearer is forced to integrate what the other embodies. Worked unconsciously, the bond cycles into recurring arguments about whether honesty or kindness matters more in verbal exchange.`,
    friendship_synastry: `In a friendship, this opposition produces a bond where the two friends operate on different conversational rhythms. The Mercury-bearer wants direct exchange; the Venus-bearer wants relational warmth. The friendship works when both friends accept the rhythm difference as the bond's structure rather than as a problem either friend is creating. These friendships tend to deepen significantly when each friend learns to honor the other's mode without forcing convergence.`,
    romantic_synastry: `In a romantic pairing, this opposition produces a relationship marked by genuine alternation between directness and relational care. The Mercury-bearer's clarity reaches the Venus-bearer with full force; the Venus-bearer's warmth reaches the Mercury-bearer as something genuine that sometimes softens precision more than the Mercury-bearer intended. Partnerships with this aspect either become honest collaborations across difference or break down into recurring arguments about conversational tone and whether the relationship values honesty or harmony more. The middle path is the work, and partners who do it well report a relationship of unusual conversational honesty and unusual relational warmth, because both poles are present and consciously held.`,
  },
} as const;
