/**
 * Astradio Insight Library — Uranus Aspects to Personal Planets (Batch 2)
 *
 * 20 objects: URANUS × SUN, MOON, VENUS, MARS × 5 aspects
 * Place at: vnext/projection/insight-library/insight-library-aspects-uranus.ts
 */

import type { AspectInsight } from './insight-library-types';

export const URANUS_ASPECT_INSIGHTS: Readonly<Record<string, AspectInsight>> = {

  URANUS_SUN_CONJUNCTION: {
    key: 'URANUS_SUN_CONJUNCTION', pair: 'URANUS_SUN', aspect: 'conjunction', intensity: 'Very high',
    core: `Uranus, the transpersonal principle of disruption, awakening, sudden liberation from pattern, and the collective force of innovation that breaks through established structures, fuses with the Sun, the seat of conscious identity and the purposeful drive toward self-expression. When these two occupy the same degree, identity and disruption become one system. This person does not experience themselves as someone who disrupts. Disruption is an expression of who they are. The ego's natural impulse toward self-definition has been shaped by Uranus's lightning-strike quality: the self is defined not by consolidation and continuity but by repeated departure from what was previously established. Born into a generational signature of Uranus's transit through a zodiac sign, their individual Sun carries the collective awakening impulse of their generation as a personal character trait.`,
    behavioral: `The ego does not consolidate in the way that Saturn-Sun conjunction egos do. It repeatedly breaks its own previous form, often to its own surprise as much as anyone else's. The result is a person with an unusual capacity for genuine originality, a strong instinctive resistance to convention and established authority, and a quality of personal freedom that can feel both liberating and destabilizing to those around them. The Sun's natural drive toward purposeful self-expression is expressed through Uranus's register: in sudden departures from established patterns, in the willingness to dismantle what has been built in service of something that has not yet taken form, and in a quality of personal authenticity that prioritizes originality over continuity. The shadow is the difficulty this configuration has with sustained, committed, evolutionary development. Uranus's quality of sudden disruption can produce a person who is brilliant at beginnings and departures and who struggles with the patient, structural work of sustained becoming.`,
    friendship: `Friends experience this person as genuinely original, unexpectedly insightful, and periodically destabilizing. Someone whose presence introduces disruptions to established patterns that are often genuinely clarifying and occasionally difficult to absorb.`,
    romantic: `Partners often describe a relationship with extraordinary aliveness and genuine originality alongside a quality of unpredictability that makes sustained relational structure genuinely challenging. The Uranus-Sun person needs freedom at the level of identity, and partners who cannot hold that need will find the relationship progressively difficult.`,
    feed: `Uranus's transit is pressing on the identity structures in this connection right now. Something in how each person understands themselves in relation to the other is being disrupted today in a way that will not simply restore to the previous pattern. What becomes visible in that disruption is worth staying with.`,
    sonic: `The Sun's purposeful melodic lines are interrupted by Uranus's sudden harmonic dislocations in the conjunction. The phrase sets off with solar clarity and then encounters a harmonic interruption that should not work but retrospectively does, revealing something the simpler solar path would not have found. The rhythm has the Sun's consistency disrupted by Uranus's sudden metric shifts. The beat is present and then briefly not where expected. Listen for the quality of music where something purposeful keeps being surprised by itself, where the direction is clear and then suddenly a harmonic door opens that was not visible from the previous vantage point.`,
  },

  URANUS_SUN_SEXTILE: {
    key: 'URANUS_SUN_SEXTILE', pair: 'URANUS_SUN', aspect: 'sextile', intensity: 'Low-medium',
    core: `Uranus, disruption, awakening, the sudden break from pattern, and collective innovation, and the Sun, conscious identity and purposeful self-expression, are in a 60-degree relationship of easy, productive cooperation. The sextile places these two forces in compatible elemental territories where Uranus's innovative, awakening quality and the Sun's purposeful self-expression can draw on each other without the identity disruption that the conjunction produces. The person has genuine access to Uranus's innovative, spiritual, and awakening dimensions without losing the ego ground that allows them to function in the world.`,
    behavioral: `The ego's drive for self-expression and the Uranian principle of originality and liberation from convention are in productive communication rather than in fusion or tension. The Sun can pursue its goals with Uranus's innovative perspective available as a genuine resource, and Uranus's awakening impulse finds its most constructive expression through the Sun's purposeful structure rather than through destabilizing disruption. The result is genuine originality, a natural independence of mind, and a quality of creative thinking that approaches established patterns with genuine curiosity about what could be different without the need to dismantle everything that is currently working.`,
    friendship: `Genuinely original in perspective, intellectually stimulating, and naturally independent without the quality of destabilization that harder Uranus aspects can produce.`,
    romantic: `Partners find a quality of genuine originality and intellectual freshness in this person that makes the relationship feel alive and forward-looking.`,
    feed: `Today's transit is opening the channel between originality and purposeful direction in this connection. There is a quality of genuine creative possibility available between these two charts right now that did not quite exist yesterday.`,
    sonic: `The Sun's directional clarity is supported by Uranus's capacity for unexpected harmonic insight in the sextile, producing melodic lines that go somewhere purposeful and discover genuinely original harmonic territory along the way. Listen for the quality of music where something purposeful also sounds genuinely surprising, where the direction is clear and the harmonic path it takes is unexpected but retrospectively inevitable.`,
  },

  URANUS_SUN_SQUARE: {
    key: 'URANUS_SUN_SQUARE', pair: 'URANUS_SUN', aspect: 'square', intensity: 'High',
    core: `Uranus, the transpersonal principle of disruption, awakening, and liberation from established pattern, meets the Sun, conscious identity and the drive toward purposeful, continuous self-expression, at a 90-degree angle of genuine, sustained tension. Uranus disrupts the ego's attempts at stable self-definition. The Sun builds. Uranus breaks. The Sun consolidates identity. Uranus insists that the current form of identity is not the final form. The 90-degree angle means neither force simply yields, and the person experiences a recurring tension between the Sun's legitimate need for continuity and coherent self-expression and Uranus's equally legitimate insistence that the current identity structure is always provisional.`,
    behavioral: `The Sun's natural drive toward stable, purposeful self-expression keeps encountering Uranus's insistence that the established form is not the destination but a staging ground for the next departure. This person's life tends to move in episodes of establishment and disruption. They build something, develop a clear identity in relation to it, and then experience a Uranian break that dismantles what was built and initiates a new phase. The disruption is not always welcomed and is rarely comfortable, but it is generative. The Uranus-Sun square person's identity is consistently being refined by the disruptions that Uranus imposes on the Sun's consolidating work.`,
    friendship: `Friends experience a person whose identity seems to periodically undergo significant revision. Someone who can change direction, change perspective, or change their fundamental self-presentation in ways that are occasionally disorienting but often reveal genuine growth.`,
    romantic: `Partners may find this person's identity revisions genuinely challenging in long-term relationship. The person they committed to is periodically replaced by a new version that Uranus has awakened into being.`,
    feed: `Uranus's transit is pressing on the tension between self-continuity and self-revision in this connection right now. Something about how each person understands their identity within this relationship is being disrupted today, and what that disruption reveals cannot be un-seen.`,
    sonic: `The Sun's melodic lines set off with solar clarity and are disrupted by Uranus's sudden harmonic dislocations in the square. The phrase attempts to reach its destination and discovers that the harmonic ground has shifted beneath it. The rhythm is the Sun's consistent pulse interrupted by Uranus's sudden metric displacement. The beat arrives and then briefly appears somewhere it was not expected. Listen for the quality of music where something purposeful keeps meeting genuine harmonic surprise that disrupts rather than supports its direction, where the path forward keeps being revised by unexpected harmonic discoveries that change where forward is.`,
  },

  URANUS_SUN_TRINE: {
    key: 'URANUS_SUN_TRINE', pair: 'URANUS_SUN', aspect: 'trine', intensity: 'Low-medium',
    core: `Uranus, disruption, awakening, the sudden break from pattern, and collective innovation, and the Sun, conscious identity and the purposeful drive toward self-expression, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces are naturally aligned. Uranus's innovative, awakening quality and the Sun's purposeful self-expression move in the same direction without the tension of harder aspects. Genuine innovation is part of how the self expresses itself rather than something that disrupts it.`,
    behavioral: `The ego's drive for self-expression and the Uranian principle of awakening and innovation are drawing from the same elemental source. The Sun can express itself through genuinely original forms without the identity disruption that the conjunction produces, and Uranus's awakening impulse finds its most graceful expression through the Sun's purposeful directional clarity. The result is genuine creative originality, a natural independence of mind, and a quality of innovative self-expression that feels both authentic and accessible. Not the shocking disruption of the conjunction but the steady, reliable originality of someone for whom unconventional thinking is simply how their mind naturally works.`,
    friendship: `Genuinely original, intellectually stimulating, and reliably independent without the periodic destabilization of harder Uranus aspects. Their originality feels like a stable feature of their character rather than an unpredictable quality.`,
    romantic: `Partners find a quality of genuine intellectual freshness and creative originality that keeps the relationship feeling alive and unconventional.`,
    feed: `The current sky is amplifying the natural creative originality available in this connection. The quality of genuine freshness and unexpected perspective that runs between these charts is more present right now than it is as a baseline.`,
    sonic: `The Sun's purposeful melodic direction is expressed through Uranus's register of genuine harmonic originality without the disruption of harder aspects in the trine. The harmonic language is major with genuine unexpected chromatic color that opens new territory without destabilizing the overall direction. Listen for the quality of music where something is both purposeful and genuinely original, where the direction is clear and the harmonic path it takes keeps making discoveries that feel both surprising and right.`,
  },

  URANUS_SUN_OPPOSITION: {
    key: 'URANUS_SUN_OPPOSITION', pair: 'URANUS_SUN', aspect: 'opposition', intensity: 'High',
    core: `Uranus, the transpersonal principle of disruption, awakening, and liberation from established pattern, stands at full polarity with the Sun, conscious identity and the drive toward purposeful self-expression. At 180 degrees, the Sun consolidates and expresses the self. Uranus disrupts and awakens it. The opposition tends to externalize. The person may encounter Uranus's awakening, disruptive principle through other people, through encounters with genuinely different others, with disruptive social forces, or with partners and circumstances that force a radical revision of the ego's current self-understanding.`,
    behavioral: `The awakening comes from outside, through encounters with what is genuinely other than the current self-understanding. In Jungian terms, the Uranian archetype is operating in the field of the not-self, projected onto others, onto social forces, onto circumstances that seem to be disrupting the ego from outside. The behavioral consequence is a life punctuated by encounters that force the ego to revise its self-understanding. Meetings with people who see through the established identity, circumstances that dismantle what was built, revelations that make the previous self-conception no longer viable.`,
    friendship: `The most significant and awakening friendships are often those that introduce disruptions to established self-understanding. People who see something in the person that the person had not previously seen in themselves.`,
    romantic: `Partners who represent a genuinely different way of being, who see through the established identity, or who introduce genuine disruption to the person's self-understanding can be among the most transformative and challenging relationship experiences.`,
    feed: `Uranus's transit is illuminating both ends of the identity-awakening axis in this connection today. How each person's presence is disrupting and awakening the other's self-understanding is more visible right now than usual, and what becomes visible in that disruption is irreversible.`,
    sonic: `The Sun's clear, forward-moving melodic statements keep encountering Uranus's sudden harmonic disruptions from across the compositional space in the opposition. The two sonic identities are pulling in fundamentally different directions, one toward purposeful continuity and the other toward sudden illuminating departure. The rhythm alternates between the Sun's consistent assertive pulse and Uranus's sudden, unpredictable metric displacement. Listen for the quality of music where something purposeful keeps being surprised by something that comes from entirely outside its established frame, where the direction is real and the awakening disruption is also real, and the encounter between them changes what forward means.`,
  },

  URANUS_MOON_CONJUNCTION: {
    key: 'URANUS_MOON_CONJUNCTION', pair: 'URANUS_MOON', aspect: 'conjunction', intensity: 'Very high',
    core: `Uranus, the transpersonal principle of disruption, awakening, sudden liberation from pattern, and the collective force of innovation, fuses with the Moon, the keeper of emotional instinct, memory, interior safety, and the body's fundamental need for nourishment and comfort. When these two occupy the same degree, the emotional world and the principle of disruption become one system. The Moon's natural instinct toward familiarity, safety, and emotional continuity is fused with Uranus's impulse toward sudden departure from established pattern. Emotional experience arrives with an electric, unpredictable quality: moods shift suddenly and completely, emotional needs change direction without warning, and the interior emotional landscape has a quality of constant low-level weather that occasionally becomes genuinely stormy.`,
    behavioral: `The Moon's natural drive toward emotional familiarity and safety has been fused with Uranus's disruptive impulse, producing an emotional interior that is genuine but not predictable, not even to the person themselves. The emotional life has a quality of genuine aliveness, authentic spontaneity, and freedom from the emotional conditioning that more conventional Moon placements carry. Partners and close friends may find it difficult to establish the relational patterns and emotional rhythms that conventional close relationships depend on, because Uranus keeps disrupting the Moon's attempts to settle into familiar emotional territory.`,
    friendship: `Friends experience a person with genuine emotional spontaneity and authentic unpredictability. Someone who is never emotionally boring and who can be emotionally destabilizing at the same time.`,
    romantic: `Partners often experience this person's emotional life as simultaneously fascinating and difficult to sustain reliable intimacy with. The emotional world is alive and genuine, and it is also not configured for conventional relational stability.`,
    feed: `Uranus's transit is activating the emotional field in this connection right now. Something in the emotional pattern between these two charts is being disrupted today in a way that will not restore to the previous configuration. What becomes available in that disruption is worth staying with.`,
    sonic: `The Moon's breathing, cycling quality keeps being interrupted by Uranus's sudden harmonic dislocations in the conjunction. The emotional phrase sets off with genuine instinctive feeling and then encounters a harmonic interruption that shifts the entire emotional register unexpectedly. The rhythm has the Moon's organic breathing quality disrupted by Uranus's sudden metric shifts. Listen for the quality of music where something deeply feeling keeps being surprised by itself, where the emotional content and the harmonic context keep shifting in ways that are genuine rather than arbitrary.`,
  },

  URANUS_MOON_SEXTILE: {
    key: 'URANUS_MOON_SEXTILE', pair: 'URANUS_MOON', aspect: 'sextile', intensity: 'Low-medium',
    core: `Uranus, disruption, awakening, and the sudden break from established pattern, and the Moon, emotional instinct, interior need, and the body's requirement for safety, are in a 60-degree relationship of easy, productive cooperation. The sextile places these two forces in compatible territories where Uranus's awakening quality and the Moon's emotional intelligence can support each other without the instability that harder aspects create.`,
    behavioral: `The Moon can feel what it feels with Uranus's liberating perspective available as a resource, allowing the person to experience and express emotions with a quality of genuine authenticity that is not bound by conventional emotional templates. The result is an unusual capacity for genuine emotional honesty, a natural independence in their emotional life, and a quality of emotional freshness that others find both genuine and occasionally surprising.`,
    friendship: `Emotionally authentic, unexpectedly perceptive, and refreshingly independent in their emotional responses. Not bound by conventional emotional expectations.`,
    romantic: `Partners find a quality of genuine emotional authenticity in this person that makes the relationship feel real rather than performed.`,
    feed: `Today's transit is opening the channel between emotional authenticity and genuine instinct in this connection. There is a quality of real emotional freshness available between these charts right now that is worth fully receiving.`,
    sonic: `The Moon's emotional instinct is given Uranus's capacity for genuine harmonic surprise without the disruptive quality of harder aspects in the sextile. Listen for the quality of music where something emotionally instinctive also sounds genuinely surprising, where the feeling is real and the harmonic language expressing it is unexpected but right.`,
  },

  URANUS_MOON_SQUARE: {
    key: 'URANUS_MOON_SQUARE', pair: 'URANUS_MOON', aspect: 'square', intensity: 'High',
    core: `Uranus, the transpersonal principle of disruption, awakening, and liberation from established pattern, meets the Moon, the principle of emotional instinct, interior safety, and the body's fundamental need for comfort and nourishment, at a 90-degree angle of genuine, sustained tension. Uranus disrupts the Moon's attempts at emotional stability. The Moon seeks familiarity and safety. Uranus insists that the current emotional pattern is not the final pattern. The 90-degree angle means neither force simply yields, and the person experiences a recurring tension between the Moon's legitimate need for emotional safety and continuity and Uranus's equally legitimate insistence that the current emotional configuration is always provisional and always subject to sudden revision.`,
    behavioral: `The Moon's natural drive toward emotional familiarity and safety keeps encountering Uranus's insistence that the established emotional pattern must be broken in service of something more authentic and less conditioned. This person's emotional life moves in episodes of settling and disruption. They establish emotional patterns, find provisional emotional safety within them, and then experience Uranian disruptions that break those patterns and initiate new emotional orientations. The disruption is not always welcomed. The Moon's need for safety is genuine. But it is consistently generative.`,
    friendship: `Friends experience a person whose emotional life periodically undergoes significant revision. Someone who can change their emotional orientation in ways that are occasionally disorienting but often reveal a deeper authenticity.`,
    romantic: `Partners may find this person's periodic emotional revisions genuinely challenging. The emotional landscape that was established keeps being disrupted by Uranus in ways that require the relationship to repeatedly re-establish its emotional ground.`,
    feed: `Uranus's transit is pressing on the tension between emotional safety and emotional awakening in this connection right now. Something in the established emotional pattern between these charts is being disrupted today, and what that disruption reveals about what was actually being held together by that pattern is significant.`,
    sonic: `The Moon's breathing, returning quality keeps being interrupted by Uranus's sudden harmonic dislocations in the square. The emotional phrase attempts to find its way home and discovers that the harmonic home it was heading toward has been relocated. The rhythm is the Moon's organic breath disrupted by Uranus's sudden metric displacement. Listen for the quality of music where something emotionally familiar keeps being interrupted by something electrically new, where the instinct toward safety keeps encountering disruptions that break the established emotional pattern.`,
  },

  URANUS_MOON_TRINE: {
    key: 'URANUS_MOON_TRINE', pair: 'URANUS_MOON', aspect: 'trine', intensity: 'Low-medium',
    core: `Uranus, disruption, awakening, and the sudden break from pattern, and the Moon, emotional instinct, interior need, and the body's requirement for safety, are in the same elemental family, separated by 120 degrees of natural resonance. The trine means these two forces are naturally aligned. Emotional authenticity and genuine feeling are integrated. The person can feel with the Moon's depth and express those feelings with Uranus's liberating originality without the instability that the conjunction or square produces.`,
    behavioral: `The Moon can feel what it feels with Uranus's liberating perspective available as an integrated quality of the emotional field itself, allowing for emotional expression that is genuine, spontaneous, and free from conventional emotional templates without the unpredictability that harder Uranus-Moon aspects produce. The result is genuine emotional freedom, natural authenticity in emotional life, and a quality of emotional independence that makes them genuinely refreshing to be around.`,
    friendship: `Emotionally genuine, refreshingly independent in their emotional responses, and naturally free from conventional emotional performance.`,
    romantic: `Partners find a quality of genuine emotional authenticity and emotional independence in this person that makes the relationship feel real and alive.`,
    feed: `The current sky is amplifying the natural emotional authenticity running between these charts. The quality of genuine feeling and emotional freshness that moves between these two people is more present and more accessible right now.`,
    sonic: `The Moon's emotional depth is expressed through Uranus's register of genuine harmonic originality without disruption in the trine. The harmonic language is modally rich with genuine unexpected color that opens new emotional territory without destabilizing the overall emotional field. Listen for the quality of music where something deeply feeling is also genuinely original in its expression, where the emotional depth and the harmonic freshness are the same quality.`,
  },

  URANUS_MOON_OPPOSITION: {
    key: 'URANUS_MOON_OPPOSITION', pair: 'URANUS_MOON', aspect: 'opposition', intensity: 'High',
    core: `Uranus, the transpersonal principle of disruption, awakening, and liberation, stands at full polarity with the Moon, emotional instinct, interior safety, and the body's fundamental need for comfort. The opposition tends to externalize. The person encounters Uranus's awakening, disruptive principle through emotionally significant others, through partners, close friends, or life circumstances that force a revision of established emotional patterns and a release of emotional conditioning that the Moon alone would not have generated.`,
    behavioral: `The Moon's need for emotional safety and familiarity keeps encountering Uranus's awakening, disruptive principle from outside rather than from within. Relationships where the Moon's emotional self becomes mixed with the other's, compassionate encounters that dissolve the protective boundaries the Moon normally maintains, or idealizations of emotionally significant others that make it difficult to see them clearly. The developmental work is integrating the Uranian capacity for emotional authenticity and liberation from conditioning as an interior quality, learning to disrupt one's own emotional patterns from within rather than requiring external Uranian encounters to do so.`,
    friendship: `The most awakening friendships are often those that disrupt established emotional patterns in ways that force genuine growth.`,
    romantic: `Partners who represent a genuinely different emotional culture or who force a revision of established emotional conditioning can be among the most transformative relationship experiences.`,
    feed: `Uranus's transit is illuminating both ends of the emotional-awakening axis in this connection today. How each person's emotional presence is disrupting and liberating the other's established patterns is more visible between these charts right now.`,
    sonic: `The Moon's breathing, cyclical emotional quality keeps encountering Uranus's sudden harmonic disruptions from across the compositional space in the opposition. Listen for the quality of music where something emotionally familiar keeps being awakened from outside by something genuinely new, where the instinctive emotional quality and the disruptive awakening are in unresolved but generative dialogue.`,
  },

  URANUS_VENUS_CONJUNCTION: {
    key: 'URANUS_VENUS_CONJUNCTION', pair: 'URANUS_VENUS', aspect: 'conjunction', intensity: 'Very high',
    core: `Uranus, the transpersonal principle of disruption, awakening, sudden liberation, and collective innovation, fuses with Venus, the planet governing love, aesthetic sensibility, relational value, and the capacity to draw beauty and connection toward oneself. When these two occupy the same degree, love and liberation become one system. This person does not experience love as something that creates binding structure. They experience love as something that must remain free, alive, and unpredictable to remain love at all. The Venus principle's natural drive toward relational attunement, aesthetic consistency, and enduring connection has been fused with Uranus's impulse toward freedom, sudden departure from established pattern, and the dissolution of structures that have become confining.`,
    behavioral: `This person cannot love from within a structure that feels confining, and conventional relational structures, monogamy, domestic stability, long-term predictable partnership, tend to feel confining to the Uranian dimension of the Venus even when the Venus dimension genuinely wants connection and warmth. The result is a person with a powerful, genuine capacity for love that is expressed through unconventional forms, sudden intense connections, and a quality of relational aliveness that depends on the maintenance of real freedom. The aesthetic dimension of Venus is amplified by Uranus's originality into a genuinely distinctive aesthetic sensibility. They are drawn to the unconventional, the innovative, and the beautiful-in-unexpected-places.`,
    friendship: `Friends experience genuine warmth and often sudden, intense connection alongside a quality of relational freedom that makes conventional expectations of availability and predictability difficult to sustain.`,
    romantic: `Partners need genuine understanding of the Uranian requirement for freedom if the relationship is to sustain. Not freedom from commitment exactly, but freedom from the kinds of relational structure that feel like constraints on the genuine aliveness of the love.`,
    feed: `Uranus's transit is pressing on the love and relational structures in this connection right now. Something in how each person understands what this relationship can be and what form it should take is being disrupted today in a way that cannot simply be restored to the previous pattern.`,
    sonic: `Venus's rich harmonic warmth is interrupted by Uranus's sudden, unexpected harmonic dislocations that open genuinely new aesthetic territory in the conjunction. The beautiful phrase discovers somewhere more originally beautiful than where it was heading. The rhythm has Venus's graceful quality disrupted by Uranus's sudden metric shifts that are jarring and then retrospectively right. Listen for the quality of music where something beautiful keeps surprising itself by finding something more originally beautiful than what it was pursuing, where the aesthetic warmth and the disruptive innovation are the same creative force.`,
  },

  URANUS_VENUS_SEXTILE: {
    key: 'URANUS_VENUS_SEXTILE', pair: 'URANUS_VENUS', aspect: 'sextile', intensity: 'Low-medium',
    core: `Uranus, disruption, awakening, and innovation, and Venus, love, aesthetic sensibility, and relational warmth, are in a 60-degree relationship of easy, productive cooperation. The person's aesthetic sensibility and relational life are naturally informed by Uranus's originality without the instability that harder aspects produce. They are genuinely original in their aesthetic choices and relational approach without needing conventional forms to feel confining before they can depart from them.`,
    behavioral: `Venus can express warmth and beauty with Uranus's originality available as an integrated resource. The result is genuine aesthetic independence, a natural preference for the unconventional and original in beauty, and a relational style that is warm but not bound by conventional relational expectations.`,
    friendship: `Genuinely warm with a quality of refreshing relational originality. Not bound by conventional friendship expectations in ways that make the friendship feel alive and authentic.`,
    romantic: `Partners find a quality of genuine aesthetic originality and relational freshness that makes the relationship feel unconventional in the best sense.`,
    feed: `Today's transit is gently opening the channel between love and creative originality in this connection. There is a quality of genuine aesthetic freshness and relational aliveness available between these charts right now.`,
    sonic: `Venus's beauty is given Uranus's capacity for genuine harmonic originality without disruption in the sextile. Listen for the quality of music where something beautiful is also genuinely surprising, where the aesthetic warmth and the unexpected harmonic choices are supporting each other.`,
  },

  URANUS_VENUS_SQUARE: {
    key: 'URANUS_VENUS_SQUARE', pair: 'URANUS_VENUS', aspect: 'square', intensity: 'High',
    core: `Uranus, disruption, awakening, and the sudden break from established pattern, meets Venus, love, beauty, relational warmth, and the desire for enduring connection, at a 90-degree angle of genuine, sustained tension. Uranus insists that love must be free. Venus insists that love must be warm, continuous, and relationally sustaining. These are not naturally compatible requirements. The 90-degree angle means neither force simply yields, and the person experiences a recurring tension between the Venus desire for genuine warmth and relational continuity and the Uranian insistence that any relational structure that has become confining must be disrupted.`,
    behavioral: `Venus establishes relational patterns, creates genuine warmth, and builds toward the kind of sustained connection it naturally seeks. Then Uranus disrupts what has been built, either through the person's own sudden need for freedom or through circumstances that dismantle the relational structure. The development task is not suppressing either the Venus drive for genuine warmth and connection or the Uranian need for freedom. It is developing the capacity to hold both simultaneously, to love in ways that are genuinely warm and also genuinely free.`,
    friendship: `Friends experience a person with genuine warmth alongside a quality of relational unpredictability that can make sustained, conventional friendship structure challenging to maintain.`,
    romantic: `Partners experience one of the more challenging relational configurations. The warmth is real, the love is genuine, and the Uranian need for freedom can dismantle what the Venus has built with genuine care.`,
    feed: `Uranus's transit is pressing on the tension between love and freedom in this connection right now. Something in the relational pattern between these charts is being disrupted today, and what each person actually needs this relationship to be versus what it has become is more visible right now.`,
    sonic: `Venus's beautiful harmonic language keeps being interrupted by Uranus's unexpected dislocations that break the aesthetic continuity in the square. The rhythm has Venus's graceful flow disrupted by Uranus's sudden shifts. Listen for the quality of music where something beautiful keeps being broken open by something electrically new, where the warmth and the disruption are in unresolved creative tension.`,
  },

  URANUS_VENUS_TRINE: {
    key: 'URANUS_VENUS_TRINE', pair: 'URANUS_VENUS', aspect: 'trine', intensity: 'Low-medium',
    core: `Uranus and Venus are in the same elemental family, separated by 120 degrees of natural resonance. Love and freedom are not in tension here. They inform each other. The person's capacity for genuine warmth and their natural orientation toward originality and aesthetic independence are harmoniously integrated. They can love unconventionally without the relational instability that harder aspects produce.`,
    behavioral: `Venus can express love with Uranus's originality available as an integrated quality rather than as a competing force. The result is genuine warmth expressed through unconventional forms without the tension between freedom and connection that harder aspects produce.`,
    friendship: `Warm, genuinely original in their relational approach, and naturally free from conventional relational expectations in ways that make the friendship feel refreshingly authentic.`,
    romantic: `Partners find a quality of genuine warmth and aesthetic originality that makes the relationship feel unconventionally alive.`,
    feed: `The current sky is amplifying the natural integration of love and creative freedom in this connection. The warmth and genuine originality that runs between these charts is more present and more accessible right now.`,
    sonic: `Venus's aesthetic warmth is expressed through Uranus's register of genuine originality without disruption in the trine. Beautiful and surprising at the same time. Listen for the quality of music where something is both genuinely warm and genuinely original, where the beauty and the unexpectedness are the same quality.`,
  },

  URANUS_VENUS_OPPOSITION: {
    key: 'URANUS_VENUS_OPPOSITION', pair: 'URANUS_VENUS', aspect: 'opposition', intensity: 'High',
    core: `Uranus, disruption, awakening, and liberation from established pattern, stands at full polarity with Venus, love, beauty, and relational warmth. The opposition tends to externalize. The person encounters Uranus's liberating, disruptive principle through partners and relationships that introduce genuine disruptions to established relational patterns, that expand the relational world beyond what the Venus alone would have sought or created.`,
    behavioral: `Venus's drive for relational warmth and aesthetic beauty keeps encountering Uranus's awakening principle from outside, through partners who represent a genuinely different relational reality, who challenge conventional relational expectations, or who introduce a quality of relational freedom that the Venus nature had not previously accessed. The developmental work is integrating the Uranian principle of relational freedom and originality as an interior resource.`,
    friendship: `The most awakening friendships often involve people whose relational style or aesthetic sensibility is genuinely different, who expand the relational and aesthetic world beyond its previous horizon.`,
    romantic: `Partners who challenge conventional relational expectations, who represent a genuinely different relational culture, or who introduce real freedom into the relational dynamic can be among the most transformative relationship experiences.`,
    feed: `Uranus's transit is illuminating both ends of the love-and-freedom axis in this connection today. How each person's relational presence is disrupting and awakening the other's established relational patterns is more visible between these charts right now.`,
    sonic: `Venus's rich, carefully shaped beauty keeps encountering Uranus's sudden harmonic disruptions from across the compositional space in the opposition. Listen for the quality of music where something beautiful keeps being awakened from outside by something genuinely original, where the warmth and the disruption are in unresolved but generative dialogue.`,
  },

  URANUS_MARS_CONJUNCTION: {
    key: 'URANUS_MARS_CONJUNCTION', pair: 'URANUS_MARS', aspect: 'conjunction', intensity: 'Very high',
    core: `Uranus, the transpersonal principle of disruption, awakening, sudden liberation, and collective innovation, fuses with Mars, the planet governing raw drive, assertion, the instinct to pursue and defend, and the force that moves the person toward what they want. When these two occupy the same degree, drive and disruption become one system. The Mars impulse toward pursuit and assertion is fused with Uranus's electric, unpredictable, pattern-breaking quality. This person's drive does not build steadily. It fires in sudden, electric bursts that are impossible to fully anticipate. The energy is genuine and can be extraordinary, and it operates according to its own timing rather than the timing that circumstances or conventional strategy would suggest.`,
    behavioral: `Mars's natural drive toward focused, sustained, strategic pursuit has been fused with Uranus's sudden, electric, pattern-disrupting quality. The result is extraordinary capacity for sudden, intense, effective action, the kind of move that no one saw coming and that changes the situation completely. It also produces a person whose drive is not available for sustained conventional strategic deployment because it fires according to Uranus's timing rather than any plan the person or their circumstances have established. The energy arrives suddenly, accomplishes something genuinely surprising, and then is unavailable until the next Uranian moment.`,
    friendship: `Friends experience a person with surprising capacity for sudden, effective action who may be less reliably available for the sustained effort that conventional collaborative projects require.`,
    romantic: `Partners experience a quality of electric, unpredictable energy that is exhilarating in acute moments and can be destabilizing in the sustained context of long-term relationship.`,
    feed: `Uranus's transit is activating where drive and disruption meet in this connection right now. Something in the energy and direction between these charts is firing in an unexpected way today, and what gets accomplished in that window matters.`,
    sonic: `Mars's driving, incisive energy is amplified by Uranus's sudden, unpredictable quality in the conjunction into something that fires in sudden intense bursts rather than building through sustained momentum. The rhythm has Mars's physical force arriving at unexpected moments. The beat hits with full weight and then shifts its position suddenly. Listen for the quality of music where something physically intense arrives without warning and then is gone, where the force is completely real and completely unpredictable in its timing.`,
  },

  URANUS_MARS_SEXTILE: {
    key: 'URANUS_MARS_SEXTILE', pair: 'URANUS_MARS', aspect: 'sextile', intensity: 'Low-medium',
    core: `Uranus and Mars are in a 60-degree relationship of easy, productive cooperation. The person's drive and their natural orientation toward originality and innovation are in easy dialogue. The Mars impulse is supported by Uranus's innovative perspective without the unpredictability that harder aspects produce. They can pursue what they want with genuine creative originality and a quality of strategic innovation that others find both effective and surprising.`,
    behavioral: `Mars provides the energy. Uranus provides the capacity for genuinely original strategic approaches that conventional thinking would not have generated. The result is reliable drive expressed through genuinely creative strategic approaches, someone who finds the unexpected angle that actually works.`,
    friendship: `Energizing and genuinely innovative in their approach to collaborative challenges. Their strategic creativity is a genuine asset.`,
    romantic: `Partners find a quality of creative drive and innovative approach that makes the relationship feel forward-moving and alive.`,
    feed: `Today's transit is opening the channel between drive and creative innovation in this connection. The energy and strategic originality available between these charts right now is more aligned than usual.`,
    sonic: `Mars's drive is given Uranus's capacity for innovative harmonic approaches without disruption in the sextile. Listen for the quality of music where something driven also sounds genuinely original in its direction, where the force and the creative strategy are supporting each other.`,
  },

  URANUS_MARS_SQUARE: {
    key: 'URANUS_MARS_SQUARE', pair: 'URANUS_MARS', aspect: 'square', intensity: 'High',
    core: `Uranus, disruption, awakening, and the sudden break from established pattern, meets Mars, raw drive, assertion, and the force that moves the person toward what they want, at a 90-degree angle of genuine, sustained tension. Uranus disrupts Mars's strategic plans. Mars builds toward a target. Uranus insists that the current strategic approach is not the final approach. The result is a recurring tension between Mars's legitimate need for strategic continuity and sustained effort and Uranus's insistence that the established approach sometimes needs to be abandoned in favor of something genuinely new.`,
    behavioral: `Mars develops a strategy, commits force toward a target, and then Uranus intervenes. Through sudden external disruptions, through the person's own sudden recognition that the current strategic approach is wrong, or through circumstances that change the strategic landscape completely. The development task is developing the capacity to hold both the Mars requirement for committed, strategic, sustained effort and the Uranian insight that the established approach sometimes needs to be abandoned in favor of something genuinely new.`,
    friendship: `Friends experience a person with genuine drive who may periodically abandon established collaborative approaches in favor of something more original that Uranus has suddenly revealed.`,
    romantic: `Partners experience a person whose drive and strategic approach to the relationship can undergo sudden unexpected revisions that the relationship has to accommodate.`,
    feed: `Uranus's transit is pressing on the tension between drive and strategic disruption in this connection right now. Something in the approach that each person has been taking to this relationship is being disrupted today in a way that reveals what was working and what was simply habit.`,
    sonic: `Mars's driving pulse keeps being displaced by Uranus's sudden metric shifts in the square. The force is real and the direction keeps being revised by unexpected disruptions. Listen for the quality of music where something driven keeps having its strategic direction disrupted by something electrically original, where the force and the disruption are in sustained creative tension.`,
  },

  URANUS_MARS_TRINE: {
    key: 'URANUS_MARS_TRINE', pair: 'URANUS_MARS', aspect: 'trine', intensity: 'Low-medium',
    core: `Uranus and Mars are in the same elemental family, separated by 120 degrees. Drive and originality are not in tension here. They reinforce each other. The person's assertive function is naturally expressed through innovative, original approaches that conventional strategic thinking would not have generated, without the unpredictability that harder aspects produce.`,
    behavioral: `The person can pursue what they want through genuinely original approaches that are both effective and surprising, without the disruption that harder aspects introduce into the strategic function.`,
    friendship: `Energizing, genuinely innovative in their collaborative approaches, and reliably original in how they pursue shared goals.`,
    romantic: `Partners find a quality of creative drive and strategic originality that makes the relationship feel forward-moving and alive.`,
    feed: `The current sky is amplifying the natural alignment between drive and innovative direction in this connection. The energy and strategic originality available between these charts is more naturally directed right now than it usually is.`,
    sonic: `Mars's energetic drive is expressed through Uranus's register of genuine strategic originality without disruption in the trine. Listen for the quality of music where something driven also sounds genuinely innovative in its approach, where the force and the original direction are the same quality.`,
  },

  URANUS_MARS_OPPOSITION: {
    key: 'URANUS_MARS_OPPOSITION', pair: 'URANUS_MARS', aspect: 'opposition', intensity: 'High',
    core: `Uranus, disruption, awakening, and liberation from established pattern, stands at full polarity with Mars, raw drive, assertion, and the force that moves toward what is wanted. The opposition tends to externalize. The person encounters Uranus's disrupting, awakening principle through external forces, through circumstances, opponents, or events that disrupt the Mars drive's established strategic approaches and force revision toward something more genuinely original.`,
    behavioral: `The Mars drive's strategic approach keeps encountering Uranus's awakening principle from outside, through external disruptions that force strategic revision, through opponents who introduce genuinely unexpected approaches, or through circumstances that make the established strategic approach suddenly inadequate. The developmental work is integrating the Uranian capacity for strategic innovation and liberation from conventional approaches as an interior resource.`,
    friendship: `The most activating collaborative relationships often involve people whose strategic approach is genuinely different, who introduce disruptions to established approaches that force innovation.`,
    romantic: `Partners who challenge established approaches to the relationship or who introduce genuine disruption to strategic patterns can be among the most developmentally significant.`,
    feed: `Uranus's transit is illuminating both ends of the drive-and-disruption axis in this connection today. How each person's force and strategic approach are meeting unexpected disruption from the other is more visible between these charts right now.`,
    sonic: `Mars's physical, incisive directional force keeps encountering Uranus's sudden harmonic dislocations from across the compositional space in the opposition. Listen for the quality of music where something driven keeps encountering something electrically disruptive from outside, where the strategic force and the awakening disruption keep answering each other.`,
  },

} as const;
