/**
 * Astradio Insight Library — Structural Claim Insights (Batch 3)
 *
 * 22 objects covering: motion profiles (5), gravity profiles (5),
 * element dominance (4), tension bands (3), tonal polarity (3), luminary weight (3).
 *
 * Keys are exact ClaimId strings from vnext/semantic/ontology-codes.ts CLAIM_IDS.
 *
 * Place this file at: vnext/projection/insight-library/insight-library-structural.ts
 */

import type { StructuralClaimInsight } from './insight-library-types';

export const STRUCTURAL_INSIGHTS: Readonly<Record<string, StructuralClaimInsight>> = {

  // ─── MOTION PROFILES ────────────────────────────────────────────────────────

  MOTION_LABEL_SURGING: {
    id: 'MOTION_LABEL_SURGING',
    category: 'motion',
    title: 'Surging',
    core: `The motion profile describes the quality of energetic movement that runs through the entire chart, the characteristic rhythm at which a person's psychological and physical energy moves through time. A surging motion profile means the chart's signals produce energy that builds continuously and releases in peaks rather than maintaining a steady baseline. This is not a chart of moderate, consistent output. It is a chart of accumulation and discharge. The surging person invests fully, builds toward a peak, releases through action or expression, and then needs genuine rest before the cycle begins again. That rhythm is not a flaw or a lack of discipline. It is the fundamental architecture of how this chart is built.`,
    behavioral: `People with surging motion profiles are at their best when given something large enough to warrant full energetic investment. They achieve extraordinary things in concentrated phases and find it genuinely costly to sustain the kind of steady, evenly distributed output that other configurations produce more naturally. Asking a surging chart to maintain perpetual moderate availability is like asking water to flow uphill. The energy has a direction and a cycle, and working with that cycle rather than against it is where the real capacity lives. They need contexts that allow genuine intensity followed by genuine recovery, not as a concession but as the design.`,
    feed: `The current sky is amplifying the surging energy cycle in this connection right now. Both charts are building toward something, and what gets expressed at the peak of that buildup today is worth paying attention to.`,
    sonic: `The composition builds through gradual intensification toward moments of maximum energetic release before beginning the cycle again. The melodic lines grow in intensity and range as the surge develops, contracting after the peak. The harmonic language becomes denser and more chromatic as the surge builds, resolving toward greater openness after discharge. Listen for the quality of music that seems to be building toward something, that has genuine forward momentum with increasing intensity, and then releases and begins again. That quality of building, peaking, and returning is the sonic signature of surging motion.`,
  },

  MOTION_LABEL_RESTLESS: {
    id: 'MOTION_LABEL_RESTLESS',
    category: 'motion',
    title: 'Restless',
    core: `A restless motion profile means the chart's signals produce energy that changes direction frequently rather than building in a single sustained direction or discharging in peaks. The characteristic rhythm of restless motion is horizontal rather than vertical. The energy moves across many different domains, interests, and engagements rather than accumulating depth in any single one. This is not a deficiency of focus. It is the fundamental architecture of a chart that is designed to cover territory, make connections across diverse domains, and maintain a quality of responsive alertness to whatever is most alive in the immediate environment.`,
    behavioral: `People with restless motion profiles are genuinely alive across many fronts simultaneously rather than concentrated in one area of deep investment. They are remarkably responsive to novelty, make unexpected connections between different domains, can initiate many things with genuine energy, and may find single-focus sustained work genuinely difficult because the restless motion keeps directing attention toward whatever is most immediately alive rather than the established priority. This is not inconsistency. It is a different kind of intelligence. The restless chart needs contexts that honor the breadth of its engagement and provide enough variety to maintain genuine alertness.`,
    feed: `Uranus's current position is activating the restless movement between these charts right now. The energy between these two people is moving quickly across multiple frequencies today, and what gets touched in that quick movement is worth tracking.`,
    sonic: `The composition moves with frequent directional changes and unexpected lateral shifts. The rhythm is syncopated and unpredictable, the accent arriving where least expected, the meter shifting without warning. The melodic lines change character frequently, setting off in one direction, pivoting, making an unexpected connection to a different melodic idea, and continuing. The harmonic language moves through many tonal areas in quick succession. Listen for the quality of music that keeps your attention by never quite settling, that maintains genuine aliveness through constant lateral movement rather than through depth or buildup.`,
  },

  MOTION_LABEL_QUIET_FLOW: {
    id: 'MOTION_LABEL_QUIET_FLOW',
    category: 'motion',
    title: 'Quiet flow',
    core: `A quiet flow motion profile means the chart's signals produce energy that moves continuously but without the dramatic intensity of surging or the directional instability of restless motion. The characteristic rhythm of quiet flow is fluid, uninterrupted, and self-sustaining. The energy moves like water finding its own level, not requiring external pressure to maintain its movement but also not building toward peaks or dispersing across many directions. This is a chart of genuine, quiet, continuous productivity.`,
    behavioral: `People with quiet flow motion profiles can sustain effort over long periods without the motivational crises that more volatile charts encounter. They rarely produce at the dramatic peaks that surging charts achieve, but they also rarely drop to the valleys, and they maintain a quality of genuine, steady engagement that others often find both admirable and quietly inspiring. The quiet flow person needs contexts that honor continuity and allow sustained, unhurried development. Demanding dramatic peaks from a quiet flow chart is asking it to be something it is not, and missing the considerable thing it actually is.`,
    feed: `Today's transit is moving with the quiet flow of this connection. The energy between these charts is moving smoothly and continuously right now, and what develops in that uninterrupted current is worth receiving.`,
    sonic: `The composition moves with smooth, uninterrupted, self-sustaining motion. The rhythm is regular without being mechanical, it flows rather than pulses, moves rather than beats. The melodic lines are continuous, connecting naturally from one phrase to the next without dramatic breaks or directional changes. The harmonic language progresses smoothly, each chord leading naturally to the next through careful voice leading rather than dramatic modulation. Listen for the quality of music that maintains genuine forward movement without announcing itself, that simply continues, beautifully and without effort.`,
  },

  MOTION_LABEL_INWARD: {
    id: 'MOTION_LABEL_INWARD',
    category: 'motion',
    title: 'Inward consolidation',
    core: `An inward consolidation motion profile means the chart's signals produce energy that moves primarily toward depth and interior development rather than outward expression and external engagement. The characteristic direction of inward motion is centripetal, drawing inward, deepening what is already present, consolidating rather than expanding. This is not a chart of low energy. It is a chart whose energy is primarily directed toward the interior: toward psychological development, toward the deepening of what matters rather than the broadening of what is engaged with.`,
    behavioral: `People with inward consolidation profiles think slowly and thoroughly. They prefer genuine depth to broad familiarity, may appear less productive than more outwardly oriented charts, and develop over time a quality of genuine integrative wisdom that other profiles cannot match because they have not had to do the interior work that produces it. The inward person needs contexts that honor the slow, thorough, interior work of genuine depth development. Mistaking quiet for inactivity, or the absence of visible output for the absence of genuine engagement, is one of the most common misreadings of this configuration.`,
    feed: `The current transit is drawing the energy in this connection inward. What is happening between these two charts today is happening at a depth that may not be immediately visible, and giving it space is exactly the right response.`,
    sonic: `The composition's energy moves toward depth rather than outward expression. The dynamic range tends toward the quieter registers, not silence but genuine interior sound, heard more from within than projected outward. The rhythm is slow and deliberate, each beat fully weighted before the next arrives. The melodic lines tend downward or inward rather than upward or outward. They are exploring interior territory rather than reaching toward an external destination. Listen for the quality of music that draws you inward, that invites attention to go deeper into the sound rather than following it outward.`,
  },

  MOTION_LABEL_STEADY: {
    id: 'MOTION_LABEL_STEADY',
    category: 'motion',
    title: 'Steady',
    core: `A steady motion profile means the chart's signals produce energy that is reliable, consistent, and evenly distributed across time rather than fluctuating between peaks and valleys, changing direction restlessly, or moving primarily inward. The characteristic rhythm of steady motion is exactly what it sounds like: even, dependable, sustainably continuous. This is a chart of reliable output over time. The person produces consistently, engages reliably, and maintains a quality of energetic availability that others find genuinely dependable.`,
    behavioral: `People with steady motion profiles finish what they start. They can be counted on to show up at consistent capacity over time, do not require dramatic peaks or constant variety to maintain their engagement, and may find the volatility of other motion profiles genuinely bewildering because the experience of dramatic energetic variation is simply not part of their own fundamental rhythm. The steady person needs contexts that recognize and value consistency, that understand sustained reliability as its own form of excellence rather than simply the absence of drama. This is one of the most underappreciated motion profiles precisely because its gifts are quiet.`,
    feed: `Today's transit is moving through the steady, reliable current in this connection. The consistent energy that runs between these charts is more noticeable right now, and what builds in that reliable space over time is worth acknowledging.`,
    sonic: `The composition moves with even, reliable, beautifully consistent motion. The rhythm is steady without being mechanical, there is genuine life in each beat, but the life is consistent rather than variable. The melodic lines move at an even pace, completing themselves without dramatic acceleration or deceleration. The dynamic range is consistent. The harmonic language progresses with reliable logic. Listen for the quality of music that you can trust, that will not suddenly surge or drop or redirect, that simply continues with genuine reliability and genuine musical life at every step.`,
  },

  // ─── GRAVITY PROFILES ───────────────────────────────────────────────────────

  GRAVITY_LABEL_ANCHORED: {
    id: 'GRAVITY_LABEL_ANCHORED',
    category: 'gravity',
    title: 'Anchored',
    core: `The gravity profile describes the quality of psychological weight and groundedness that characterizes how this person relates to the world, the degree to which they feel rooted in a stable center versus lighter and more mobile in their engagement. An anchored gravity profile means the chart's signals create a strong, stable, downward-oriented psychological center of gravity. This person is grounded in a way that is not merely a personality trait. It is a structural feature of how their chart is built. They do not drift easily from their established center, are not easily destabilized by external pressure, and carry a quality of rootedness that others often experience as stabilizing and reliable.`,
    behavioral: `An anchored person's sense of who they are and what they value is not easily moved by social pressure, emotional turbulence, or environmental change. They can be deeply trusted to maintain their commitments. Their values and perspective remain consistent across contexts. They provide genuine psychological stability for the people around them. The developmental edge is learning to distinguish between genuine rootedness and unnecessary rigidity. The same anchoring that provides stability can produce resistance to change that is actually needed, and an anchored chart may need to actively cultivate the willingness to shift when shifting is genuinely called for.`,
    feed: `The current transit is pressing on the anchored center of this connection. What is genuinely stable and rooted between these charts is being tested today, and what does not move under that pressure is the real foundation.`,
    sonic: `The composition has a strong, clear gravitational center, a bass register that is genuinely present and stabilizing, a rhythmic foundation that does not waver, a tonal center established early and maintained throughout. The melodic lines move within the range that the gravitational center permits. They do not drift far from the established tonal ground. The harmonic language resolves reliably toward the established center. Listen for the quality of music that feels completely grounded, where the bass and the tonal center provide a foundation so reliable that the upper voices can move with genuine freedom above it.`,
  },

  GRAVITY_LABEL_WEIGHTED_SPARK: {
    id: 'GRAVITY_LABEL_WEIGHTED_SPARK',
    category: 'gravity',
    title: 'Weighted with spark',
    core: `A weighted with spark gravity profile means the chart's signals create a combination of genuine gravitational weight alongside a quality of energetic volatility or brightness that periodically fires against that stable weight. This is the profile of a person who is genuinely grounded and also genuinely alive in a way that prevents the groundedness from becoming mere heaviness. The weight provides the stable foundation. The spark provides the quality of energetic presence and periodic brightness that makes the grounded person genuinely engaging rather than simply static.`,
    behavioral: `A person with this profile can be deeply trusted to maintain their commitments and center while also bringing genuine aliveness and occasional surprising energy to whatever they engage with. The weight keeps them from being destabilized by the spark. The spark keeps them from becoming merely inert under the weight. This is one of the more naturally attractive gravity profiles because it combines the reliability of anchored gravity with the aliveness that prevents reliability from becoming predictable.`,
    feed: `Today's transit is activating the spark within the stable weight of this connection. Something reliably grounded between these charts is firing with unusual brightness right now, and that combination of stability and aliveness is worth fully receiving.`,
    sonic: `The composition has a substantial gravitational center that is periodically interrupted by bright, energetic moments of clarity or intensity. The bass register is genuinely present and stabilizing. The upper register occasionally fires with a brightness that illuminates the heavier foundation beneath. The rhythm is fundamentally grounded but with moments of syncopated energy that animate the steady pulse. Listen for the quality of music that feels deeply grounded and also genuinely alive, where the stable weight and the energetic spark are both completely present and in productive dialogue.`,
  },

  GRAVITY_LABEL_FLOATING: {
    id: 'GRAVITY_LABEL_FLOATING',
    category: 'gravity',
    title: 'Floating',
    core: `A floating gravity profile means the chart's signals produce energy whose relationship to gravitational grounding is unusually light. This person moves through the world with a quality of psychological buoyancy that is both their gift and their challenge. They are not constrained by the same gravitational pull that anchors other configurations. They move easily, adapt readily, and engage with a quality of lightness that others may find either refreshing or unreliable depending on what they need.`,
    behavioral: `Floating charts are genuinely responsive to their environment in a way that more heavily grounded profiles cannot match. They can move through very different contexts and relationships without losing their essential character. They meet people where they are with natural ease. The developmental challenge is the same quality reversed: genuine sustained commitment, stable relational structure, and the kind of rootedness that others depend on can be genuinely difficult to maintain, because the same lightness that enables mobility also limits the capacity to stay put when staying put matters.`,
    feed: `Neptune's current influence is amplifying the floating quality of this connection. The energy between these charts is moving with unusual buoyancy today, and what becomes available in that lightness is worth receiving without insisting on immediate structural form.`,
    sonic: `The composition moves in the upper and middle registers more than in the deep bass. The tonal center is present but not heavily emphasized. The rhythm has a quality of lift rather than weight. The melodic lines move freely through harmonic space without feeling the pull of a single gravitational center. The harmonic language is mobile and comfortable in many tonal areas without being pulled strongly toward any one. Listen for the quality of music that seems to exist slightly above the ground, that moves with ease and buoyancy rather than weight.`,
  },

  GRAVITY_LABEL_LIGHT: {
    id: 'GRAVITY_LABEL_LIGHT',
    category: 'gravity',
    title: 'Light',
    core: `A light gravity profile means the chart's signals produce energy with minimal gravitational weight. This person moves through the world with a quality of genuine psychological lightness that is their most characteristic feature. Where the anchored profile is defined by rootedness and the floating profile by buoyancy, the light profile is defined by the relative absence of gravitational pull in any direction. They move through the world with less baggage, less resistance, and less gravitational drag than most configurations.`,
    behavioral: `People with light gravity profiles carry very little psychological accumulation of past experience as ongoing weight. They can release what has been experienced with relative ease and engage with the present without the accumulation of historical gravity that heavier profiles inevitably carry. The result is genuine psychological freshness and a natural capacity for beginning again. The developmental challenge is corresponding: genuine commitment, deep relational investment, and the kind of psychological depth that comes from sustained engagement with what is difficult require a degree of gravitational anchoring that the light profile must consciously develop rather than naturally possessing.`,
    feed: `Today's transit is moving through the light, unencumbered quality of this connection. What flows between these charts right now moves easily and without resistance, and there is a quality of genuine freshness available between these people today.`,
    sonic: `The composition moves with genuine psychological and musical lightness. Minimal bass presence, upper register clarity, a quality of harmonic and melodic movement that feels unencumbered. The rhythm is light-footed rather than grounded, the melodic lines nimble rather than weighted, the harmonic language clear and unencumbered rather than dense. Listen for the quality of music that feels genuinely unburdened, that moves through harmonic space without accumulating weight.`,
  },

  GRAVITY_LABEL_BALANCED: {
    id: 'GRAVITY_LABEL_BALANCED',
    category: 'gravity',
    title: 'Balanced',
    core: `A balanced gravity profile means the chart's signals produce energy whose relationship to gravitational weight is evenly distributed. Neither heavily anchored nor noticeably light, neither floating nor weighted with spark. The characteristic quality of balanced gravity is exactly what it sounds like: the psychological center of gravity is well-positioned for the full range of ordinary human engagement. This person can access both groundedness and mobility, both stability and adaptability, without either pole being dramatically dominant.`,
    behavioral: `People with balanced gravity profiles are genuinely capable across a wide range of contexts and demands. They are reliably grounded without being rigid, adaptable without being unmoored, and capable of sustaining genuine commitment alongside genuine responsiveness to changing circumstances. The balanced gravity profile does not produce the dramatic gifts or the dramatic challenges of the more extreme profiles. Its characteristic quality is a kind of psychological versatility that is genuinely valuable precisely because it is rare among people who lean strongly toward one end of the gravity spectrum.`,
    feed: `The current transit is moving through the balanced, well-centered gravity of this connection. Both charts are operating from a place of even psychological weight right now, and what becomes possible from that stable, versatile center is worth building on.`,
    sonic: `The composition's relationship to gravitational weight is evenly distributed across the register. Genuine bass presence without heaviness, upper register clarity without lightness, a rhythmic foundation that is reliable without being heavy. The melodic lines and harmonic language occupy the full range of the musical space with genuine balance. Listen for the quality of music that feels well-centered, that has both weight and lightness, both stability and mobility, without either pole being dramatically dominant.`,
  },

  // ─── ELEMENT DOMINANCE ──────────────────────────────────────────────────────

  ELEMENT_FIRE_DOM: {
    id: 'ELEMENT_FIRE_DOM',
    category: 'element',
    title: 'Fire dominant',
    core: `Element dominance describes the primary elemental character of the entire chart, the fundamental quality of energy, temperament, and engagement that pervades the person's psychological life. Fire dominant charts carry the elemental quality of fire as their primary register: enthusiasm, inspiration, initiation, and the forward-moving quality of energy that ignites rather than sustains, that reaches toward the horizon rather than consolidating what is already present. Fire is the element of the creative spark, of the vision that precedes the structure, of the faith that something genuinely new is possible.`,
    behavioral: `Fire dominant charts correspond to what Jung described as the intuitive function, the capacity to perceive possibilities, to see the whole before the parts, to be energized by what has not yet taken form. The result is genuine creative energy, real inspirational force, and a capacity for enthusiasm that can genuinely ignite the people around them. The developmental challenge of fire dominance is the same in every era: fire illuminates but does not sustain. The fire dominant person needs to develop the capacity for the patient, structural work that converts the fire's inspired vision into something that actually exists and endures. The vision arrives first. The architecture is learned.`,
    feed: `The current sky is moving through the fire frequencies of this connection. The inspiration and forward-reaching energy between these charts is running hotter than usual right now, and what ignites in that heat is worth following.`,
    sonic: `Fire dominant charts produce a composition whose primary character is brightness, forward momentum, and inspirational energy. The upper register is prominent and alive. The rhythm has a quality of forward urgency. The melodic lines reach upward and forward, aspiring toward the upper range rather than settling or descending. The harmonic language moves with confidence and brightness, favoring major tonality and clear tonal direction. Listen for the quality of music that feels genuinely inspiring, that makes you want to move forward, that has genuine brightness and forward-reaching energy.`,
  },

  ELEMENT_EARTH_DOM: {
    id: 'ELEMENT_EARTH_DOM',
    category: 'element',
    title: 'Earth dominant',
    core: `Earth dominant charts carry the elemental quality of earth as their primary register: materiality, practicality, patient development, and the grounding of vision into actual form. Earth is the element of what endures, of the body, of material reality, of the painstaking work that converts inspiration into substance. Where fire reaches toward what is possible, earth works with what is actual. Where fire ignites and moves on, earth stays with what it has begun and develops it thoroughly.`,
    behavioral: `Earth dominant charts correspond to what Jung described as the sensation function, the capacity to perceive and engage with the world as it actually is, with precise attention to material reality, physical sensation, and the concrete details that fire might bypass in favor of the broader vision. The result is genuine practical intelligence, real sustained productive capacity, and the kind of patient, thorough engagement with material reality that converts good ideas into actual things. The developmental challenge of earth dominance is the reverse of fire's: earth produces results but may undervalue the visionary inspiration that gives those results their deepest meaning and direction.`,
    feed: `Today's transit is moving through the earth frequencies of this connection. The practical, grounded, materially real dimension of what is being built between these charts is more visible right now, and what has actually been constructed is worth acknowledging.`,
    sonic: `Earth dominant charts produce a composition whose primary character is grounded weight, patient development, and material substance. The bass register is prominent and genuinely present. The rhythm is reliable and patient, each beat fully weighted, the tempo unhurried. The melodic lines develop patiently, completing themselves thoroughly before moving on. The harmonic language resolves toward genuine tonal stability. Listen for the quality of music that feels genuinely grounded, that has weight and substance and patient development rather than inspiration and forward urgency.`,
  },

  ELEMENT_AIR_DOM: {
    id: 'ELEMENT_AIR_DOM',
    category: 'element',
    title: 'Air dominant',
    core: `Air dominant charts carry the elemental quality of air as their primary register: thought, communication, connection, the relationship between ideas and between people, and the movement of information and meaning through the social and intellectual field. Air is the element of the mind in its social and relational dimension, not the deep interior thinking of water or the visionary inspiration of fire, but the quick, communicative, connective intelligence that moves between people and ideas, sees relationships and patterns, speaks and writes and connects.`,
    behavioral: `Air dominant charts correspond to what Jung described as the thinking function in its social dimension, the capacity to perceive and navigate the relationships between ideas and people with genuine facility. The result is genuine intellectual agility, real communicative capacity, and the kind of social intelligence that makes a person effective in any context that requires navigating the human information field. The developmental challenge of air dominance is the emotional depth that the water element provides. Air can understand feeling but may struggle to fully inhabit it, and the relational intelligence of air without water's emotional depth can produce social competence that falls short of genuine intimacy.`,
    feed: `The current sky is moving through the air frequencies of this connection. The intellectual resonance and communicative current between these charts is more alive right now than usual, and what gets said or understood between these two people today matters.`,
    sonic: `Air dominant charts produce a composition whose primary character is intellectual movement, harmonic agility, and communicative exchange. The middle register is prominent. The rhythm is alert and syncopated. The melodic lines move with intellectual facility, making quick connections between different harmonic areas. The harmonic language is mobile and intellectually engaging, many tonal areas visited in quick, coherent succession. Listen for the quality of music that feels genuinely intelligent, that makes connections you did not anticipate, that moves with alert facility through harmonic space.`,
  },

  ELEMENT_WATER_DOM: {
    id: 'ELEMENT_WATER_DOM',
    category: 'element',
    title: 'Water dominant',
    core: `Water dominant charts carry the elemental quality of water as their primary register: emotional depth, instinctive wisdom, the unconscious, empathy, and the flowing, permeable quality of experience that does not maintain hard boundaries between self and other, between feeling and knowing, between present and past. Water is the element of the interior life, of the feeling world that underlies conscious thought, of the emotional memory that shapes present experience, of the empathic attunement that dissolves the separation between the self and what it encounters.`,
    behavioral: `Water dominant charts correspond to what Jung described as the feeling function, the capacity to evaluate experience through emotional resonance, to know what matters through what is genuinely felt. The result is extraordinary emotional depth, genuine empathic capacity, real intuitive intelligence about the hidden emotional life of situations and relationships, and a quality of compassionate attunement that others find both sustaining and occasionally overwhelming. The developmental challenge of water dominance is the clarity and boundary-maintenance that earth and air elements provide. The water dominant person may need to develop the capacity for clear thinking and firm boundary-setting that prevents the depth from becoming a dissolution of the self into the emotional field around them.`,
    feed: `Today's transit is moving through the water frequencies of this connection. The emotional depth and instinctive resonance between these charts is more present and more accessible right now, and what is felt rather than thought between these two people is the real signal today.`,
    sonic: `Water dominant charts produce a composition whose primary character is emotional depth, fluid movement, and instinctive resonance. The lower-middle register is prominent. The rhythm has the Moon's breathing, tide-like quality amplified by the element, felt as atmosphere rather than counted as meter. The melodic lines move with emotional instinct, curving and returning rather than progressing linearly. The harmonic language is modally rich, emotionally ambiguous, sustained rather than quickly resolved. Listen for the quality of music that feels genuinely felt, that resonates at an emotional depth below the level of conscious response.`,
  },

  // ─── TENSION BANDS ──────────────────────────────────────────────────────────

  TENSION_BAND_LOW: {
    id: 'TENSION_BAND_LOW',
    category: 'tension',
    title: 'Low tension',
    core: `The tension band describes the overall level of internal psychological and energetic tension that characterizes this chart, derived from the ratio of squares and oppositions to harmonious aspects in the natal aspect pattern. A low tension band means this chart carries a relatively harmonious aspect signature. The planets are predominantly in trine and sextile relationships rather than square and opposition, which means the fundamental energetic architecture of the chart is one of internal cooperation rather than internal friction. The person carries relatively little chronic internal conflict between their planetary energies.`,
    behavioral: `People with low tension charts have psychological functions that are not chronically at odds with each other. They do not require significant ongoing internal management to prevent conflict. Decisions tend to be less internally conflicted, recovery from setbacks tends to be faster, and the psychological energy that high tension charts must spend managing internal friction is available for external engagement. The developmental shadow of low tension is real: the growth that comes from genuine internal friction is less available, and the person may need to seek challenge deliberately rather than having it provided by the internal architecture of the chart. Ease is a gift. It is also not a teacher.`,
    feed: `The current transit is moving through the harmonious channel of this connection. The natural ease and internal cooperation between these charts is amplified right now, and what becomes available in that reduced friction is worth stepping into.`,
    sonic: `Low tension charts produce a composition whose primary harmonic character is consonance, smooth voice leading, and natural resolution. Chords resolve naturally. Melodic lines find their destinations without significant resistance. The relationship between melody and harmony is one of mutual support rather than creative friction. Listen for the quality of music that feels genuinely at ease with itself, where the harmonic elements cooperate naturally and resolution arrives without struggle.`,
  },

  TENSION_BAND_MED: {
    id: 'TENSION_BAND_MED',
    category: 'tension',
    title: 'Medium tension',
    core: `A medium tension band means this chart carries a balanced aspect signature: a productive mixture of harmonious aspects that provide internal cooperation and challenging aspects that provide internal creative friction. This is the most common tension profile and in many ways the most productive. Enough harmony to maintain internal coherence and enough friction to drive genuine psychological development, without the chronic intensity that high tension charts carry.`,
    behavioral: `People with medium tension charts have enough internal cooperation to function effectively and enough internal friction to be genuinely motivated toward growth and development. The characteristic quality is what might be called productive engagement with difficulty: the chart provides enough friction to keep the person genuinely developing without the exhausting quality of perpetual internal conflict. They experience real internal conflict in significant decisions and can generally navigate that conflict toward productive outcomes because the harmonic aspects provide sufficient foundation.`,
    feed: `Today's transit is moving through the productive complexity of this connection. The mixture of ease and friction between these charts is more noticeable right now, and the creative tension that mixture generates is the actual content of what is worth exploring.`,
    sonic: `Medium tension charts produce a composition whose harmonic character is a productive mixture of consonance and dissonance, enough harmonic ease to maintain coherence and enough harmonic friction to maintain genuine interest. The relationship between melody and harmony is one of productive engagement rather than either pure cooperation or pure conflict. Listen for the quality of music that feels both grounded and genuinely interesting, where the harmonic ease and the harmonic friction are in productive dialogue.`,
  },

  TENSION_BAND_HIGH: {
    id: 'TENSION_BAND_HIGH',
    category: 'tension',
    title: 'High tension',
    core: `A high tension band means this chart carries a challenging aspect signature: a significant proportion of squares and oppositions relative to harmonious aspects. The fundamental energetic architecture of the chart is one of internal friction, creative conflict, and the ongoing negotiation between psychological forces that do not naturally cooperate. A high tension chart is not a damaged chart. It is a chart that has been given significant internal pressure as its primary developmental resource. The friction is the engine.`,
    behavioral: `People with high tension charts are rarely internally simple. They bring genuine complexity to their engagement with experience, tend toward the kind of depth and intensity that high-friction internal architectures consistently produce, and may find the effortless ease of lower tension configurations both admirable and genuinely puzzling. The developmental task is learning to work with the internal friction rather than against it, to understand the squares and oppositions not as problems to be solved but as the generative pressure that is producing the depth. The people who figure this out often become some of the most interesting and genuinely powerful individuals in any room they enter.`,
    feed: `The current transit is pressing on the high-tension architecture of this connection right now. The internal complexity and creative friction between these charts is more active and more visible today than it usually is, and what gets produced from that pressure is worth paying attention to.`,
    sonic: `High tension charts produce a composition whose primary harmonic character is creative friction. Significant dissonance, harmonic tension that resolves only after genuine development, and the productive creative energy that comes from musical elements in genuine conflict. Chords do not resolve easily. Melodic lines encounter significant harmonic resistance. The relationship between melody and harmony is more one of productive conflict than natural cooperation. Listen for the quality of music that feels genuinely complex, where the harmonic tension is real and the resolution, when it comes, carries the full weight of everything that preceded it.`,
  },

  // ─── TONAL POLARITY ─────────────────────────────────────────────────────────

  TONAL_BRIGHT: {
    id: 'TONAL_BRIGHT',
    category: 'tonal',
    title: 'Bright',
    core: `Tonal polarity describes the overall quality of psychological brightness or darkness that characterizes this chart's fundamental emotional register, derived from the brightness index calculated from the chart's structural elements. A bright tonal polarity means the overall emotional register of this chart tends toward the lighter, more luminous, more outwardly expressive end of the psychological spectrum. Brightness in astrological tonal analysis corresponds to the quality of the Sun's register, the capacity for radiance, for forward-moving optimism, for expressing the interior life in forms that are legible and visible to the world. A bright chart leads with what is luminous rather than what is hidden.`,
    behavioral: `People with bright tonal polarity tend to express their inner life outwardly with relative ease. Their characteristic emotional quality is one of accessible warmth and visibility, and their engagement with the world has a quality of psychological luminosity that others often experience as genuinely uplifting. The developmental shadow of bright polarity is the depth and complexity that darker registers naturally develop through their relationship with shadow material. The bright chart may need to deliberately cultivate the capacity to stay with what is difficult without immediately converting it into a more luminous form.`,
    feed: `Today's transit is moving through the bright register of this connection. What is warm, visible, and luminous between these charts is more present right now, and the quality of genuine light between these people is worth fully receiving.`,
    sonic: `Bright polarity charts produce a composition whose primary register is the Sun's harmonic territory: upper-midrange warmth and clarity, major tonality, melodic lines that reach upward and forward, a dynamic quality that tends toward the more luminous end of the range. The overall emotional register is one of accessible warmth and psychological brightness. Listen for the quality of music that feels genuinely warm and luminous, where the emotional register is primarily bright and forward-facing.`,
  },

  TONAL_BALANCED: {
    id: 'TONAL_BALANCED',
    category: 'tonal',
    title: 'Balanced',
    core: `A balanced tonal polarity means the brightness index of this chart produces an overall emotional register that occupies the middle ground between bright and dark. Neither predominantly luminous nor predominantly shadowed, but genuinely occupying the full range of the psychological spectrum. The balanced chart has access to both the warmth and expressiveness of bright polarity and the depth and complexity of dark polarity without either being dominant.`,
    behavioral: `People with balanced tonal polarity have genuine access to both the lighter, more expressive dimensions of their inner life and the deeper, more complex dimensions, without either being chronically suppressed by the dominance of the other. They have genuine emotional range. They can be genuinely warm and accessible and also genuinely deep and complex, and can meet others across the full spectrum of human emotional experience without significant restriction at either end.`,
    feed: `The current transit is moving through the balanced register of this connection. Both the warmth and the depth that run between these charts are equally available right now, and the full emotional range of this connection is accessible today.`,
    sonic: `Balanced polarity charts produce a composition whose emotional register occupies the full range between bright and dark. Major and minor tonality both genuinely present. Upper and lower registers both genuinely occupied. The dynamic range spanning from warm brightness to genuine depth. Listen for the quality of music that feels emotionally complete, that has both warmth and depth available without either dominating.`,
  },

  TONAL_DARK: {
    id: 'TONAL_DARK',
    category: 'tonal',
    title: 'Dark',
    core: `A dark tonal polarity means the brightness index of this chart produces an overall emotional register that tends toward the deeper, more interior, more psychologically complex end of the spectrum. Darkness in astrological tonal analysis does not mean negativity or depression. It means the quality of depth, interiority, complexity, and the capacity to hold what is difficult without converting it prematurely into something more comfortable. The dark chart leads with what is hidden, complex, and deeply felt rather than with what is immediately luminous and outwardly expressive.`,
    behavioral: `People with dark tonal polarity tend to have an inner life that is rich and complex in ways that do not always express easily outward. Their characteristic emotional quality is one of depth and psychological weight, and their engagement with the world has a quality of interiority that others often experience as genuinely profound. The developmental shadow of dark polarity is the warmth and accessibility that brighter registers make natural. The dark chart may need to deliberately cultivate the capacity to bring its depth into forms that are accessible to others without losing the complexity that makes that depth genuine.`,
    feed: `Today's transit is moving through the deeper register of this connection. What is complex, interior, and genuinely weighty between these charts is more present right now, and the depth available in this moment between these two people deserves genuine attention.`,
    sonic: `Dark polarity charts produce a composition whose primary register is the Moon's and Pluto's harmonic territory: lower-midrange and bass depth, modal and minor tonality, melodic lines that move inward and downward rather than upward and forward, a dynamic quality that tends toward the deeper and more interior end of the range. The overall emotional register is one of genuine depth and psychological complexity. Listen for the quality of music that draws you inward, where the emotional register is primarily deep and interior rather than bright and outward-facing.`,
  },

  // ─── LUMINARY WEIGHT ────────────────────────────────────────────────────────

  STRUCT_LUMINARY_SUN: {
    id: 'STRUCT_LUMINARY_SUN',
    category: 'luminary',
    title: 'Sun weighted',
    core: `Luminary weight describes which of the two great luminaries, the Sun or the Moon, is the more dominant structural force in this chart. A Sun weighted chart means the Sun's principle of conscious identity, willful purpose, and active self-expression is the more powerful organizing force in the overall chart structure. The Sun's energetic quality, its clarity, its forward motion, its capacity for radiant self-definition, pervades the chart's overall character more than the Moon's instinctive, interior, emotional quality. This does not mean the Moon is absent or unimportant. It means the chart's fundamental orientation is more solar: directed toward conscious purpose, outward expression, and the active shaping of the self and the world.`,
    behavioral: `People with Sun weighted charts tend to lead with their purpose, their will, and their active self-expression rather than with their instinctive emotional responses. The solar quality of deliberate self-definition, of the capacity to choose who one is becoming rather than simply responding to who one has been, is the primary psychological resource. The result is a person who is genuinely purposeful, who takes an active rather than reactive stance toward their life, and whose sense of self is most alive when it is actively engaged in the process of becoming rather than simply reflecting what has been.`,
    feed: `The current transit is activating the solar dimension of this connection. The conscious purpose and active direction that each person brings to this relationship is more present right now, and what each person is actively reaching toward in this connection is worth naming.`,
    sonic: `Sun weighted charts produce a composition whose primary organizing force is the Sun's sonic identity: clear major tonality, purposeful forward-moving melodic direction, assertive rhythmic pulse, upper-midrange warmth and clarity. The overall character of the composition is one of conscious, directed, actively expressed energy. Listen for the quality of music where the forward-moving, purposeful quality of the Sun's signature is the dominant organizing force.`,
  },

  STRUCT_LUMINARY_MOON: {
    id: 'STRUCT_LUMINARY_MOON',
    category: 'luminary',
    title: 'Moon weighted',
    core: `A Moon weighted chart means the Moon's principle of emotional instinct, interior feeling, memory, and the body's fundamental need for safety and nourishment is the more powerful organizing force in the overall chart structure. The Moon's energetic quality, its depth, its cyclic nature, its instinctive responsiveness, its connection to what is felt before it is thought, pervades the chart's overall character more than the Sun's purposeful forward motion. This does not mean the Sun is absent. It means the chart's fundamental orientation is more lunar: directed toward interior life, emotional wisdom, and the instinctive navigation of experience through feeling rather than through deliberate purpose.`,
    behavioral: `People with Moon weighted charts tend to lead with their feeling responses, their instinctive wisdom, and their emotional intelligence rather than with deliberate conscious purpose. The lunar quality of instinctive knowing, of the body's wisdom that precedes conscious thought, of the deep emotional memory that shapes present experience, is the primary psychological resource. The result is a person who is genuinely emotionally perceptive, who navigates experience through the wisdom of the feeling body, and whose sense of self is most alive when it is in genuine contact with the emotional reality of the moment.`,
    feed: `Today's transit is activating the lunar dimension of this connection. The instinctive feeling and emotional wisdom that each person brings to this relationship is more present right now, and what is felt between these two people today is the real signal.`,
    sonic: `Moon weighted charts produce a composition whose primary organizing force is the Moon's sonic identity: modal harmonic ambiguity, breathing rhythmic quality, memory-cycling melodic instinct, lower-midrange emotional warmth and depth. The overall character of the composition is one of instinctive, feeling-forward, emotionally resonant energy. Listen for the quality of music where the instinctive, cycling, emotionally deep quality of the Moon's signature is the dominant organizing force.`,
  },

  STRUCT_LUMINARY_BALANCED: {
    id: 'STRUCT_LUMINARY_BALANCED',
    category: 'luminary',
    title: 'Luminary balanced',
    core: `A luminary balanced chart means the Sun and Moon are roughly equivalent in their structural influence on the overall chart. Neither the solar principle of conscious purpose and active self-expression nor the lunar principle of emotional instinct and interior wisdom is clearly dominant. The chart has genuine access to both luminaries as equally weighted organizing forces, which produces a psychological character that draws authentically from both the solar and lunar dimensions of human experience.`,
    behavioral: `People with luminary balanced charts have genuine access to both deliberate conscious purpose and instinctive emotional wisdom without either chronically overriding the other. They have a quality of psychological wholeness in the solar-lunar dimension that is neither primarily purposeful nor primarily instinctive but genuinely capable of both, drawing from the Sun's clarity and the Moon's depth as the situation calls for each. This is one of the more genuinely complete configurations in its primary dimension, and people who carry it often have an unusual capacity to move between thinking and feeling, between direction and instinct, without feeling pulled toward one at the expense of the other.`,
    feed: `The current transit is activating both luminaries in this connection equally. The conscious purpose and the instinctive feeling that each person brings to this relationship are both equally present right now, and the full range of what this connection offers is available today.`,
    sonic: `Luminary balanced charts produce a composition whose organizing forces are genuinely dual. The Sun's forward-moving, purposeful, bright-tonal quality and the Moon's cycling, instinctive, modally-warm quality are equally present and in genuine dialogue. Neither the solar nor the lunar signature dominates. They cooperate as equal organizing forces. Listen for the quality of music where both the forward clarity of the Sun and the instinctive depth of the Moon are genuinely present as equal voices.`,
  },

} as const;
