/**
 * Astradio Insight Library — Mercury Aspects (Phase 3A scope)
 *
 * Mercury aspect entries authored as net-new content during v2 Phase 3.
 * Unlike Phase 2 retrofit work (which added synastry fields to pre-existing
 * natal entries), Phase 3 entries are full 14-field blocks authored from
 * scratch under the locked authoring rule from Phase 2A revision: shared
 * synastry blocks (core_synastry, behavioral_synastry) use chart-bearer
 * attribution, no partnership-coded language, no second-person pronouns.
 * Role-specific framing is reserved for friendship_synastry and
 * romantic_synastry where contextually licensed.
 *
 * Phase 3A scope (50 entries total in this file):
 *   Phase 3A1 — Mercury × Personal pairs (25 entries):
 *     - SUN_MERCURY × 5 aspects
 *     - MOON_MERCURY × 5 aspects
 *     - MERCURY_VENUS × 5 aspects
 *     - MERCURY_MARS × 5 aspects
 *     - MERCURY_MERCURY × 5 aspects (synastry-only, no natal occurrence;
 *       natal fields describe the conceptual register of the geometry)
 *   Phase 3A2 — Mercury × Outer pairs (25 entries):
 *     - SATURN_MERCURY × 5 aspects
 *     - JUPITER_MERCURY × 5 aspects
 *     - URANUS_MERCURY × 5 aspects
 *     - NEPTUNE_MERCURY × 5 aspects
 *     - PLUTO_MERCURY × 5 aspects
 *
 * Note on natal field authoring for synastry-only aspects: SUN_MERCURY
 * reaches conjunction natally (Mercury's max elongation from Sun is ~28°);
 * sextile/square/trine/opposition do not occur natally. Natal fields for
 * these entries describe the geometric register conceptually rather than
 * as an active natal manifestation, matching how Phase 2 personal.ts
 * handles the analogous SUN_VENUS_SEXTILE/SQUARE/TRINE/OPPOSITION
 * configurations that are similarly bounded by orbital geometry.
 *
 * Phase 3A1a (this batch): SUN_MERCURY × 5 entries as the methodology pilot.
 *
 * Place at: vnext/projection/insight-library/insight-library-aspects-mercury.ts
 */

import type { AspectInsight } from './insight-library-types';

export const MERCURY_ASPECT_INSIGHTS: Readonly<Record<string, AspectInsight>> = {
  SUN_MERCURY_CONJUNCTION: {
    key: 'SUN_MERCURY_CONJUNCTION', pair: 'SUN_MERCURY', aspect: 'conjunction', intensity: 'Background',
    core: `The Sun, the seat of conscious identity and willful self-direction, fuses with Mercury, the planet governing the mind, perception, learning, and the function of articulation that converts inner experience into language and thought into form. Where a conjunction occurs, two planets operate as one undivided system. Here that means the sense of who this person is and the way they think and speak are not two separate registers. They run along the same current. The conscious self does not experience itself as separate from its own voice. What this person thinks, they identify with. How they articulate, they recognize as themselves. The mind is not a tool the self deploys; it is the self in motion. This produces a quality of intellectual presence that others read as alert, articulate, and characteristically self-defined through speech.`,
    behavioral: `Because the Sun's identity-function and Mercury's cognitive function are fused rather than distinct, this person's psychological self-recognition runs heavily through verbal and intellectual channels. Thinking is identity work. Speaking aloud, writing, and reasoning through a problem are not just methods of processing for this person; they are the means by which the self continually confirms its own shape. There is little distance between a thought arriving and that thought being attributed to the conscious self as something genuinely meant. The fusion also exposes the Mercury function to the Sun's full ego-investment. Criticism of how this person thinks, speaks, or perceives is not received as feedback about a peripheral skill. It registers at the level of identity. Being called wrong about a fact and being called wrong about who they are can feel indistinguishable. The development task is the slow recognition that thought is information about reality, not the report card on the self.`,
    friendship: `Friends experience this person as articulate, present, and quick to find words. Conversation is how they show up. The friendship lives partly in language.`,
    romantic: `Partners feel met when this person speaks. Verbal exchange is a form of intimacy here. Misunderstandings about words or meaning land harder than they would in less Mercury-identified people because language and self are the same territory.`,
    feed: `The current sky is threading solar and Mercurial frequencies through this connection at the same pitch. A window is open right now where what each person thinks and how each understands themselves are aligned and audible between these two charts.`,
    sonic: `The Sun contributes a clear, forward-moving tonal center and a steady purposeful pulse. Mercury contributes quick melodic articulation, contrapuntal motion, and rapid figure-work that traces the harmonic outline with light incisive notes. In the conjunction these two voices are fused. The Sun's directional clarity is delivered through Mercury's articulate, intricate, fast-moving phrasing. The result is a single unified sound where every melodic statement is sharply enunciated and where the pulse and the figure-work share the same intent. The harmonic language is major and clear, voiced with Mercury's preference for transparency over weight. Listen for the quality of a melody that thinks aloud, where the line and the articulation of the line are the same thing, and where what is being said and the act of saying it cannot be pulled apart.`,
    core_synastry: `When one chart's Sun meets another's Mercury at conjunction, the Sun-bearer's conscious identity arrives at the precise frequency of how the Mercury-bearer perceives, thinks, and articulates. The Mercury-bearer reads the Sun-bearer with unusual clarity, often putting words to who the Sun-bearer is in a way the Sun-bearer recognizes as accurate before they had managed it themselves. The Sun-bearer, in turn, finds their natural way of being received as something the Mercury-bearer can name, describe, and reflect back. This is one of the most immediately legible resonances in synastry, often felt as the experience of being understood without having had to explain.`,
    behavioral_synastry: `In practice, the Mercury-bearer notices things about the Sun-bearer that the Sun-bearer has not yet noticed about themselves: turns of phrase the Sun-bearer uses without meaning to, patterns in how the Sun-bearer makes decisions, recurrences in what the Sun-bearer cares about. This perception is offered easily, and the Sun-bearer often experiences it as recognition rather than analysis. The Sun-bearer's identity gives the Mercury-bearer's mind a real subject to engage with. The shadow is asymmetric: the Mercury-bearer can come to know the Sun-bearer faster than the Sun-bearer comes to know the Mercury-bearer, because the Sun-bearer's identity is the thing being articulated rather than the thing doing the articulating. Both chart-bearers benefit from the Mercury-bearer remaining a real interlocutor rather than becoming the Sun-bearer's mirror.`,
    friendship_synastry: `In a friendship, this conjunction produces the friend who can describe the Sun-bearer to themselves. The Mercury-bearer is the one who remembers what the Sun-bearer said three years ago and quotes it back when it becomes relevant; the Sun-bearer is the one whose presence gives the Mercury-bearer's mind something genuinely worth turning over. These friendships often involve a great deal of conversation that neither friend would describe as small talk. The work is making sure the Mercury-bearer is also seen, not only the one doing the seeing.`,
    romantic_synastry: `In a romantic pairing, this conjunction produces the experience of feeling articulated by the other. The Sun-bearer encounters the Mercury-bearer as someone whose words for the relationship and for the Sun-bearer are unusually accurate; the Mercury-bearer encounters the Sun-bearer as someone whose presence gives every conversation a real subject. Verbal intimacy runs unusually high in partnerships with this aspect, and the relationship often deepens through extended conversation more than through other channels. The sustaining work is making sure the Sun-bearer also learns to articulate the Mercury-bearer rather than simply being articulated by them.`,
  },

  SUN_MERCURY_SEXTILE: {
    key: 'SUN_MERCURY_SEXTILE', pair: 'SUN_MERCURY', aspect: 'sextile', intensity: 'Low',
    core: `The Sun, conscious identity and the drive toward purposeful self-expression, and Mercury, the mind, perception, and the function of articulation that turns thought into form, are in a 60-degree relationship of easy, compatible exchange. The sextile places these two forces in neighboring territories where they understand each other's language. The person's sense of self and their cognitive life do not compete for psychological priority. Identity supports thought, and thought supports identity. The capacity to articulate who they are and what they perceive is available without internal friction.`,
    behavioral: `The sextile between the Sun's identity-function and Mercury's cognitive function creates a productive working relationship between the self and the mind. The conscious self uses thought as a tool rather than identifying with every passing perception, and the mind serves the self's articulation rather than running on tracks separate from it. The result is intellectual reliability without intellectual rigidity. This person can think out loud without the thinking destabilizing the self, and can hold a position firmly while remaining genuinely curious about contrary evidence. Their voice tends to sound like them rather than like someone playing a part. The shadow of the sextile is its own ease: without significant friction between identity and mind, this person may not develop unusual depth in either dimension, since both functions are competent enough that neither requires the kind of work that produces real range.`,
    friendship: `Easy to talk to. Reliably articulate without being performative. Friends find conversation with this person comfortable rather than effortful.`,
    romantic: `Partners appreciate that this person can usually find words for what they mean. The match between what they think and what they say is steady, and verbal exchange does not become a site of recurring misunderstanding.`,
    feed: `Today's transit field is gently opening the channel between conscious direction and articulated thought in this connection. There is easier access between what each person thinks and how each understands themselves than there is on an ordinary day.`,
    sonic: `The Sun contributes its steady purposeful pulse and clear melodic direction. Mercury contributes light articulate figure-work and quick contrapuntal motion. In the sextile these two voices cooperate without fusing. The Sun's directional melodic statements are accompanied by Mercury's clear, intricate articulation that traces the harmonic outline without obscuring it. The harmonic language is major and unambiguous, voiced with Mercury's clarity. The rhythm has the Sun's regularity and Mercury's lighter rhythmic surface working in natural cooperation. Listen for the quality of music that moves with both purpose and articulate intelligence, where the line knows where it is going and the articulation of every note along the way is precise.`,
    core_synastry: `When one chart's Sun meets another's Mercury at sextile, the Sun-bearer's natural self-expression and the Mercury-bearer's mind find a reliable channel of cooperation. The Mercury-bearer perceives the Sun-bearer accurately enough to be a useful interlocutor without producing the immediate identity-recognition the conjunction generates. The Sun-bearer's identity gives the Mercury-bearer's mind a genuine subject to engage; the Mercury-bearer's articulation gives the Sun-bearer language for what they were already becoming. The bond's intellectual register runs steady rather than electric.`,
    behavioral_synastry: `The Mercury-bearer reads the Sun-bearer well, with enough accuracy to be helpful and enough distance to remain a separate mind rather than a mirror. Conversations between the two chart-bearers tend to clarify rather than complicate, and decisions made together tend to be articulated honestly because each chart-bearer can describe what they actually want without misrepresentation. The aspect produces durable working compatibility in the verbal and intellectual domain without the immediacy of the conjunction. Both chart-bearers remain themselves, the contact between them is reliably productive, and shared thinking lands somewhere both can stand.`,
    friendship_synastry: `In a friendship, this sextile produces the friend conversations are easy with. The Mercury-bearer enjoys the Sun-bearer's company because the Sun-bearer gives them something real to think about; the Sun-bearer enjoys the Mercury-bearer's company because the Mercury-bearer's articulation is welcome rather than intrusive. These friendships are often the ones marked by ongoing genuine conversation across years and life phases.`,
    romantic_synastry: `In a romantic pairing, this sextile produces a relationship where verbal communication runs reliably well. The Mercury-bearer can describe what the relationship needs without it landing as criticism on the Sun-bearer's identity; the Sun-bearer can express what they want without the Mercury-bearer over-analyzing it. Partnerships with this aspect tend to weather difficulty better than those without strong Mercury contact, because the partners can actually talk about what is happening between them when difficulty arrives.`,
  },

  SUN_MERCURY_SQUARE: {
    key: 'SUN_MERCURY_SQUARE', pair: 'SUN_MERCURY', aspect: 'square', intensity: 'Medium',
    core: `The Sun, the principle of conscious identity and willful direction, meets Mercury, the mind, perception, and the function of articulation, at a 90-degree angle of sustained tension. The square does not resolve easily because identity and thought are both genuinely strong here and neither yields to the other. The Sun knows what it wants to be. Mercury notices things that complicate that picture. The person experiences a recurring friction between the self they consciously identify with and the perceptions, doubts, and articulations the mind produces about that self. This is not a flaw. It is a configuration that produces unusual self-awareness alongside unusual self-questioning.`,
    behavioral: `The Sun's drive toward unified self-definition and Mercury's tendency to notice nuance, contradiction, and contrary evidence are in 90-degree friction that neither can resolve by simply overriding the other. This produces a pattern recognizable as the smart self-doubter: a person whose intellectual capacity is real, who can analyze most situations clearly, and who turns that same capacity onto themselves with results that are not always kind. The internal critic is loud. Thoughts arrive faster than the self can absorb them, and the self ends up arguing with its own perception. The development task is learning to let Mercury be a tool rather than a tribunal: the mind notices things, including unflattering things, and the self decides what to do with the information rather than treating every perception as a verdict on identity.`,
    friendship: `May be self-deprecating or quick to second-guess. Friends sometimes see this person more clearly than this person sees themselves, and serve as a useful counterweight to the inner critic that runs louder here than is fair.`,
    romantic: `Partners may notice the gap between this person's actual capabilities and their self-assessment. The Mercury function turns inward more sharply than is warranted. Reassurance helps but does not finally resolve it; the work is internal.`,
    feed: `A transit is pressing on the friction point between identity and articulation in this connection. The gap between what each person consciously identifies with and what each perceives about themselves is closer to the surface today than usual, and there is something productive available in naming it.`,
    sonic: `The Sun pushes its melody forward with directional confidence. Mercury cuts across that confidence with quick contrapuntal lines that question, qualify, and complicate the harmonic landing. In the square these two sonic characters are in genuine friction. The Sun's clear major statements are interrupted by Mercury's incisive counter-figures, and Mercury's articulate intelligence keeps adding qualifications the Sun's pulse did not invite. The harmonic language moves between major resolution and quick chromatic passing motion that destabilizes the resolution before it fully lands. Listen for the quality of music where a clear statement is made and then a quick mind picks at it, where the melody and the commentary on the melody are happening at the same time and not always in agreement.`,
    core_synastry: `When one chart's Sun meets another's Mercury at square, the Sun-bearer's identity and the Mercury-bearer's perception find each other through friction. The Mercury-bearer's natural articulations of the Sun-bearer consistently miss in some small way: too pointed, too clinical, too quick, or focused on something the Sun-bearer was hoping would not be noticed. The Sun-bearer's identity, in turn, registers in the Mercury-bearer's awareness as something not quite matching the words available to describe it. Neither chart-bearer is doing anything wrong. The geometry produces real, structural mismatch between what one is and what the other can name.`,
    behavioral_synastry: `The Mercury-bearer's observations about the Sun-bearer often land with more weight than the Mercury-bearer intended, because what reads as a casual remark to the Mercury-bearer registers in the Sun-bearer's awareness as a description of self. The Sun-bearer's responses sometimes seem to the Mercury-bearer like overreaction, because the Mercury-bearer was simply thinking aloud. This produces a bond marked by recurring small misunderstandings about what was meant, what was heard, and what was actually being said. The work is real: the Mercury-bearer learning to register the weight their articulations carry, the Sun-bearer learning to receive observations as information rather than as verdicts on the self.`,
    friendship_synastry: `In a friendship, this square produces a bond marked by genuine intellectual engagement and recurring small misfires in conversation. The Mercury-bearer's quick observations sometimes land harder than intended; the Sun-bearer sometimes hears critique where description was offered. These friendships endure when both friends learn that the friction is the aspect's signature rather than evidence of bad faith, and develop the habit of repairing quickly when an exchange goes off-key.`,
    romantic_synastry: `In a romantic pairing, this square produces a relationship of substance where verbal exchanges carry unusual weight. The Mercury-bearer's words land on the Sun-bearer's identity rather than glancing off, and the Sun-bearer's responses can read to the Mercury-bearer as defensive when the Mercury-bearer was simply observing. Partnerships with this aspect develop genuine fluency in each other's communicative styles when both partners commit to the work, and the verbal intimacy that results is more honest than easier configurations produce.`,
  },

  SUN_MERCURY_TRINE: {
    key: 'SUN_MERCURY_TRINE', pair: 'SUN_MERCURY', aspect: 'trine', intensity: 'Low',
    core: `The Sun, conscious identity and the drive toward purposeful self-definition, and Mercury, the mind, perception, and the function of articulation that converts thought into form, are separated by 120 degrees, placing them in the same elemental family. The trine means these two forces do not experience each other as foreign. The conscious self and the thinking self are oriented toward compatible ends, drawing on the same elemental register, supporting each other without effort. This person's voice tends to sound like them. What they think and what they identify with run on the same current.`,
    behavioral: `The trine between the Sun's identity-function and Mercury's cognitive function creates a well-integrated articulating self. The mind serves the conscious will rather than running on a separate track, and the conscious will is articulate about its own ends rather than driving forward without intellectual self-awareness. This person can describe what they want, why they want it, and how they propose to pursue it without significant internal friction in any of those operations. The cognitive style tends to be clear without being cold, verbal without being verbose, and articulate without performing articulacy. The shadow of this trine is the same shadow it carries everywhere: ease can produce comfortable underdevelopment of either function, since neither identity nor mind is forced into the kind of contention that produces depth.`,
    friendship: `Reliable conversational presence. This person finds words easily and means what they say. Friends return to them because talking with them clarifies rather than complicates.`,
    romantic: `Partners often cite the ease of being understood by this person. They listen well and articulate accurately. The match between intent and expression is steady.`,
    feed: `The current sky is amplifying the natural coherence between identity and articulation in this connection. What runs easily between these two charts in the verbal and intellectual register is running more easily right now than it does on an ordinary day.`,
    sonic: `The Sun and Mercury are in the same elemental family in the trine. The Sun's directional clarity and Mercury's articulate figure-work flow together without friction between purpose and precision. The melodic lines have the Sun's purposeful direction and Mercury's clean articulation simultaneously. The harmonic language is clear, voiced with Mercury's preference for transparency. Every note is well-placed; every line knows where it is going; every articulation lands precisely where it was aiming. Listen for the quality of music that thinks aloud with grace, where the line and the articulation of the line are both clear and never at odds with each other.`,
    core_synastry: `When one chart's Sun meets another's Mercury at trine, the Sun-bearer's identity and the Mercury-bearer's mind find each other in the same elemental family, moving in compatible directions without effort. The Mercury-bearer perceives the Sun-bearer accurately as a default rather than as an achievement; the Sun-bearer's identity gives the Mercury-bearer a real subject to engage with, and the Mercury-bearer's articulations land where the Sun-bearer recognizes themselves rather than missing slightly. The bond runs intellectually warm without effort.`,
    behavioral_synastry: `The Mercury-bearer's observations about the Sun-bearer tend to be the kind the Sun-bearer recognizes immediately, and the Sun-bearer's responses give the Mercury-bearer real material to work with. Conversations clarify; shared thinking moves forward; decisions made together get articulated honestly because both chart-bearers can describe what they actually mean. The aspect produces sustained intellectual ease that does not need to be manufactured. The trine's limitation is that the same ease can let both chart-bearers stay at a comfortable level of mutual understanding without ever pushing into the harder territory where real depth lives.`,
    friendship_synastry: `In a friendship, this trine produces the friend conversations work with by default. The Mercury-bearer enjoys the Sun-bearer's company because the Sun-bearer's identity gives every exchange a real subject; the Sun-bearer enjoys the Mercury-bearer's company because the Mercury-bearer's articulation is welcome and accurate. These friendships often last across years because the underlying intellectual compatibility holds without effort.`,
    romantic_synastry: `In a romantic pairing, this trine produces a relationship marked by sustained verbal ease. The Mercury-bearer can describe what is happening between the two without it landing as criticism; the Sun-bearer can express what they want without the Mercury-bearer parsing it into something it was not. Partnerships with this aspect tend to weather difficulty well because the partners can actually talk to each other when difficulty arrives, and the conversation tends to clarify rather than complicate.`,
  },

  SUN_MERCURY_OPPOSITION: {
    key: 'SUN_MERCURY_OPPOSITION', pair: 'SUN_MERCURY', aspect: 'opposition', intensity: 'Medium',
    core: `The Sun, conscious identity, willful direction, and the ego's drive to define itself, stands opposite Mercury, the mind, perception, and the function of articulation, across a 180-degree axis of full polarity. The opposition holds these two forces apart and in constant awareness of each other. The Sun knows the mind is observing. Mercury knows the self is acting. Neither can ignore the other. The person experiences a structural distance between the self that does and the self that thinks about doing, with each pole fully visible to the other across the gap.`,
    behavioral: `The psychological mechanism of the Sun-Mercury opposition is the gap between action and articulation, made conscious. The person who acts and the person who narrates that action are not the same psychological agent in this configuration. They face each other. Where the conjunction fuses identity and mind into a single voice, the opposition holds them at maximum distance, which produces a characteristic capacity for self-observation alongside a characteristic difficulty trusting that the observer and the observed are the same person. This person often processes their own life through dialogue with others, because external interlocutors temporarily collapse the internal axis: someone else's articulation can be received without the suspicion that always attends the person's own self-description. The development task is learning to be both poles of the axis at once rather than alternating between them.`,
    friendship: `Friends are often important sounding boards. The articulation that happens in conversation does work for this person that internal monologue cannot finish on its own.`,
    romantic: `Partnership becomes a primary site of self-articulation. The partner's words for the relationship and for this person carry weight because they bridge an internal gap that this person cannot fully bridge alone.`,
    feed: `Today's transits are illuminating both ends of the identity-articulation axis in this connection. The space between what each person is and what each can say about themselves is more visible right now between these two charts than it usually is, and there is something to do with that visibility today.`,
    sonic: `The Sun and Mercury in opposition produce a composition built on call and response between two distinct voices. The Sun's purposeful, directional melodic statements are answered by Mercury's quick, articulate counter-lines from the opposite end of the musical space. The two voices are at maximum distance and in constant dialogue across that distance. Neither dominates for long; each comments on the other. The harmonic language alternates between the Sun's clear major resolutions and Mercury's quick chromatic passing motion that observes and qualifies the resolution from outside. Listen for the quality of music where action and observation are happening as two separate voices in conversation, where the doing and the watching the doing are both audible at the same time and never fully merge.`,
    core_synastry: `When one chart's Sun meets another's Mercury at opposition, the two charts face each other across the full width of the synastry axis. The Sun-bearer's identity sits at one pole; the Mercury-bearer's mind sits at the other. Each is fully visible to the other across the distance, and neither is hidden. The Mercury-bearer's perception of the Sun-bearer is unusually clear, sometimes uncomfortably so. The Sun-bearer's presence gives the Mercury-bearer's mind something to circle, describe, and articulate, sometimes more than the Sun-bearer asked for. The bond becomes a site where being and being-described meet across genuine distance.`,
    behavioral_synastry: `The Mercury-bearer often finds themselves narrating, observing, or articulating the Sun-bearer in ways neither chart-bearer fully chose. The Sun-bearer often finds themselves reflected in the Mercury-bearer's words, sometimes recognizing themselves and sometimes not. This produces a bond marked by significant verbal exchange where the stakes are higher than they appear: each conversation is partly the Mercury-bearer trying to put words to the Sun-bearer, and the Sun-bearer either claiming or refusing those words. Worked consciously, the polarity becomes one of the most generative configurations for mutual understanding. Worked unconsciously, the bond cycles between the Mercury-bearer over-articulating and the Sun-bearer feeling defined from outside.`,
    friendship_synastry: `In a friendship, this opposition produces the friend whose conversations carry weight. The Mercury-bearer becomes the one who can put words to what the Sun-bearer is going through; the Sun-bearer becomes the one who gives the Mercury-bearer's mind something genuinely worth articulating. These friendships often involve long, important conversations that neither friend would describe as casual, and they tend to deepen significantly when both friends accept that what is being exchanged is more than information.`,
    romantic_synastry: `In a romantic pairing, this opposition produces a relationship where verbal exchange carries unusual stakes. The Mercury-bearer's articulations of the Sun-bearer and of the relationship reach across distance and can land with significant force; the Sun-bearer's responses to those articulations shape what the relationship actually becomes. Partnerships with this aspect either develop genuine fluency in the dialogue between identity and articulation or break down into recurring arguments about what was meant, what was heard, and who has the right to describe whom. The middle path is the work, and partners who do it well report a relationship of unusual verbal honesty.`,
  },
} as const;
