/**
 * Angle placements . Ascendant, Midheaven, IC (Imum Coeli).
 * Keys: PLCMT_ASCENDANT_{SIGN}, PLCMT_MC_{SIGN}, PLCMT_IC_{SIGN}
 * Sign-only framing (angles are house cusps; no house subsection in Identity UI).
 */

import type { PlanetInSignInsight } from './insight-library-types';

export const ASCENDANT_PLACEMENTS: Readonly<Record<string, PlanetInSignInsight>> = {
  PLCMT_ASCENDANT_ARIES: {
    key: 'PLCMT_ASCENDANT_ARIES',
    planet: 'ASCENDANT',
    sign: 'ARIES',
    title: 'Ascendant in Aries',
    core: `Your Ascendant in Aries means you present with immediate directness, forward momentum, and the energy of someone who acts first and reflects later. People experience you as pioneering, courageous, and refreshingly unfiltered in your approach to new situations.`,
    behavioral: `You enter rooms with visible purpose, make quick decisions without waiting for group consensus, and naturally take initiative when situations require action. Your physical presence carries the quality of readiness. You look like someone who's about to do something rather than someone who's waiting for permission.`,
    friendship: `In friendship, your Aries rising shows up as the friend who suggests the plan, speaks first, and keeps the bond moving. Others read your directness as enthusiasm rather than aggression when the connection is honest.`,
    romantic: `In romance, your Aries rising brings immediate chemistry and unmistakable pursuit energy. Partners feel chosen quickly and clearly; the opening movement of the relationship often sets its pace.`,
    feed: `Your rising sign carries Aries energy today. First impressions run hot, direct, and ready to initiate.`,
    sonic: `Your Aries Ascendant contributes sharp melodic attacks, bright harmonic energy, and rhythm that initiates without hesitation. The sound of immediate presence and forward drive.`,
  },

  PLCMT_ASCENDANT_TAURUS: {
    key: 'PLCMT_ASCENDANT_TAURUS',
    planet: 'ASCENDANT',
    sign: 'TAURUS',
    title: 'Ascendant in Taurus',
    core: `Your Ascendant in Taurus means you present with grounded steadiness, physical presence, and the energy of someone who can't be rushed. People experience you as calm, reliable, and possessing a natural authority that comes from being fully embodied.`,
    behavioral: `You move through space deliberately, respond to questions after taking a moment to consider, and carry yourself with the quality of someone who knows their own weight. Your physical presence communicates 'I'm here, and I'm not going anywhere until I'm ready.'`,
    friendship: `In friendship, your Taurus rising offers steady presence, tangible comfort, and patience with pacing. Friends experience you as someone who shows up consistently rather than dramatically.`,
    romantic: `In romance, your Taurus rising signals sensual calm and durability in first contact. Attraction builds through reliability and physical ease as much as through words.`,
    feed: `Your rising sign carries Taurus energy today. Presence reads grounded, patient, and physically reassuring.`,
    sonic: `Your Taurus Ascendant contributes rich sustained tones, warm harmonic grounding, and rhythm that is patient and unhurried. The sound of physical presence and embodied certainty.`,
  },

  PLCMT_ASCENDANT_GEMINI: {
    key: 'PLCMT_ASCENDANT_GEMINI',
    planet: 'ASCENDANT',
    sign: 'GEMINI',
    title: 'Ascendant in Gemini',
    core: `Your Ascendant in Gemini means you present with quick adaptability, intellectual curiosity, and the energy of someone who's always ready for the next conversation. People experience you as clever, sociable, and perpetually interested in learning what you don't already know.`,
    behavioral: `You engage new situations through questions and observation, shift your presentation to match the context you're in, and naturally create connection through wit and verbal agility. Your physical presence is light and mobile. You look like someone who could pivot to something completely different at any moment.`,
    friendship: `In friendship, your Gemini rising sparks conversation, introduces ideas, and keeps social contact lively. Friends experience you as curious, witty, and easy to talk with on short notice.`,
    romantic: `In romance, your Gemini rising opens doors through words, humor, and mental rapport. Initial attraction often starts as fascination before it deepens.`,
    feed: `Your rising sign carries Gemini energy today. First contact favors conversation, curiosity, and quick mental exchange.`,
    sonic: `Your Gemini Ascendant contributes nimble melodic movement, airy harmonic textures, and rhythm that is conversational and quick. The sound of mental agility and adaptive presence.`,
  },

  PLCMT_ASCENDANT_CANCER: {
    key: 'PLCMT_ASCENDANT_CANCER',
    planet: 'ASCENDANT',
    sign: 'CANCER',
    title: 'Ascendant in Cancer',
    core: `Your Ascendant in Cancer means you present with emotional receptivity, protective instinct, and the energy of someone who feels their way into situations before committing. People experience you as nurturing, intuitive, and possessing a natural ability to make others feel safe.`,
    behavioral: `You approach new situations cautiously, read the emotional temperature of rooms before speaking, and instinctively create comfort for others even when you're personally uncertain. Your physical presence communicates 'I'm here to hold space, not to dominate it.'`,
    friendship: `In friendship, your Cancer rising offers warmth, attunement, and protective care. Friends feel met emotionally before they feel evaluated.`,
    romantic: `In romance, your Cancer rising signals tenderness and emotional safety in first meetings. Partners sense that vulnerability could be welcome here.`,
    feed: `Your rising sign carries Cancer energy today. Presence reads receptive, protective, and emotionally attuned.`,
    sonic: `Your Cancer Ascendant contributes flowing melodic waves, warm harmonic shelter, and rhythm that ebbs and flows with emotional tides. The sound of receptive presence and protective care.`,
  },

  PLCMT_ASCENDANT_LEO: {
    key: 'PLCMT_ASCENDANT_LEO',
    planet: 'ASCENDANT',
    sign: 'LEO',
    title: 'Ascendant in Leo',
    core: `Your Ascendant in Leo means you present with natural radiance, generous warmth, and the energy of someone who expects to be noticed. People experience you as confident, dignified, and carrying yourself as though you have every right to take up space.`,
    behavioral: `You enter situations with visible self-assurance, speak and move as though performing for an audience (even when alone), and naturally draw attention through sheer presence rather than effort. Your physical bearing communicates 'I'm here, and my being here matters.'`,
    friendship: `In friendship, your Leo rising brings warmth, loyalty, and visible enjoyment of the bond. Friends feel celebrated when you turn your attention toward them.`,
    romantic: `In romance, your Leo rising radiates confident charm and generous attention. First encounters often feel theatrically alive and personally honoring.`,
    feed: `Your rising sign carries Leo energy today. First impressions run warm, visible, and self-assured.`,
    sonic: `Your Leo Ascendant contributes bold melodic statements, radiant harmonic warmth, and rhythm that commands attention. The sound of dignified presence and generous self-expression.`,
  },

  PLCMT_ASCENDANT_VIRGO: {
    key: 'PLCMT_ASCENDANT_VIRGO',
    planet: 'ASCENDANT',
    sign: 'VIRGO',
    title: 'Ascendant in Virgo',
    core: `Your Ascendant in Virgo means you present with careful observation, practical modesty, and the energy of someone who's assessing how to be useful. People experience you as thoughtful, precise, and more interested in competence than performance.`,
    behavioral: `You approach situations by noticing what needs fixing or organizing, present yourself with clean efficiency rather than dramatic flair, and naturally offer helpful observations even when not asked. Your physical presence is understated and functional. You look like someone who's here to work, not to be admired.`,
    friendship: `In friendship, your Virgo rising shows up as practical help, thoughtful detail, and quiet reliability. Friends trust your observations even when you underplay yourself.`,
    romantic: `In romance, your Virgo rising signals discernment and understated care. Attraction grows through competence, attentiveness, and modest steadiness.`,
    feed: `Your rising sign carries Virgo energy today. Presence reads precise, helpful, and quietly competent.`,
    sonic: `Your Virgo Ascendant contributes precise melodic detail, refined harmonic clarity, and rhythm that is efficient and measured. The sound of careful attention and practical presence.`,
  },

  PLCMT_ASCENDANT_LIBRA: {
    key: 'PLCMT_ASCENDANT_LIBRA',
    planet: 'ASCENDANT',
    sign: 'LIBRA',
    title: 'Ascendant in Libra',
    core: `Your Ascendant in Libra means you present with graceful diplomacy, aesthetic awareness, and the energy of someone who instinctively seeks balance and harmony. People experience you as charming, fair-minded, and naturally skilled at making others feel considered and valued.`,
    behavioral: `You enter situations looking for the point of connection or agreement, adjust your presentation to create relational ease, and naturally mediate conflicts even when not directly involved. Your physical presence is poised and pleasing. You look like someone who cares how things (including yourself) are perceived.`,
    friendship: `In friendship, your Libra rising smooths friction, invites fairness, and keeps tone pleasant. Friends feel aesthetically and relationally considered.`,
    romantic: `In romance, your Libra rising opens with charm, balance, and mutual regard. First meetings often feel elegant and mutually attentive.`,
    feed: `Your rising sign carries Libra energy today. First contact favors harmony, grace, and relational balance.`,
    sonic: `Your Libra Ascendant contributes balanced melodic phrases, harmonious chord progressions, and rhythm that seeks equilibrium. The sound of graceful presence and relational attunement.`,
  },

  PLCMT_ASCENDANT_SCORPIO: {
    key: 'PLCMT_ASCENDANT_SCORPIO',
    planet: 'ASCENDANT',
    sign: 'SCORPIO',
    title: 'Ascendant in Scorpio',
    core: `Your Ascendant in Scorpio means you present with intense focus, psychological depth, and the energy of someone who sees through surfaces to what's hidden underneath. People experience you as powerful, private, and possessing a penetrating gaze that makes superficial conversation feel inadequate.`,
    behavioral: `You approach new situations with strategic caution, reveal only what serves your purposes, and naturally command respect through sheer intensity rather than explicit assertion. Your physical presence is magnetically controlled. You look like someone who could handle whatever darkness the situation might reveal.`,
    friendship: `In friendship, your Scorpio rising signals loyalty, depth, and discretion. Friends sense that secrets could be safe and that you see more than you say.`,
    romantic: `In romance, your Scorpio rising carries magnetic restraint and emotional gravity. First contact often feels fated, private, or impossible to ignore.`,
    feed: `Your rising sign carries Scorpio energy today. Presence reads intense, perceptive, and strategically contained.`,
    sonic: `Your Scorpio Ascendant contributes smoldering melodic intensity, dark harmonic depth, and rhythm that pulses with contained power. The sound of penetrating presence and strategic revelation.`,
  },

  PLCMT_ASCENDANT_SAGITTARIUS: {
    key: 'PLCMT_ASCENDANT_SAGITTARIUS',
    planet: 'ASCENDANT',
    sign: 'SAGITTARIUS',
    title: 'Ascendant in Sagittarius',
    core: `Your Ascendant in Sagittarius means you present with expansive enthusiasm, philosophical curiosity, and the energy of someone who's always ready for the next adventure. People experience you as optimistic, blunt, and carrying yourself with the freedom of someone who doesn't take social convention too seriously.`,
    behavioral: `You enter situations openly and without guile, speak your truth even when diplomacy might serve you better, and naturally inspire others through your genuine belief that life is meant to be explored. Your physical presence is unrestrained and broad. You look like someone who needs room to move and thinks borders are suggestions.`,
    friendship: `In friendship, your Sagittarius rising brings humor, honesty, and appetite for experience. Friends feel invited into a larger world when you're around.`,
    romantic: `In romance, your Sagittarius rising signals openness, adventure, and candid warmth. First meetings can feel exciting and slightly unbounded.`,
    feed: `Your rising sign carries Sagittarius energy today. First impressions run open, blunt, and forward-looking.`,
    sonic: `Your Sagittarius Ascendant contributes soaring melodic range, expansive harmonic openness, and rhythm that gallops toward the horizon. The sound of adventurous presence and philosophical freedom.`,
  },

  PLCMT_ASCENDANT_CAPRICORN: {
    key: 'PLCMT_ASCENDANT_CAPRICORN',
    planet: 'ASCENDANT',
    sign: 'CAPRICORN',
    title: 'Ascendant in Capricorn',
    core: `Your Ascendant in Capricorn means you present with serious authority, disciplined restraint, and the energy of someone who has earned their presence through competence. People experience you as responsible, mature beyond your years, and naturally commanding respect without demanding it.`,
    behavioral: `You carry yourself with measured dignity, speak only when you have something substantive to say, and demonstrate competence through action rather than words. Your physical presence communicates 'I'm here to accomplish something real, not to perform for approval.'`,
    friendship: `In friendship, your Capricorn rising reads as dependable, reserved, and structurally loyal. Friends trust your judgment and your follow-through.`,
    romantic: `In romance, your Capricorn rising signals seriousness and earned trust. Attraction respects maturity, reliability, and demonstrated character.`,
    feed: `Your rising sign carries Capricorn energy today. Presence reads composed, authoritative, and purpose-driven.`,
    sonic: `Your Capricorn Ascendant contributes austere melodic structure, authoritative harmonic foundations, and rhythm that builds with patient discipline. The sound of earned authority and enduring presence.`,
  },

  PLCMT_ASCENDANT_AQUARIUS: {
    key: 'PLCMT_ASCENDANT_AQUARIUS',
    planet: 'ASCENDANT',
    sign: 'AQUARIUS',
    title: 'Ascendant in Aquarius',
    core: `Your Ascendant in Aquarius means you present with detached originality, intellectual independence, and the energy of someone who's operating on a frequency slightly different from everyone else. People experience you as unconventional, principled, and genuinely unbothered by whether your approach matches social norms.`,
    behavioral: `You enter situations as an observer rather than a participant, present yourself as uniquely yourself without apology or explanation, and naturally challenge conventions through simply being who you are. Your physical presence is both friendly and remote. You look like someone who's here with you but also somewhere else entirely.`,
    friendship: `In friendship, your Aquarius rising offers originality, principled honesty, and respectful distance. Friends feel accepted as individuals rather than managed.`,
    romantic: `In romance, your Aquarius rising signals friendship-first chemistry and unconventional pacing. First contact can feel intriguing and slightly unpredictable.`,
    feed: `Your rising sign carries Aquarius energy today. First impressions read original, principled, and lightly detached.`,
    sonic: `Your Aquarius Ascendant contributes unexpected melodic intervals, innovative harmonic progressions, and rhythm that breaks conventional patterns. The sound of original presence and intellectual detachment.`,
  },

  PLCMT_ASCENDANT_PISCES: {
    key: 'PLCMT_ASCENDANT_PISCES',
    planet: 'ASCENDANT',
    sign: 'PISCES',
    title: 'Ascendant in Pisces',
    core: `Your Ascendant in Pisces means you present with gentle fluidity, emotional permeability, and the energy of someone whose boundaries are more porous than most. People experience you as compassionate, dreamy, and possessing an otherworldly quality that makes you seem like you're channeling something beyond yourself.`,
    behavioral: `You approach situations by absorbing the emotional atmosphere, adapt your presentation to reflect what others need from you, and naturally dissolve barriers between yourself and whoever you're with. Your physical presence is soft and yielding. You look like someone who could dissolve into mist if the world gets too harsh.`,
    friendship: `In friendship, your Pisces rising offers empathy, imaginative warmth, and nonjudgmental presence. Friends feel emotionally held without being fixed.`,
    romantic: `In romance, your Pisces rising signals softness, mystery, and romantic idealism in first contact. Partners sense depth beneath a gentle surface.`,
    feed: `Your rising sign carries Pisces energy today. Presence reads gentle, porous, and imaginatively receptive.`,
    sonic: `Your Pisces Ascendant contributes flowing melodic dissolve, ethereal harmonic wash, and rhythm that moves like water without edges. The sound of permeable presence and transcendent empathy.`,
  },
};

export const MIDHEAVEN_PLACEMENTS: Readonly<Record<string, PlanetInSignInsight>> = {
  PLCMT_MC_ARIES: {
    key: 'PLCMT_MC_ARIES',
    planet: 'MC',
    sign: 'ARIES',
    title: 'Midheaven in Aries',
    core: `Your Midheaven in Aries means your career direction and public image are organized around pioneering, leadership, and the courage to blaze new trails. You're building a legacy of first-mover action and independent achievement.`,
    behavioral: `You pursue career goals with direct urgency, take professional risks others avoid, and build your reputation through visible initiative. When you're working toward achievement, you lead rather than follow, initiate rather than wait for consensus.`,
    friendship: `In professional networks, your Aries Midheaven reads as the colleague who steps up first and names the bold move others were circling.`,
    romantic: `In partnership, your public drive can show as a partner who wants shared goals to move fast and feel unmistakably chosen.`,
    feed: `Your Midheaven carries Aries energy today. Public direction favors initiative, leadership, and visible first steps.`,
    sonic: `Your Aries Midheaven contributes bold melodic ambition, bright harmonic authority, and rhythm that drives toward professional conquest. The sound of leadership and pioneering achievement.`,
  },

  PLCMT_MC_TAURUS: {
    key: 'PLCMT_MC_TAURUS',
    planet: 'MC',
    sign: 'TAURUS',
    title: 'Midheaven in Taurus',
    core: `Your Midheaven in Taurus means your career direction and public image are organized around building lasting value, material security, and the patient accumulation of real achievement. You're constructing a legacy that endures through tangible contribution and unshakeable reliability.`,
    behavioral: `You pursue career goals steadily and methodically, build reputation through consistent high-quality work, and achieve through refusing to be rushed past what takes time. When you're working toward mastery, you trust the process more than the timeline.`,
    friendship: `In professional networks, your Taurus Midheaven reads as the builder others trust for quality, steadiness, and follow-through.`,
    romantic: `In partnership, your public steadiness can show as a partner who equates love with reliability and tangible security over time.`,
    feed: `Your Midheaven carries Taurus energy today. Public direction favors patience, quality, and durable results.`,
    sonic: `Your Taurus Midheaven contributes rich harmonic abundance, sustained melodic building, and rhythm that is patient and grounded. The sound of enduring achievement and material mastery.`,
  },

  PLCMT_MC_GEMINI: {
    key: 'PLCMT_MC_GEMINI',
    planet: 'MC',
    sign: 'GEMINI',
    title: 'Midheaven in Gemini',
    core: `Your Midheaven in Gemini means your career direction and public image are organized around communication, intellectual versatility, and the ability to connect disparate ideas. You're building a legacy through the power of words, information, and mental agility.`,
    behavioral: `You pursue career goals through multiple channels simultaneously, build reputation through clever communication and intellectual range, and achieve by staying curious and adaptable. When you're working toward success, you're learning, teaching, and translating between different worlds.`,
    friendship: `In professional networks, your Gemini Midheaven reads as the connector who translates between teams, ideas, and audiences with ease.`,
    romantic: `In partnership, your public versatility can show as a partner who keeps the relationship mentally alive through conversation and shared learning.`,
    feed: `Your Midheaven carries Gemini energy today. Public direction favors communication, curiosity, and agile exchange.`,
    sonic: `Your Gemini Midheaven contributes nimble melodic conversation, airy harmonic exchange, and rhythm that is quick and articulate. The sound of intellectual achievement and communicative mastery.`,
  },

  PLCMT_MC_CANCER: {
    key: 'PLCMT_MC_CANCER',
    planet: 'MC',
    sign: 'CANCER',
    title: 'Midheaven in Cancer',
    core: `Your Midheaven in Cancer means your career direction and public image are organized around nurturing, emotional intelligence, and creating sanctuary for others. You're building a legacy through care, protection, and the capacity to make people feel safe and seen.`,
    behavioral: `You pursue career goals by tending to human needs, build reputation through genuine emotional attunement and protective leadership, and achieve by creating environments where others can thrive. When you're working toward your calling, you're mothering the world in your particular way.`,
    friendship: `In professional networks, your Cancer Midheaven reads as the leader who protects the team and remembers what people need to feel secure.`,
    romantic: `In partnership, your public care can show as a partner who builds home, safety, and emotional continuity into shared life.`,
    feed: `Your Midheaven carries Cancer energy today. Public direction favors care, protection, and emotionally intelligent leadership.`,
    sonic: `Your Cancer Midheaven contributes flowing emotional melody, warm harmonic shelter, and rhythm that nurtures and protects. The sound of caring leadership and emotional authority.`,
  },

  PLCMT_MC_LEO: {
    key: 'PLCMT_MC_LEO',
    planet: 'MC',
    sign: 'LEO',
    title: 'Midheaven in Leo',
    core: `Your Midheaven in Leo means your career direction and public image are organized around creative self-expression, dignified leadership, and the courage to shine without apology. You're building a legacy through the radiance of your authentic presence and generous authority.`,
    behavioral: `You pursue career goals with bold confidence, build reputation through dramatic excellence and magnetic presence, and achieve by taking center stage when your talents demand it. When you're working toward greatness, you're not dimming your light to make others comfortable.`,
    friendship: `In professional networks, your Leo Midheaven reads as the figure others look to for vision, warmth, and visible excellence.`,
    romantic: `In partnership, your public radiance can show as a partner who wants shared life to feel celebrated and proudly chosen.`,
    feed: `Your Midheaven carries Leo energy today. Public direction favors creative leadership, visibility, and generous authority.`,
    sonic: `Your Leo Midheaven contributes radiant melodic statements, warm harmonic confidence, and rhythm that commands attention. The sound of dignified achievement and creative authority.`,
  },

  PLCMT_MC_VIRGO: {
    key: 'PLCMT_MC_VIRGO',
    planet: 'MC',
    sign: 'VIRGO',
    title: 'Midheaven in Virgo',
    core: `Your Midheaven in Virgo means your career direction and public image are organized around precision, useful service, and the mastery of technical skill. You're building a legacy of excellence through meticulous attention to craft and genuine utility.`,
    behavioral: `You pursue career goals through continuous improvement, earn reputation by solving real problems better than anyone else, and achieve through patient refinement of skill. When you're working toward mastery, you focus on what actually works rather than what looks impressive.`,
    friendship: `In professional networks, your Virgo Midheaven reads as the craftsperson others rely on when the details must be right.`,
    romantic: `In partnership, your public precision can show as a partner who expresses care through practical competence and steady improvement.`,
    feed: `Your Midheaven carries Virgo energy today. Public direction favors craft, service, and refined usefulness.`,
    sonic: `Your Virgo Midheaven contributes precise melodic craft, intricate harmonic detail, and rhythm that perfects through careful iteration. The sound of technical mastery and useful service.`,
  },

  PLCMT_MC_LIBRA: {
    key: 'PLCMT_MC_LIBRA',
    planet: 'MC',
    sign: 'LIBRA',
    title: 'Midheaven in Libra',
    core: `Your Midheaven in Libra means your career direction and public image are organized around creating beauty, facilitating fairness, and bringing disparate parties into balance. You're building a legacy through aesthetic refinement, diplomatic skill, and the capacity to see all sides.`,
    behavioral: `You pursue career goals through partnership and collaboration, build reputation through graceful mediation and aesthetic judgment, and achieve by creating harmony where others see only conflict. When you're working toward your calling, you're making the world more beautiful and more just.`,
    friendship: `In professional networks, your Libra Midheaven reads as the diplomat who elevates tone, design, and fair process.`,
    romantic: `In partnership, your public grace can show as a partner who values balance, beauty, and mutual regard in shared ambition.`,
    feed: `Your Midheaven carries Libra energy today. Public direction favors diplomacy, aesthetics, and relational balance.`,
    sonic: `Your Libra Midheaven contributes balanced harmonic progressions, graceful melodic partnership, and rhythm that seeks equilibrium. The sound of diplomatic achievement and aesthetic authority.`,
  },

  PLCMT_MC_SCORPIO: {
    key: 'PLCMT_MC_SCORPIO',
    planet: 'MC',
    sign: 'SCORPIO',
    title: 'Midheaven in Scorpio',
    core: `Your Midheaven in Scorpio means your career direction and public image are organized around transformation, psychological depth, and the courage to work with what others won't touch. You're building a legacy through your capacity to face darkness and emerge with power.`,
    behavioral: `You pursue career goals with strategic intensity, build reputation through your willingness to go deeper than anyone else, and achieve through confronting what most people avoid. When you're working toward mastery, you're transforming both yourself and the systems you engage.`,
    friendship: `In professional networks, your Scorpio Midheaven reads as the strategist others trust with what cannot be said aloud.`,
    romantic: `In partnership, your public intensity can show as a partner who wants truth, depth, and loyalty beneath the surface story.`,
    feed: `Your Midheaven carries Scorpio energy today. Public direction favors depth, transformation, and strategic power.`,
    sonic: `Your Scorpio Midheaven contributes smoldering melodic intensity, dark harmonic depth, and rhythm that pulses with controlled power. The sound of transformative achievement and psychological authority.`,
  },

  PLCMT_MC_SAGITTARIUS: {
    key: 'PLCMT_MC_SAGITTARIUS',
    planet: 'MC',
    sign: 'SAGITTARIUS',
    title: 'Midheaven in Sagittarius',
    core: `Your Midheaven in Sagittarius means your career direction and public image are organized around exploration, philosophical truth, and expanding beyond known boundaries. You're building a legacy through adventure, teaching, and the conviction that life's meaning is found in growth and discovery.`,
    behavioral: `You pursue career goals with enthusiastic optimism, build reputation through bold vision and infectious belief in possibility, and achieve by taking risks others consider reckless. When you're working toward your calling, you're following truth wherever it leads, even when the destination is uncertain.`,
    friendship: `In professional networks, your Sagittarius Midheaven reads as the visionary who widens the frame and invites others toward a bigger horizon.`,
    romantic: `In partnership, your public optimism can show as a partner who wants shared life to keep expanding in meaning and adventure.`,
    feed: `Your Midheaven carries Sagittarius energy today. Public direction favors vision, teaching, and bold exploration.`,
    sonic: `Your Sagittarius Midheaven contributes soaring melodic range, expansive harmonic optimism, and rhythm that gallops toward the horizon. The sound of adventurous achievement and philosophical authority.`,
  },

  PLCMT_MC_CAPRICORN: {
    key: 'PLCMT_MC_CAPRICORN',
    planet: 'MC',
    sign: 'CAPRICORN',
    title: 'Midheaven in Capricorn',
    core: `Your Midheaven in Capricorn means your career direction and public image are organized around mastery, enduring achievement, and the patient climb toward genuine authority. You're building a legacy that will outlast you through disciplined excellence and structural integrity.`,
    behavioral: `You pursue career goals with serious determination, build reputation through demonstrated competence and unwavering reliability, and achieve by earning every step rather than taking shortcuts. When you're working toward mastery, you're constructing something that will stand the test of time.`,
    friendship: `In professional networks, your Capricorn Midheaven reads as the authority others respect for competence and long-range judgment.`,
    romantic: `In partnership, your public discipline can show as a partner who builds security through commitment, structure, and earned trust.`,
    feed: `Your Midheaven carries Capricorn energy today. Public direction favors mastery, structure, and enduring achievement.`,
    sonic: `Your Capricorn Midheaven contributes austere melodic structure, authoritative harmonic foundations, and rhythm that builds with patient discipline. The sound of earned mastery and enduring achievement.`,
  },

  PLCMT_MC_AQUARIUS: {
    key: 'PLCMT_MC_AQUARIUS',
    planet: 'MC',
    sign: 'AQUARIUS',
    title: 'Midheaven in Aquarius',
    core: `Your Midheaven in Aquarius means your career direction and public image are organized around innovation, collective contribution, and the courage to work outside conventional systems. You're building a legacy through original thinking, technological advancement, or social reform that benefits the many rather than the few.`,
    behavioral: `You pursue career goals through unconventional methods, build reputation through breakthrough ideas and principled independence, and achieve by refusing to conform to industry norms that don't serve progress. When you're working toward your calling, you're building the future rather than perfecting the present.`,
    friendship: `In professional networks, your Aquarius Midheaven reads as the innovator who challenges norms in service of collective progress.`,
    romantic: `In partnership, your public independence can show as a partner who values freedom, principle, and shared ideals over convention.`,
    feed: `Your Midheaven carries Aquarius energy today. Public direction favors innovation, reform, and principled originality.`,
    sonic: `Your Aquarius Midheaven contributes unexpected melodic innovation, progressive harmonic structures, and rhythm that breaks conventional patterns. The sound of revolutionary achievement and intellectual authority.`,
  },

  PLCMT_MC_PISCES: {
    key: 'PLCMT_MC_PISCES',
    planet: 'MC',
    sign: 'PISCES',
    title: 'Midheaven in Pisces',
    core: `Your Midheaven in Pisces means your career direction and public image are organized around creative vision, compassionate service, and dissolving boundaries between self and collective need. You're building a legacy through art, healing, or work that serves something larger than individual ambition.`,
    behavioral: `You pursue career goals through intuitive navigation rather than strategic planning, build reputation by responding to unspoken needs, and achieve through surrendering to flow rather than forcing outcomes. When you're working toward your calling, you're channeling something beyond yourself.`,
    friendship: `In professional networks, your Pisces Midheaven reads as the empathic creative others turn to when the work needs soul as well as skill.`,
    romantic: `In partnership, your public sensitivity can show as a partner who seeks spiritual or artistic union beyond practical roles alone.`,
    feed: `Your Midheaven carries Pisces energy today. Public direction favors vision, compassion, and transcendent purpose.`,
    sonic: `Your Pisces Midheaven contributes dreamlike melodic vision, dissolving harmonic boundaries, and rhythm that flows without edges. The sound of transcendent purpose and compassionate achievement.`,
  },
};

export const IC_PLACEMENTS: Readonly<Record<string, PlanetInSignInsight>> = {
  PLCMT_IC_ARIES: {
    key: 'PLCMT_IC_ARIES',
    planet: 'IC',
    sign: 'ARIES',
    title: 'IC in Aries',
    core: `Your IC in Aries means your emotional foundation and sense of home are organized around independence, self-reliance, and the freedom to act without asking permission. Your roots are pioneering. You come from (or create) a foundation of courage and self-determination.`,
    behavioral: `You create sanctuary through space to move freely, process emotions through physical action, and need your private life to support autonomy. When you're at home, you're recharging your capacity for independent action, home is where you remember you don't need anyone's permission.`,
    friendship: `In private life, your Aries IC favors friends who respect your need for space and direct honesty without emotional games.`,
    romantic: `In intimacy, your roots show as a partner who needs home to feel like a base camp for independence, not a cage.`,
    feed: `Your IC carries Aries energy today. Private foundation favors autonomy, courage, and self-reliant rest.`,
    sonic: `Your Aries IC contributes bold foundational rhythm, bright interior energy, and the sound of self-reliant emotional grounding. What safety sounds like when it's built on courage.`,
  },

  PLCMT_IC_TAURUS: {
    key: 'PLCMT_IC_TAURUS',
    planet: 'IC',
    sign: 'TAURUS',
    title: 'IC in Taurus',
    core: `Your IC in Taurus means your emotional foundation and sense of home are organized around physical comfort, material security, and sensory pleasure. Your roots are grounded. You come from (or create) a foundation of embodied stability and the right to rest.`,
    behavioral: `You create sanctuary through beautiful spaces and physical comfort, process emotions through your body and senses, and need your private life to be a place of reliable pleasure. When you're at home, you're restoring your capacity for sensory presence, home is where your body can finally relax.`,
    friendship: `In private life, your Taurus IC favors friends who share meals, comfort, and unhurried presence.`,
    romantic: `In intimacy, your roots show as a partner who builds safety through touch, consistency, and tangible care.`,
    feed: `Your IC carries Taurus energy today. Private foundation favors comfort, rest, and embodied stability.`,
    sonic: `Your Taurus IC contributes rich harmonic grounding, warm melodic comfort, and rhythm that is slow and embodied. The sound of physical safety and sensory foundation.`,
  },

  PLCMT_IC_GEMINI: {
    key: 'PLCMT_IC_GEMINI',
    planet: 'IC',
    sign: 'GEMINI',
    title: 'IC in Gemini',
    core: `Your IC in Gemini means your emotional foundation and sense of home are organized around mental stimulation, variety, and the freedom to stay curious. Your roots are intellectual. You come from (or create) a foundation of learning, communication, and mental agility.`,
    behavioral: `You create sanctuary through books, conversation, and access to information, process emotions by talking them through or writing them out, and need your private life to keep your mind engaged. When you're at home, you're recharging your mental batteries, home is where you can think freely without judgment.`,
    friendship: `In private life, your Gemini IC favors friends who talk, text, and keep your inner world mentally alive.`,
    romantic: `In intimacy, your roots show as a partner who needs home to be a place for conversation and curious exchange.`,
    feed: `Your IC carries Gemini energy today. Private foundation favors mental stimulation and free thinking.`,
    sonic: `Your Gemini IC contributes nimble interior melody, airy harmonic foundation, and rhythm that is conversational and light. The sound of mental sanctuary and intellectual grounding.`,
  },

  PLCMT_IC_CANCER: {
    key: 'PLCMT_IC_CANCER',
    planet: 'IC',
    sign: 'CANCER',
    title: 'IC in Cancer',
    core: `Your IC in Cancer means your emotional foundation and sense of home are organized around nurturing, emotional safety, and the deep need to belong. Your roots are tender. You come from (or create) a foundation of care, protection, and the right to feel without censorship.`,
    behavioral: `You create sanctuary through emotional warmth and protective privacy, process emotions through feeling them fully in safe containers, and need your private life to be a space where vulnerability is honored. When you're at home, you're restoring your capacity for emotional openness, home is where you can cry, rage, or melt without explanation.`,
    friendship: `In private life, your Cancer IC favors friends who feel like family and honor emotional truth.`,
    romantic: `In intimacy, your roots show as a partner who needs home to be emotionally safe and deeply belonging.`,
    feed: `Your IC carries Cancer energy today. Private foundation favors nurture, protection, and emotional honesty.`,
    sonic: `Your Cancer IC contributes flowing emotional depth, warm harmonic shelter, and rhythm that ebbs and flows with feeling. The sound of emotional sanctuary and nurturing foundation.`,
  },

  PLCMT_IC_LEO: {
    key: 'PLCMT_IC_LEO',
    planet: 'IC',
    sign: 'LEO',
    title: 'IC in Leo',
    core: `Your IC in Leo means your emotional foundation and sense of home are organized around creative self-expression, playful joy, and the right to take up space. Your roots are radiant. You come from (or create) a foundation of celebration, dignity, and the freedom to shine in private.`,
    behavioral: `You create sanctuary through beauty, drama, and permission to be yourself fully, process emotions through creative expression and play, and need your private life to honor your specialness. When you're at home, you're recharging your inner light, home is where you can be as big as you actually are.`,
    friendship: `In private life, your Leo IC favors friends who celebrate you and make private life feel special.`,
    romantic: `In intimacy, your roots show as a partner who needs home to feel warm, proud, and creatively alive.`,
    feed: `Your IC carries Leo energy today. Private foundation favors joy, dignity, and expressive rest.`,
    sonic: `Your Leo IC contributes radiant interior warmth, generous harmonic foundation, and rhythm that celebrates self. The sound of dignified sanctuary and creative grounding.`,
  },

  PLCMT_IC_VIRGO: {
    key: 'PLCMT_IC_VIRGO',
    planet: 'IC',
    sign: 'VIRGO',
    title: 'IC in Virgo',
    core: `Your IC in Virgo means your emotional foundation and sense of home are organized around order, useful routine, and the right to perfect your private life. Your roots are practical. You come from (or create) a foundation of service, competence, and the belief that care is demonstrated through helpful action.`,
    behavioral: `You create sanctuary through clean organization and useful rituals, process emotions by analyzing them and finding practical solutions, and need your private life to run efficiently. When you're at home, you're restoring your capacity for precision, home is where everything has its place and purpose.`,
    friendship: `In private life, your Virgo IC favors friends who respect routines and show care through practical help.`,
    romantic: `In intimacy, your roots show as a partner who restores safety through order, usefulness, and quiet competence.`,
    feed: `Your IC carries Virgo energy today. Private foundation favors order, craft, and practical care.`,
    sonic: `Your Virgo IC contributes precise interior rhythm, refined harmonic order, and melody that is careful and measured. The sound of organized sanctuary and practical foundation.`,
  },

  PLCMT_IC_LIBRA: {
    key: 'PLCMT_IC_LIBRA',
    planet: 'IC',
    sign: 'LIBRA',
    title: 'IC in Libra',
    core: `Your IC in Libra means your emotional foundation and sense of home are organized around harmony, aesthetic beauty, and the presence of partnership or balanced relationship. Your roots are refined. You come from (or create) a foundation of grace, fairness, and relational equity.`,
    behavioral: `You create sanctuary through beautiful environments and the presence of valued others, process emotions through dialogue and seeking balance, and need your private life to feel aesthetically pleasing and relationally fair. When you're at home, you're restoring your sense of harmony, home is where everything is in right proportion.`,
    friendship: `In private life, your Libra IC favors friends who bring grace, fairness, and beautiful shared space.`,
    romantic: `In intimacy, your roots show as a partner who needs home to feel balanced, lovely, and mutually considerate.`,
    feed: `Your IC carries Libra energy today. Private foundation favors harmony, beauty, and relational balance.`,
    sonic: `Your Libra IC contributes balanced harmonic foundations, graceful interior melody, and rhythm that seeks equilibrium. The sound of harmonious emotional grounding and aesthetic sanctuary.`,
  },

  PLCMT_IC_SCORPIO: {
    key: 'PLCMT_IC_SCORPIO',
    planet: 'IC',
    sign: 'SCORPIO',
    title: 'IC in Scorpio',
    core: `Your IC in Scorpio means your emotional foundation and sense of home are organized around intensity, psychological depth, and the right to privacy around transformation. Your roots are powerful. You come from (or create) a foundation of emotional extremity and the capacity to face darkness.`,
    behavioral: `You create sanctuary through complete privacy and permission to feel everything without censoring, process emotions through diving into depth rather than skating surfaces, and need your private life to be completely protected from intrusion. When you're at home, you're regenerating your capacity for intensity, home is where you can be as deep as you need to be.`,
    friendship: `In private life, your Scorpio IC favors friends who can hold depth, secrecy, and emotional truth without flinching.`,
    romantic: `In intimacy, your roots show as a partner who needs home to be a sealed container for transformation and trust.`,
    feed: `Your IC carries Scorpio energy today. Private foundation favors depth, privacy, and regenerative feeling.`,
    sonic: `Your Scorpio IC contributes dark harmonic depth, intense foundational power, and rhythm that pulses with emotional extremity. The sound of profound privacy and transformative emotional grounding.`,
  },

  PLCMT_IC_SAGITTARIUS: {
    key: 'PLCMT_IC_SAGITTARIUS',
    planet: 'IC',
    sign: 'SAGITTARIUS',
    title: 'IC in Sagittarius',
    core: `Your IC in Sagittarius means your emotional foundation and sense of home are organized around freedom, philosophical meaning, and the space to explore without constraint. Your roots are adventurous. You come from (or create) a foundation of optimism, truth-seeking, and the belief that home is wherever you're free to roam.`,
    behavioral: `You create sanctuary through open space and permission to follow curiosity, process emotions through finding their larger meaning, and need your private life to support expansion rather than containment. When you're at home, you're recharging your sense of possibility, home is where the doors and windows are always open.`,
    friendship: `In private life, your Sagittarius IC favors friends who widen your world and honor your need for room to roam.`,
    romantic: `In intimacy, your roots show as a partner who needs home to feel spacious, honest, and oriented toward meaning.`,
    feed: `Your IC carries Sagittarius energy today. Private foundation favors freedom, truth, and expansive rest.`,
    sonic: `Your Sagittarius IC contributes expansive interior range, optimistic harmonic foundation, and rhythm that gallops freely. The sound of adventurous sanctuary and philosophical grounding.`,
  },

  PLCMT_IC_CAPRICORN: {
    key: 'PLCMT_IC_CAPRICORN',
    planet: 'IC',
    sign: 'CAPRICORN',
    title: 'IC in Capricorn',
    core: `Your IC in Capricorn means your emotional foundation and sense of home are organized around structure, self-sufficiency, and the right to build something enduring in your private life. Your roots are disciplined. You come from (or create) a foundation of responsibility, maturity, and the belief that emotional stability is earned through effort.`,
    behavioral: `You create sanctuary through reliable routines and self-sufficient systems, process emotions by taking responsibility for managing them, and need your private life to be well-structured and under your control. When you're at home, you're recharging your capacity for discipline, home is where you can maintain order without external demands.`,
    friendship: `In private life, your Capricorn IC favors friends who respect boundaries, reliability, and mature steadiness.`,
    romantic: `In intimacy, your roots show as a partner who builds safety through structure, duty, and earned trust over time.`,
    feed: `Your IC carries Capricorn energy today. Private foundation favors structure, discipline, and self-sufficiency.`,
    sonic: `Your Capricorn IC contributes austere foundational structure, disciplined harmonic grounding, and rhythm that is controlled and measured. The sound of self-sufficient sanctuary and earned emotional stability.`,
  },

  PLCMT_IC_AQUARIUS: {
    key: 'PLCMT_IC_AQUARIUS',
    planet: 'IC',
    sign: 'AQUARIUS',
    title: 'IC in Aquarius',
    core: `Your IC in Aquarius means your emotional foundation and sense of home are organized around intellectual freedom, unconventional family structures, and the right to be different in private. Your roots are innovative. You come from (or create) a foundation of independence, progressive values, and the belief that home should support your uniqueness.`,
    behavioral: `You create sanctuary through space that honors your individuality, process emotions by detaching and analyzing them objectively, and need your private life to be free from conventional expectations. When you're at home, you're recharging your capacity for originality, home is where you don't have to explain why you're wired differently.`,
    friendship: `In private life, your Aquarius IC favors friends who accept your difference and keep expectations unconventional.`,
    romantic: `In intimacy, your roots show as a partner who needs home to honor freedom, principle, and nonconformity.`,
    feed: `Your IC carries Aquarius energy today. Private foundation favors originality, detachment, and intellectual freedom.`,
    sonic: `Your Aquarius IC contributes unexpected harmonic foundations, innovative interior rhythm, and melody that is both detached and unique. The sound of unconventional sanctuary and intellectual grounding.`,
  },

  PLCMT_IC_PISCES: {
    key: 'PLCMT_IC_PISCES',
    planet: 'IC',
    sign: 'PISCES',
    title: 'IC in Pisces',
    core: `Your IC in Pisces means your emotional foundation and sense of home are organized around imaginative escape, spiritual connection, and dissolving into something larger than yourself. Your roots are mystical. You come from (or create) a foundation of dreams, compassion, and the belief that home is where boundaries can safely dissolve.`,
    behavioral: `You create sanctuary through art, music, or spiritual practice, process emotions by letting them wash through you without resistance, and need your private life to be a refuge from harsh reality. When you're at home, you're restoring your capacity for transcendence, home is where you can disappear into the infinite.`,
    friendship: `In private life, your Pisces IC favors friends who honor sensitivity, imagination, and compassionate retreat.`,
    romantic: `In intimacy, your roots show as a partner who needs home to feel spiritually soft and emotionally permeable.`,
    feed: `Your IC carries Pisces energy today. Private foundation favors dreams, compassion, and gentle dissolution.`,
    sonic: `Your Pisces IC contributes dreamlike harmonic dissolve, ethereal interior flow, and rhythm that moves like water without edges. The sound of mystical sanctuary and boundless emotional foundation.`,
  },
};

export const ANGLE_PLACEMENTS: Readonly<Record<string, PlanetInSignInsight>> = {
  ...ASCENDANT_PLACEMENTS,
  ...MIDHEAVEN_PLACEMENTS,
  ...IC_PLACEMENTS,
};
