/**
 * Astradio Insight Library: Planet Archetypes
 *
 * 10 standalone planet archetypes: Sun, Moon, Mercury, Venus, Mars, 
 * Jupiter, Saturn, Uranus, Neptune, Pluto
 *
 * Keys: PLANET_{BODY} (e.g., PLANET_SUN, PLANET_MOON)
 * Place at: vnext/projection/insight-library/insight-library-planets.ts
 *
 * v2 Phase 5A: Foundational planet meanings authored as standalone archetypes
 * describing singular chart contexts (A), not cross-chart comparisons (A + B).
 * Each entry contains 6 natal fields only. No synastry fields, as these describe
 * what a planet means in a chart rather than between charts.
 *
 * Authoring rule: core and behavioral fields use chart-bearer attribution 
 * ("the person," "this chart-bearer") and avoid partnership-coded language.
 * Role-specific framing lives in friendship and romantic fields where contextually
 * licensed.
 */

import type { PlanetInsight } from './insight-library-types';

export const PLANET_INSIGHTS: Readonly<Record<string, PlanetInsight>> = {

  PLANET_SUN: {
    key: 'PLANET_SUN',
    planet: 'SUN',
    title: 'The Sun',
    core: `The Sun is the principle of conscious identity, the seat of willful self-direction, and the organizing center of the personality. It represents who the person knows themselves to be when they are asked to define themselves, what they identify with as their essential nature, and the capacity to direct the self purposefully through the world. The Sun is not the whole self. It is the part of the self that can observe itself, name itself, and choose how to express itself. In the natal chart, the Sun's placement describes how this person experiences their own agency, what they feel is worth pursuing, and the particular quality of presence they bring when they are being most genuinely themselves. Psychologically, the Sun is the ego-function: not the inflated sense of self that the word "ego" sometimes carries in common usage, but the executive function of consciousness that makes coherent selfhood possible. Where the Moon responds instinctively and Mars acts impulsively, the Sun decides. Where Venus attracts and Jupiter expands, the Sun centers. The Sun is the "I" that speaks when the person says "I want," "I choose," "I am." It is the capacity to hold purpose across time, to remain recognizably oneself through changing circumstances, and to act from a stable sense of what matters. The Sun's dignity is found not in dominance but in clarity: the capacity to know what one stands for and to stand there without apology or performance.`,
    behavioral: `The Sun's psychological expression is the capacity for self-authorship: the ability to take responsibility for one's choices, to direct one's life according to internally generated purpose rather than purely reactive response to external pressure, and to maintain a coherent sense of identity across different contexts and relationships. This is the part of the psyche that can say "this is who I am" and mean it, that can set a goal and pursue it across years, that can choose a direction and commit to it even when the initial enthusiasm fades. Behaviorally, the Sun shows in how the person makes decisions, what they are willing to be publicly known for, and how they respond when their sense of self is challenged or affirmed. A person with a strongly expressed Sun takes up space without apology, makes their preferences known, and directs themselves with confidence. A person with a more quietly expressed Sun may be less visible in group settings but is no less purposeful. They simply express their will more selectively. The Sun's pathology, when it occurs, is inflation: the mistaking of the ego's perspective for the totality of reality, the refusal to be questioned or to admit uncertainty, the equation of selfhood with dominance. But at its best, the Sun is the capacity for genuine individuation: becoming who you actually are rather than who others expect or who circumstances would shape you to be. The Sun is what allows a person to say "I did this" and "I chose that" and mean it fully, accepting both the credit and the consequence.`,
    friendship: `In friendship contexts, the Sun describes how this person shows up as themselves in the bond. What they contribute when they are being genuine rather than performing a role. A person with a strong solar presence in friendship is the one who sets the tone, who decides what the group will do, who takes responsibility for outcomes. They are the friend who says "let's do this" and means it, who follows through on commitments, who can be counted on to be recognizably themselves rather than shifting to accommodate the room. The solar friend is not necessarily the loudest or most socially visible, but they are the one whose sense of self remains stable across different social contexts. The friendship serves them best when it allows them to express their will without having to suppress it for the sake of harmony, and when it receives their directional energy as a contribution rather than as dominance. Friendships where the Sun is honored are marked by mutual respect for each person's autonomy, the capacity to disagree without threatening the bond, and the freedom to pursue individual purposes without the friendship demanding total convergence.`,
    romantic: `In romantic contexts, the Sun describes what this person needs in order to remain themselves within the partnership. A person's Sun does not compromise easily, because compromise at the level of core identity is not sustainable. The Sun needs to be seen, to be received as it actually is rather than as the partner wishes it to be, and to have space within the relationship to continue directing itself according to its own purpose. The partner who honors the Sun receives this person's will without trying to reshape it, allows them to pursue their own goals even when those goals are not shared, and treats their sense of self as sovereign rather than as negotiable. Romantic relationships that suppress the Sun produce resentment over time, because the person experiences the relationship as requiring them to be less than themselves. The Sun in romance is not selfish. It is the part of the person that maintains integrity, that refuses to disappear into fusion, that insists on remaining a distinct self even in deep intimacy. Partnerships that work with the Sun honor both people's autonomy, create space for individual purpose alongside shared purpose, and treat each person's identity as a foundation rather than as an obstacle.`,
    feed: `The Sun is active in the current sky. How this person understands themselves, what they identify with, and the direction they are choosing to move in are all being illuminated right now. This is a window for greater clarity about who they are and what they are here to do.`,
    sonic: `The Sun contributes a clear, forward-moving tonal center, a warm and steady melodic voice, and a consistent rhythmic pulse that holds the composition together. The harmonic language is major, resolved, affirmative, confident, with enough directional momentum that the music knows where it is going and arrives there with purpose. The Sun's rhythm is regular and organized, a steady beat that other elements can rely on. The melodic statements are singable and memorable, not ornate or elusive. Listen for the quality of music where the central theme is clear, where the harmonic motion resolves rather than suspends, where the rhythm provides a foundation that other voices can move against. The Sun's sonic character is presence without apology, clarity without harshness, purpose without rigidity. It is the part of the musical texture that says "this is what we are doing, and we are doing it with confidence."`,
  },

  PLANET_MOON: {
    key: 'PLANET_MOON',
    planet: 'MOON',
    title: 'The Moon',
    core: `The Moon is the principle of emotional instinct, interior need, and the body's immediate, pre-cognitive responses to the world. It governs what the person requires in order to feel safe, what they return to when they need emotional restoration, and the particular quality of care and nourishment their nervous system recognizes as home. The Moon is not reason or choice. It is the part of the self that knows what it feels before it knows why it feels that way, that reacts to safety and threat at the level of the body rather than through conscious assessment, and that carries the archive of every moment when the person felt held or abandoned, met or unseen. In the natal chart, the Moon's placement describes the person's attachment style, their capacity for emotional regulation, and the specific conditions under which they can relax their vigilance and simply be. Psychologically, the Moon is the affect system and the attachment system working together: it is what generates the emotional signal that tells the person whether a situation is safe or dangerous, familiar or foreign, nourishing or depleting, and it is what organizes the person's strategies for seeking care and avoiding abandonment. The Moon does not think. It feels, it remembers, it responds. It is the part of the psyche that cycles through moods without consulting the conscious will, that pulls toward or away from people and situations based on visceral recognition rather than rational assessment, and that holds the record of what worked and what didn't work when the person was most vulnerable.`,
    behavioral: `The Moon's psychological expression is the capacity for emotional authenticity and the struggle for emotional regulation. A person with a well-integrated Moon can feel what they feel without being controlled by it, can name their emotional state accurately, and can communicate needs without shame or aggression. A person with a more defended Moon may suppress feeling entirely, may experience emotions as overwhelming and uncontrollable, or may swing between emotional flooding and emotional shutdown. Behaviorally, the Moon shows in how the person responds to stress, what they do when they are hurt or frightened, and what they require in order to feel emotionally restored. The Moon is visible in the person's rhythms: how they move between engagement and withdrawal, how they manage transitions, how they respond to change and instability. It is also visible in what they seek when they are overwhelmed, whether they reach for solitude or connection, whether they process through talking or through silence, whether they need physical comfort or emotional witness. The Moon's pathology, when it occurs, is emotional reactivity so intense it bypasses the reflective mind entirely, or emotional suppression so complete that the person loses access to their own interior life. But at its best, the Moon is the capacity for genuine emotional intimacy: the ability to be with one's own feelings without judgment, to communicate emotional need without performance, and to receive care without having to earn it through perfect behavior.`,
    friendship: `In friendship contexts, the Moon describes what this person needs in order to feel emotionally safe in the bond. A person with a prominent Moon in friendship is the one who creates the emotional atmosphere, who notices when the group's mood has shifted, who checks in and follows up. They are the friend who remembers what you said three months ago about something that mattered, who can read your emotional state from your voice before you've said anything direct, who shows up when you're going through difficulty without needing to be asked. The lunar friend needs the friendship to feel emotionally real, not performative, not transactional, but genuinely caring. They need to know that the bond can hold difficulty, that they can be sad or scared or struggling without the friendship evaporating, and that care is reciprocal rather than one-directional. Friendships where the Moon is honored are marked by genuine emotional availability, the capacity to witness each other's interior lives without judgment, and the safety to be vulnerable without that vulnerability being weaponized later.`,
    romantic: `In romantic contexts, the Moon describes what this person needs in order to feel emotionally nourished and safe within the partnership. The Moon does not negotiate its needs easily, because emotional safety is not a luxury. It is a baseline requirement for the nervous system to relax. A person's Moon needs to be met where it actually is rather than where the partner thinks it should be, and it needs care that is consistent rather than intermittent. The partner who honors the Moon notices this person's emotional rhythms, responds to small signals of distress before they escalate, and creates conditions where this person can be emotionally unguarded without risking rejection or criticism. Romantic relationships that ignore the Moon produce chronic emotional dysregulation: the person feels perpetually on alert, unable to rest, because the partnership does not feel safe at the nervous system level. The Moon in romance is not needy. It is the part of the person that knows what home feels like and insists on finding it. Partnerships that work with the Moon create genuine emotional sanctuary, honor rhythms of closeness and distance, and treat each person's interior emotional life as worthy of care rather than as a problem to manage.`,
    feed: `The Moon is active in the current sky. How this person feels, what they need emotionally, and the conditions that allow them to feel safe are all being touched right now. This is a window for greater awareness of their interior emotional life and what genuinely nourishes them.`,
    sonic: `The Moon contributes modal harmonic ambiguity, a breathing rhythmic quality that ebbs and flows like tides, and melodic phrases that cycle and return rather than progressing linearly. The harmonic language is not resolved. It dwells in suspended chords, in unresolved tensions, in emotional colors that shift between major and minor without settling. The Moon's rhythm is organic, not metronomic: it breathes, it hesitates, it speeds and slows according to an internal pulse that is felt rather than counted. The melodic content is repetitive and memory-driven, phrases that return with small variations, themes that circle back rather than moving forward into new territory. Listen for the quality of music where the emotional register is more important than the structural progression, where the sound feels like it is moving through interior space rather than across physical distance, where the harmonic ambiguity creates a quality of longing or nostalgia or quiet comfort. The Moon's sonic character is receptivity, interiority, and the emotional undertow that runs beneath the surface of more assertive elements.`,
  },

  PLANET_MERCURY: {
    key: 'PLANET_MERCURY',
    planet: 'MERCURY',
    title: 'Mercury',
    core: `Mercury is the principle of perception, communication, and the connective intelligence that makes sense of information. It governs how the person takes in data from the world, how they organize that data into patterns and meaning, and how they translate their internal understanding into language that others can receive. Mercury is the cognitive function: not reason in the deep philosophical sense, but the practical, everyday intelligence that allows the person to learn, to adapt, to notice, to name, to explain. In the natal chart, Mercury's placement describes the person's learning style, their conversational rhythm, the particular quality of their curiosity, and the speed and flexibility of their mental processing. Psychologically, Mercury is the mediating function between raw perception and coherent thought. It is what converts the blur of sensory input into recognizable categories, what links one idea to another, what notices patterns and makes analogies. Mercury is not wisdom. It is cleverness, agility, the capacity to move quickly between different frames of reference and to find language for experiences that do not yet have names. Where the Moon feels and the Sun decides, Mercury observes, categorizes, and communicates. It is the voice in the mind that narrates experience as it happens, the translator that converts interior states into shareable language, and the detector of patterns that others might miss.`,
    behavioral: `Mercury's psychological expression is the capacity for articulation and the speed of mental processing. A person with a well-developed Mercury can think on their feet, can explain complex ideas in accessible language, and can shift between different conceptual frameworks without losing the thread. A person with a more challenged Mercury may struggle to find words for what they know, may process information more slowly but more thoroughly, or may think in ways that do not translate easily into conventional language. Behaviorally, Mercury shows in how the person learns, how they communicate, and how they engage with new information. It is visible in whether they ask questions or make statements, whether they process through talking or through writing, whether they learn through reading or through doing. Mercury also governs the person's relationship to language itself: whether they use words precisely or loosely, whether they speak to clarify or to persuade, whether they value wit or sincerity. The pathology of Mercury, when it occurs, is either mental rigidity, the inability to revise a position when new information arrives, or mental chaos, where thoughts scatter in too many directions to be useful. But at its best, Mercury is the capacity for genuine curiosity: the willingness to ask real questions, to listen to answers that complicate what was previously understood, and to communicate in ways that genuinely reach the other person rather than simply performing intelligence.`,
    friendship: `In friendship contexts, Mercury describes how this person engages intellectually and conversationally in the bond. A person with a strong Mercurial presence in friendship is the one who keeps the conversation moving, who asks good questions, who makes connections between what one person said and what another said three topics ago. They are the friend who introduces new ideas, who shares articles and podcasts, who can explain complicated things in ways that make them suddenly clear. The Mercurial friend needs the friendship to be mentally engaging, not necessarily intellectual in a formal sense, but genuinely interesting, with real exchange of ideas rather than purely social pleasantries. They need to be able to talk things through, to think out loud, to process verbally. Friendships where Mercury is honored are marked by good conversation, mutual curiosity, and the freedom to disagree without the friendship interpreting disagreement as rejection. The Mercurial friend can be restless in friendships that are emotionally rich but intellectually static, and they thrive in bonds where learning and discovery happen together.`,
    romantic: `In romantic contexts, Mercury describes what this person needs in order to stay mentally engaged within the partnership. Mercury does not sustain romantic interest through chemistry or emotional resonance alone. It needs conversation that remains interesting, the capacity to learn from the partner, and mental exchange that does not flatten into routine. A person's Mercury needs to be met by a partner who can actually engage with their ideas, who listens not just to be supportive but to genuinely think alongside them, and who brings their own intellectual substance to the relationship. The partner who honors Mercury treats this person's curiosity as valuable, responds to their questions with real answers rather than deflection, and participates in the ongoing project of making sense of the world together. Romantic relationships that starve Mercury produce boredom and restlessness, because the person experiences the partnership as intellectually stagnant. The Mercury in romance is not cold or detached. It is the part of the person that stays interested by continuing to learn, that deepens connection through understanding, and that treats conversation as an essential form of intimacy. Partnerships that work with Mercury create space for ongoing intellectual exchange, honor each person's way of thinking even when they differ, and treat curiosity as a shared resource rather than as a distraction from emotional closeness.`,
    feed: `Mercury is active in the current sky. How this person perceives, processes information, and communicates what they understand are all being activated right now. This is a window for greater mental clarity and more effective articulation of what they know.`,
    sonic: `Mercury contributes rapid, articulate melodic phrases, quick rhythmic motion, and harmonic movement that shifts keys and modes with agility. The melodic lines are conversational, questions and answers, call and response, motifs that pass between voices and transform as they go. The rhythm is quick and light, not heavy or sustained, with a quality of forward momentum that keeps the music moving rather than dwelling. The harmonic language is restless, modulating frequently, visiting different tonal centers without committing to any one for long. Mercury's sound is bright and clear, not thick or weighted, with a transparency that allows every note to be heard distinctly. Listen for the quality of music where ideas are being exchanged rather than stated, where the melodic content feels like it is thinking out loud, where the harmonic motion creates a sense of intellectual curiosity and ongoing discovery. Mercury's sonic character is wit, agility, and the pleasure of pattern recognition happening in real time.`,
  },

  PLANET_VENUS: {
    key: 'PLANET_VENUS',
    planet: 'VENUS',
    title: 'Venus',
    core: `Venus is the principle of value, attraction, and the capacity to draw beauty and connection toward oneself. It governs what the person finds desirable, what they are willing to reach for or receive, and the particular quality of aesthetic and relational attunement that allows them to recognize what is worth loving. Venus is not just romantic love. It is the valuing function itself, the part of the psyche that makes judgments about worth, beauty, pleasure, and connection. In the natal chart, Venus's placement describes what the person experiences as beautiful, what they seek in relationship, and the style of care and affection they recognize as genuine. Psychologically, Venus is the magnetic function: it does not pursue directly like Mars, but it attracts, it draws toward itself, it creates the conditions under which others want to move closer. Venus is also the relational attunement system, the part of the psyche that registers resonance and dissonance with others, that knows when harmony is present and when friction has entered the field. Where the Sun asserts and Mars acts, Venus receives, responds, and values. It is the capacity to appreciate beauty for its own sake, to give and receive affection without immediate transaction, and to create environments, physical, social, relational, that feel genuinely pleasant to inhabit.`,
    behavioral: `Venus's psychological expression is the capacity for aesthetic discernment and relational generosity. A person with a well-developed Venus knows what they like and why, can articulate their values without apology, and can create beauty in their immediate environment, whether through how they dress, how they arrange their living space, or how they curate their social world. A person with a more challenged Venus may struggle to identify what they actually want versus what they think they should want, may give care compulsively in order to earn affection, or may withhold care as a form of self-protection. Behaviorally, Venus shows in what the person surrounds themselves with, what they spend money on, and how they engage in relationships. It is visible in whether they initiate affection easily or wait to be approached, whether they express appreciation directly or show care through action, whether they prioritize harmony or authenticity when the two are in conflict. The pathology of Venus, when it occurs, is either shallow aestheticism, valuing surface beauty while ignoring substance, or relational accommodation so complete that the person loses track of their own preferences. But at its best, Venus is the capacity for genuine appreciation: the ability to love what is actually there rather than what one wishes were there, to create beauty that serves life rather than escaping it, and to give care that is genuine rather than strategic.`,
    friendship: `In friendship contexts, Venus describes what this person values in the bond and how they express care. A person with a strong Venusian presence in friendship is the one who creates warmth, who notices what people enjoy and provides it, who makes the group feel pleasant to be in. They are the friend who remembers birthdays, who brings thoughtful gifts, who makes spaces beautiful and welcoming. The Venusian friend needs the friendship to feel mutually appreciative, not transactional in a cold sense, but genuinely reciprocal, where care is both given and received. They need to know that they are valued for who they are, not just for what they provide, and that affection is freely offered rather than withheld until earned. Friendships where Venus is honored are marked by genuine mutual appreciation, shared aesthetic pleasure, and the freedom to express affection without it being misinterpreted as need or weakness. The Venusian friend can be hurt by friendships that take their care for granted, and they thrive in bonds where generosity is mutual and beauty is created together.`,
    romantic: `In romantic contexts, Venus describes what this person needs in order to feel loved and how they express love in return. Venus does not demand or chase. It receives, it welcomes, it creates conditions where love can be given freely. A person's Venus needs to be appreciated for what it actually offers rather than for what the partner wishes it would offer, and it needs affection that is consistent rather than intermittent. The partner who honors Venus treats this person's values as legitimate even when they differ, expresses appreciation directly rather than assuming it is understood, and participates in creating shared beauty, whether through physical environment, shared experiences, or the aesthetic of the relationship itself. Romantic relationships that ignore Venus produce a quality of emotional thinness, because the person feels unappreciated at the level of what they value most. The Venus in romance is not shallow or materialistic. It is the part of the person that knows love through beauty, that deepens connection through shared pleasure, and that treats affection as a generative resource rather than as a scarce commodity. Partnerships that work with Venus honor both people's values, create environments that feel genuinely pleasant to inhabit, and treat beauty and care as legitimate forms of intimacy rather than as distractions from more serious connection.`,
    feed: `Venus is active in the current sky. What this person values, what they find beautiful, and how they give and receive care are all being touched right now. This is a window for greater clarity about what genuinely matters to them and how they want to be loved.`,
    sonic: `Venus contributes rich consonant harmony, careful voice leading, and melodic lines that are singable, graceful, and aesthetically pleasing. The harmonic language is warm and colorful, major tonality with added sixths and sevenths, resolved chords with enough complexity to feel luxurious rather than simple. The rhythm flows smoothly, without harsh accents or abrupt changes, creating a sense of ease and grace. The melodic phrases are beautiful for their own sake, not just as vehicles for harmonic progression. They linger, they shape themselves carefully, they arrive somewhere pleasant. Listen for the quality of music where the aesthetic pleasure is immediate and unforced, where the sound feels like it was made to be enjoyed, where the harmonic richness and melodic warmth combine to create something genuinely beautiful. Venus's sonic character is sensory pleasure, relational warmth, and the experience of being in the presence of something that simply feels good.`,
  },

  PLANET_MARS: {
    key: 'PLANET_MARS',
    planet: 'MARS',
    title: 'Mars',
    core: `Mars is the principle of drive, assertion, and the force that converts intention into action. It governs how the person pursues what they want, how they defend what they value, and the particular quality of energy they bring when they are moving toward desire or away from threat. Mars is not aggression for its own sake. It is the warrior archetype in its essential form: the capacity to act decisively, to engage with conflict when necessary, to claim space and resources, and to protect what matters. In the natal chart, Mars's placement describes the person's action style, their relationship to anger and assertiveness, and the conditions under which their drive is accessible versus suppressed. Psychologically, Mars is the mobilizing function: it is what gets the person out of bed in the morning, what provides the physical and emotional energy to pursue goals, and what responds to obstacles by pushing through rather than giving up. Where Venus attracts and the Moon responds, Mars initiates, pursues, and asserts. It is the part of the psyche that does not wait for permission, that moves toward what it wants with directness, and that can engage in productive conflict without collapsing into either aggression or avoidance. Mars is also the survival instinct in its most basic form: the fight-or-flight response, the capacity to defend oneself when threatened, and the willingness to use force when gentler approaches have failed.`,
    behavioral: `Mars's psychological expression is the capacity for healthy assertion and the struggle with anger. A person with a well-integrated Mars can pursue what they want without guilt or hesitation, can express anger cleanly when it arises, and can engage in conflict productively rather than destructively. A person with a more suppressed Mars may avoid conflict entirely, may experience anger as overwhelming and dangerous, or may express anger indirectly through passive resistance or sudden explosions. Behaviorally, Mars shows in how the person competes, how they respond to frustration, and what they do when someone crosses a boundary. It is visible in whether they pursue goals actively or wait for opportunities to arrive, whether they state their wants directly or hint at them obliquely, whether they defend themselves immediately or absorb mistreatment until it becomes unbearable. The pathology of Mars, when it occurs, is either unchecked aggression, anger that is not modulated by empathy or consequence, or total suppression, where the person's drive is so inhibited that they become passive and resentful. But at its best, Mars is the capacity for genuine courage: the willingness to act even when success is uncertain, to stand up for what matters even when it is costly, and to use force in service of protection and pursuit rather than as dominance or revenge.`,
    friendship: `In friendship contexts, Mars describes how this person shows up when action is required and how they handle conflict in the bond. A person with a strong Martian presence in friendship is the one who makes things happen, who takes the lead on shared projects, who defends the group when it is challenged. They are the friend who will show up and help you move, who will confront someone who has hurt you, who takes action rather than endlessly discussing possibilities. The Martian friend needs the friendship to allow for direct engagement. They become frustrated in bonds that require constant emotional caution or that avoid conflict at all costs. They need to know that honest disagreement will not destroy the friendship, and that they can assert themselves without being labeled as aggressive or difficult. Friendships where Mars is honored are marked by mutual respect for each person's boundaries, the capacity to address problems directly rather than letting them fester, and the freedom to compete or challenge without it threatening the underlying bond. The Martian friend can be exhausting in friendships that require constant gentleness, and they thrive in bonds where energy and directness are valued.`,
    romantic: `In romantic contexts, Mars describes what this person needs in order to stay engaged and how they pursue what they want within the partnership. Mars does not sustain romantic interest through comfort alone. It needs challenge, pursuit, and the experience of genuine desire. A person's Mars needs to be able to assert itself without being pathologized, to express anger when it arises without the partner treating it as abandonment, and to pursue what it wants, sexually, professionally, recreationally, without the partnership demanding that all desire be channeled exclusively into the relationship. The partner who honors Mars receives this person's drive as vitality rather than as threat, allows them to disagree and compete without interpreting it as rejection, and participates in keeping the relationship energetically alive rather than letting it settle into passive coexistence. Romantic relationships that suppress Mars produce either resentment or deadness, because the person experiences the partnership as requiring them to become passive in order to be acceptable. The Mars in romance is not violent or domineering. It is the part of the person that stays alive by continuing to want, that deepens connection through honest engagement, and that treats desire as a legitimate force rather than as something to be managed or controlled. Partnerships that work with Mars create space for both people's drive, honor productive conflict as a form of intimacy, and treat assertion as a sign of engagement rather than as a threat to harmony.`,
    feed: `Mars is active in the current sky. How this person pursues what they want, how they defend what matters to them, and the quality of energy they have available for action are all being activated right now. This is a window for greater courage and more direct engagement with what needs to be done.`,
    sonic: `Mars contributes a driving, physical pulse, short incisive melodic gestures, and harmonic language that favors directional clarity over aesthetic dwelling. The rhythm is strong and emphatic, with heavy downbeats and a forward momentum that does not hesitate. The melodic content is declarative, short, forceful phrases that state rather than question, that move with purpose rather than lingering. The harmonic language is direct, often using power chords or open voicings that emphasize force over complexity. Mars's sound is cutting and immediate, not soft or blended, each element is clearly articulated, each attack is precise. Listen for the quality of music where the energy is physical and undeniable, where the drive forward is more important than the beauty of the sound, where the pulse creates a sense of unstoppable momentum. Mars's sonic character is assertion, physical energy, and the sound of something that will not be stopped.`,
  },

  PLANET_JUPITER: {
    key: 'PLANET_JUPITER',
    planet: 'JUPITER',
    title: 'Jupiter',
    core: `Jupiter is the principle of expansion, meaning-making, and the drive toward growth beyond current limits. It governs how the person seeks understanding, what they believe gives life meaning, and the particular quality of optimism or faith that allows them to reach for more than what is immediately visible. Jupiter is not naive positivity. It is the philosophical function, the part of the psyche that asks "what is this for?" and "what is possible here?" rather than simply accepting what is. In the natal chart, Jupiter's placement describes the person's relationship to belief, their capacity for generosity and abundance, and the domains of life where they naturally expand and take risks. Psychologically, Jupiter is the meaning-making function: it is what converts raw experience into narrative, what sees patterns across time and extrapolates future possibilities, and what provides the sense that life is moving toward something rather than simply happening randomly. Where Mercury observes and categorizes, Jupiter synthesizes and interprets. Where Saturn establishes limits, Jupiter pushes against them. Jupiter is the capacity to see potential where others see only what is, to believe that growth is possible even when current conditions are constrained, and to act from a sense of abundance rather than scarcity. It is also the social expansiveness that allows the person to be generous, to share what they have, and to create opportunities for others as well as for themselves.`,
    behavioral: `Jupiter's psychological expression is the capacity for optimism and the struggle with overreach. A person with a well-developed Jupiter can see possibilities without ignoring limitations, can take calculated risks, and can maintain faith in future growth even during difficult present circumstances. A person with a more challenged Jupiter may either suppress their expansive impulses entirely, becoming cautious and limited, or may expand recklessly, taking on more than they can sustain and creating chaos through overcommitment. Behaviorally, Jupiter shows in how the person approaches new opportunities, how generous they are with their resources, and whether they err on the side of saying yes or saying no. It is visible in what they believe about the world, whether they see it as fundamentally abundant or fundamentally scarce, whether they trust that things will work out or assume the worst, whether they take leaps of faith or demand guarantees before moving. The pathology of Jupiter, when it occurs, is either inflation. The belief that one is exempt from consequence, that limits do not apply, that expansion is always good. Or deflation, where the person's sense of possibility collapses entirely and they become resigned to limitation. But at its best, Jupiter is the capacity for genuine wisdom: the ability to see the bigger picture, to learn from experience without becoming cynical, and to remain open to growth without becoming reckless.`,
    friendship: `In friendship contexts, Jupiter describes how this person expands the bond and what they bring in terms of possibility and generosity. A person with a strong Jupiterian presence in friendship is the one who sees potential in people, who encourages ambitions, who says "you should try that" when others are cautious. They are the friend who introduces new ideas and new people, who invites the group to bigger experiences, who is generous with their time, resources, and enthusiasm. The Jupiterian friend needs the friendship to allow for growth. They become restless in bonds that feel static or small, and they need friends who can match their enthusiasm for new experiences rather than pulling them back toward safety. Friendships where Jupiter is honored are marked by mutual encouragement, shared exploration of ideas and experiences, and the freedom to pursue individual growth without the friendship demanding that everyone stay at the same level. The Jupiterian friend can be overwhelming in friendships that value stability over expansion, and they thrive in bonds where possibility and generosity are mutual.`,
    romantic: `In romantic contexts, Jupiter describes what this person needs in order to continue growing within the partnership and how they express generosity toward their partner. Jupiter does not thrive in relationships that feel limiting or small. It needs the partnership to be a space where both people are encouraged to become more than they currently are. A person's Jupiter needs a partner who shares their sense of possibility, who supports their ambitions even when those ambitions require risk, and who treats the relationship as a platform for mutual growth rather than as a contract to stay the same. The partner who honors Jupiter is generous in return, encourages this person's expansive impulses rather than trying to contain them, and participates in creating a shared life that feels abundant rather than constrained. Romantic relationships that suppress Jupiter produce restlessness and resentment, because the person experiences the partnership as limiting their potential. The Jupiter in romance is not irresponsible or commitment-phobic. It is the part of the person that needs the relationship to be big enough to hold ongoing growth, that deepens connection through shared exploration, and that treats optimism and generosity as legitimate relationship values rather than as naive or reckless. Partnerships that work with Jupiter create space for both people to expand, honor individual ambitions alongside shared goals, and treat the relationship as an ongoing project of becoming rather than as a static agreement.`,
    feed: `Jupiter is active in the current sky. What this person believes is possible, how they understand the meaning of current circumstances, and their capacity for optimism and generosity are all being touched right now. This is a window for seeing bigger possibilities and taking meaningful risks.`,
    sonic: `Jupiter contributes expansive harmonic voicings, wide melodic intervals, and a rhythmic quality that is broad and unhurried. The harmonic language is rich and full, chords with added extensions, voicings that use the full range of available pitch space rather than staying in a narrow register. The melodic lines are wide-ranging, moving through large intervals with confidence, reaching upward and outward rather than staying confined. The rhythm is spacious, allowing time for each phrase to resonate fully before moving to the next. Jupiter's sound is warm and generous, not sparse or economical. It fills the sonic space without crowding it. Listen for the quality of music where the scope feels large, where the harmonic and melodic content suggests abundance and possibility, where the overall effect is one of expansion and optimism. Jupiter's sonic character is breadth, generosity, and the sense that more is available than what is immediately present.`,
  },

  PLANET_SATURN: {
    key: 'PLANET_SATURN',
    planet: 'SATURN',
    title: 'Saturn',
    core: `Saturn is the principle of structure, limit, and the reality-testing function that separates what is possible from what is fantasy. It governs how the person relates to authority, how they build enduring achievement, and the particular quality of discipline and restraint that allows them to work within constraints rather than being defeated by them. Saturn is not oppression. It is the structural intelligence that allows a building to stand, a career to develop, and a commitment to hold across time. In the natal chart, Saturn's placement describes where the person encounters limitation, where they must develop mastery through sustained effort, and where they experience the gap between what they want and what reality will allow. Psychologically, Saturn is the superego in its most functional form: not the punishing internal critic, but the part of the psyche that can delay gratification, tolerate frustration, and work toward long-term goals even when immediate pleasure is unavailable. Where Jupiter expands, Saturn consolidates. Where Mars acts impulsively, Saturn plans. Saturn is the capacity to accept that some things take time, that shortcuts undermine quality, and that genuine mastery requires repetition and patience. It is also the internalized sense of responsibility. The part of the person that understands they are accountable for their choices, that consequences are real, and that some forms of difficulty cannot be avoided but must be worked through.`,
    behavioral: `Saturn's psychological expression is the capacity for discipline and the struggle with internalized limitation. A person with a well-developed Saturn can work steadily toward long-term goals, can tolerate delayed gratification, and can build structures that endure. A person with a more challenged Saturn may either become rigidly self-controlling, allowing no room for spontaneity or pleasure, or may avoid discipline entirely, sabotaging their own efforts through procrastination or giving up when difficulty arrives. Behaviorally, Saturn shows in how the person approaches long-term commitments, how they handle authority figures, and whether they can sustain effort when the initial enthusiasm fades. It is visible in whether they take responsibility for outcomes or blame external circumstances, whether they learn from failure or become paralyzed by it, whether they respect limitations or resent them. The pathology of Saturn, when it occurs, is either harsh self-judgment, an internal authority so punishing that the person can never meet their own standards, or total abdication of responsibility, where the person refuses to acknowledge that they have any power to shape their circumstances. But at its best, Saturn is the capacity for genuine mastery: the willingness to do the work even when it is unglamorous, to build slowly and solidly rather than quickly and shoddily, and to accept limitation as a constraint that focuses energy rather than as a prison that destroys possibility.`,
    friendship: `In friendship contexts, Saturn describes what this person brings in terms of reliability and where they need the friendship to honor their boundaries. A person with a strong Saturnian presence in friendship is the one who shows up consistently, who remembers commitments, who can be counted on even when it is inconvenient. They are the friend who tells you the truth even when it is uncomfortable, who holds you accountable, who does not enable avoidance or self-deception. The Saturnian friend needs the friendship to have clear boundaries and reciprocal responsibility. They become resentful in bonds where they are always the reliable one while others show up only when it suits them. Friendships where Saturn is honored are marked by mutual respect for each person's limits, the capacity to make and keep commitments, and the freedom to say no without the friendship interpreting it as rejection. The Saturnian friend can be experienced as heavy or demanding in friendships that value spontaneity over structure, and they thrive in bonds where reliability and accountability are mutual.`,
    romantic: `In romantic contexts, Saturn describes what this person needs in order to commit and how they honor their responsibilities within the partnership. Saturn does not enter commitment lightly. It needs to know that the partnership is built on solid ground, that both people are willing to do the work, and that the relationship can endure difficulty rather than dissolving when things become hard. A person's Saturn needs a partner who is equally serious about commitment, who honors agreements rather than treating them as negotiable when convenient, and who is willing to work through problems rather than exiting when conflict arises. The partner who honors Saturn takes this person's boundaries seriously, does not pressure them to commit before they are ready, and participates in building something enduring rather than expecting passion alone to sustain the relationship. Romantic relationships that ignore Saturn produce either premature commitment that collapses under pressure or chronic instability where neither person trusts the bond to hold. The Saturn in romance is not cold or withholding. It is the part of the person that knows the difference between infatuation and commitment, that builds intimacy through sustained presence rather than dramatic gestures, and that treats responsibility as a form of love rather than as a burden. Partnerships that work with Saturn honor both people's limits, build slowly and solidly, and treat commitment as a choice that is renewed through action rather than as a contract that is signed once and forgotten.`,
    feed: `Saturn is active in the current sky. Where this person encounters limitation, where they must build structure, and what they are being asked to take responsibility for are all being touched right now. This is a window for greater clarity about what endures and what requires sustained effort.`,
    sonic: `Saturn contributes sparse, economical voicings, slow harmonic rhythm, and a sense of gravity and weight in the bass. The harmonic language is austere, often simple triads or open fifths, without ornament or added color tones. The rhythm is slow and measured, with long note values that create a sense of deliberate pacing. The melodic content is restrained, moving through small intervals, staying within a defined range, never reaching wildly. Saturn's sound is solid and grounded, not light or airy, each note has weight, each chord sits firmly rather than floating. Listen for the quality of music where space and silence matter as much as sound, where the structure is more important than the decoration, where the overall effect is one of seriousness and endurance. Saturn's sonic character is discipline, limitation, and the architecture that holds when everything else falls away.`,
  },

  PLANET_URANUS: {
    key: 'PLANET_URANUS',
    planet: 'URANUS',
    title: 'Uranus',
    core: `Uranus is the principle of disruption, innovation, and the sudden insight that breaks through established patterns. It governs how the person relates to change, how they individuate from collective norms, and the particular quality of originality and rebellion that marks their contribution. Uranus is not chaos for its own sake. It is the revolutionary impulse that recognizes when existing structures have become rigid and life-denying, and that has the courage to break those structures in service of greater freedom. In the natal chart, Uranus's placement describes where the person experiences sudden change, where they are most likely to deviate from convention, and where they bring genuinely original thinking. Psychologically, Uranus is the individuation function in its most radical form: it is what separates the person from the collective, what allows them to think independently even when that thinking is unpopular, and what generates the flashes of insight that reorganize everything that came before. Where Saturn builds structures, Uranus breaks them. Where Jupiter expands gradually, Uranus leaps. Uranus is the lightning strike of understanding that arrives without warning, the sudden shift in perspective that makes the old way of seeing impossible to return to, and the willingness to destabilize one's life in service of living more authentically. It is also the social impulse toward equality and liberation. The part of the person that recognizes hierarchy as constructed rather than natural, and that works to dismantle systems of oppression rather than simply navigating them more successfully.`,
    behavioral: `Uranus's psychological expression is the capacity for radical authenticity and the struggle with instability. A person with a well-integrated Uranus can tolerate change without being destabilized by it, can think independently without becoming isolated, and can challenge convention without needing to destroy everything indiscriminately. A person with a more challenged Uranus may either suppress their originality entirely, conforming out of fear of rejection, or may become so committed to rebellion that they reject anything traditional simply because it is traditional. Behaviorally, Uranus shows in how the person responds to being told what to do, how they handle sudden disruptions, and whether they initiate change or resist it. It is visible in whether they conform to social expectations or deliberately defy them, whether they seek stability or find it stifling, whether they value tradition or innovation. The pathology of Uranus, when it occurs, is either compulsive rebellion, disruption without purpose, change for the sake of change, or total suppression of the individuation impulse, where the person becomes so committed to fitting in that they lose access to their own originality. But at its best, Uranus is the capacity for genuine innovation: the willingness to see what others have not seen, to question what others take for granted, and to live according to one's own truth even when that truth is not popular.`,
    friendship: `In friendship contexts, Uranus describes how this person brings originality to the bond and where they need the friendship to allow for independence. A person with a strong Uranian presence in friendship is the one who introduces new perspectives, who challenges group consensus, who refuses to go along simply to preserve harmony. They are the friend who lives differently, who experiments with unconventional choices, who can be counted on to say the thing everyone else is thinking but not saying. The Uranian friend needs the friendship to allow for individual difference. They become suffocated in bonds that demand conformity or that punish deviation from group norms. Friendships where Uranus is honored are marked by mutual respect for each person's uniqueness, the capacity to handle disagreement without requiring consensus, and the freedom to live unconventionally without being judged. The Uranian friend can be disruptive in friendships that value stability and predictability, and they thrive in bonds where originality is celebrated rather than pathologized.`,
    romantic: `In romantic contexts, Uranus describes what this person needs in order to remain free within the partnership and how they challenge the relationship to evolve. Uranus does not thrive in relationships that demand total merging or that expect both people to follow conventional scripts. A person's Uranus needs a partner who can tolerate unpredictability, who supports their need for autonomy even within commitment, and who is willing to renegotiate the terms of the relationship as both people change. The partner who honors Uranus does not try to control or contain this person, does not interpret their need for space as a threat to the bond, and participates in keeping the relationship alive through ongoing change rather than expecting it to settle into a fixed form. Romantic relationships that suppress Uranus produce either sudden exits or chronic restlessness, because the person experiences the partnership as limiting their freedom. The Uranus in romance is not commitment-phobic. It is the part of the person that knows partnership must allow for ongoing individuation, that deepens connection through honoring difference rather than demanding sameness, and that treats change as a sign of life rather than as a threat to stability. Partnerships that work with Uranus create space for both people's evolution, honor individual autonomy alongside commitment, and treat the relationship as an ongoing experiment rather than as a fixed contract.`,
    feed: `Uranus is active in the current sky. Where this person is being asked to break from convention, where sudden change is disrupting established patterns, and what needs to be liberated are all being touched right now. This is a window for seeing with new eyes and living more authentically.`,
    sonic: `Uranus contributes sudden harmonic shifts, unexpected rhythmic disruptions, and melodic content that breaks patterns rather than establishing them. The harmonic language is unpredictable, moving from one key to another without preparation, introducing dissonances that do not resolve conventionally, creating jarring juxtapositions of tonal centers. The rhythm is unstable, with unexpected accents and syncopations that disrupt the expected pulse. The melodic phrases are angular and discontinuous, jumping between registers, avoiding singable or predictable contours. Uranus's sound is electric and sharp, not warm or blended. It cuts through the texture rather than supporting it. Listen for the quality of music where the pattern is established only to be broken, where what happens next is genuinely unpredictable, where the overall effect is one of surprise and sudden insight. Uranus's sonic character is disruption, originality, and the lightning strike of understanding that reorganizes everything.`,
  },

  PLANET_NEPTUNE: {
    key: 'PLANET_NEPTUNE',
    planet: 'NEPTUNE',
    title: 'Neptune',
    core: `Neptune is the principle of dissolution, transcendence, and the longing for union with something larger than the individual self. It governs the person's relationship to the numinous, their capacity for imagination and fantasy, and the particular quality of sensitivity that allows them to perceive what is beneath or beyond the surface of ordinary reality. Neptune is not delusion. It is the perceptual sensitivity that recognizes that material reality is not the totality of what exists, that there are dimensions of experience that logic and reason cannot fully capture, and that the boundaries between self and other are more permeable than ego-consciousness suggests. In the natal chart, Neptune's placement describes where the person experiences the dissolution of boundaries, where they are most permeable to collective or transpersonal forces, and where they seek transcendence of ordinary limitation. Psychologically, Neptune is the mystical function: it is what allows the person to experience states of consciousness where the usual distinctions, between self and world, between one person and another, between real and imagined, temporarily dissolve. Where Saturn establishes boundaries, Neptune dissolves them. Where Mercury categorizes, Neptune blurs categories. Neptune is the capacity to imagine what does not yet exist, to experience empathy so complete it becomes identification, and to perceive beauty, meaning, and connection in ways that do not require empirical verification. It is also the source of the person's idealism. The vision of how things could be that is uncontaminated by how things are.`,
    behavioral: `Neptune's psychological expression is the capacity for transcendence and the struggle with groundedness. A person with a well-integrated Neptune can access states of creative flow, spiritual experience, or deep empathy without losing their capacity to function in ordinary reality. A person with a more challenged Neptune may either become so defended against Neptunian dissolution that they suppress their imagination and sensitivity entirely, or may become so ungrounded that they cannot distinguish between what is real and what they wish were real. Behaviorally, Neptune shows in how the person engages with art, spirituality, and altered states, and in how they handle the gap between the ideal and the actual. It is visible in whether they are idealistic or cynical, whether they trust intuition or dismiss it, whether they can tolerate ambiguity or demand clarity. The pathology of Neptune, when it occurs, is either complete dissolution, where the person loses the capacity to function in consensus reality, or total disenchantment, where the person becomes so defended against disappointment that they refuse to hope or imagine at all. But at its best, Neptune is the capacity for genuine compassion: the ability to feel with others without losing oneself, to hold ideals without demanding that reality conform to them immediately, and to access states of consciousness that renew rather than escape.`,
    friendship: `In friendship contexts, Neptune describes how this person creates emotional and imaginative depth in the bond and where they need the friendship to honor their sensitivity. A person with a strong Neptunian presence in friendship is the one who perceives what is not being said, who responds to the emotional undercurrent, who can hold space for vulnerability and uncertainty. They are the friend who creates beauty and meaning, who sees potential where others see only what is, who offers forgiveness and acceptance even when it is not deserved. The Neptunian friend needs the friendship to allow for emotional porousness. They are hurt by bonds that demand constant clarity and explicit boundaries, and they need friends who can meet them in the realm of feeling and imagination rather than only in practical reality. Friendships where Neptune is honored are marked by genuine empathy, shared creative or spiritual pursuits, and the capacity to be with each other without needing everything to be defined or resolved. The Neptunian friend can be experienced as vague or unreliable in friendships that value precision and follow-through, and they thrive in bonds where sensitivity and imagination are valued.`,
    romantic: `In romantic contexts, Neptune describes what this person needs in order to experience the partnership as sacred and how they idealize love itself. Neptune does not thrive in relationships that are purely practical or transactional. It needs the partnership to feel like it transcends ordinary reality, to carry a quality of magic or destiny or spiritual significance. A person's Neptune needs a partner who can meet them in the realm of the ideal, who shares their vision of what love could be, and who honors their sensitivity without pathologizing it. The partner who honors Neptune participates in creating beauty and meaning together, understands that this person's idealism is a gift rather than a flaw, and does not demand that the relationship be entirely grounded in practical reality. Romantic relationships that ignore Neptune produce disenchantment, because the person experiences the partnership as mundane and soul-deadening. The Neptune in romance is not naive. It is the part of the person that knows love through its capacity to dissolve ordinary boundaries, that deepens connection through shared imagination and spiritual resonance, and that treats idealism as a legitimate relationship value rather than as childish fantasy. Partnerships that work with Neptune create space for transcendence alongside practicality, honor both people's sensitivity, and treat the relationship as a doorway to something larger than the sum of two individuals.`,
    feed: `Neptune is active in the current sky. What this person imagines, what they long for, and their capacity to perceive what is beneath the surface are all being touched right now. This is a window for seeing beyond ordinary reality and connecting with deeper meaning.`,
    sonic: `Neptune contributes harmonic ambiguity, blurred boundaries between voices, and a quality of spaciousness and reverberation. The harmonic language is suspended, chords that do not resolve, modal harmonies that shift between major and minor without committing to either, sustained pedal tones that create a sense of floating. The rhythm is fluid and undefined, without sharp attacks or clear metric pulse, creating a sense of timelessness. The melodic content is elusive, drifting rather than moving purposefully, often obscured by layers of texture. Neptune's sound is soft and diffuse, not sharp or defined, elements blend together rather than standing distinctly. Listen for the quality of music where boundaries dissolve, where you cannot tell where one voice ends and another begins, where the overall effect is one of dreamlike immersion. Neptune's sonic character is transcendence, dissolution, and the experience of being suspended in something larger than oneself.`,
  },

  PLANET_PLUTO: {
    key: 'PLANET_PLUTO',
    planet: 'PLUTO',
    title: 'Pluto',
    core: `Pluto is the principle of transformation, power, and the confrontation with what has been hidden or denied. It governs how the person engages with death and rebirth, not literal death, but the psychological process of destroying what no longer serves in order to make space for what is trying to emerge. Pluto is not violence. It is the regenerative force that operates through crisis, breakdown, and the forced relinquishment of control when control has become a defense against necessary change. In the natal chart, Pluto's placement describes where the person encounters power dynamics, where they experience depth and intensity, and where they must undergo transformation whether they choose it or not. Psychologically, Pluto is the depth function: it is what pulls the person beneath the surface of ordinary consciousness into the realm of shadow, compulsion, and everything the ego would prefer not to acknowledge. Where Neptune dissolves boundaries gently, Pluto destroys them forcefully. Where Saturn builds structures to endure, Pluto destroys structures that have become prisons. Pluto is the capacity to face what is terrifying, to allow what is dead to die rather than clinging to it, and to trust that something new can emerge from the wreckage of what was. It is also the dimension of power, not power as domination, but power as the capacity to effect change, to transform circumstances, and to refuse to be a passive victim of forces beyond one's control.`,
    behavioral: `Pluto's psychological expression is the capacity for depth and the struggle with control. A person with a well-integrated Pluto can tolerate intensity without being overwhelmed by it, can face uncomfortable truths without collapsing into despair, and can allow transformation to occur without trying to micromanage the outcome. A person with a more challenged Pluto may either avoid depth entirely, staying on the surface of experience to avoid confronting what is hidden, or may become so consumed by depth that they cannot function in ordinary life. Behaviorally, Pluto shows in how the person handles crisis, how they engage with power dynamics, and whether they can let go of what is finished rather than trying to resurrect it. It is visible in whether they are willing to face their own shadow material or whether they project it onto others, whether they use power to transform or to dominate, whether they trust the process of breakdown and renewal or fight it at every step. The pathology of Pluto, when it occurs, is either obsessive control, the attempt to prevent loss and change through total domination of circumstances, or total powerlessness, where the person experiences themselves as a victim with no agency. But at its best, Pluto is the capacity for genuine transformation: the willingness to die to what one has been in order to become what one is meant to be, to face the darkest parts of the psyche without flinching, and to use power in service of regeneration rather than destruction.`,
    friendship: `In friendship contexts, Pluto describes how this person creates depth and intensity in the bond and where they confront power dynamics. A person with a strong Plutonian presence in friendship is the one who sees beneath the surface, who asks the questions no one else is willing to ask, who will not accept superficial answers. They are the friend who can hold the darkest material, who will not abandon you in crisis, who understands that real intimacy requires facing uncomfortable truths. The Plutonian friend needs the friendship to allow for depth. They are bored and frustrated by bonds that stay safely on the surface, and they need friends who can meet them in the realm of shadow and transformation rather than only in light social exchange. Friendships where Pluto is honored are marked by genuine intimacy that includes the difficult parts, mutual willingness to confront what is hidden, and the capacity to transform through the relationship rather than simply maintaining it. The Plutonian friend can be overwhelming in friendships that value lightness and ease, and they thrive in bonds where depth and intensity are mutual.`,
    romantic: `In romantic contexts, Pluto describes what this person needs in order to experience the partnership as transformative and how they engage with power within the relationship. Pluto does not thrive in relationships that are comfortable and safe. It needs the partnership to be a crucible, a space where both people are changed by the encounter. A person's Pluto needs a partner who can tolerate intensity, who is willing to face their own shadow material rather than projecting it, and who understands that real intimacy requires confronting power dynamics rather than pretending they do not exist. The partner who honors Pluto participates in the ongoing work of transformation, does not use the relationship as an escape from depth, and treats crisis as an opportunity for renewal rather than as evidence that the partnership is failing. Romantic relationships that avoid Pluto produce either chronic superficiality or explosive crises that cannot be integrated. The Pluto in romance is not destructive. It is the part of the person that knows partnership through its capacity to transform, that deepens connection through facing what is hidden, and that treats power as something to be negotiated consciously rather than as something to avoid or dominate with. Partnerships that work with Pluto create space for ongoing transformation, honor the shadow material that surfaces between the two, and treat intensity as a sign of life rather than as a problem to solve.`,
    feed: `Pluto is active in the current sky. Where this person is being asked to let go, where hidden material is surfacing, and what needs to be transformed are all being touched right now. This is a window for facing what has been avoided and allowing necessary change to occur.`,
    sonic: `Pluto contributes harmonic density, dark tonal colors, and a quality of inevitability and weight. The harmonic language is heavy, thick voicings in low registers, dissonances that do not resolve easily, minor keys with added tension. The rhythm is inexorable, moving forward with a sense of fate rather than choice, often using ostinato patterns that repeat with increasing intensity. The melodic content is brooding and chromatic, descending rather than ascending, moving through half-steps that create a sense of unease. Pluto's sound is dark and powerful, not light or decorative. It fills the space with dense, shadowy texture. Listen for the quality of music where the sense is one of depth and gravity, where something hidden is being revealed, where the overall effect is one of confrontation and transformation. Pluto's sonic character is intensity, inevitability, and the sound of something that must be faced rather than avoided.`,
  },

} as const;
