/**
 * Astradio Insight Library: House Archetypes
 *
 * 12 standalone house archetypes: 1st through 12th houses
 *
 * Keys: HOUSE_{N} (e.g., HOUSE_1, HOUSE_2)
 * Place at: vnext/projection/insight-library/insight-library-houses.ts
 *
 * v2 Phase 5A: Foundational house meanings authored as standalone archetypes
 * describing singular chart contexts (A), not cross-chart comparisons (A + B).
 * Each entry contains 6 natal fields only. No synastry fields, as these describe
 * what a house means in a chart rather than between charts.
 *
 * Authoring rule: core and behavioral fields use chart-bearer attribution 
 * ("the person," "this chart-bearer") and avoid partnership-coded language.
 * Role-specific framing lives in friendship and romantic fields where contextually
 * licensed.
 */

import type { HouseInsight } from './insight-library-types';

export const HOUSE_INSIGHTS: Readonly<Record<string, HouseInsight>> = {

  HOUSE_1: {
    key: 'HOUSE_1',
    house: 1,
    title: '1st House',
    domain: 'identity and self-presentation',
    core: `The 1st house is the domain of immediate self-presentation, the visible persona, and the energy with which the person first enters a room or situation. It describes how they are perceived at first contact before anyone knows them well, the default style and manner they adopt when not consciously performing a role, and the temperament or mood that colors all their interactions. The 1st house cusp, the Ascendant, is the filter through which the entire chart expresses itself into the world. It is the lens that colors how every other planetary placement manifests in visible behavior. A person with Mars rising will express their chart's potentials through assertiveness and directness even if the chart contains quieter elements. A person with Neptune rising will express the same chart's contents through sensitivity and permeability even if other factors suggest firmness. The 1st house is not the whole self. It is the edge where interior meets exterior, where private reality must translate into public legibility. Psychologically, it represents the ego-boundary, the way the person distinguishes self from other, and the energy they bring to self-assertion and self-definition. The 1st house is the part of the self that says "I am" before saying anything else about what "I am" might mean.`,
    behavioral: `Behaviorally, the 1st house describes the person's default approach to new situations, their baseline energy level, and the physical body as a vehicle for selfhood. Planets in the 1st house are visible. They cannot hide. A person with Sun in the 1st is immediately recognizable as purposeful and self-directed. A person with Moon in the 1st wears their emotional state on their face. A person with Saturn in the 1st carries themselves with a quality of seriousness or reserve that others notice before anything is said. The psychological work of the 1st house is learning to own one's immediate presence rather than apologizing for it. Some people experience their Ascendant as alien. This is not how I feel inside, but this is how I am seen. The development task is integration: bringing the interior self into alignment with the visible self so that self-presentation feels genuine rather than performed. The 1st house also governs the physical body and physical vitality. Health, appearance, and the capacity for physical self-care all belong to this domain. Neglecting the body is neglecting the 1st house.`,
    friendship: `In friendship, the 1st house describes the first impression this person makes and the energy they bring to initial social contact. Planets in the 1st house shape how approachable the person seems, whether they appear confident or tentative, whether they take up space or minimize themselves. The 1st house does not describe depth of connection, that belongs to other houses, but it describes whether connection is initiated easily or with difficulty. A person with Venus in the 1st is often received warmly before they have done anything to earn it. A person with Saturn in the 1st may be respected but not immediately welcomed. Understanding the 1st house in friendship means understanding how this person is seen before they are known, and how that first impression either facilitates or complicates the development of genuine bond.`,
    romantic: `In romance, the 1st house describes immediate attraction and the physical chemistry that arises before psychological compatibility is assessed. The 1st house governs first encounters, whether there is spark, whether the person's energy is magnetically appealing or off-putting, whether the physical presence creates desire. Planets in the 1st shape how the person moves through romantic pursuit: whether they approach directly or indirectly, whether they present themselves with confidence or vulnerability, whether their physical presence is commanding or gentle. The 1st house is not love. It is attraction. But attraction matters, and the person's Ascendant and any 1st house planets will significantly shape whether romantic interest is ignited at all.`,
    feed: `The 1st house is being activated. How this person presents themselves, the energy they bring to first contact, and their sense of their own presence are all being touched right now. This is a time for greater awareness of how they are seen and for aligning that visibility with who they actually are.`,
    sonic: `The 1st house contributes immediate attack, the opening gesture, and the quality of presence that announces the music has begun. The sonic character is determined by what planet or sign governs the 1st house, but the house itself represents the moment of first contact. The opening phrase, the initial harmonic statement, the rhythmic impulse that sets the tone for everything that follows. Listen for the quality of arrival, for how the music enters the space, for the energy that says "this is who we are" before the composition has developed its themes. The 1st house is the sonic equivalent of a person walking into a room. The immediate impression, the mood established, the presence felt.`,
  },

  HOUSE_2: {
    key: 'HOUSE_2',
    house: 2,
    title: '2nd House',
    domain: 'resources and values',
    core: `The 2nd house is the domain of resources, material security, and what the person values as worth having or protecting. It describes the relationship to money and possessions, the capacity to accumulate and maintain resources, and the underlying sense of abundance or scarcity that shapes financial behavior. But the 2nd house is not only material. It is also the domain of self-worth, the internal sense of deserving, and the capacity to recognize one's own value independent of external validation. The person's relationship to money often mirrors their relationship to self-worth. Someone who struggles financially may also struggle to claim their own value. Someone who accumulates wealth compulsively may be attempting to secure self-worth through external means. Psychologically, the 2nd house represents the foundational sense of "I have" that follows the 1st house's "I am." It is the part of the self that knows what belongs to it, what it needs in order to feel secure, and what it is willing to work for or protect.`,
    behavioral: `Behaviorally, the 2nd house describes how the person earns, spends, and saves money, and what they value enough to invest resources in acquiring or maintaining. Planets in the 2nd house shape financial style. A person with Jupiter in the 2nd may be generous and optimistic about money, trusting that more will arrive. A person with Saturn in the 2nd may be cautious and conservative, accumulating slowly and spending reluctantly. A person with Uranus in the 2nd may have erratic income or unconventional attitudes toward money. The psychological work of the 2nd house is developing a healthy relationship to material resources and self-worth. This includes learning to earn in ways that honor one's values, to spend in alignment with genuine priorities rather than compulsive patterns, and to recognize that self-worth is not determined by net worth even as material security is a legitimate need.`,
    friendship: `In friendship, the 2nd house describes how this person relates to shared resources and whether generosity or scarcity shapes the bond. Some friendships involve material exchange, lending money, sharing possessions, buying gifts. The 2nd house governs whether these exchanges feel natural or fraught, whether the person can give without resentment and receive without guilt. A person with strong 2nd house emphasis may express care through material provision or may need friends who share their values about money and possessions. Understanding the 2nd house in friendship means recognizing that material resources can be a medium of connection or a source of tension depending on whether values are aligned.`,
    romantic: `In romance, the 2nd house describes the role of material security in the partnership and whether shared values around money strengthen or destabilize the bond. Questions of who earns what, how resources are shared, and what material standard of living is acceptable all belong to the 2nd house. A person with Venus in the 2nd may express love through gifts and material provision. A person with Mars in the 2nd may be competitive or possessive about resources. The 2nd house also governs physical pleasure and sensuality. The enjoyment of food, touch, beauty, and comfort. Partnerships that honor the 2nd house create material security together, align on values about money and possessions, and honor the body's need for pleasure and comfort.`,
    feed: `The 2nd house is being activated. How this person relates to resources, what they value as worth having, and their sense of their own worth are all being touched right now. This is a time for greater awareness of material security and for aligning financial behavior with genuine values.`,
    sonic: `The 2nd house contributes grounded bass lines, rich harmonic foundations, and a quality of material presence and weight. The sonic character reflects the resources available, thick, full voicings when resources are abundant; sparse, economical voicings when they are scarce. Listen for the quality of the foundation, for how the music is supported from below, for whether the harmonic ground feels secure or unstable. The 2nd house is the sonic equivalent of material infrastructure. The bass that holds everything else, the economic foundation on which the rest of the composition builds.`,
  },

  HOUSE_3: {
    key: 'HOUSE_3',
    house: 3,
    title: '3rd House',
    domain: 'communication and immediate environment',
    core: `The 3rd house is the domain of communication, learning, and the immediate environment. It describes how the person thinks, speaks, and processes information, their relationship to siblings and neighbors, and their experience of early education and local travel. The 3rd house governs all forms of exchange that happen in the nearby social world, conversations, errands, short trips, daily routines of coming and going. Psychologically, it represents the capacity for articulation, the voice that translates interior experience into shareable language, and the curiosity that drives ongoing learning. The 3rd house is not deep philosophy. That belongs to the 9th. The 3rd is practical intelligence, everyday communication, and the small-scale social fabric that connects the person to their immediate surroundings.`,
    behavioral: `Behaviorally, the 3rd house describes communication style, learning preferences, and how the person engages with their immediate environment. Planets in the 3rd shape how the person speaks and learns. A person with Mercury in the 3rd is articulate and curious. A person with Mars in the 3rd speaks directly and sometimes bluntly. A person with Neptune in the 3rd may communicate through image and metaphor more than through precise language. The psychological work of the 3rd house is developing genuine communication skill. The capacity to say what one means, to listen to what is actually being said rather than what one expects to hear, and to learn in ways that honor one's natural cognitive style rather than forcing adaptation to a single method.`,
    friendship: `In friendship, the 3rd house describes the conversational dimension of the bond and whether shared communication style facilitates or complicates connection. Friends who communicate in compatible ways can talk for hours. Friends with incompatible 3rd house dynamics may care deeply about each other but struggle to understand what the other is actually saying. The 3rd house also governs siblings and the social network of neighbors and acquaintances. The people who are not intimate friends but who populate the immediate social world. Understanding the 3rd house in friendship means recognizing that conversation is a form of connection, that being able to talk easily matters, and that some friendships thrive on verbal exchange while others do not require it.`,
    romantic: `In romance, the 3rd house describes whether the partners can talk to each other, whether conversation remains interesting, and whether the daily routines of communication feel easy or effortful. A partnership with strong 3rd house compatibility can talk through anything. A partnership with 3rd house friction may love each other deeply but struggle to communicate clearly, leading to recurring misunderstandings. The 3rd house also governs the immediate shared environment, whether the couple lives in a neighborhood they both enjoy, whether daily routines are compatible, whether small errands and local travel are sources of connection or friction.`,
    feed: `The 3rd house is being activated. How this person communicates, how they learn, and how they move through their immediate environment are all being touched right now. This is a time for greater clarity in conversation and for paying attention to the small-scale social fabric that shapes daily life.`,
    sonic: `The 3rd house contributes conversational texture, rapid melodic exchange, and a quality of articulate movement. The sonic character is quick and communicative, call and response between voices, motifs that pass back and forth, rhythmic patterns that suggest speech or dialogue. Listen for the quality of conversation happening in sound, for how ideas are being exchanged, for whether the musical texture feels like genuine dialogue or like voices talking past each other. The 3rd house is the sonic equivalent of everyday speech, not formal oration, but the quick, flexible exchange of a good conversation.`,
  },

  HOUSE_4: {
    key: 'HOUSE_4',
    house: 4,
    title: '4th House',
    domain: 'home and emotional foundation',
    core: `The 4th house is the domain of home, family, and the emotional foundation. It describes the experience of origin. The family one was born into, the early environment that shaped emotional responses, and the internalized sense of what "home" means. The 4th house is also the domain of privacy, interiority, and the self that exists when no one is watching. It is the opposite of the 10th house's public identity. Where the 10th is what is shown to the world, the 4th is what is kept hidden, the roots that anchor the visible self. Psychologically, the 4th house represents the unconscious foundation of the personality, the emotional bedrock that supports or undermines everything built on top of it, and the sense of belonging or alienation that comes from early family experience.`,
    behavioral: `Behaviorally, the 4th house describes the person's relationship to home, family, and privacy. Planets in the 4th shape what "home" means and how the person creates it. A person with Venus in the 4th may create a beautiful, welcoming home environment. A person with Saturn in the 4th may have experienced family as cold or restrictive and may struggle to create safety in their own home. A person with Uranus in the 4th may move frequently or have an unconventional living situation. The psychological work of the 4th house is healing the emotional foundation, separating from family patterns that no longer serve, and creating a sense of home that feels genuinely safe rather than simply familiar.`,
    friendship: `In friendship, the 4th house describes whether this person allows friends into their private space and what it means when they do. For some people, inviting someone home is intimate. For others, home is purely private, and friendship happens elsewhere. The 4th house also governs whether the person can be emotionally vulnerable with friends or whether vulnerability is reserved for family or romantic partners alone. Understanding the 4th house in friendship means recognizing that privacy has different meanings for different people, and that some friends create emotional safety while others do not.`,
    romantic: `In romance, the 4th house describes the capacity to create home together and whether emotional foundation is shared or separate. Questions of where to live, how to structure domestic life, and whether the partnership feels like home belong to the 4th house. A person with Moon in the 4th needs the partnership to provide emotional sanctuary. A person with Mars in the 4th may experience domestic life as a site of conflict. The 4th house also governs family of origin and whether those patterns support or undermine the partnership. Partnerships that honor the 4th house create genuine emotional safety, build home together, and address family patterns rather than unconsciously replicating them.`,
    feed: `The 4th house is being activated. How this person relates to home, family, and emotional foundation are all being touched right now. This is a time for greater awareness of what provides genuine safety and for tending to the interior emotional life that supports everything else.`,
    sonic: `The 4th house contributes deep bass tones, sustained harmonic foundations, and a quality of interiority and emotional depth. The sonic character is private and grounded. The bass line that holds everything, the harmonic roots that are felt more than heard, the slow-moving chords that create emotional stability beneath more active voices. Listen for the quality of emotional foundation, for what is supporting the music from below, for the sense of being held or unmoored. The 4th house is the sonic equivalent of home. The place the music returns to, the emotional ground that makes everything else possible.`,
  },

  HOUSE_5: {
    key: 'HOUSE_5',
    house: 5,
    title: '5th House',
    domain: 'creativity and pleasure',
    core: `The 5th house is the domain of creative self-expression, pleasure, play, and the joy of being alive. It describes what the person does for pure enjoyment, what they create when they are not working toward practical goals, and the capacity to take risks for the sake of aliveness rather than security. The 5th house governs romance in the sense of courtship and play rather than committed partnership, children and the experience of generativity, and any activity that is pursued for its own sake rather than for instrumental value. Psychologically, the 5th house represents the capacity to play, to create, and to experience joy without requiring justification. It is the opposite of the Saturn principle. Where Saturn demands that everything serve a purpose, the 5th house insists that some things are valuable precisely because they serve no purpose other than delight.`,
    behavioral: `Behaviorally, the 5th house describes what the person does for fun, how they express creativity, and whether they can tolerate the risk and vulnerability that play requires. Planets in the 5th shape creative style and risk tolerance. A person with Sun in the 5th is built for performance and self-expression. A person with Saturn in the 5th may struggle with play, experiencing it as frivolous or finding creativity blocked by self-criticism. A person with Jupiter in the 5th takes creative risks easily and enjoys games and speculation. The psychological work of the 5th house is learning to play without requiring that play be productive, to create for the sake of creation, and to take risks that serve aliveness rather than security.`,
    friendship: `In friendship, the 5th house describes whether the bond includes shared play, creative collaboration, or the experience of pure enjoyment together. Some friendships are work-oriented or emotionally supportive but do not include fun. The 5th house governs whether fun is part of the bond and what form it takes. A person with Venus in the 5th may create beauty with friends. A person with Mars in the 5th may engage in physical play or competition. Understanding the 5th house in friendship means recognizing that play matters, that shared joy is a legitimate form of connection, and that some friendships are sustained precisely because they are enjoyable rather than useful.`,
    romantic: `In romance, the 5th house describes courtship, flirtation, and the playful phase of relationship before commitment is established. It governs whether romance remains playful and alive even in long-term partnership or whether it disappears once the relationship settles. A person with strong 5th house emphasis needs romance to include ongoing play, creative expression, and the freedom to take relational risks. The 5th house also governs children, both the decision to have them and the experience of parenting as creative generativity. Partnerships that honor the 5th house keep play alive, support each other's creative expression, and treat pleasure as a legitimate relationship value.`,
    feed: `The 5th house is being activated. What this person creates, what they enjoy, and their capacity for play and pleasure are all being touched right now. This is a time for creative expression, for taking risks that serve aliveness, for allowing joy without requiring justification.`,
    sonic: `The 5th house contributes playful melodic ornamentation, rhythmic vitality, and a quality of spontaneous creative expression. The sonic character is joyful and alive, unexpected flourishes, improvisational passages, moments where the music seems to be playing for the sheer pleasure of playing. Listen for the quality of delight, for when the music stops serving structure and simply enjoys itself, for the moments of risk and surprise that make the composition feel alive. The 5th house is the sonic equivalent of play. The part of the music that exists for joy rather than for function.`,
  },

  HOUSE_6: {
    key: 'HOUSE_6',
    house: 6,
    title: '6th House',
    domain: 'work and health',
    core: `The 6th house is the domain of daily work, physical health, and the routines that maintain functionality. It describes the person's approach to service, employment, and the small tasks that must be done repeatedly in order for life to function. The 6th house governs the body as a practical instrument that requires maintenance, the daily rituals of hygiene and exercise, and the capacity to work steadily rather than in bursts of inspiration. Psychologically, the 6th house represents the capacity for discipline, the relationship to duty and obligation, and the understanding that some forms of value are created through repetition rather than through brilliance. It is the opposite of the 12th house's transcendence. Where the 12th dissolves boundaries, the 6th establishes routines. Where the 12th seeks spiritual meaning, the 6th asks whether the body has been fed and whether the work has been done.`,
    behavioral: `Behaviorally, the 6th house describes work style, relationship to health and illness, and whether the person can maintain daily routines. Planets in the 6th shape how the person works. A person with Mars in the 6th is productive and hardworking. A person with Neptune in the 6th may struggle with consistent routines or may work in healing or artistic fields. A person with Saturn in the 6th takes duty seriously and may overwork to the point of burnout. The psychological work of the 6th house is learning to work sustainably, to care for the body without requiring crisis to justify rest, and to find meaning in small daily tasks rather than only in grand achievements.`,
    friendship: `In friendship, the 6th house describes whether the bond includes practical mutual support and whether friends help each other with daily tasks. Some friendships are purely social. Others include tangible assistance, helping with moves, lending tools, providing care during illness. The 6th house governs whether this dimension exists in the friendship and whether it is reciprocal. A person with strong 6th house emphasis may show care through practical help and may need friends who reciprocate in kind.`,
    romantic: `In romance, the 6th house describes the daily routines of shared life and whether domestic labor is distributed fairly. Questions of who does the dishes, who takes care of health needs, and whether the partnership functions smoothly in ordinary time all belong to the 6th house. A partnership with 6th house compatibility handles daily tasks without resentment. A partnership with 6th house friction may love deeply but struggle with the unglamorous work of maintenance. The 6th house also governs health and whether the partnership supports both people's physical wellbeing.`,
    feed: `The 6th house is being activated. How this person approaches work, how they care for their health, and the daily routines that structure their life are all being touched right now. This is a time for sustainable discipline, for tending to the body's needs, for honoring the small tasks that make everything else possible.`,
    sonic: `The 6th house contributes steady rhythmic patterns, repetitive motifs, and a quality of disciplined regularity. The sonic character is workmanlike and functional, ostinato patterns that repeat without variation, rhythms that keep the music moving forward through simple regularity, harmonic progressions that serve the structure rather than drawing attention to themselves. Listen for the quality of routine, for what is repeated reliably, for the infrastructure that keeps the music functioning. The 6th house is the sonic equivalent of maintenance. The regular pulse that allows everything else to happen.`,
  },

  HOUSE_7: {
    key: 'HOUSE_7',
    house: 7,
    title: '7th House',
    domain: 'partnership and committed relationship',
    core: `The 7th house is the domain of committed partnership, contracts, and the experience of the other as equal. It describes the person's approach to one-on-one relationships, what they seek in a partner, and the qualities they project onto others rather than recognizing in themselves. The 7th house cusp, the Descendant, is the opposite point from the Ascendant, representing what is not immediately visible in the self but is encountered through relationship. Psychologically, the 7th house represents the capacity for genuine partnership, the ability to see the other as distinct and equal, and the work of integrating what has been projected outward back into conscious ownership. Where the 1st house is "I am," the 7th is "we are." Where the 1st is self-assertion, the 7th is negotiation and compromise.`,
    behavioral: `Behaviorally, the 7th house describes partnership style and what the person needs from committed relationship. Planets in the 7th shape what is sought in a partner and what is projected onto them. A person with Venus in the 7th seeks beauty and harmony in partnership. A person with Mars in the 7th may attract partners who are assertive or combative, or may project their own Mars onto the partner. A person with Saturn in the 7th takes commitment seriously and may delay partnership until they are certain. The psychological work of the 7th house is learning to own what has been projected, to see the partner as they actually are rather than as what is needed, and to negotiate fairly between self and other.`,
    friendship: `In friendship, the 7th house describes whether the person engages in one-on-one bonds or prefers group connection. Some people have many acquaintances but few intimate friends. Others invest deeply in a small number of close one-on-one relationships. The 7th house governs the latter. The capacity for committed friendship that includes genuine equality and mutual investment. A person with strong 7th house emphasis needs close partnerships rather than diffuse social networks.`,
    romantic: `In romance, the 7th house describes the experience of committed partnership, what is sought in a long-term partner, and whether the person can sustain genuine equality in relationship. This is not courtship (5th house) or emotional sanctuary (4th house). It is the work of building a life together as equals. Questions of how decisions are made, whether power is shared, and whether both people's autonomy is honored all belong to the 7th house. Partnerships that honor the 7th house create genuine equality, negotiate fairly, and see each other clearly rather than through projection.`,
    feed: `The 7th house is being activated. How this person relates to committed partnership, what they seek in others, and their capacity for genuine equality in relationship are all being touched right now. This is a time for seeing others clearly and for examining what has been projected onto partners.`,
    sonic: `The 7th house contributes dialogue between voices, balanced call and response, and a quality of genuine partnership in the musical texture. The sonic character is relational, two voices in conversation, neither dominating, both contributing equally. Listen for the quality of balance, for whether the voices are genuinely listening to each other, for moments when the music is created through partnership rather than through solo assertion. The 7th house is the sonic equivalent of committed relationship. The part of the music that requires two equals working together.`,
  },

  HOUSE_8: {
    key: 'HOUSE_8',
    house: 8,
    title: '8th House',
    domain: 'transformation and shared resources',
    core: `The 8th house is the domain of transformation, death and rebirth, and resources that are shared rather than solely owned. It describes the person's relationship to intensity, crisis, and the processes that force change whether or not change is wanted. The 8th house governs sexuality as transformation rather than as pleasure, inheritance and shared finances, and all experiences that involve merging with or being transformed by another. Psychologically, the 8th house represents the shadow, the taboo, and everything the conscious self would prefer not to acknowledge. It is the domain of power in its most intimate and intense forms, not the public authority of the 10th house, but the private power dynamics that shape intimate bonds.`,
    behavioral: `Behaviorally, the 8th house describes how the person handles crisis, whether they can face what is hidden or denied, and how they engage with shared resources and power. Planets in the 8th shape the capacity for depth and intensity. A person with Pluto in the 8th experiences transformation as central to their life. A person with Venus in the 8th may seek intensity in intimacy and may confuse love with possession. A person with Saturn in the 8th may fear loss and attempt to control shared resources. The psychological work of the 8th house is learning to allow transformation, to face shadow material without being destroyed by it, and to negotiate power consciously rather than through manipulation.`,
    friendship: `In friendship, the 8th house describes whether the bond includes genuine depth and whether friends can face each other's shadow material. Some friendships stay light and pleasant. Others become sites of transformation where both people are changed by the encounter. The 8th house governs the latter, friendships that include crisis support, emotional intensity, and the willingness to see what is hidden. A person with strong 8th house emphasis needs friends who can tolerate depth and who will not abandon them during difficult transformations.`,
    romantic: `In romance, the 8th house describes sexual intimacy, shared finances, and the capacity for genuine transformation through partnership. This is not the playful courtship of the 5th house or the committed equality of the 7th. It is the merging, the loss of boundaries, the experience of being changed by the other. Questions of sexual compatibility, how money and resources are merged, and whether the partnership can survive crisis all belong to the 8th house. Partnerships that honor the 8th house create genuine intimacy, face power dynamics directly, and allow both people to be transformed rather than remaining static.`,
    feed: `The 8th house is being activated. How this person handles transformation, what is hidden or denied, and their relationship to shared resources and power are all being touched right now. This is a time for facing what has been avoided, for allowing necessary change, for engaging with depth rather than staying on the surface.`,
    sonic: `The 8th house contributes chromatic harmony, dense layered textures, and a quality of intensity and depth. The sonic character is dark and powerful, minor keys with added tensions, voicings that create harmonic density, rhythms that drive forward with inexorable force. Listen for the quality of transformation, for when the music descends into darker territory, for the moments of crisis and intensity that force change. The 8th house is the sonic equivalent of death and rebirth. The part of the music that destroys what came before in order to create something new.`,
  },

  HOUSE_9: {
    key: 'HOUSE_9',
    house: 9,
    title: '9th House',
    domain: 'philosophy and expansion',
    core: `The 9th house is the domain of meaning, philosophy, and the search for truth beyond immediate experience. It describes the person's relationship to belief systems, higher education, long-distance travel, and all experiences that expand perspective beyond the familiar. The 9th house governs the quest for understanding, the synthesis of experience into coherent worldview, and the capacity to see patterns across diverse information. Psychologically, the 9th house represents the meaning-making function, the part of the psyche that asks "what is this for?" and "what does this mean?" rather than simply accepting what is. It is the opposite of the 3rd house's local detail. Where the 3rd gathers facts, the 9th synthesizes them into philosophy.`,
    behavioral: `Behaviorally, the 9th house describes the person's approach to learning, travel, and belief. Planets in the 9th shape philosophical orientation and the quest for meaning. A person with Jupiter in the 9th is naturally philosophical and may travel extensively. A person with Saturn in the 9th takes belief seriously and may commit to a single system rather than sampling many. A person with Uranus in the 9th questions all received wisdom and creates their own worldview. The psychological work of the 9th house is developing a coherent philosophy that is genuinely believed rather than simply inherited, expanding perspective through encounter with what is foreign, and finding meaning that sustains even during difficulty.`,
    friendship: `In friendship, the 9th house describes whether the bond includes shared philosophical inquiry and whether friends challenge each other's beliefs. Some friendships are comfortable and confirming. Others push both people to expand their understanding. The 9th house governs the latter, friendships that include real intellectual challenge, shared travel or exploration, and the willingness to question together. A person with strong 9th house emphasis needs friends who can engage with big questions and who will not be threatened by honest disagreement.`,
    romantic: `In romance, the 9th house describes whether the partnership includes shared vision and whether both people are growing in their understanding. Questions of religious or philosophical compatibility, whether the couple travels together, and whether the relationship expands both people's perspectives all belong to the 9th house. A partnership with 9th house compatibility shares core beliefs and grows together intellectually. A partnership with 9th house friction may love deeply but struggle with incompatible worldviews. Partnerships that honor the 9th house create shared meaning, support each other's growth, and engage in ongoing philosophical dialogue.`,
    feed: `The 9th house is being activated. How this person makes meaning, what they believe, and their capacity to expand beyond the familiar are all being touched right now. This is a time for philosophical inquiry, for travel or exploration, for seeking truth beyond comfortable assumptions.`,
    sonic: `The 9th house contributes expansive harmonic voicings, adventurous modulations, and a quality of intellectual exploration. The sonic character is open and searching, wide melodic intervals, harmonic progressions that visit distant keys, rhythms that suggest journey and discovery. Listen for the quality of expansion, for when the music leaves familiar territory, for moments of intellectual excitement and philosophical synthesis. The 9th house is the sonic equivalent of philosophical inquiry. The part of the music that asks "what does this mean?" and searches for coherent answers.`,
  },

  HOUSE_10: {
    key: 'HOUSE_10',
    house: 10,
    title: '10th House',
    domain: 'career and public identity',
    core: `The 10th house is the domain of career, public identity, and the reputation one builds through sustained achievement. It describes the person's relationship to authority, their professional ambitions, and what they are known for in the public sphere. The 10th house cusp, the Midheaven, represents the highest point in the chart, the achievement toward which the person is climbing, and the legacy they are building. Psychologically, the 10th house represents the capacity for mastery, the willingness to take on public responsibility, and the part of the self that is visible to the collective rather than only to intimates. It is the opposite of the 4th house's private foundation. Where the 4th is home and roots, the 10th is public achievement and status.`,
    behavioral: `Behaviorally, the 10th house describes career path, relationship to authority, and public reputation. Planets in the 10th shape professional life. A person with Sun in the 10th is built for leadership and public visibility. A person with Saturn in the 10th takes career seriously and builds slowly toward mastery. A person with Neptune in the 10th may work in creative or healing professions or may struggle with unclear professional direction. The psychological work of the 10th house is building genuine achievement rather than merely seeking status, taking responsibility for public role, and accepting that reputation is earned through sustained effort rather than claimed through ambition alone.`,
    friendship: `In friendship, the 10th house describes whether shared professional or public pursuits are part of the bond. Some friendships are purely personal. Others include collaboration on public projects, mutual professional support, or shared commitment to causes that serve the collective. The 10th house governs whether this dimension exists in the friendship and whether it strengthens or complicates the personal bond.`,
    romantic: `In romance, the 10th house describes whether the partnership supports both people's professional ambitions and public roles. Questions of career compatibility, whether one partner's success threatens the other, and how public and private life are balanced all belong to the 10th house. A partnership with 10th house compatibility supports both people's achievement. A partnership with 10th house friction may involve competition or resentment about professional success. Partnerships that honor the 10th house create space for both people's public roles, support each other's professional development, and build shared achievement that serves the collective.`,
    feed: `The 10th house is being activated. How this person builds public achievement, what they are becoming known for, and their relationship to authority and responsibility are all being touched right now. This is a time for professional development, for taking on public roles, for building reputation through sustained effort.`,
    sonic: `The 10th house contributes formal structure, clear hierarchical organization, and a quality of public-facing presentation. The sonic character is authoritative and organized, well-defined formal structures, clear sectional divisions, harmonic progressions that demonstrate mastery. Listen for the quality of achievement, for when the music demonstrates competence and control, for moments of formal clarity that could be performed in public. The 10th house is the sonic equivalent of professional mastery. The part of the music that is built to endure public scrutiny.`,
  },

  HOUSE_11: {
    key: 'HOUSE_11',
    house: 11,
    title: '11th House',
    domain: 'community and collective purpose',
    core: `The 11th house is the domain of collective purpose, friendship networks, and the communities one chooses to belong to. It describes the person's relationship to groups, their hopes for the future, and the causes they align themselves with beyond personal interest. The 11th house governs friendships in the sense of chosen affinity rather than family obligation or romantic bond, and it represents the capacity to work toward collective good rather than only individual advancement. Psychologically, the 11th house represents the utopian impulse, the part of the self that can imagine better futures, and the willingness to subordinate personal gain to collective wellbeing. It is the opposite of the 5th house's individual creative joy. Where the 5th creates for personal pleasure, the 11th creates for the benefit of the group.`,
    behavioral: `Behaviorally, the 11th house describes how the person engages with groups, what communities they belong to, and whether they work toward collective goals. Planets in the 11th shape group orientation. A person with Sun in the 11th finds identity through group affiliation. A person with Saturn in the 11th may feel alienated from groups or may take on serious responsibility within them. A person with Uranus in the 11th is drawn to revolutionary or unconventional communities. The psychological work of the 11th house is finding genuine community rather than simply belonging for the sake of belonging, contributing to collective good, and maintaining individual identity within group contexts.`,
    friendship: `In friendship, the 11th house describes the broader network of chosen affiliations and whether friendships are embedded in larger communities. Some people have isolated one-on-one friendships. Others have friendship networks that are part of larger social or political communities. The 11th house governs the latter, friendships that are connected to shared causes, group projects, or collective visions. A person with strong 11th house emphasis needs community and may struggle with isolated personal relationships that are not connected to larger purpose.`,
    romantic: `In romance, the 11th house describes whether the partnership includes shared social networks and collective commitments. Questions of whether the couple shares friends, whether they work together on causes, and whether the relationship serves something larger than the two individuals all belong to the 11th house. A partnership with 11th house compatibility shares community and works together toward collective goals. A partnership with 11th house friction may struggle with incompatible social networks or divergent political commitments. Partnerships that honor the 11th house create shared community, support each other's group affiliations, and understand that the relationship serves collective good as well as personal satisfaction.`,
    feed: `The 11th house is being activated. How this person relates to community, what groups they align with, and their hopes for collective future are all being touched right now. This is a time for finding genuine community, for working toward shared goals, for contributing to something larger than individual interest.`,
    sonic: `The 11th house contributes communal textures, ensemble coordination, and a quality of collective purpose. The sonic character is collaborative, multiple voices working together toward shared musical goals, ensemble passages where individual parts serve the whole, harmonic progressions that create a sense of collective movement. Listen for the quality of group coordination, for when the music is created through collective effort rather than individual assertion, for moments when the whole is greater than the sum of its parts. The 11th house is the sonic equivalent of community. The part of the music that belongs to everyone rather than to one voice alone.`,
  },

  HOUSE_12: {
    key: 'HOUSE_12',
    house: 12,
    title: '12th House',
    domain: 'transcendence and the unconscious',
    core: `The 12th house is the domain of transcendence, the unconscious, and everything that dissolves ordinary ego boundaries. It describes the person's relationship to spirituality, isolation, and the parts of the psyche that are hidden even from the self. The 12th house governs experiences of merging with something larger, through meditation, art, service, or suffering, and the capacity to surrender control when control is no longer possible. Psychologically, the 12th house represents the collective unconscious, the parts of experience that are too diffuse to be integrated into ordinary consciousness, and the longing for dissolution that can manifest as spiritual transcendence or as escape into addiction and fantasy. It is the opposite of the 6th house's practical function. Where the 6th maintains routines, the 12th dissolves them. Where the 6th serves through work, the 12th serves through sacrifice.`,
    behavioral: `Behaviorally, the 12th house describes the person's relationship to solitude, spirituality, and the unconscious. Planets in the 12th are often hidden, operating beneath conscious awareness. A person with Moon in the 12th may struggle to access their own emotions. A person with Neptune in the 12th has natural spiritual sensitivity. A person with Mars in the 12th may suppress anger or express it indirectly. The psychological work of the 12th house is learning to access what is hidden, to surrender when surrender is required, and to distinguish between transcendence that renews and escape that merely avoids.`,
    friendship: `In friendship, the 12th house describes whether the bond includes spiritual depth and whether friends can be with each other in silence and solitude. Some friendships require constant activity. Others can hold quiet companionship and shared contemplation. The 12th house governs the latter, friendships that include genuine spiritual or creative communion, the capacity to be together without needing to do anything, and the willingness to witness each other's suffering. A person with strong 12th house emphasis needs friends who can meet them in depth and who understand that some forms of connection happen in silence.`,
    romantic: `In romance, the 12th house describes the mystical or spiritual dimension of partnership and the capacity for genuine surrender. This is not the practical partnership of the 6th house or the committed equality of the 7th. It is the dissolution of boundaries, the experience of union that transcends the personal. Questions of spiritual compatibility, whether the relationship includes genuine transcendence, and whether both people can surrender control all belong to the 12th house. Partnerships that honor the 12th house create space for spiritual practice, honor the unconscious material that surfaces between the two, and treat the relationship as a doorway to something larger than ego.`,
    feed: `The 12th house is being activated. How this person relates to the unconscious, what is hidden even from themselves, and their capacity for transcendence or surrender are all being touched right now. This is a time for solitude, for spiritual practice, for allowing what cannot be controlled to simply be.`,
    sonic: `The 12th house contributes harmonic dissolution, ambient textures, and a quality of boundlessness. The sonic character is mystical and diffuse, suspended harmonies that do not resolve, textures that blend into a continuous wash of sound, rhythms that dissolve into timelessness. Listen for the quality of transcendence, for when the music stops being about distinct voices and becomes an oceanic whole, for moments when boundaries dissolve and you cannot tell where one element ends and another begins. The 12th house is the sonic equivalent of spiritual union. The part of the music that is no longer music but pure sound dissolving into silence.`,
  },

} as const;
