/** Heuristics for auto-generated display names (registration defaults, QA labels). */
const AUTO_DISPLAY_NAME_PATTERNS: RegExp[] = [
  /^usr_[a-z0-9_-]+$/i,
  /^Demo User \d+$/i,
  /^[A-Za-z][A-Za-z0-9]*_\d{10,}$/,
  /^Natal QA \d+$/i,
  /^Natal \d+$/i,
];

export function isAutoGeneratedDisplayName(name: string): boolean {
  const trimmed = String(name || '').trim();
  if (!trimmed || trimmed === 'User') return true;
  return AUTO_DISPLAY_NAME_PATTERNS.some((re) => re.test(trimmed));
}

export function isPersonalizedDisplayName(name: string): boolean {
  return !isAutoGeneratedDisplayName(name);
}

/** Prefer a human display name over chart / connection fallback labels. */
export function preferPersonalizedPartnerLabel(
  displayName: string | undefined | null,
  chartLabel: string | undefined | null,
  fallback: string
): string {
  const dn = String(displayName || '').trim();
  if (dn && isPersonalizedDisplayName(dn)) return dn;
  const lab = String(chartLabel || '').trim();
  if (lab) return lab;
  const fb = String(fallback || '').trim();
  return fb || 'Partner';
}
