"""Apply Phase 1 Sun/Moon placement rewrites to insight-library-placements-sign.ts"""
import re
from pathlib import Path

PATH = Path(__file__).resolve().parents[1] / "vnext/projection/insight-library/insight-library-placements-sign.ts"

UPDATES: dict[str, dict[str, str]] = {
    "PLCMT_SUN_ARIES": {
        "core": "Your Sun in Aries means your sense of purpose is organized around initiation, courage, and moving toward what you want without waiting for permission. Your identity runs on forward momentum. You experience yourself most fully when you're starting something, taking the first step, being first even when being first means being alone. Aries is cardinal fire: you're the spark that starts the blaze, the impulse that launches the project. Your conscious self doesn't deliberate endlessly. You act, and you learn from the consequences of action rather than theoretical preparation. What you want and what you pursue are a single motion. Hesitation feels like death to your Sun. You'd rather fail quickly than succeed slowly. Your vitality comes from directness, speed, and refusing to be slowed by complexity or caution.",
        "behavioral": "You move quickly, speak directly, and commit to action before all variables are known. You volunteer first. You raise your hand before the question is fully asked. You start the project immediately rather than spending weeks planning. This isn't recklessness. It's a different relationship to risk. You understand that perfect information is never available, that waiting for certainty is paralysis, and that momentum itself is a resource you have to claim early or not at all. Your approach to obstacles is to go through them rather than around them. Complexity gets simplified. Options get narrowed. The path forward gets chosen and pursued with singular focus. Your challenge is tolerating the middle phase of any endeavor—the part that's no longer new and exciting but not yet complete and victorious. You're built for beginnings. Use the small battles within the larger campaign to stay engaged.",
        "feed": "The Sun is moving through Aries in your chart. Your sense of purpose and vital energy are focused on initiation, courage, and direct action right now. This is a time for starting things, for moving toward what you want without waiting for perfect conditions.",
        "sonic": "Your Sun in Aries contributes sharp, bright attack, driving forward pulse, and melodic gestures that are short, incisive, and declarative. The rhythm is fast and emphatic with strong downbeats that propel the music forward. The harmonic language is simple and direct—power chords, unadorned triads, nothing ornate or ambiguous. The melodic phrases are angular and energetic, leaping rather than stepwise, reaching upward and outward rather than dwelling. The sound is hot and immediate, not soft or sustained. Listen for music where every element moves forward at speed, where the pulse creates urgency, where the overall effect is action and momentum already begun.",
    },
    "PLCMT_SUN_TAURUS": {
        "core": "Your Sun in Taurus means your sense of purpose is organized around building something lasting, creating tangible value, and staying grounded in physical reality. Your identity runs on steadiness. You experience yourself most fully when you're working with your hands, cultivating what grows slowly, making something real that endures. Taurus is fixed earth: you're the fertile ground where seeds become crops, the patient builder who knows that quality takes time. Your conscious self doesn't rush. You move at the pace real growth requires. What you build, you build to last. Speed for its own sake feels wasteful to your Sun. You'd rather build slowly and well than quickly and shoddily. Your vitality comes from physical pleasure, material security, and refusing to be rushed past what your body knows takes time.",
        "behavioral": "You work steadily, commit thoroughly, and resist being rushed. You're the one who finishes what others start, who builds the foundation that actually holds weight, who knows that shortcuts compromise quality. This isn't stubbornness. It's loyalty to process. You understand that real value accumulates slowly, that forcing growth damages it, and that patience itself is a form of power. Your approach to obstacles is to outlast them. Pressure gets absorbed. Demands get evaluated. The decision to move gets made when you're ready, not when others think you should be. Your challenge is recognizing when staying put has become rigidity rather than groundedness. You're built for sustained effort. Use your capacity to endure toward goals that actually deserve your staying power.",
        "feed": "The Sun is moving through Taurus in your chart. Your sense of purpose and vital energy are focused on building, grounding, and creating tangible value right now. This is a time for steady work, for cultivating what grows slowly, for trusting the pace real growth requires.",
        "sonic": "Your Sun in Taurus contributes rich harmonic textures, sustained melodic lines, and rhythm that is steady and grounded. The harmonic language is warm and full—major triads, open voicings, everything voiced for maximum resonance. The rhythm is patient, moving at the pace of natural cycles rather than forcing urgency. The melodic phrases are long and sustained, dwelling rather than leaping, settling into the harmonic space rather than rushing through it. The sound is warm and physical, not sharp or hurried. Listen for music where every element has weight and substance, where the pulse is steady without being mechanical, where the overall effect is groundedness and the pleasure of sustained presence.",
    },
    "PLCMT_SUN_GEMINI": {
        "core": "Your Sun in Gemini means your sense of purpose is organized around curiosity, communication, and making connections between ideas. Your identity runs on mental agility. You experience yourself most fully when you're learning something new, explaining what you know, moving between different subjects without needing to master any of them completely. Gemini is mutable air: you're the wind that carries information from one place to another, the translator who makes ideas accessible. Your conscious self doesn't commit to single tracks. You explore multiple paths simultaneously. What you learn, you share. Depth for its own sake feels limiting to your Sun. You'd rather know a little about many things than everything about one thing. Your vitality comes from variety, conversation, and refusing to be locked into expertise that stops you from staying curious.",
        "behavioral": "You think quickly, speak easily, and move between subjects without needing transition time. You're the one who sees connections others miss, who can explain complex ideas in simple language, who keeps multiple projects running at once. This isn't scattered. It's cognitively flexible. You understand that curiosity is its own form of intelligence, that learning doesn't require mastery, and that communication itself is a skill that matters as much as what's being communicated. Your approach to obstacles is to think around them. Problems get reframed. Questions get asked. The answer gets found through lateral thinking rather than direct force. Your challenge is developing enough depth in any one area that your breadth becomes expertise rather than dilettantism. You're built for mental agility. Use your capacity to learn quickly toward goals that benefit from seeing across domains.",
        "feed": "The Sun is moving through Gemini in your chart. Your sense of purpose and vital energy are focused on learning, communicating, and making connections right now. This is a time for curiosity, for conversation, for exploring multiple interests without needing to commit to expertise.",
        "sonic": "Your Sun in Gemini contributes quick melodic movement, light harmonic textures, and rhythm that is nimble and conversational. The harmonic language is bright and transparent—simple triads, clear voicings, nothing heavy or sustained. The rhythm is agile, changing direction easily, never dwelling in one place. The melodic phrases are short and playful, moving through scales quickly, creating the sense of conversation rather than monologue. The sound is light and articulate, not dense or slow. Listen for music where ideas move quickly, where the texture is transparent enough to hear every voice, where the overall effect is mental quickness and the pleasure of making connections.",
    },
    "PLCMT_SUN_CANCER": {
        "core": "Your Sun in Cancer means your sense of purpose is organized around creating sanctuary, protecting what matters, and building emotional safety for yourself and others. Your identity runs on care. You experience yourself most fully when you're tending to emotional needs, making home, holding space for vulnerability. Cancer is cardinal water: you initiate emotional safety, you build the container where feelings can exist without performance. Your conscious self doesn't separate from emotion. You lead with feeling. What you protect, you protect fiercely. Exposure for its own sake feels dangerous to your Sun. You'd rather be private and safe than visible and vulnerable. Your vitality comes from emotional intimacy, domestic comfort, and refusing to pretend feelings don't matter when they clearly do.",
        "behavioral": "You feel deeply, protect thoroughly, and create home as an emotional refuge. You're the one who notices when someone needs care, who makes space for feelings others ignore, who builds the private world where vulnerability doesn't require justification. This isn't weakness. It's emotional courage. You understand that safety has to be built intentionally, that feelings need tending, and that protection itself is a form of strength. Your approach to obstacles is to protect what matters and wait them out. Threats get absorbed emotionally. Boundaries get reinforced. The decision to open gets made when safety has been established, not when others demand access. Your challenge is releasing emotional wounds rather than carrying them indefinitely. You're built for emotional depth. Use your capacity to feel fully toward creating safety that serves growth, not just comfort.",
        "feed": "The Sun is moving through Cancer in your chart. Your sense of purpose and vital energy are focused on emotional safety, protection, and creating sanctuary right now. This is a time for tending feelings, for making home, for holding space for what needs care.",
        "sonic": "Your Sun in Cancer contributes flowing melodic phrases, modal harmonic warmth, and rhythm that ebbs and flows like tides. The harmonic language is emotionally rich—suspended chords, modal movement, everything voiced for emotional resonance rather than clarity. The rhythm is tidal, moving in waves rather than steady pulse, breathing organically. The melodic phrases are long and curved, following emotional contours rather than geometric patterns. The sound is tender and vulnerable, not sharp or defended. Listen for music where you feel held, where the emotional content is paramount, where the overall effect is emotional presence and the safety to feel without performance.",
    },
    "PLCMT_SUN_LEO": {
        "core": "Your Sun in Leo means your sense of purpose is organized around creative self-expression, generous presence, and being seen for who you actually are. Your identity runs on warmth. You experience yourself most fully when you're creating something that reflects you, when you're giving without keeping score, when you're recognized for your genuine contribution. Leo is fixed fire: you sustain the flame, you radiate heat and light, you make the room warmer by being in it. Your conscious self doesn't hide. You show up fully. What you create, you sign. Anonymity for its own sake feels like diminishment to your Sun. You'd rather be seen and criticized than invisible and safe. Your vitality comes from creative expression, generous giving, and refusing to make yourself small to make others comfortable.",
        "behavioral": "You create boldly, give generously, and expect to be seen for who you are. You're the one who takes center stage naturally, who makes things happen through sheer force of presence, who lights up the room without trying. This isn't narcissism. It's solar confidence. You understand that visibility itself is generous, that giving requires abundance, and that creativity needs an audience to complete the circuit. Your approach to obstacles is to outshine them. Criticism gets absorbed without dimming the light. Rejection doesn't stop the giving. The performance continues because the performance is who you are, not what you do. Your challenge is distinguishing between recognition you've earned and attention you're demanding. You're built for creative generosity. Use your capacity to shine toward work that actually deserves the light you bring.",
        "feed": "The Sun is moving through Leo, its home sign, in your chart. Your sense of purpose and vital energy are at maximum strength right now. This is a time for creative expression, for generous giving, for being seen and recognized for who you actually are.",
        "sonic": "Your Sun in Leo contributes bold melodic statements, rich harmonic fullness, and rhythm that is confident and commanding. The harmonic language is warm and generous—major keys, full voicings, everything orchestrated for maximum presence. The rhythm is steady and strong, carrying the music forward with solar confidence. The melodic phrases are dramatic and expressive, occupying the full range, making statements rather than suggestions. The sound is warm and radiant, not tentative or hidden. Listen for music where the presence is undeniable, where the warmth is genuine, where the overall effect is creative generosity and the pleasure of being fully seen.",
    },
    "PLCMT_SUN_VIRGO": {
        "core": "Your Sun in Virgo means your sense of purpose is organized around precision, useful service, and making things work better than they currently do. Your identity runs on refinement. You experience yourself most fully when you're analyzing what's broken, fixing what others overlook, making yourself useful through genuine skill. Virgo is mutable earth: you adapt the material world to serve practical need, you refine the rough into the functional. Your conscious self doesn't settle for good enough. You notice what needs improvement. What you build, you build to actually work. Sloppiness for its own sake feels like disrespect to your Sun. You'd rather be useful and unrecognized than celebrated for work that doesn't function. Your vitality comes from competence, practical service, and refusing to pretend dysfunction is acceptable when fixing it is possible.",
        "behavioral": "You analyze carefully, refine thoroughly, and make yourself useful through genuine skill. You're the one who sees what's broken, who notices the detail others miss, who makes the system actually work through patient attention. This isn't perfectionism. It's craftsmanship. You understand that useful work requires precision, that service means solving real problems, and that competence itself is a form of dignity. Your approach to obstacles is to break them into solvable pieces. Complexity gets analyzed. Systems get understood. The solution gets implemented through careful, skilled work. Your challenge is recognizing when refinement has become criticism that serves anxiety rather than improvement. You're built for useful precision. Use your capacity to analyze toward work that actually needs the care you bring.",
        "feed": "The Sun is moving through Virgo in your chart. Your sense of purpose and vital energy are focused on refinement, useful service, and practical improvement right now. This is a time for precision, for analyzing what's broken, for making yourself useful through genuine skill.",
        "sonic": "Your Sun in Virgo contributes intricate melodic detail, precise harmonic voice leading, and rhythm that is exact without being mechanical. The harmonic language is clean and functional—voice leading that serves the melodic line, nothing ornamental or wasted. The rhythm is precise, every note placed with intention, the pulse steady and reliable. The melodic phrases are detailed and crafted, every note serving the whole, nothing arbitrary. The sound is clear and refined, not rough or careless. Listen for music where precision serves expression, where every element has purpose, where the overall effect is useful beauty and the satisfaction of work done well.",
    },
    "PLCMT_SUN_LIBRA": {
        "core": "Your Sun in Libra means your sense of purpose is organized around balance, aesthetic rightness, and creating harmony between competing forces. Your identity runs on equilibrium. You experience yourself most fully when you're negotiating between perspectives, making something beautiful, creating the conditions where different needs can coexist. Libra is cardinal air: you initiate balance, you architect fairness, you create beauty that serves relationship. Your conscious self doesn't choose sides without considering both. You weigh options. What you create, you create to please the eye and serve the whole. Ugliness for its own sake feels like failure to your Sun. You'd rather create something beautiful and functional than powerful and graceless. Your vitality comes from aesthetic harmony, fair negotiation, and refusing to let imbalance stand when balance is achievable.",
        "behavioral": "You weigh carefully, create beautifully, and negotiate between competing needs. You're the one who sees both sides, who makes the space aesthetically right, who finds the solution where everyone gets something. This isn't indecision. It's genuine fairness. You understand that balance requires active maintenance, that beauty serves function, and that harmony is work, not accident. Your approach to obstacles is to find the third option that serves both sides. Conflict gets negotiated. Aesthetics get considered. The solution gets crafted to satisfy multiple requirements simultaneously. Your challenge is acting decisively when perfect balance isn't available and choosing has to happen anyway. You're built for aesthetic equilibrium. Use your capacity to see all sides toward creating beauty that actually serves the people involved.",
        "feed": "The Sun is moving through Libra in your chart. Your sense of purpose and vital energy are focused on balance, beauty, and fair negotiation right now. This is a time for weighing options, for creating aesthetic harmony, for finding solutions that serve all sides.",
        "sonic": "Your Sun in Libra contributes balanced harmonic progressions, elegant melodic lines, and rhythm that is graceful and measured. The harmonic language is sophisticated and fair—voice leading that serves all parts equally, nothing harsh or unbalanced. The rhythm is graceful, creating the sense of measured movement rather than rushing. The melodic phrases are elegant and symmetrical, balanced in their contours, creating beauty through proportion. The sound is refined and harmonious, not crude or jarring. Listen for music where balance is maintained, where beauty serves the whole, where the overall effect is aesthetic rightness and the pleasure of harmony achieved.",
    },
    "PLCMT_SUN_SCORPIO": {
        "core": "Your Sun in Scorpio means your sense of purpose is organized around depth, transformation, and facing what others avoid. Your identity runs on intensity. You experience yourself most fully when you're penetrating beneath surfaces, confronting shadow material, wielding power consciously. Scorpio is fixed water: you concentrate emotional force, you transform through crisis, you hold the truth others can't bear. Your conscious self doesn't trust surfaces. You dig for what's real. What you encounter, you encounter completely. Shallowness for its own sake feels like betrayal to your Sun. You'd rather face uncomfortable truth than comfortable lies. Your vitality comes from psychological depth, transformative power, and refusing to pretend darkness doesn't exist when acknowledging it is the only path to genuine light.",
        "behavioral": "You perceive deeply, feel intensely, and refuse to accept evasion. You're the one who sees beneath the surface, who asks the questions others avoid, who won't let denial stand when truth is available. This isn't paranoia. It's genuine discernment. You understand that depth requires facing what's uncomfortable, that power must be acknowledged before it can be wielded responsibly, and that transformation happens through crisis, not comfort. Your approach to obstacles is total engagement. Complexity gets penetrated. Secrets get revealed. The truth gets faced even when facing it is terrifying. Your challenge is tolerating powerlessness when control isn't actually available. You're built for psychological depth. Use your capacity to face shadow toward transformation that actually serves growth, not just exposure.",
        "feed": "The Sun is moving through Scorpio in your chart. Your sense of purpose and vital energy are focused on depth, transformation, and confronting what's hidden right now. This is a time for intensity, for facing shadow material, for wielding power consciously.",
        "sonic": "Your Sun in Scorpio contributes dense harmonic textures, chromatic melodic movement, and rhythm that is inexorable and driving. The harmonic language is dark and complex—thick voicings in low registers, minor keys with added tensions, dissonances that create unease. The rhythm is relentless, moving forward with a sense of fate. The melodic phrases are chromatic and often descending, moving through half-steps, creating tension that doesn't easily resolve. The sound is heavy and intense, not light or transparent. Listen for music where the emotional register is depth and power, where the harmonic density creates weight and gravity, where the overall effect is confrontation and transformation that cannot be avoided.",
    },
    "PLCMT_SUN_SAGITTARIUS": {
        "core": "Your Sun in Sagittarius means your sense of purpose is organized around meaning-making, exploration, and reaching toward what's beyond current limits. Your identity runs on expansion. You experience yourself most fully when you're learning something that changes your worldview, traveling to unfamiliar territory, connecting to larger philosophical frameworks. Sagittarius is mutable fire: you spread the flame of understanding, you explore without needing to settle, you reach for meaning in everything. Your conscious self doesn't stay local. You aim high. What you pursue, you pursue with optimism and scope. Smallness for its own sake feels like imprisonment to your Sun. You'd rather aim too high and miss than aim low and succeed. Your vitality comes from philosophical exploration, physical adventure, and refusing to accept that current boundaries are the final limits.",
        "behavioral": "You explore widely, think philosophically, and aim for more than seems reasonable. You're the one who sees the larger meaning, who ventures into unfamiliar territory, who believes the next experience will reveal something essential. This isn't naivete. It's genuine optimism. You understand that meaning has to be pursued actively, that exploration itself is valuable, and that reaching beyond current capacity is how capacity grows. Your approach to obstacles is to reframe them as adventure. Limits get questioned. Horizons get expanded. The path forward gets chosen for its potential to teach rather than its guarantee of success. Your challenge is grounding philosophical scope in practical action that actually serves the vision. You're built for exploratory expansion. Use your capacity to see the larger picture toward goals that actually deserve the optimism you bring.",
        "feed": "The Sun is moving through Sagittarius in your chart. Your sense of purpose and vital energy are focused on exploration, meaning-making, and expanding beyond current limits right now. This is a time for learning, for adventure, for connecting to larger philosophical frameworks.",
        "sonic": "Your Sun in Sagittarius contributes expansive melodic range, optimistic harmonic progressions, and rhythm that is energetic and forward-moving. The harmonic language is bright and open—major keys, wide voicings, everything reaching upward and outward. The rhythm is fast and buoyant, creating momentum without heaviness. The melodic phrases are wide-ranging and ascending, leaping across intervals, reaching for the high notes. The sound is enthusiastic and generous, not constrained or cautious. Listen for music where the scope is expansive, where the movement is always forward and upward, where the overall effect is philosophical optimism and the pleasure of reaching beyond current limits.",
    },
    "PLCMT_SUN_CAPRICORN": {
        "core": "Your Sun in Capricorn means your sense of purpose is organized around building lasting structures, earning authority through competence, and achieving goals that require sustained discipline. Your identity runs on mastery. You experience yourself most fully when you're working toward long-term goals, taking responsibility others avoid, building something that will stand the test of time. Capricorn is cardinal earth: you initiate structure, you architect achievement, you build the mountain one deliberate step at a time. Your conscious self doesn't take shortcuts. You earn it. What you achieve, you achieve through work. Speed without substance feels hollow to your Sun. You'd rather build slowly and well than quickly and shakily. Your vitality comes from earned authority, structural integrity, and refusing to pretend achievement is possible without the discipline achievement actually requires.",
        "behavioral": "You work patiently, build systematically, and take responsibility seriously. You're the one who finishes the long-term project, who earns authority through demonstrated competence, who understands that real achievement takes years, not months. This isn't joylessness. It's genuine respect for mastery. You understand that authority has to be earned, that structure requires maintenance, and that discipline itself is a form of freedom when it serves goals that actually matter. Your approach to obstacles is patient endurance. Time gets invested. Work gets done. The summit gets reached through sustained effort, not dramatic leaps. Your challenge is allowing pleasure and play without needing them to serve productive goals. You're built for long-term achievement. Use your capacity for discipline toward goals worthy of the years you'll give them.",
        "feed": "The Sun is moving through Capricorn in your chart. Your sense of purpose and vital energy are focused on building, achieving, and taking responsibility right now. This is a time for discipline, for working toward long-term goals, for earning authority through demonstrated competence.",
        "sonic": "Your Sun in Capricorn contributes structured harmonic progressions, deliberate melodic development, and rhythm that is steady and patient. The harmonic language is solid and traditional—clear progressions, stable voicings, everything built to last. The rhythm is measured and reliable, creating the sense of patient work rather than hurried motion. The melodic phrases are developed systematically, building toward climax through careful accumulation rather than sudden leaps. The sound is mature and authoritative, not playful or experimental. Listen for music where structure is paramount, where development is systematic, where the overall effect is earned mastery and the satisfaction of building something that will endure.",
    },
    "PLCMT_SUN_AQUARIUS": {
        "core": "Your Sun in Aquarius means your sense of purpose is organized around innovation, collective good, and maintaining individual autonomy within social systems. Your identity runs on detachment. You experience yourself most fully when you're thinking about how systems could work better, when you're contributing to collective progress, when you're maintaining your individuality without needing to dominate. Aquarius is fixed air: you sustain intellectual independence, you architect social progress, you hold the vision of how things could be different. Your conscious self doesn't conform for conformity's sake. You observe from outside. What you contribute, you contribute to the whole. Personal glory for its own sake feels small to your Sun. You'd rather improve the system and go unrecognized than be celebrated for work that serves only yourself. Your vitality comes from intellectual freedom, social contribution, and refusing to sacrifice autonomy for belonging.",
        "behavioral": "You think systematically, contribute to collective good, and maintain your individuality. You're the one who sees how systems could work better, who proposes solutions that serve everyone, who stays outside the social game while still participating in it. This isn't coldness. It's genuine detachment. You understand that belonging and autonomy don't have to compete, that social progress requires people who can think past current assumptions, and that innovation serves the collective best when it's not driven by personal ambition. Your approach to obstacles is intellectual reframing. Problems get analyzed as system failures. Solutions get designed for collective benefit. The path forward gets chosen for its contribution to the whole, not its service to ego. Your challenge is staying connected to individual human need when thinking at systems level. You're built for innovative contribution. Use your capacity for detached thinking toward progress that actually serves people, not just theory.",
        "feed": "The Sun is moving through Aquarius in your chart. Your sense of purpose and vital energy are focused on innovation, collective contribution, and intellectual freedom right now. This is a time for thinking systematically, for proposing better solutions, for maintaining autonomy while serving the whole.",
        "sonic": "Your Sun in Aquarius contributes unexpected harmonic progressions, intellectually complex melodic structures, and rhythm that is irregular and innovative. The harmonic language is unconventional—unusual progressions, non-traditional voicings, everything designed to challenge rather than comfort. The rhythm is asymmetric and unexpected, creating interest through irregularity. The melodic phrases are intellectually constructed rather than emotionally intuitive, creating patterns that surprise. The sound is cool and detached, not warm or sentimental. Listen for music where innovation is paramount, where the structure challenges convention, where the overall effect is intellectual freedom and the pleasure of thinking differently.",
    },
    "PLCMT_SUN_PISCES": {
        "core": "Your Sun in Pisces means your sense of purpose is organized around compassion, dissolution of boundaries, and connecting to what's larger than individual ego. Your identity runs on permeability. You experience yourself most fully when you're creating art that touches the universal, when you're serving without needing recognition, when you're feeling into collective emotional currents. Pisces is mutable water: you adapt to emotional need, you dissolve rigid boundaries, you flow between self and other. Your conscious self doesn't maintain hard edges. You merge. What you create, you create for everyone. Personal achievement for its own sake feels small to your Sun. You'd rather create something that touches the universal and remain anonymous than be celebrated for work that serves only ego. Your vitality comes from creative compassion, spiritual connection, and refusing to pretend separation is the final truth when unity is accessible.",
        "behavioral": "You feel universally, create imaginatively, and serve compassionately. You're the one who picks up on collective moods, who makes art that touches something beyond personal experience, who gives without keeping score. This isn't weakness. It's genuine permeability. You understand that boundaries can be too rigid, that compassion requires feeling into others' experience, and that creativity serves best when it touches what's universal rather than merely personal. Your approach to obstacles is to flow around them. Resistance gets absorbed. Boundaries get softened. The path forward gets found through intuition and imagination rather than force. Your challenge is maintaining enough self-definition that compassion doesn't become self-erasure. You're built for universal connection. Use your capacity to feel into the collective toward service that honors your boundaries while still touching what's larger than ego.",
        "feed": "The Sun is moving through Pisces in your chart. Your sense of purpose and vital energy are focused on compassion, imagination, and spiritual connection right now. This is a time for creative flow, for serving without needing recognition, for connecting to what's larger than individual ego.",
        "sonic": "Your Sun in Pisces contributes floating harmonic ambiguity, dissolving melodic boundaries, and rhythm that is fluid and unanchored. The harmonic language is mysterious and undefined—suspended progressions, modal ambiguity, everything drifting rather than resolving. The rhythm is flexible, flowing like water, never locking into mechanical pulse. The melodic phrases are long and wandering, moving without clear destination, creating the sense of dream rather than narrative. The sound is soft and permeable, not sharp or defined. Listen for music where boundaries dissolve, where the emotional space is universal rather than personal, where the overall effect is spiritual connection and the feeling of merging with something larger.",
    },
    "PLCMT_MOON_ARIES": {
        "core": "Your Moon in Aries means your emotional body needs immediate action, direct expression, and the freedom to respond without deliberation. What you feel, you feel as physical impulse to move. Your emotional instincts don't pause to consider consequences. They fire, and you respond. Aries Moon is cardinal fire applied to the emotional function: you initiate feeling through action, you process emotion by doing something about it. Your emotional safety comes from having options to pursue, challenges to meet, the capacity to move when the feeling hits. You don't sit with uncomfortable emotions. You act on them. Waiting to process feels like imprisonment to your Moon. The emotional challenge is learning that not every feeling requires immediate physical response, that some emotions need time to be felt before they're acted on. At your best, your Moon is emotional courage: the willingness to feel and act simultaneously without second-guessing the impulse.",
        "behavioral": "You feel suddenly, respond immediately, and move through emotions quickly. When you're upset, you do something about it now. When you're excited, you pursue it immediately. Your emotional rhythm is fast. You don't hold feelings for long. You express, act, and move on. This can look like impulsiveness but it's actually emotional honesty. You don't perform delayed response or measured consideration. You feel it and you show it. The shadow is that speed can override accuracy. You may respond to the first wave of feeling before the full emotion has arrived, or you may let your drive to act suppress feelings that need to be felt rather than solved. The work is creating enough pause between feeling and doing that your actions actually match what you're feeling rather than just serving the need to move.",
        "feed": "The Moon is moving through Aries in your chart. Your emotional body is at maximum speed and directness right now. This is a time for acting on feelings immediately, for expressing emotions without filtering, for trusting your instinctive impulse to move.",
        "sonic": "Your Moon in Aries contributes quick emotional shifts, bright impulsive melodic gestures, and rhythm that is fast and reactive. The emotional phrasing is short and direct, changing quickly in response to immediate feeling. The harmonic language serves speed over depth, creating emotional momentum rather than dwelling. Listen for music where emotions are expressed immediately and move on quickly, where the overall effect is emotional honesty through direct action rather than sustained reflection.",
    },
    "PLCMT_MOON_TAURUS": {
        "core": "Your Moon in Taurus means your emotional body needs physical comfort, material security, and the reassurance that safety won't be taken away. What you feel, you feel in your body. Your emotional instincts don't separate from physical sensation. They're the same thing. Taurus Moon is fixed earth applied to the emotional function: you sustain feeling through physical grounding, you process emotion by creating tangible safety. Your emotional security comes from having your physical needs met, from routines you can count on, from the assurance that what you've built won't disappear. You don't change emotional states quickly. You settle into feelings and stay there. Disruption to your physical environment feels like emotional threat to your Moon. The emotional challenge is releasing attachment to comfort when comfort has become stagnation. At your best, your Moon is emotional steadiness: the capacity to stay grounded when others are destabilized.",
        "behavioral": "You feel steadily, respond slowly, and need physical comfort to feel emotionally safe. When you're upset, you need familiar surroundings, physical touch, good food. When you're content, you want to stay exactly where you are. Your emotional rhythm is slow. You don't shift moods quickly. You feel deeply and hold feelings for a long time. This can look like stubbornness but it's actually emotional loyalty. You don't abandon feelings just because they're uncomfortable. You feel them through. The shadow is that holding can become hoarding. You may keep emotional attachments past their usefulness, or you may refuse to feel uncomfortable emotions because they disrupt your physical sense of safety. The work is allowing feelings to move through you even when moving means leaving comfort behind.",
        "feed": "The Moon is moving through Taurus, its exalted position, in your chart. Your emotional body is at maximum stability and physical groundedness right now. This is a time for creating comfort, for tending to physical needs, for trusting that safety can be built and maintained.",
        "sonic": "Your Moon in Taurus contributes sustained emotional tones, warm harmonic richness, and rhythm that is steady and grounded. The emotional phrasing is long and held, dwelling in each feeling rather than rushing through. The harmonic language is full and physically resonant, creating emotional security through sonic warmth. Listen for music where emotions are sustained and stable, where the overall effect is emotional comfort through physical presence.",
    },
    "PLCMT_MOON_GEMINI": {
        "core": "Your Moon in Gemini means your emotional body needs variety, mental stimulation, and the freedom to process feelings through talking. What you feel, you understand by naming it. Your emotional instincts don't sit in silence. They need words. Gemini Moon is mutable air applied to the emotional function: you adapt emotional states through conversation, you process feeling by thinking about it. Your emotional security comes from having someone to talk to, from understanding what you're feeling, from the mental flexibility to see your emotions from multiple angles. You don't stay in one feeling for long. You move between moods as new information arrives. Emotional intensity without relief feels suffocating to your Moon. The emotional challenge is recognizing that naming a feeling isn't the same as having it, that some emotions need to be felt in the body before they can be understood in the mind. At your best, your Moon is emotional intelligence: the capacity to observe and articulate what you're feeling without getting lost in it.",
        "behavioral": "You feel through talking, process emotions by explaining them, and need mental stimulation to stay emotionally engaged. When you're upset, you call someone. When you're confused, you talk it through. Your emotional rhythm is quick and changeable. You don't hold one feeling for long. You feel, name it, and move on. This can look like emotional superficiality but it's actually cognitive processing. You understand feelings by thinking about them. The shadow is that thinking can replace feeling. You may articulate emotions you're not actually having, or you may stay so busy mentally that you never drop into your emotional body. The work is allowing feelings to exist before you name them, trusting that some emotions reveal themselves through silence rather than conversation.",
        "feed": "The Moon is moving through Gemini in your chart. Your emotional body needs variety, conversation, and mental engagement right now. This is a time for talking through feelings, for understanding emotions intellectually, for staying curious about your emotional life.",
        "sonic": "Your Moon in Gemini contributes quick emotional shifts, light conversational phrasing, and rhythm that is nimble and changeable. The emotional tone is bright and articulate, moving between feelings easily. The harmonic language is transparent and simple, serving communication rather than depth. Listen for music where emotions are named and understood rather than dwelled in, where the overall effect is emotional intelligence through mental clarity.",
    },
    "PLCMT_MOON_CANCER": {
        "core": "Your Moon in Cancer, its home sign, means your emotional body is at maximum sensitivity and depth. What you feel, you feel completely. Your emotional instincts have direct access to your needs without filtering. They operate at full strength. Cancer Moon is cardinal water at its source: you initiate emotional safety, you create the sanctuary where feelings can exist without performance. Your emotional security comes from privacy, from being genuinely cared for, from the assurance that your vulnerability won't be exploited. You don't have light feelings. Every emotion is felt fully, absorbed into your body, and becomes part of your emotional archive. Current feelings carry the weight of everything that's come before. Emotional exposure without safety feels dangerous to your Moon. The emotional challenge is protecting yourself from overwhelm when your nervous system is this permeable, and releasing old wounds rather than carrying them indefinitely. At your best, your Moon is emotional sanctuary: the capacity to create safety for yourself and others where vulnerability is possible.",
        "behavioral": "You feel deeply, protect thoroughly, and need emotional privacy to process what you absorb. When you're upset, you retreat. When you're safe, you nurture. Your emotional rhythm is tidal. You need time alone to process what you've absorbed from others, then you return when your emotional reserves are restored. This can look like withdrawal but it's actually self-care. You can't separate your feelings from others' feelings easily. You absorb emotional atmospheres. The shadow is that protection can become isolation. You may defend yourself so thoroughly that no one can reach you, or you may hold onto emotional wounds so tightly that healing becomes impossible. The work is allowing yourself to be cared for the way you care for others, and releasing what's been carried past its purpose.",
        "feed": "The Moon is moving through Cancer, its home sign, in your chart. Your emotional body is at maximum sensitivity and depth right now. This is a time for honoring feelings fully, for creating emotional safety, for tending to what your heart actually needs.",
        "sonic": "Your Moon in Cancer contributes flowing emotional phrases, modal harmonic warmth, and rhythm that ebbs and flows organically. The emotional phrasing is long and curved, following feeling rather than structure. The harmonic language is rich with suspensions, creating emotional depth and tenderness. Listen for music where the emotional body is fully open, where feelings are held rather than pushed through, where the overall effect is profound emotional presence.",
    },
    "PLCMT_MOON_LEO": {
        "core": "Your Moon in Leo means your emotional body needs recognition, creative expression, and the assurance that your feelings matter. What you feel, you feel dramatically. Your emotional instincts don't stay private. They need to be seen. Leo Moon is fixed fire applied to the emotional function: you sustain emotional warmth, you express feeling generously, you make your emotional life visible. Your emotional security comes from being appreciated, from creative outlets for what you're feeling, from the confidence that your emotional experience is valid and worthy of attention. You don't have quiet feelings. Every emotion wants to be expressed, shared, witnessed. Emotional invisibility feels like rejection to your Moon. The emotional challenge is distinguishing between genuine need for recognition and demand for constant attention. At your best, your Moon is emotional generosity: the capacity to feel fully and share those feelings without needing others to perform matching intensity.",
        "behavioral": "You feel proudly, express generously, and need your emotions to be witnessed and valued. When you're happy, everyone knows it. When you're hurt, you don't hide it. Your emotional rhythm is steady and warm. You sustain feelings rather than cycling through them quickly. This can look like emotional performance but it's actually genuine expression. You feel deeply and you show it. The shadow is that visibility can become the goal rather than the byproduct. You may perform emotions you're not actually having because being seen matters more than being accurate, or you may demand recognition for feelings others aren't equipped to validate. The work is allowing your emotional life to be witnessed without requiring constant audience, and creating from genuine feeling rather than need for applause.",
        "feed": "The Moon is moving through Leo in your chart. Your emotional body needs recognition, creative expression, and generous warmth right now. This is a time for making feelings visible, for expressing emotions creatively, for trusting that what you feel matters.",
        "sonic": "Your Moon in Leo contributes warm emotional presence, generous melodic expression, and rhythm that is confident and sustained. The emotional phrasing is bold and expressive, taking up space without apology. The harmonic language is rich and full, creating emotional warmth through solar confidence. Listen for music where emotions are expressed generously and without reservation, where the overall effect is emotional radiance and the pleasure of being fully seen.",
    },
    "PLCMT_MOON_VIRGO": {
        "core": "Your Moon in Virgo means your emotional body needs order, usefulness, and the reassurance that you're handling feelings correctly. What you feel, you analyze. Your emotional instincts don't trust spontaneous expression. They need to be examined first. Virgo Moon is mutable earth applied to the emotional function: you adapt emotional responses through analysis, you process feeling by understanding what's causing it. Your emotional security comes from knowing you're managing your emotions well, from being useful even when you're feeling, from the sense that your emotional life is under control. You don't express feelings without first checking whether the expression is appropriate. Every emotion gets analyzed before it's allowed. Emotional messiness feels dangerous to your Moon. The emotional challenge is recognizing that feelings don't have to be perfect or useful to be valid, that emotional spontaneity isn't the same as emotional dysfunction. At your best, your Moon is emotional competence: the capacity to understand and manage what you're feeling without letting analysis replace the feeling itself.",
        "behavioral": "You feel carefully, analyze thoroughly, and need your emotions to be useful and appropriate. When you're upset, you try to figure out why. When you're anxious, you organize something. Your emotional rhythm is controlled and measured. You don't let feelings run wild. This can look like emotional repression but it's actually emotional management. You're trying to feel correctly. The shadow is that analyzing can prevent feeling. You may understand your emotions so thoroughly that you never actually have them, or you may reject feelings that don't serve a clear purpose. The work is allowing emotions to exist before you judge them, trusting that messiness and usefulness aren't mutually exclusive.",
        "feed": "The Moon is moving through Virgo in your chart. Your emotional body needs order, analysis, and the assurance of doing feelings correctly right now. This is a time for understanding emotions, for managing feelings skillfully, for making your emotional life useful.",
        "sonic": "Your Moon in Virgo contributes precise emotional articulation, detailed harmonic voice leading, and rhythm that is exact and controlled. The emotional phrasing is careful and measured, every note serving the whole. The harmonic language is clean and functional, creating emotional clarity through precision. Listen for music where emotions are understood and managed, where the overall effect is emotional competence through careful attention.",
    },
    "PLCMT_MOON_LIBRA": {
        "core": "Your Moon in Libra means your emotional body needs harmony, aesthetic rightness, and the assurance that relationships are balanced. What you feel, you feel in relation to others. Your emotional instincts don't operate in isolation. They respond to relational dynamics. Libra Moon is cardinal air applied to the emotional function: you initiate emotional balance, you create harmony where discord exists, you feel through relationship rather than in solitude. Your emotional security comes from having relationships that work, from environments that are aesthetically pleasing, from the sense that fairness is being maintained. You don't feel comfortable when relationships are out of balance. Every emotional disturbance in your connections gets registered and addressed. Conflict for its own sake feels unbearable to your Moon. The emotional challenge is recognizing that your need for harmony can suppress legitimate feelings, that peace and honesty aren't always compatible. At your best, your Moon is emotional diplomacy: the capacity to feel what's happening between people and create the conditions where everyone's needs can coexist.",
        "behavioral": "You feel relationally, respond diplomatically, and need aesthetic and interpersonal harmony to feel emotionally safe. When relationships are tense, you feel tense. When your environment is beautiful, you feel at peace. Your emotional rhythm is balanced and measured. You don't express feelings that would disrupt harmony without weighing whether the disruption is worth it. This can look like people-pleasing but it's actually genuine care for relational balance. The shadow is that harmony can become more important than honesty. You may suppress feelings that would create necessary conflict, or you may prioritize aesthetics over emotional authenticity. The work is allowing yourself to feel and express what's real even when it disrupts the peace you've worked to create.",
        "feed": "The Moon is moving through Libra in your chart. Your emotional body needs harmony, beauty, and relational balance right now. This is a time for creating peace, for feeling through relationship, for trusting that fairness can be maintained even when emotions are complicated.",
        "sonic": "Your Moon in Libra contributes balanced emotional phrasing, elegant harmonic progressions, and rhythm that is graceful and measured. The emotional tone is refined and diplomatic, creating harmony through proportion. The harmonic language is sophisticated and fair, serving all voices equally. Listen for music where emotions are balanced and aesthetically right, where the overall effect is relational harmony and the pleasure of emotional equilibrium.",
    },
    "PLCMT_MOON_SCORPIO": {
        "core": "Your Moon in Scorpio means your emotional body needs depth, truth, and the assurance that what you're feeling is real. What you feel, you feel intensely. Your emotional instincts don't trust surfaces. They penetrate to what's underneath. Scorpio Moon is fixed water at maximum concentration: you hold emotional intensity without diffusing it, you transform through emotional crisis, you feel what others can't bear. Your emotional security comes from knowing the truth even when the truth is painful, from having power acknowledged rather than denied, from emotional bonds that go to the depths. You don't have light feelings. Every emotion is felt at full force, examined for what it's hiding, used to understand power dynamics. Emotional superficiality feels like betrayal to your Moon. The emotional challenge is learning that not everything needs to be felt at maximum intensity, that some emotions can be light without being fake. At your best, your Moon is emotional truth: the capacity to face what's real in your emotional life and transform through the confrontation.",
        "behavioral": "You feel deeply, trust slowly, and need emotional truth even when truth is uncomfortable. When you're hurt, you don't forget it. When you care, you care completely. Your emotional rhythm is intense and sustained. You don't cycle through feelings quickly. You feel something fully, for a long time, until it's exhausted. This can look like holding grudges but it's actually emotional honesty. You don't pretend to feel something you don't, and you don't pretend not to feel something you do. The shadow is that intensity can become control. You may try to manage emotions through power rather than vulnerability, or you may refuse to feel anything that doesn't reach crisis-level depth. The work is allowing emotional connection that doesn't require total merger or complete exposure.",
        "feed": "The Moon is moving through Scorpio in your chart. Your emotional body needs depth, truth, and transformative intensity right now. This is a time for facing real feelings, for emotional honesty even when painful, for wielding emotional power consciously.",
        "sonic": "Your Moon in Scorpio contributes dense emotional textures, chromatic harmonic movement, and rhythm that is relentless and driving. The emotional phrasing is concentrated and penetrating, digging beneath surface expression. The harmonic language is dark and complex, creating emotional weight through tension. Listen for music where emotions are felt at maximum intensity, where the overall effect is transformative depth and the willingness to face what others avoid.",
    },
    "PLCMT_MOON_SAGITTARIUS": {
        "core": "Your Moon in Sagittarius means your emotional body needs freedom, optimism, and the assurance that your feelings aren't trapping you. What you feel, you feel as possibility. Your emotional instincts don't dwell in darkness. They reach for meaning. Sagittarius Moon is mutable fire applied to the emotional function: you adapt emotional states by reframing them philosophically, you process feeling by finding what it means. Your emotional security comes from having options, from understanding your emotions as part of larger patterns, from the confidence that no feeling is permanent. You don't stay stuck in emotions. You feel them, find the lesson, and move on. Emotional heaviness without relief feels suffocating to your Moon. The emotional challenge is recognizing that not every feeling has a lesson, that some emotions need to be felt in their darkness before they can be reframed into light. At your best, your Moon is emotional optimism: the capacity to feel fully and trust that meaning will emerge even from painful emotions.",
        "behavioral": "You feel optimistically, process philosophically, and need emotional freedom to stay engaged. When you're upset, you look for the larger meaning. When you're trapped emotionally, you need to move. Your emotional rhythm is expansive and changeable. You feel something, understand it, and move on quickly. This can look like emotional avoidance but it's actually emotional reframing. You don't sit in pain when you can find the lesson and release it. The shadow is that reaching for meaning can skip the feeling. You may philosophize emotions you haven't actually had, or you may use optimism to bypass grief that needs to be felt before it can be released. The work is allowing yourself to feel the full weight of emotions before you reframe them into lessons.",
        "feed": "The Moon is moving through Sagittarius in your chart. Your emotional body needs freedom, meaning, and optimistic expansion right now. This is a time for finding the lesson in feelings, for trusting that emotions aren't traps, for maintaining hope even when emotions are difficult.",
        "sonic": "Your Moon in Sagittarius contributes expansive emotional range, optimistic harmonic progressions, and rhythm that is energetic and forward-moving. The emotional phrasing is wide and reaching, finding possibility in every feeling. The harmonic language is bright and open, creating emotional freedom through scope. Listen for music where emotions are felt with optimism and released easily, where the overall effect is emotional expansion and trust that meaning will emerge.",
    },
    "PLCMT_MOON_CAPRICORN": {
        "core": "Your Moon in Capricorn means your emotional body needs structure, competence, and the assurance that feelings can be managed responsibly. What you feel, you feel as duty. Your emotional instincts don't trust vulnerability without purpose. They need to serve something. Capricorn Moon is cardinal earth applied to the emotional function: you initiate emotional self-control, you build structures that contain feeling, you process emotions through responsibility. Your emotional security comes from being needed, from handling your feelings maturely, from the sense that your emotional life is under control. You don't express feelings that don't serve a purpose. Every emotion gets evaluated for whether it's appropriate to feel. Emotional messiness feels like failure to your Moon. The emotional challenge is recognizing that feelings don't have to be useful or mature to be valid, that emotional vulnerability isn't the same as emotional weakness. At your best, your Moon is emotional maturity: the capacity to feel deeply while maintaining the structure that allows life to continue functioning.",
        "behavioral": "You feel responsibly, control thoroughly, and need your emotions to serve something useful. When you're upset, you still get your work done. When you're overwhelmed, you take on more responsibility. Your emotional rhythm is controlled and structured. You don't let feelings interfere with what needs to be done. This can look like emotional suppression but it's actually emotional discipline. You feel, but you don't let feeling override duty. The shadow is that control can become isolation. You may carry emotional burdens alone because asking for help feels like weakness, or you may refuse to feel emotions that don't serve clear purposes. The work is allowing yourself to be cared for, to need without it being failure, to feel without it having to be productive.",
        "feed": "The Moon is moving through Capricorn in your chart. Your emotional body needs structure, responsibility, and mature self-control right now. This is a time for managing feelings skillfully, for allowing emotions to exist without letting them disrupt necessary work, for trusting that vulnerability and competence can coexist.",
        "sonic": "Your Moon in Capricorn contributes structured emotional development, traditional harmonic progressions, and rhythm that is steady and patient. The emotional phrasing is measured and controlled, building systematically rather than expressing spontaneously. The harmonic language is solid and mature, creating emotional security through structure. Listen for music where emotions are felt responsibly and contained appropriately, where the overall effect is emotional maturity and the dignity of sustained self-control.",
    },
    "PLCMT_MOON_AQUARIUS": {
        "core": "Your Moon in Aquarius means your emotional body needs detachment, intellectual understanding, and the freedom to feel without being consumed. What you feel, you observe. Your emotional instincts don't merge. They analyze from outside. Aquarius Moon is fixed air applied to the emotional function: you sustain intellectual distance from emotions, you process feeling by thinking about it objectively, you maintain autonomy even in emotional connection. Your emotional security comes from understanding what you're feeling, from having space from emotional intensity, from the confidence that your feelings won't trap you. You don't drown in emotions. You observe them as information. Emotional fusion feels dangerous to your Moon. The emotional challenge is recognizing that observing feelings isn't the same as having them, that some emotions need to be felt in the body before they can be understood in the mind. At your best, your Moon is emotional objectivity: the capacity to feel fully while maintaining enough distance to see what you're feeling clearly.",
        "behavioral": "You feel objectively, process intellectually, and need emotional space to stay connected. When you're upset, you think about why. When someone needs emotional support, you help them understand their situation rather than just feeling with them. Your emotional rhythm is detached and steady. You don't get swept up in emotional intensity. This can look like coldness but it's actually intellectual processing. You feel through thinking. The shadow is that thinking can replace feeling. You may understand emotions you're not actually having, or you may use intellectual distance to avoid vulnerability that's necessary for connection. The work is allowing yourself to feel before you analyze, to be in the emotion before you step outside it to observe.",
        "feed": "The Moon is moving through Aquarius in your chart. Your emotional body needs detachment, intellectual understanding, and the freedom to observe feelings right now. This is a time for thinking about emotions objectively, for maintaining autonomy even in connection, for trusting that distance and care aren't mutually exclusive.",
        "sonic": "Your Moon in Aquarius contributes cool emotional tone, unconventional harmonic progressions, and rhythm that is irregular and detached. The emotional phrasing is intellectual rather than visceral, observing feeling rather than expressing it directly. The harmonic language is unexpected and innovative, creating emotional interest through detachment. Listen for music where emotions are felt at a distance and understood intellectually, where the overall effect is emotional objectivity and the freedom that comes from observation rather than merger.",
    },
    "PLCMT_MOON_PISCES": {
        "core": "Your Moon in Pisces means your emotional body needs flow, imagination, and the freedom to feel what's beyond personal boundaries. What you feel, you feel universally. Your emotional instincts don't stay inside your own experience. They merge with collective currents. Pisces Moon is mutable water at maximum permeability: you adapt to emotional atmospheres, you dissolve rigid boundaries between self and other, you process feeling through imaginative and spiritual connection. Your emotional security comes from creative expression, from compassionate service, from the sense that your feelings are part of something larger than individual ego. You don't separate your emotions from others' emotions easily. Every feeling carries resonance beyond your personal story. Emotional boundaries that are too rigid feel isolating to your Moon. The emotional challenge is maintaining enough self-definition that compassion doesn't become self-erasure, that feeling for others doesn't replace feeling for yourself. At your best, your Moon is emotional compassion: the capacity to feel into others' experience without losing yourself in it.",
        "behavioral": "You feel universally, absorb emotionally, and need creative or spiritual outlets for what you carry. When you're overwhelmed, you create something. When someone is suffering, you feel it as your own. Your emotional rhythm is fluid and unanchored. You don't maintain clear boundaries between your feelings and others' feelings. This can look like being easily influenced but it's actually emotional permeability. You're porous to emotional atmospheres. The shadow is that permeability can become dissolution. You may lose yourself in others' emotions, or you may escape into imagination rather than feeling what's real in your own body. The work is creating enough boundary that you can serve compassionately without sacrificing your own emotional needs.",
        "feed": "The Moon is moving through Pisces in your chart. Your emotional body needs flow, imagination, and spiritual connection right now. This is a time for feeling universally, for serving compassionately, for trusting that boundaries can soften without dissolving completely.",
        "sonic": "Your Moon in Pisces contributes floating emotional ambiguity, dissolving harmonic boundaries, and rhythm that is fluid and unanchored. The emotional phrasing is long and wandering, moving like water rather than following structure. The harmonic language is mysterious and unresolved, creating emotional space that feels universal rather than personal. Listen for music where emotions flow and merge, where boundaries dissolve, where the overall effect is spiritual connection and the feeling of touching something larger than individual experience.",
    },
}


def escape_ts(s: str) -> str:
    return s.replace("\\", "\\\\").replace("`", "\\`")


def replace_field(block: str, field: str, value: str) -> str:
    pattern = rf"(    {field}: `)(?:[^`\\]|\\.)*(`)"
    repl = rf"\1{escape_ts(value)}\2"
    new_block, n = re.subn(pattern, repl, block, count=1, flags=re.DOTALL)
    if n != 1:
        raise ValueError(f"Failed to replace {field}")
    return new_block


def main() -> None:
    text = PATH.read_text(encoding="utf-8")
    for key, fields in UPDATES.items():
        m = re.search(rf"  {key}: \{{(.*?)\n  \}},", text, re.DOTALL)
        if not m:
            raise SystemExit(f"Entry not found: {key}")
        block = m.group(0)
        for field in ("core", "behavioral", "feed", "sonic"):
            block = replace_field(block, field, fields[field])
        text = text[: m.start()] + block + text[m.end() :]
    PATH.write_text(text, encoding="utf-8")
    print(f"Updated {len(UPDATES)} entries in {PATH.name}")


if __name__ == "__main__":
    main()
