"""Apply Phase 1 Sun/Moon in-house placement rewrites to insight-library-placements-house.ts."""
import re
from pathlib import Path

PATH = Path(__file__).resolve().parents[1] / "vnext/projection/insight-library/insight-library-placements-house.ts"

UPDATES: dict[str, dict[str, str]] = {
    "PLCMT_SUN_HOUSE1": {
        "core": "Your Sun in the 1st house means your sense of purpose is organized around self-expression, immediate presence, and being visible as who you actually are. Your identity needs to be seen. The 1st house is the domain of immediate self-presentation, physical appearance, and how you arrive in any room. Your Sun here makes your conscious self inseparable from how others perceive you. You experience yourself through being witnessed. Your vitality comes from showing up fully, from making an impression, from the assurance that who you are is obvious without explanation. You don't hide. Your presence announces itself. The challenge is distinguishing between genuine self-expression and performance for its own sake, between being seen for who you are and being seen because visibility itself feels necessary.",
        "behavioral": "You show up boldly, lead naturally, and need your presence to register. When you walk into a room, people notice. When you speak, you expect attention. Your approach to life is direct and immediate. You don't wait to be invited into spaces. You enter and assume your place. This isn't arrogance. It's solar confidence applied to self-presentation. You understand that visibility itself is part of your purpose. The shadow is that visibility can become the goal rather than the byproduct. You may perform identity rather than express it, or you may need constant audience to feel like yourself. The work is ensuring that what you're showing is actually who you are, not just what gets the strongest response.",
        "feed": "The Sun is moving through your 1st house. Your conscious vitality and sense of purpose are focused on self-expression, physical presence, and being visible right now. This is a time for showing up fully, for making yourself known, for trusting that your presence matters.",
        "sonic": "Your Sun in the 1st house contributes bold melodic statements in the foreground, strong rhythmic presence, and harmonic clarity that demands attention. The musical identity is immediate and undeniable. Listen for the lead voice that announces itself without hesitation, where the overall effect is confident presence and the pleasure of being heard without ambiguity.",
    },
    "PLCMT_SUN_HOUSE2": {
        "core": "Your Sun in the 2nd house means your sense of purpose is organized around building resources, creating tangible value, and knowing what you actually have. Your identity is connected to material reality. The 2nd house is the domain of money, possessions, and self-worth derived from what you can build and keep. Your Sun here makes your conscious self inseparable from your relationship to resources. You experience yourself through what you create and own. Your vitality comes from building something lasting, from financial security, from the assurance that what you have is actually yours. You don't separate identity from material reality. Your worth is proven through what you build. The challenge is distinguishing between genuine value creation and hoarding for its own sake, between security and accumulation that serves anxiety rather than purpose.",
        "behavioral": "You build steadily, value tangibly, and need material security to feel like yourself. When you have resources, you feel powerful. When you lack them, you feel diminished. Your approach to life is through accumulation and skill development. You don't trust abstract promises. You trust what you can touch and count. This isn't materialism. It's identity built through tangible creation. You understand that resources are how you express purpose in the physical world. The shadow is that value can become the only measure. You may judge yourself entirely by what you have, or you may refuse to pursue goals that don't generate obvious resources. The work is ensuring that what you're building actually serves who you are, not just what you think proves your worth.",
        "feed": "The Sun is moving through your 2nd house. Your conscious vitality and sense of purpose are focused on resources, value creation, and material security right now. This is a time for building what's tangible, for understanding your worth, for creating resources that actually serve your life.",
        "sonic": "Your Sun in the 2nd house contributes rich harmonic textures, sustained melodic development, and rhythm that accumulates rather than disperses. The musical identity is built through layering and substance. Listen for the quality of accumulated value, where every element adds weight, where the overall effect is tangible presence and the satisfaction of building something that endures.",
    },
    "PLCMT_SUN_HOUSE3": {
        "core": "Your Sun in the 3rd house means your sense of purpose is organized around communication, learning, and connecting ideas to people. Your identity is inseparable from how you think and speak. The 3rd house is the domain of immediate environment, siblings, short trips, and everyday communication. Your Sun here makes your conscious self depend on mental activity and social exchange. You experience yourself through conversation and curiosity. Your vitality comes from learning new things, from explaining what you know, from the assurance that your ideas are reaching others. You don't exist in isolation. Your identity forms through dialogue. The challenge is distinguishing between genuine curiosity and mental restlessness, between communication that serves connection and talking that's just filling silence.",
        "behavioral": "You think actively, communicate constantly, and need mental stimulation to feel alive. When you're learning, you're engaged. When you're isolated from conversation, you wilt. Your approach to life is through questions and explanations. You don't sit quietly with information. You share it, test it, connect it to other ideas. This isn't superficiality. It's identity built through intellectual exchange. You understand that who you are emerges through what you think and say. The shadow is that communication can become noise. You may talk without having anything to communicate, or you may need constant mental activity to avoid deeper self-examination. The work is ensuring that what you're learning and sharing actually serves understanding, not just the need to keep your mind busy.",
        "feed": "The Sun is moving through your 3rd house. Your conscious vitality and sense of purpose are focused on communication, learning, and immediate connections right now. This is a time for conversations, for curiosity, for engaging your local environment and the people in it.",
        "sonic": "Your Sun in the 3rd house contributes nimble melodic phrases, conversational rhythmic patterns, and harmonic movement that connects ideas. The musical identity is expressed through dialogue and quick exchange. Listen for the quality of active communication, where ideas move between voices, where the overall effect is intellectual engagement and the pleasure of connection through language.",
    },
    "PLCMT_SUN_HOUSE4": {
        "core": "Your Sun in the 4th house means your sense of purpose is organized around home, roots, and building emotional foundation. Your identity is connected to where you come from and what you're creating as sanctuary. The 4th house is the domain of family, ancestry, private life, and the emotional bedrock beneath public presentation. Your Sun here makes your conscious self inseparable from your need for emotional security and domestic grounding. You experience yourself through your relationship to home and lineage. Your vitality comes from building sanctuary, from understanding your roots, from the assurance that your private life is solid even when your public life is unstable. You don't separate identity from foundation. Who you are is built on where you come from and what you're creating as home. The challenge is distinguishing between honoring your roots and being trapped by them, between building sanctuary and hiding from the world.",
        "behavioral": "You build from the ground up, protect your private life, and need emotional foundation to express yourself publicly. When your home life is stable, you can show up in the world. When it's chaotic, you can't function. Your approach to life is through creating emotional security first. You don't build outward without building inward. This isn't weakness. It's identity built on emotional bedrock. You understand that public expression requires private foundation. The shadow is that foundation can become fortress. You may protect your private life so thoroughly that no one gets in, or you may refuse public visibility because it feels like betrayal of your need for privacy. The work is ensuring that the sanctuary you're building actually supports your life rather than replacing it.",
        "feed": "The Sun is moving through your 4th house. Your conscious vitality and sense of purpose are focused on home, roots, and emotional foundation right now. This is a time for building sanctuary, for understanding where you come from, for tending to your private emotional life.",
        "sonic": "Your Sun in the 4th house contributes deep harmonic foundations, emotionally resonant melodic lines, and rhythm that feels grounded and cyclical. The musical identity is built from the bass up, creating emotional security through harmonic stability. Listen for the quality of foundational support, where the root is always present, where the overall effect is emotional grounding and the safety that comes from solid bedrock.",
    },
    "PLCMT_SUN_HOUSE5": {
        "core": "Your Sun in the 5th house means your sense of purpose is organized around creative expression, play, and the joy of making things for the pleasure of making them. Your identity is inseparable from your creative output and capacity for pleasure. The 5th house is the domain of art, romance, children, and activities pursued purely for enjoyment. Your Sun here makes your conscious self depend on creative freedom and the right to play. You experience yourself through what you create and how you enjoy yourself. Your vitality comes from making things, from romantic connection, from the assurance that pleasure is legitimate and necessary. You don't separate identity from creative joy. Who you are is what you make and how you play. The challenge is distinguishing between creative expression that serves genuine joy and performance that's serving ego validation.",
        "behavioral": "You create naturally, play seriously, and need outlets for creative expression to feel alive. When you're making something, you're engaged. When you're blocked creatively, you're depressed. Your approach to life is through joy and self-expression. You don't work without finding the pleasure in it. This isn't frivolity. It's identity built through creative play. You understand that who you are emerges through what you make for the pleasure of making it. The shadow is that pleasure can become the only goal. You may pursue joy so relentlessly that you avoid necessary difficulty, or you may need constant creative validation to feel like yourself. The work is ensuring that what you're creating serves genuine expression, not just the need to be seen as creative.",
        "feed": "The Sun is moving through your 5th house. Your conscious vitality and sense of purpose are focused on creativity, pleasure, and joyful expression right now. This is a time for making things, for playing, for allowing yourself to enjoy life without justifying the enjoyment.",
        "sonic": "Your Sun in the 5th house contributes playful melodic invention, colorful harmonic choices, and rhythm that prioritizes pleasure over precision. The musical identity is expressed through creative freedom and joyful experimentation. Listen for the quality of play, where every phrase serves delight, where the overall effect is creative pleasure and the satisfaction of making for the sake of making.",
    },
    "PLCMT_SUN_HOUSE6": {
        "core": "Your Sun in the 6th house means your sense of purpose is organized around useful work, health maintenance, and making yourself valuable through competence. Your identity is connected to your capacity to serve and function well. The 6th house is the domain of daily routines, health, employment, and the work that keeps life running. Your Sun here makes your conscious self inseparable from your ability to be useful and maintain your physical functioning. You experience yourself through what you do every day and how well your body works. Your vitality comes from being competent, from having routines that support health, from the assurance that you're contributing something useful. You don't separate identity from daily function. Who you are is proven through what you do reliably and well. The challenge is distinguishing between useful service and compulsive work that serves anxiety rather than purpose.",
        "behavioral": "You work consistently, maintain routines, and need to feel useful to feel like yourself. When you're being productive, you're at peace. When you're idle, you're anxious. Your approach to life is through daily practice and skill refinement. You don't trust grand visions. You trust what you do every single day. This isn't drudgery. It's identity built through reliable function. You understand that who you are emerges through what you do when no one's watching. The shadow is that usefulness can become the only measure. You may work compulsively to avoid feeling worthless, or you may refuse to rest because rest feels like failure. The work is ensuring that your service actually honors your health rather than destroying it.",
        "feed": "The Sun is moving through your 6th house. Your conscious vitality and sense of purpose are focused on useful work, health routines, and daily practice right now. This is a time for refining your skills, for tending to your body, for making yourself valuable through competent service.",
        "sonic": "Your Sun in the 6th house contributes precise rhythmic execution, functional harmonic progressions, and melodic lines that serve the whole rather than standing out. The musical identity is expressed through reliable craft and useful skill. Listen for the quality of competent work, where every element functions smoothly, where the overall effect is useful beauty and the satisfaction of work done well.",
    },
    "PLCMT_SUN_HOUSE7": {
        "core": "Your Sun in the 7th house means your sense of purpose is organized around partnership, relationship, and understanding yourself through others. Your identity is inseparable from how you relate one-on-one. The 7th house is the domain of committed partnership, contracts, and the experience of the other as equal. Your Sun here makes your conscious self depend on having significant relationships where you're genuinely seen and met. You experience yourself through partnership. Your vitality comes from relating deeply, from negotiations that honor both sides, from the assurance that you're in relationships that matter. You don't know who you are in isolation. Your identity forms through committed connection. The challenge is distinguishing between genuine partnership and losing yourself in relationships, between being defined through connection and having no definition without it.",
        "behavioral": "You relate naturally, partner seriously, and need significant relationships to feel complete. When you're in genuine partnership, you thrive. When you're alone too long, you lose touch with yourself. Your approach to life is through relationship. You don't make major decisions without considering how they affect your partnerships. This isn't codependence. It's identity built through relational exchange. You understand that who you are emerges through how you relate to equals. The shadow is that partnership can become required rather than chosen. You may stay in relationships past their purpose because being alone feels like losing yourself, or you may give up too much autonomy to maintain connection. The work is ensuring that partnerships actually serve mutual growth rather than just preventing aloneness.",
        "feed": "The Sun is moving through your 7th house. Your conscious vitality and sense of purpose are focused on partnership, relationship, and how you relate to equals right now. This is a time for committed connection, for seeing yourself through others, for honoring genuine partnership.",
        "sonic": "Your Sun in the 7th house contributes balanced dialogue between voices, harmonic progressions that serve both parts equally, and rhythm that creates genuine exchange. The musical identity is expressed through partnership rather than solo performance. Listen for the quality of conversation between equals, where neither dominates, where the overall effect is relational balance and the pleasure of genuine meeting.",
    },
    "PLCMT_SUN_HOUSE8": {
        "core": "Your Sun in the 8th house means your sense of purpose is organized around transformation, shared resources, and facing what's hidden. Your identity is connected to depth, power, and psychological truth. The 8th house is the domain of death, regeneration, other people's resources, and intimacy that goes beyond surface connection. Your Sun here makes your conscious self inseparable from your capacity to transform through crisis and merge completely in relationship. You experience yourself through intensity and change. Your vitality comes from going deep, from confronting shadow material, from the assurance that you can survive complete transformation. You don't stay on surfaces. Your identity forms through death and rebirth cycles. The challenge is distinguishing between transformation that serves growth and crisis that serves compulsive intensity.",
        "behavioral": "You go deep naturally, transform through crisis, and need psychological intensity to feel alive. When life is challenging, you're engaged. When it's comfortable, you're bored. Your approach to life is through confrontation with what's hidden. You don't accept comfortable stories. You dig for what's real beneath them. This isn't masochism. It's identity built through transformation. You understand that who you are emerges through what you survive and how you change. The shadow is that intensity can become the only valid experience. You may create crisis to feel alive, or you may refuse connection that doesn't reach merger-level depth. The work is ensuring that transformation actually serves growth rather than just satisfying your need for intensity.",
        "feed": "The Sun is moving through your 8th house. Your conscious vitality and sense of purpose are focused on transformation, depth, and psychological truth right now. This is a time for facing what's hidden, for allowing necessary death and regeneration, for wielding power consciously.",
        "sonic": "Your Sun in the 8th house contributes dark harmonic density, transformative melodic development, and rhythm that builds toward crisis and release. The musical identity is expressed through intensity and change. Listen for the quality of transformation, where tension builds to breaking point, where the overall effect is psychological depth and the power that comes from surviving complete change.",
    },
    "PLCMT_SUN_HOUSE9": {
        "core": "Your Sun in the 9th house means your sense of purpose is organized around meaning-making, exploration, and expanding beyond what you currently know. Your identity is connected to learning, travel, and philosophical understanding. The 9th house is the domain of higher education, long journeys, belief systems, and the search for truth. Your Sun here makes your conscious self inseparable from your need to understand life in larger contexts. You experience yourself through what you're learning and where you're going. Your vitality comes from expanding your worldview, from traveling to unfamiliar places, from the assurance that there's always more to know. You don't settle into comfortable certainty. Your identity forms through ongoing exploration. The challenge is distinguishing between genuine learning and restless escape from commitment.",
        "behavioral": "You explore naturally, philosophize constantly, and need to keep learning to feel alive. When you're discovering something new, you're engaged. When you're stuck in familiar territory, you wilt. Your approach to life is through questions and expansion. You don't accept current understanding as final. This isn't dilettantism. It's identity built through meaning-making. You understand that who you are emerges through what you learn and how you expand. The shadow is that exploration can become avoidance. You may keep learning to avoid actually applying what you know, or you may use philosophy to escape from practical reality. The work is ensuring that exploration actually deepens understanding rather than just keeping you moving.",
        "feed": "The Sun is moving through your 9th house. Your conscious vitality and sense of purpose are focused on exploration, learning, and expanding your worldview right now. This is a time for travel, for philosophical inquiry, for reaching beyond what you currently know and believe.",
        "sonic": "Your Sun in the 9th house contributes expansive melodic range, harmonic progressions that reach outward, and rhythm that creates forward momentum. The musical identity is expressed through exploration and scope. Listen for the quality of expansion, where every phrase reaches further, where the overall effect is philosophical optimism and the pleasure of learning something that changes how you see everything.",
    },
    "PLCMT_SUN_HOUSE10": {
        "core": "Your Sun in the 10th house means your sense of purpose is organized around achievement, public recognition, and building something visible in the world. Your identity is inseparable from your career and public reputation. The 10th house is the domain of vocation, authority, and how you're known publicly. Your Sun here makes your conscious self depend on having a clear professional direction and being recognized for your competence. You experience yourself through what you achieve publicly. Your vitality comes from career success, from being respected in your field, from the assurance that your work matters beyond your private life. You don't separate identity from public achievement. Who you are is proven through what you build in the world. The challenge is distinguishing between genuine vocation and achievement that serves only ego validation or external approval.",
        "behavioral": "You work toward visible goals, build your public reputation, and need career success to feel like yourself. When your professional life is thriving, you're confident. When it's stalled, you feel lost. Your approach to life is through achievement and recognition. You don't hide your ambition. This isn't vanity. It's identity built through public contribution. You understand that who you are emerges through what you accomplish where others can see it. The shadow is that achievement can become the only measure. You may sacrifice everything for career success, or you may judge yourself entirely by public recognition. The work is ensuring that what you're building publicly actually reflects who you are privately.",
        "feed": "The Sun is moving through your 10th house. Your conscious vitality and sense of purpose are focused on career, public achievement, and building your reputation right now. This is a time for professional ambition, for being visible in your work, for earning recognition through demonstrated competence.",
        "sonic": "Your Sun in the 10th house contributes structured melodic development, authoritative harmonic progressions, and rhythm that builds toward public climax. The musical identity is expressed through visible achievement and earned mastery. Listen for the quality of professional excellence, where craft is undeniable, where the overall effect is public recognition and the satisfaction of building something that endures beyond private experience.",
    },
    "PLCMT_SUN_HOUSE11": {
        "core": "Your Sun in the 11th house means your sense of purpose is organized around collective good, friendship networks, and working toward shared vision. Your identity is connected to groups and future possibilities. The 11th house is the domain of communities, friendships, collective movements, and hopes for what could be. Your Sun here makes your conscious self inseparable from your participation in groups and your contribution to collective goals. You experience yourself through your place in networks. Your vitality comes from working with others toward shared vision, from friendships based on common values, from the assurance that your work serves something larger than personal ambition. You don't define yourself through individual achievement. Your identity forms through collective contribution. The challenge is distinguishing between genuine community and losing yourself in group identity.",
        "behavioral": "You build networks naturally, contribute to collective goals, and need community to feel complete. When you're working with others toward shared vision, you're alive. When you're isolated or working only for yourself, you lose purpose. Your approach to life is through collaboration and future thinking. You don't just fix what's broken. You imagine what could be different. This isn't impracticality. It's identity built through collective contribution. You understand that who you are emerges through how you participate in groups and what you're building for the future. The shadow is that collective good can override individual need. You may sacrifice yourself for the group, or you may stay in communities that no longer serve you because leaving feels like betrayal. The work is ensuring that your contribution to collective goals actually honors your individual purpose.",
        "feed": "The Sun is moving through your 11th house. Your conscious vitality and sense of purpose are focused on community, collective goals, and shared vision right now. This is a time for collaboration, for contributing to groups, for imagining future possibilities rather than just fixing present problems.",
        "sonic": "Your Sun in the 11th house contributes collaborative harmonic textures, forward-looking melodic gestures, and rhythm that creates collective pulse. The musical identity is expressed through participation in ensemble rather than solo prominence. Listen for the quality of shared vision, where individual voices serve the whole, where the overall effect is collective contribution and the satisfaction of building something together.",
    },
    "PLCMT_SUN_HOUSE12": {
        "core": "Your Sun in the 12th house means your sense of purpose is organized around inner life, spiritual development, and serving in ways that don't require recognition. Your identity is connected to what's hidden, transcendent, and beyond ego. The 12th house is the domain of the unconscious, spirituality, institutions, and work done behind the scenes. Your Sun here makes your conscious self paradoxically dependent on retreating from consciousness, on serving without ego validation, on developing spiritually rather than materially. You experience yourself through solitude and surrender. Your vitality comes from time alone, from spiritual practice, from the assurance that your work matters even when no one sees it. You don't need public visibility to know who you are. Your identity forms through what happens in private, in retreat, in service that goes unnamed. The challenge is distinguishing between healthy solitude and isolation that serves fear rather than spiritual development.",
        "behavioral": "You work behind the scenes, need solitude to recharge, and find purpose in service that doesn't bring recognition. When you have time alone, you thrive. When you're forced into constant visibility, you're depleted. Your approach to life is through inner development and quiet service. You don't need applause to know your work matters. This isn't martyrdom. It's identity built through spiritual practice and hidden contribution. You understand that who you are emerges through what you do when no one's watching. The shadow is that hiddenness can become avoidance. You may retreat so thoroughly that you never show up in the world, or you may use spiritual practice to escape from necessary worldly engagement. The work is ensuring that your spiritual development actually serves your capacity to show up in life rather than replacing it.",
        "feed": "The Sun is moving through your 12th house. Your conscious vitality and sense of purpose are focused on inner life, spiritual development, and hidden service right now. This is a time for solitude, for retreat, for serving in ways that don't require recognition, for developing spiritually rather than materially.",
        "sonic": "Your Sun in the 12th house contributes ambient harmonic textures, dissolving melodic boundaries, and rhythm that feels suspended and timeless. The musical identity is expressed through what's felt rather than what's clearly articulated. Listen for the quality of mystery and transcendence, where definition softens, where the overall effect is spiritual depth and the peace that comes from letting ego dissolve into something larger.",
    },
    "PLCMT_MOON_HOUSE1": {
        "core": "Your Moon in the 1st house means your emotional body is visible and immediate. How you feel shows on your face. The 1st house is the domain of immediate self-presentation, and your Moon here makes your emotional state inseparable from how you appear to others. You can't hide what you're feeling. Your emotional instincts are expressed directly through your physical presence. People read your moods before you speak. Your emotional security comes from being allowed to feel visibly, from environments where you don't have to perform emotional neutrality, from the assurance that your feelings are obvious and that's acceptable. You don't process emotions privately before showing them. They arrive and they show. The challenge is learning that emotional transparency isn't always appropriate or safe, that some situations require more emotional management than your instincts naturally provide.",
        "behavioral": "Your emotions show immediately, your moods shift visibly, and you need environments where emotional expression is welcome. When you're happy, everyone knows it. When you're upset, you can't hide it. Your emotional rhythm is reactive and visible. You feel something and it registers on your body instantly. This isn't manipulation. It's genuine emotional transparency. You can't separate how you feel from how you appear. The shadow is that visibility can create vulnerability. Others know your emotional state before you've decided whether to share it, or you may feel pressure to manage emotions that naturally want immediate expression. The work is developing enough awareness of your emotional visibility that you can choose when transparency serves you and when it doesn't.",
        "feed": "The Moon is moving through your 1st house. Your emotional body is at maximum visibility right now. How you feel is obvious to everyone around you. This is a time for allowing emotions to show, for trusting that transparency is strength, for honoring your need to feel visibly.",
        "sonic": "Your Moon in the 1st house contributes immediate emotional expression in the melodic foreground, reactive harmonic shifts, and rhythm that follows feeling in real time. The emotional state is always audible and present. Listen for music where the emotional content is undeniable and immediate, where the overall effect is transparent feeling that doesn't hide or delay.",
    },
    "PLCMT_MOON_HOUSE2": {
        "core": "Your Moon in the 2nd house means your emotional body needs material security, physical comfort, and the assurance that resources won't disappear. How you feel is connected to what you have. The 2nd house is the domain of resources and possessions, and your Moon here makes your emotional state inseparable from your sense of material stability. You feel secure when you have money. You feel unsafe when resources are uncertain. Your emotional instincts respond to material reality. Your emotional security comes from building resources you control, from physical comfort and pleasure, from the assurance that you have enough. You don't separate feelings from finances. Your emotional state tracks your bank account. The challenge is recognizing that emotional security and material security aren't identical, that some feelings can't be solved through accumulation.",
        "behavioral": "You feel through your body, seek comfort through material means, and need financial stability to feel emotionally safe. When you have enough money, you're calm. When finances are uncertain, you're anxious. Your emotional rhythm is tied to resource stability. You feel secure through what you can touch and count. This isn't materialism. It's emotional grounding through tangible reality. Your nervous system registers material security as emotional safety. The shadow is that accumulation can become compulsive. You may hoard resources to manage anxiety, or you may believe that every emotional problem can be solved by having more. The work is distinguishing between legitimate need for security and using resources to avoid emotional work that money can't fix.",
        "feed": "The Moon is moving through your 2nd house. Your emotional body needs material security and physical comfort right now. This is a time for tending to resources, for creating financial stability, for trusting that tangible security supports emotional wellbeing.",
        "sonic": "Your Moon in the 2nd house contributes sustained emotional tones, rich harmonic textures, and rhythm that creates sense of accumulation and groundedness. The emotional state is built through layering and substance. Listen for music where security is felt through sonic weight and sustained presence, where the overall effect is emotional comfort through material solidity.",
    },
    "PLCMT_MOON_HOUSE3": {
        "core": "Your Moon in the 3rd house means your emotional body needs conversation, mental stimulation, and the freedom to process feelings through talking. How you feel becomes clear when you speak it. The 3rd house is the domain of communication and immediate environment, and your Moon here makes your emotional state inseparable from your mental activity and social exchange. You understand emotions by talking about them. Your emotional instincts don't sit in silence. They need words. Your emotional security comes from having people to talk to, from environments where conversation flows easily, from the assurance that you can think and speak your way to emotional clarity. You don't feel in isolation. Your emotions form through dialogue. The challenge is recognizing that talking about feelings isn't the same as having them, that some emotions need to be felt in the body before they can be articulated.",
        "behavioral": "You process emotions through talking, need conversation to feel emotionally connected, and understand feelings by naming them. When you're upset, you call someone. When you're confused, you talk it through. Your emotional rhythm is verbal and social. You feel something and you need to speak it to know what it is. This isn't avoidance. It's emotional processing through language. The shadow is that words can replace feelings. You may articulate emotions you're not actually having, or you may stay so busy talking that you never drop into your emotional body. The work is allowing feelings to exist before you explain them, trusting that some emotions reveal themselves through silence rather than conversation.",
        "feed": "The Moon is moving through your 3rd house. Your emotional body needs conversation, mental engagement, and verbal processing right now. This is a time for talking through feelings, for understanding emotions through words, for connecting emotionally through dialogue.",
        "sonic": "Your Moon in the 3rd house contributes conversational emotional phrasing, quick harmonic shifts, and rhythm that follows the pace of dialogue. The emotional state is expressed through articulation and exchange. Listen for music where feelings are communicated rather than sustained, where the overall effect is emotional understanding through verbal clarity.",
    },
    "PLCMT_MOON_HOUSE4": {
        "core": "Your Moon in the 4th house, its natural home, means your emotional body is at maximum depth and sensitivity. How you feel is connected to where you come from and what you're creating as sanctuary. The 4th house is the domain of home, family, and emotional foundation, and your Moon here makes your emotional state inseparable from your sense of rootedness and domestic security. You need home to feel emotionally safe. Your emotional instincts operate through family patterns and the need for privacy. Your emotional security comes from having a home that's actually yours, from understanding your roots, from the assurance that your private emotional life is protected. You don't separate feelings from foundation. Your emotional state depends on whether home feels safe. The challenge is recognizing when protecting your private life has become isolation, when honoring your roots has become being trapped by them.",
        "behavioral": "You feel through your connection to home and family, need private space to process emotions, and require domestic stability to function. When your home life is secure, you're emotionally stable. When it's chaotic, you can't regulate. Your emotional rhythm is tidal and private. You need time alone to process what you've absorbed, then you return when restored. This isn't withdrawal. It's emotional maintenance through sanctuary. The shadow is that protection can become fortress. You may isolate so thoroughly that connection becomes impossible, or you may hold onto family patterns that no longer serve your emotional growth. The work is creating sanctuary that supports your life in the world rather than replacing it.",
        "feed": "The Moon is moving through your 4th house, its natural home. Your emotional body is at maximum depth and sensitivity right now. This is a time for tending to home, for understanding your roots, for creating sanctuary where your emotional life can exist without performance.",
        "sonic": "Your Moon in the 4th house contributes deep emotional resonance, modal harmonic warmth, and rhythm that follows organic cycles. The emotional state is grounded in foundational security. Listen for music where the emotional presence is profound and protected, where the overall effect is safety that comes from solid emotional bedrock.",
    },
    "PLCMT_MOON_HOUSE5": {
        "core": "Your Moon in the 5th house means your emotional body needs creative expression, play, and the freedom to feel joy. How you feel wants to be shown through what you make. The 5th house is the domain of creativity, romance, and pleasure, and your Moon here makes your emotional state inseparable from your capacity for creative joy and romantic connection. You feel through creating and playing. Your emotional instincts need outlets for expression. Your emotional security comes from having creative freedom, from romantic relationships that feel playful, from the assurance that pleasure is legitimate. You don't feel in isolation or silence. Your emotions want to be expressed creatively. The challenge is distinguishing between genuine emotional expression and performance that serves validation rather than authentic feeling.",
        "behavioral": "You feel through creating, express emotions dramatically, and need play and pleasure to stay emotionally regulated. When you're making something or in love, you're happy. When you're blocked creatively or romantically isolated, you're depressed. Your emotional rhythm is expressive and warm. You feel something and you want to show it, make it, play with it. This isn't narcissism. It's emotional processing through creative expression. The shadow is that expression can become performance. You may show emotions you're not actually having because being seen matters more than being accurate, or you may need constant creative validation to feel emotionally stable. The work is ensuring that what you're expressing serves genuine feeling rather than just the need for attention.",
        "feed": "The Moon is moving through your 5th house. Your emotional body needs creative expression, romantic connection, and permission to play right now. This is a time for making things that reflect what you feel, for allowing joy, for trusting that pleasure serves emotional health.",
        "sonic": "Your Moon in the 5th house contributes playful emotional expression, colorful harmonic choices, and rhythm that prioritizes pleasure and spontaneity. The emotional state is shown through creative freedom. Listen for music where feelings are expressed with joy and dramatic flair, where the overall effect is emotional vitality through creative play.",
    },
    "PLCMT_MOON_HOUSE6": {
        "core": "Your Moon in the 6th house means your emotional body needs routine, useful work, and the assurance that you're functioning well. How you feel is connected to your daily habits and physical health. The 6th house is the domain of work, health, and daily routines, and your Moon here makes your emotional state inseparable from whether your body is working properly and your daily life is organized. You feel secure when you have routines. You feel anxious when your health is uncertain or your days are chaotic. Your emotional instincts respond to physical function and useful service. Your emotional security comes from being productive, from having your health under control, from the assurance that you're being useful. You don't separate feelings from function. Your emotional state tracks how well your life is running. The challenge is recognizing that emotional wellbeing requires more than just productivity, that rest isn't failure.",
        "behavioral": "You feel through your daily routines, regulate emotions through productive work, and need physical health to feel emotionally stable. When your days are organized and you're being useful, you're calm. When routines break down or you're not working, you're anxious. Your emotional rhythm is structured and controlled. You manage feelings through maintaining order and serving others. This isn't avoidance. It's emotional regulation through useful function. The shadow is that work can become compulsive. You may use productivity to avoid feeling, or you may believe that rest means you're failing emotionally. The work is allowing yourself to feel without needing every emotion to serve a productive purpose.",
        "feed": "The Moon is moving through your 6th house. Your emotional body needs routine, useful work, and attention to physical health right now. This is a time for organizing your days, for serving others, for tending to your body as the foundation of emotional stability.",
        "sonic": "Your Moon in the 6th house contributes precise emotional rhythms, functional harmonic progressions, and steady pulse that creates security through order. The emotional state is maintained through structure and useful work. Listen for music where feelings are managed through discipline and craft, where the overall effect is emotional stability through reliable function.",
    },
    "PLCMT_MOON_HOUSE7": {
        "core": "Your Moon in the 7th house means your emotional body needs partnership, relational harmony, and feeling met by another. How you feel is inseparable from your relationships. The 7th house is the domain of partnership and one-on-one connection, and your Moon here makes your emotional state completely dependent on whether your relationships are working. You feel secure when you're in genuine partnership. You feel lost when you're alone. Your emotional instincts don't operate in isolation. They need another person to reflect them back. Your emotional security comes from being in committed relationships, from having partners who actually see you, from the assurance that you're not navigating life alone. You don't know how you feel without checking it against another person. The challenge is distinguishing between genuine relational need and losing yourself completely in partnership.",
        "behavioral": "You feel through relationship, need partnership to feel emotionally complete, and process emotions in dialogue with others. When you're in working partnerships, you're stable. When you're alone or relationships are strained, you're unmoored. Your emotional rhythm is relational and responsive. You feel something and you need to know how another person receives it before you know what it means. This isn't codependence. It's emotional processing through relational exchange. The shadow is that partnership can become required. You may stay in relationships past their purpose because being alone feels intolerable, or you may give up emotional autonomy to maintain connection. The work is developing enough capacity to feel alone that partnership becomes choice rather than emotional necessity.",
        "feed": "The Moon is moving through your 7th house. Your emotional body needs partnership, relational connection, and being emotionally met by others right now. This is a time for tending to your one-on-one relationships, for allowing yourself to need others, for trusting that relational security supports emotional wellbeing.",
        "sonic": "Your Moon in the 7th house contributes responsive emotional dialogue, balanced harmonic exchange, and rhythm that creates relational pulse. The emotional state forms through partnership rather than solo experience. Listen for music where feelings are expressed through relationship between voices, where the overall effect is emotional security through genuine meeting.",
    },
    "PLCMT_MOON_HOUSE8": {
        "core": "Your Moon in the 8th house means your emotional body needs depth, transformation, and complete merger with what you're feeling. How you feel is intense. The 8th house is the domain of depth, power, and transformation, and your Moon here makes your emotional state inseparable from crisis, intensity, and psychological truth. You don't have light feelings. Every emotion goes to the depths. Your emotional instincts don't trust surfaces or comfort. They need to know what's real even when reality is dark. Your emotional security comes from being able to face shadow material, from relationships that go to merger-level intimacy, from the assurance that you can survive complete emotional transformation. You don't protect yourself from intensity. Your emotional life is built through it. The challenge is recognizing that not everything needs to be felt at crisis level, that some emotions can be lighter without being fake.",
        "behavioral": "You feel intensely, transform through emotional crisis, and need depth to feel emotionally alive. When life is emotionally intense, you're engaged. When it's comfortable, you create crisis. Your emotional rhythm is concentrated and sustained. You feel something deeply and hold it for a long time. This isn't drama. It's emotional honesty at maximum depth. You can't pretend light feelings when you're having deep ones. The shadow is that intensity can become the only valid emotional experience. You may create crisis to avoid feeling emotionally dead, or you may refuse connection that doesn't reach merger level. The work is allowing emotional connection that has range, where intensity and lightness can both exist without either invalidating the other.",
        "feed": "The Moon is moving through your 8th house. Your emotional body needs depth, transformation, and the willingness to feel at maximum intensity right now. This is a time for facing shadow emotions, for allowing crisis to transform you, for trusting that emotional death serves regeneration.",
        "sonic": "Your Moon in the 8th house contributes dense emotional textures, chromatic harmonic tension, and rhythm that builds to crisis and release. The emotional state is felt at maximum intensity. Listen for music where emotions are concentrated and transformative, where the overall effect is psychological depth and the power that comes from surviving emotional death and rebirth.",
    },
    "PLCMT_MOON_HOUSE9": {
        "core": "Your Moon in the 9th house means your emotional body needs freedom, optimism, and the assurance that feelings aren't traps. How you feel is connected to meaning and expansion. The 9th house is the domain of exploration, philosophy, and long journeys, and your Moon here makes your emotional state inseparable from your need to understand feelings in larger contexts. You don't sit in emotions. You reach for their meaning. Your emotional instincts want to expand rather than contract. Your emotional security comes from having freedom to move, from understanding what your feelings mean philosophically, from the assurance that no emotional state is permanent. You process feelings by finding the lesson and releasing them. The challenge is recognizing that some emotions need to be felt in their darkness before they can be reframed into light, that reaching for meaning can skip the actual feeling.",
        "behavioral": "You feel optimistically, process emotions through meaning-making, and need freedom to stay emotionally engaged. When you're learning something or traveling, you're emotionally alive. When you're trapped in familiar emotional patterns, you need to escape. Your emotional rhythm is expansive and changeable. You feel something, understand what it means, and move on. This isn't avoidance. It's emotional processing through philosophical reframing. The shadow is that expansion can replace feeling. You may philosophize emotions you haven't actually had, or you may use optimism to bypass grief that needs to be felt before it can be released. The work is allowing yourself to feel the full weight of emotions before you reach for their meaning.",
        "feed": "The Moon is moving through your 9th house. Your emotional body needs freedom, expansion, and philosophical understanding right now. This is a time for finding meaning in feelings, for trusting that emotions aren't traps, for allowing optimism to support emotional movement.",
        "sonic": "Your Moon in the 9th house contributes expansive emotional range, optimistic harmonic progressions, and rhythm that moves forward without dwelling. The emotional state is felt through expansion and release. Listen for music where feelings open outward, where the overall effect is emotional freedom and the trust that meaning will emerge from whatever is felt.",
    },
    "PLCMT_MOON_HOUSE10": {
        "core": "Your Moon in the 10th house means your emotional body needs achievement, recognition, and the assurance that your feelings serve your public purpose. How you feel is visible in your career. The 10th house is the domain of public life and vocation, and your Moon here makes your emotional state inseparable from your professional reputation and career success. You feel secure when your work is going well. You feel exposed when your career is uncertain. Your emotional instincts are tied to public achievement. Your emotional security comes from having a clear professional direction, from being respected publicly, from the assurance that your emotional needs and your career goals aren't in conflict. You don't separate private feelings from public image. Your emotional life shows in your work. The challenge is recognizing that emotional authenticity sometimes conflicts with professional image, that not every feeling needs to serve your career.",
        "behavioral": "You feel through your work, need professional success to feel emotionally stable, and process emotions in relationship to your career. When your professional life is thriving, you're emotionally secure. When it's struggling, you're destabilized. Your emotional rhythm is tied to achievement and recognition. You feel something and you evaluate whether it serves your professional goals. This isn't coldness. It's emotional organization through vocational purpose. The shadow is that career can become the only emotional measure. You may sacrifice all private emotional life for professional success, or you may believe that feelings that don't serve your career are invalid. The work is allowing yourself to have emotional needs that don't contribute to your public image.",
        "feed": "The Moon is moving through your 10th house. Your emotional body needs achievement, public recognition, and professional purpose right now. This is a time for allowing your feelings to show in your work, for trusting that emotional authenticity supports rather than undermines professional success.",
        "sonic": "Your Moon in the 10th house contributes emotionally resonant public expression, harmonic progressions that build authority, and rhythm that creates sense of professional presence. The emotional state is felt through achievement and recognition. Listen for music where feelings support public purpose, where the overall effect is emotional maturity expressed through vocational mastery.",
    },
    "PLCMT_MOON_HOUSE11": {
        "core": "Your Moon in the 11th house means your emotional body needs community, shared vision, and the assurance that your feelings serve collective good. How you feel is connected to groups. The 11th house is the domain of friendship networks and collective movements, and your Moon here makes your emotional state inseparable from your participation in communities and contribution to shared goals. You feel secure when you're part of something larger. You feel isolated when you're working alone. Your emotional instincts respond to group dynamics and collective need. Your emotional security comes from having genuine friendships, from working toward shared vision, from the assurance that your emotional life serves more than just personal satisfaction. You don't process feelings in isolation. Your emotions form through collective exchange. The challenge is recognizing that belonging to community doesn't require sacrificing individual emotional needs.",
        "behavioral": "You feel through your friendships, need community to stay emotionally regulated, and process emotions in relationship to collective good. When you're connected to groups and working toward shared vision, you're emotionally stable. When you're isolated, you lose emotional grounding. Your emotional rhythm is social and collaborative. You feel something and you bring it to your community. This isn't loss of self. It's emotional processing through collective exchange. The shadow is that group needs can override individual ones. You may sacrifice your emotional wellbeing for the collective, or you may stay in communities that no longer serve you because leaving feels like emotional abandonment. The work is honoring individual emotional needs while still participating in collective life.",
        "feed": "The Moon is moving through your 11th house. Your emotional body needs community, friendship, and collective contribution right now. This is a time for connecting with groups, for sharing emotional life with others, for trusting that belonging supports individual emotional wellbeing.",
        "sonic": "Your Moon in the 11th house contributes collaborative emotional textures, harmonic progressions that serve the ensemble, and rhythm that creates collective pulse. The emotional state forms through participation rather than solo experience. Listen for music where feelings are shared rather than held individually, where the overall effect is emotional security through genuine community.",
    },
    "PLCMT_MOON_HOUSE12": {
        "core": "Your Moon in the 12th house means your emotional body needs solitude, spiritual connection, and the freedom to feel without explaining. How you feel often remains hidden. The 12th house is the domain of the unconscious, spirituality, and what's beyond ego, and your Moon here makes your emotional state inseparable from your need for retreat and surrender. You don't process emotions publicly. You need time alone to understand what you're feeling. Your emotional instincts are permeable to collective currents and spiritual dimensions. Your emotional security comes from having private space, from spiritual practices that hold what's too large for words, from the assurance that you don't have to explain your emotional life to anyone. You feel things others miss. Your emotional body is porous to what's unconscious and universal. The challenge is recognizing when solitude has become isolation, when permeability has become loss of emotional boundaries.",
        "behavioral": "You feel privately, need solitude to process emotions, and absorb collective emotional atmospheres without filter. When you have time alone, you can understand what you're feeling. When you're forced into constant social exposure, you're overwhelmed. Your emotional rhythm is tidal and hidden. You feel something deeply but you don't show it immediately. This isn't repression. It's emotional processing through privacy and spiritual practice. The shadow is that hiddenness can become complete isolation. You may retreat so thoroughly that no one can reach you emotionally, or you may absorb so much collective pain that you lose touch with your own feelings. The work is creating enough boundary that you can serve compassionately without dissolving your own emotional needs.",
        "feed": "The Moon is moving through your 12th house. Your emotional body needs solitude, spiritual connection, and permission to feel without explaining right now. This is a time for retreat, for processing emotions privately, for trusting that not every feeling needs to be shared or understood by others.",
        "sonic": "Your Moon in the 12th house contributes ambient emotional textures, dissolving harmonic boundaries, and rhythm that feels suspended and timeless. The emotional state is felt through what's unconscious and universal. Listen for music where feelings merge with something larger, where boundaries soften, where the overall effect is spiritual depth and the peace that comes from emotional surrender.",
    },
}


def escape_ts(s: str) -> str:
    return s.replace("\\", "\\\\").replace("`", "\\`")


def replace_field(block: str, field: str, value: str) -> str:
    pattern = rf"(    {field}: `)(?:[^`\\]|\\.)*(`)"
    repl = rf"\1{escape_ts(value)}\2"
    new_block, n = re.subn(pattern, repl, block, count=1, flags=re.DOTALL)
    if n != 1:
        raise ValueError(f"Failed to replace {field}")
    return new_block


def main() -> None:
    text = PATH.read_text(encoding="utf-8")
    for key, fields in UPDATES.items():
        m = re.search(rf"  {key}: \{{(.*?)\n  \}},", text, re.DOTALL)
        if not m:
            raise SystemExit(f"Entry not found: {key}")
        block = m.group(0)
        for field in ("core", "behavioral", "feed", "sonic"):
            block = replace_field(block, field, fields[field])
        text = text[: m.start()] + block + text[m.end() :]
    PATH.write_text(text, encoding="utf-8")
    print(f"Updated {len(UPDATES)} entries in {PATH.name}")


if __name__ == "__main__":
    main()