"""Pluto in houses 1-12 — Phase 3 placement copy (core, behavioral, feed, sonic)."""

UPDATES: dict[str, dict[str, str]] = {
    "PLCMT_PLUTO_HOUSE1": {
        "core": """Your Pluto in the 1st house means where you face power and transform is inseparable from your immediate presence and identity. Your self is the site of transformation. The 1st house is how you show up, and your Pluto here makes your capacity for death and rebirth visible in your presence. You transform through being yourself. Your power work lives in claiming your existence. The shadow you face is your own presence. You're wired to see where identity has become mask. Death and rebirth of self is your work. The challenge is allowing transformation without losing yourself entirely in the process.""",
        "behavioral": """You transform through your presence, face power in how you show up, and confront death and rebirth through identity itself. When you're encountering Pluto, it's in the mirror—you're the site of transformation. Your power work is learning that who you are must die and be reborn repeatedly. You're transforming the entire structure of identity. This isn't just change. It's total metamorphosis of self. The maturation is recognizing that your presence carries intensity whether you want it to or not, that transformation is visible in how you exist. Your power is earned through facing that you are the transformation, that identity itself is the work. The shadow is using intensity of presence to control or overwhelm others rather than just existing authentically.""",
        "feed": """Pluto is moving through your 1st house. Where you face power and transform is focused on your identity, presence, and how you show up right now. This is a time for confronting the shadow of self, for allowing identity to die and be reborn, for facing that you are the transformation.""",
        "sonic": """Your Pluto in the 1st house contributes relentless presence in the foreground, dark harmonic identity, and rhythmic confrontation visible in how you exist. The quality of transformation is immediate and total, creating death and rebirth through the self. Listen for music where identity itself must die and presence becomes the site of complete metamorphosis.""",
    },
    "PLCMT_PLUTO_HOUSE2": {
        "core": """Your Pluto in the 2nd house means where you face power and transform is organized around resources, value, and what security means. Material reality is the site of transformation. The 2nd house is resources and worth, and your Pluto here makes your capacity for death and rebirth connected to money, earth, and self-value. You transform through facing power around what you have and what you're worth. Your power work lives in resource dynamics. The shadow you face is material control. You're wired to see where security has become hoarding or where scarcity has become identity. Death and rebirth of value is your work. The challenge is allowing resources to transform without total loss destroying you.""",
        "behavioral": """You transform through resources, face power in how value operates, and confront death and rebirth through money and worth. When you're encountering Pluto, it's in your relationship to having and being enough—resources are the site of transformation. Your power work is learning that what you have and what you're worth must die and be reborn. You're transforming the entire structure of value. This isn't just money problems. It's total confrontation with security and worth. The maturation is recognizing that your relationship to resources carries intensity, that scarcity and abundance are both tests. Your power is earned through facing that material reality is where you transform. The shadow is using resources to control others or allowing scarcity to control you.""",
        "feed": """Pluto is moving through your 2nd house. Where you face power and transform is focused on resources, value, and reimagining security right now. This is a time for confronting the shadow of material reality, for allowing worth and resources to die and be reborn, for facing power in what you have.""",
        "sonic": """Your Pluto in the 2nd house contributes relentless rhythmic accumulation and loss, dark harmonic materiality, and melodic confrontation with value. The quality of transformation is physical and total, creating death and rebirth through resources. Listen for music where material reality itself must die and security becomes the site of complete metamorphosis.""",
    },
    "PLCMT_PLUTO_HOUSE3": {
        "core": """Your Pluto in the 3rd house means where you face power and transform is organized around communication, thought, and how information moves. Your mind is the site of transformation. The 3rd house is learning and local connection, and your Pluto here makes your capacity for death and rebirth connected to how you think and speak. You transform through facing power in ideas and language. Your power work lives in what gets said and known. The shadow you face is mental control. You're wired to see where communication has become manipulation or where knowledge has become weapon. Death and rebirth of thought is your work. The challenge is allowing ideas to transform without using words to destroy.""",
        "behavioral": """You transform through communication, face power in how ideas move, and confront death and rebirth through thought itself. When you're encountering Pluto, it's in your mind and speech—thinking is the site of transformation. Your power work is learning that how you think and communicate must die and be reborn. You're transforming the entire structure of understanding. This isn't just learning. It's total confrontation with the power of language. The maturation is recognizing that your words carry intensity, that what you say can wound or heal. Your power is earned through facing that thought is where you transform. The shadow is using words as weapons or allowing mental patterns to control you rigidly.""",
        "feed": """Pluto is moving through your 3rd house. Where you face power and transform is focused on communication, learning, and how ideas move right now. This is a time for confronting the shadow of thought, for allowing mental patterns to die and be reborn, for facing power in what you say and know.""",
        "sonic": """Your Pluto in the 3rd house contributes relentless melodic interrogation, dark harmonic communication, and rhythmic confrontation through language. The quality of transformation is mental and total, creating death and rebirth through thought. Listen for music where ideas themselves must die and communication becomes the site of complete metamorphosis.""",
    },
    "PLCMT_PLUTO_HOUSE4": {
        "core": """Your Pluto in the 4th house means where you face power and transform is organized around home, family, and emotional foundation. Your roots are the site of transformation. The 4th house is sanctuary and belonging, and your Pluto here makes your capacity for death and rebirth connected to where you come from and what you call home. You transform through facing power in family and emotional safety. Your power work lives in your origins. The shadow you face is family dynamics and inherited trauma. You're wired to see where home has become prison or where belonging has become control. Death and rebirth of foundation is your work. The challenge is allowing roots to transform without destroying all sense of home.""",
        "behavioral": """You transform through family and home, face power in emotional foundation, and confront death and rebirth through where you come from. When you're encountering Pluto, it's in your private life and roots—home is the site of transformation. Your power work is learning that family patterns and emotional foundations must die and be reborn. You're transforming the entire structure of belonging. This isn't just leaving home. It's total confrontation with inherited power. The maturation is recognizing that your family carries intensity you didn't create, that roots can be transformed without being destroyed. Your power is earned through facing that home is where you transform. The shadow is using family dynamics to control or being controlled by ancestral patterns.""",
        "feed": """Pluto is moving through your 4th house. Where you face power and transform is focused on home, family, and emotional foundation right now. This is a time for confronting family shadows, for allowing roots to die and be reborn, for facing inherited power dynamics.""",
        "sonic": """Your Pluto in the 4th house contributes relentless emotional depth, dark harmonic foundations, and rhythmic confrontation with family power. The quality of transformation is domestic and total, creating death and rebirth through roots. Listen for music where home itself must die and belonging becomes the site of complete metamorphosis.""",
    },
    "PLCMT_PLUTO_HOUSE5": {
        "core": """Your Pluto in the 5th house means where you face power and transform is organized around creativity, self-expression, and what brings joy. Your creative output is the site of transformation. The 5th house is play and celebration, and your Pluto here makes your capacity for death and rebirth connected to what you create and how you express yourself. You transform through facing power in creativity and pleasure. Your power work lives in your art and joy. The shadow you face is creative control or blocked expression. You're wired to see where self-expression has become performance of power or where joy has been suppressed. Death and rebirth of creativity is your work. The challenge is allowing expression to transform without destroying the capacity to create.""",
        "behavioral": """You transform through creativity, face power in self-expression, and confront death and rebirth through what you make and how you celebrate. When you're encountering Pluto, it's in your creative work—art is the site of transformation. Your power work is learning that how you express and what brings you joy must die and be reborn. You're transforming the entire structure of pleasure. This isn't just creating art. It's total confrontation with creative power. The maturation is recognizing that your creative output carries intensity, that what you make can transform others. Your power is earned through facing that creativity is where you transform. The shadow is using creative expression to dominate or allowing fear to block all creative flow.""",
        "feed": """Pluto is moving through your 5th house. Where you face power and transform is focused on creativity, self-expression, and reimagining joy right now. This is a time for confronting creative shadows, for allowing expression to die and be reborn, for facing power in what you make.""",
        "sonic": """Your Pluto in the 5th house contributes relentless creative intensity, dark harmonic expression, and rhythmic confrontation through art. The quality of transformation is creative and total, creating death and rebirth through self-expression. Listen for music where creativity itself must die and joy becomes the site of complete metamorphosis.""",
    },
    "PLCMT_PLUTO_HOUSE6": {
        "core": """Your Pluto in the 6th house means where you face power and transform is organized around work, health, and daily practice. Your body and labor are sites of transformation. The 6th house is service and wellness, and your Pluto here makes your capacity for death and rebirth connected to how you work and care for your physical self. You transform through facing power in labor and health. Your power work lives in your daily life. The shadow you face is work as control or health as obsession. You're wired to see where service has become exploitation or where wellness has become control. Death and rebirth of function is your work. The challenge is allowing work and health to transform without destroying your body or capacity to serve.""",
        "behavioral": """You transform through work and health, face power in daily practice, and confront death and rebirth through service and your body. When you're encountering Pluto, it's in your routines and physical function—work and wellness are sites of transformation. Your power work is learning that how you serve and care for your body must die and be reborn. You're transforming the entire structure of daily life. This isn't just health problems. It's total confrontation with the power of labor and embodiment. The maturation is recognizing that your work and body carry the intensity of transformation. Your power is earned through facing that function is where you transform. The shadow is working compulsively to avoid powerlessness or controlling health obsessively.""",
        "feed": """Pluto is moving through your 6th house. Where you face power and transform is focused on work, health, and daily practice right now. This is a time for confronting shadows in service, for allowing your relationship to labor and body to die and be reborn, for facing power in function.""",
        "sonic": """Your Pluto in the 6th house contributes relentless precision, dark harmonic functionality, and rhythmic confrontation through work. The quality of transformation is practical and total, creating death and rebirth through service. Listen for music where daily life itself must die and wellness becomes the site of complete metamorphosis.""",
    },
    "PLCMT_PLUTO_HOUSE7": {
        "core": """Your Pluto in the 7th house means where you face power and transform is organized around partnership, relationship, and how you relate to equals. Others are the site of transformation. The 7th house is committed connection, and your Pluto here makes your capacity for death and rebirth connected to partnerships and who you meet as equals. You transform through facing power in relationship. Your power work lives in your partnerships. The shadow you face is control in intimacy or power struggles with equals. You're wired to see where partnership has become domination or where relating has become power dynamic. Death and rebirth of relationship is your work. The challenge is allowing partnerships to transform without destroying everyone involved.""",
        "behavioral": """You transform through partnership, face power in how you relate, and confront death and rebirth through committed relationships. When you're encountering Pluto, it's with others—relationship is the site of transformation. Your power work is learning that how you partner must die and be reborn. You're transforming the entire structure of relating to equals. This isn't just relationship problems. It's total confrontation with interpersonal power. The maturation is recognizing that your partnerships carry intensity, that relationship is where power must be faced. Your power is earned through facing that others are where you transform. The shadow is using relationship to control others or allowing partners to control you.""",
        "feed": """Pluto is moving through your 7th house. Where you face power and transform is focused on partnership, relationship, and how you relate to equals right now. This is a time for confronting power in intimacy, for allowing relationships to die and be reborn, for facing that others are your transformation.""",
        "sonic": """Your Pluto in the 7th house contributes relentless harmonic tension between voices, dark melodic partnership, and rhythmic confrontation through relationship. The quality of transformation is interpersonal and total, creating death and rebirth through others. Listen for music where partnership itself must die and relating becomes the site of complete metamorphosis.""",
    },
    "PLCMT_PLUTO_HOUSE8": {
        "core": """Your Pluto in the 8th house, its home, means where you face power and transform is at maximum depth and intensity. Transformation is your nature. The 8th house is shadow and shared resources, and your Pluto here operates at full strength—confronting what's hidden, wielding power consciously, forcing complete metamorphosis. You transform through total engagement with depth. Your power work lives in facing what others avoid. The shadow you face is power itself. You're wired to see all of it. Death and rebirth is who you are. The challenge is using this intensity to serve actual growth rather than just satisfying need for control.""",
        "behavioral": """You transform through total depth, face power at its source, and confront death and rebirth as your essential nature. When you're encountering Pluto, it's everywhere—transformation is not what you do but who you are. Your power work is learning that you ARE the transformation, that depth is your element. You're not transforming power dynamics; you're the place where power transforms. This is your nature. The maturation is recognizing that you carry more intensity than most can bear, that your capacity for facing shadow is both gift and burden. Your power is earned through using depth consciously rather than wielding it unconsciously. The shadow is becoming the very thing you're meant to transform—using power to dominate rather than to liberate.""",
        "feed": """Pluto is moving through your 8th house, its home. Where you face power and transform is at maximum depth right now. This is a time for total confrontation with shadow, for recognizing that transformation is your nature, for facing that you ARE the depth.""",
        "sonic": """Your Pluto in the 8th house contributes total chromatic intensity, absolute harmonic depth, and rhythmic confrontation at maximum power. The quality of transformation is complete and inevitable, creating death and rebirth as fundamental nature. Listen for music where transformation itself is the substance and power is the medium through which everything moves.""",
    },
    "PLCMT_PLUTO_HOUSE9": {
        "core": """Your Pluto in the 9th house means where you face power and transform is organized around belief, meaning, and what truth is. Your philosophy is the site of transformation. The 9th house is understanding and expansion, and your Pluto here makes your capacity for death and rebirth connected to what you believe and how you find meaning. You transform through facing power in belief systems. Your power work lives in truth-telling. The shadow you face is dogma and fundamentalism. You're wired to see where belief has become control or where meaning has been weaponized. Death and rebirth of understanding is your work. The challenge is allowing beliefs to transform without losing all sense of truth.""",
        "behavioral": """You transform through belief, face power in what counts as truth, and confront death and rebirth through your philosophy. When you're encountering Pluto, it's in your worldview—meaning is the site of transformation. Your power work is learning that what you believe must die and be reborn. You're transforming the entire structure of understanding. This isn't just changing your mind. It's total confrontation with the power of belief. The maturation is recognizing that your philosophy carries intensity, that what you hold as true has power to liberate or imprison. Your power is earned through facing that meaning is where you transform. The shadow is using belief to control others or allowing fundamentalism to control you.""",
        "feed": """Pluto is moving through your 9th house. Where you face power and transform is focused on belief, meaning, and what truth is right now. This is a time for confronting dogma, for allowing your philosophy to die and be reborn, for facing power in what you hold as true.""",
        "sonic": """Your Pluto in the 9th house contributes relentless philosophical depth, dark harmonic expansion, and rhythmic confrontation with truth. The quality of transformation is ideological and total, creating death and rebirth through belief. Listen for music where understanding itself must die and meaning becomes the site of complete metamorphosis.""",
    },
    "PLCMT_PLUTO_HOUSE10": {
        "core": """Your Pluto in the 10th house means where you face power and transform is organized around career, public achievement, and how you're known. Your public life is the site of transformation. The 10th house is vocation and authority, and your Pluto here makes your capacity for death and rebirth connected to what you do publicly and how you wield institutional power. You transform through facing power in structures. Your power work lives in your career and reputation. The shadow you face is authority itself. You're wired to see where hierarchy has become oppression or where achievement has become exploitation. Death and rebirth of public power is your work. The challenge is wielding authority consciously without becoming the very systems you're meant to transform.""",
        "behavioral": """You transform through career, face power in institutions, and confront death and rebirth through public achievement. When you're encountering Pluto, it's in your vocation—your public work is the site of transformation. Your power work is learning that how you succeed and wield authority must die and be reborn. You're transforming the entire structure of institutional power. This isn't just career success. It's total confrontation with systemic authority. The maturation is recognizing that your public presence carries transformative power, that how you succeed matters as much as whether you succeed. Your power is earned through facing that institutions are where you transform. The shadow is becoming a tyrant or being destroyed by the systems you're trying to change.""",
        "feed": """Pluto is moving through your 10th house. Where you face power and transform is focused on career, public achievement, and institutional authority right now. This is a time for confronting power in structures, for allowing your public role to die and be reborn, for facing that you wield transformative authority.""",
        "sonic": """Your Pluto in the 10th house contributes relentless structural pressure, dark harmonic authority, and rhythmic confrontation with institutional power. The quality of transformation is systemic and total, creating death and rebirth through public achievement. Listen for music where hierarchy itself must die and authority becomes the site of complete metamorphosis.""",
    },
    "PLCMT_PLUTO_HOUSE11": {
        "core": """Your Pluto in the 11th house means where you face power and transform is organized around friendship, collective vision, and what community means. Groups are the site of transformation. The 11th house is shared dreams and networks, and your Pluto here makes your capacity for death and rebirth connected to communities and collective movements. You transform through facing power in groups. Your power work lives in collective action. The shadow you face is group dynamics and mob mentality. You're wired to see where collective good has become new tyranny or where friendship has become cult. Death and rebirth of community is your work. The challenge is participating in collective transformation without losing yourself or using groups to wield power unconsciously.""",
        "behavioral": """You transform through community, face power in collective movements, and confront death and rebirth through friendship networks. When you're encountering Pluto, it's in groups—the collective is the site of transformation. Your power work is learning that how you belong to communities must die and be reborn. You're transforming the entire structure of collective action. This isn't just joining groups. It's total confrontation with collective power. The maturation is recognizing that your participation in groups carries transformative intensity, that collective movements can liberate or imprison. Your power is earned through facing that community is where you transform. The shadow is using collective power to dominate or being consumed by group dynamics.""",
        "feed": """Pluto is moving through your 11th house. Where you face power and transform is focused on friendship, community, and collective vision right now. This is a time for confronting power in groups, for allowing your relationship to community to die and be reborn, for facing collective shadow.""",
        "sonic": """Your Pluto in the 11th house contributes relentless collaborative intensity, dark harmonic collectivity, and rhythmic confrontation through group dynamics. The quality of transformation is communal and total, creating death and rebirth through shared power. Listen for music where community itself must die and collective action becomes the site of complete metamorphosis.""",
    },
    "PLCMT_PLUTO_HOUSE12": {
        "core": """Your Pluto in the 12th house means where you face power and transform is organized around the unconscious, spirituality, and what's hidden. The invisible realm is the site of transformation. The 12th house is what's beyond ego, and your Pluto here makes your capacity for death and rebirth connected to what operates beneath conscious awareness. You transform through facing power in the unconscious. Your power work lives in what you can't see. The shadow you face is your own shadow—everything repressed, denied, or operating invisibly. You're wired to see how hidden power operates. Death and rebirth happens in darkness. The challenge is working with unconscious power without being destroyed by it or using it to manipulate from the shadows.""",
        "behavioral": """You transform through the unconscious, face power in what's hidden, and confront death and rebirth through invisible work. When you're encountering Pluto, it's beneath awareness—shadow is the site of transformation. Your power work is learning that what operates unconsciously must be brought to light and transformed. You're transforming power that operates invisibly. This isn't just therapy. It's total confrontation with what's been repressed. The maturation is recognizing that your deepest power operates beneath conscious awareness, that transformation happens in darkness before it's visible. Your power is earned through facing your own unconscious without being destroyed by what you find. The shadow is using hidden power to manipulate or being controlled by unconscious patterns.""",
        "feed": """Pluto is moving through your 12th house. Where you face power and transform is focused on the unconscious, hidden work, and what operates invisibly right now. This is a time for confronting shadow at its source, for allowing unconscious patterns to die and be reborn, for facing power in darkness.""",
        "sonic": """Your Pluto in the 12th house contributes invisible but relentless pressure, dark harmonic undercurrents, and rhythmic patterns that operate beneath conscious awareness. The quality of transformation is hidden and total, creating death and rebirth in darkness. Listen for music where power operates beneath the surface and transformation happens in what cannot be seen but only felt.""",
    },
}
