"""Neptune in houses 1-12 — Phase 3 placement copy (core, behavioral, feed, sonic)."""

UPDATES: dict[str, dict[str, str]] = {
    "PLCMT_NEPTUNE_HOUSE1": {
        "core": """Your Neptune in the 1st house means where you encounter mystery and dissolve boundaries is inseparable from your immediate presence and self-expression. Your identity is fluid. The 1st house is how you show up, and your Neptune here makes your capacity for imagination visible in your presence. You dissolve boundaries through being yourself. Your confusion lives in who you actually are. Your spiritual longing is for perfect self-expression. You're wired to sense where rigid identity prevents authentic flow. Your sense of self is permeable. The work is maintaining enough definition that compassion includes actually showing up rather than just dissolving.""",
        "behavioral": """You idealize your own presence, dream of perfect identity, and dissolve boundaries around who you are. When you're connecting to mystery, it arrives through questions about your own nature and how you should appear. Your confusion lives in the gap between ideal self and actual presence. You're learning that the dream of perfect identity both inspires and deceives. This isn't just lack of self. It's genuine spiritual permeability of identity. The shadow is that dissolution can prevent showing up. You may dream of perfect presence without actually being visible, or you may use spiritual bypassing to avoid claiming any stable identity. The work is using your capacity to imagine fluid identity while maintaining enough self to actually exist in the world.""",
        "feed": """Neptune is moving through your 1st house. Where you encounter mystery and dissolve boundaries is focused on your identity, presence, and how you show up right now. This is a time for spiritual visions of self, for dissolving rigid identity, for trusting that who you are can include mystery.""",
        "sonic": """Your Neptune in the 1st house contributes dreamlike presence in the foreground, dissolving harmonic identity, and rhythm that is fluid and permeable. The quality of mystery is found in the self, creating spiritual longing through visions of perfect presence. Listen for music where identity dissolves and presence becomes fluid, where showing up includes mystery.""",
    },
    "PLCMT_NEPTUNE_HOUSE2": {
        "core": """Your Neptune in the 2nd house means where you encounter mystery and dissolve boundaries is organized around resources, value, and what security means. Your relationship to material reality is mystical. The 2nd house is resources, and your Neptune here makes your capacity for imagination connected to what has value and what provides security. You dissolve boundaries through idealized relationship to money and earth. Your confusion lives in what actually secures you. Your spiritual longing is for perfect abundance. You're wired to sense where materialism prevents spiritual wealth. Material boundaries are permeable. The work is maintaining enough groundedness that compassion includes actual resources rather than just spiritual ideals.""",
        "behavioral": """You idealize abundance, dream of perfect security, and dissolve boundaries around what has value. When you're connecting to mystery, it arrives through visions of material paradise or spiritual wealth that transcends money. Your confusion lives in the gap between ideal security and actual resources. You're learning that the dream of perfect abundance both inspires and deceives. This isn't just impracticality. It's genuine spiritual permeability around material reality. The shadow is that idealization can prevent building actual security. You may dream of abundance without creating real resources, or you may use spiritual bypassing to avoid practical work with money. The work is using your capacity to imagine sacred materialism while maintaining enough groundedness to actually build resources.""",
        "feed": """Neptune is moving through your 2nd house. Where you encounter mystery and dissolve boundaries is focused on resources, value, and reimagining security right now. This is a time for spiritual visions of abundance, for dissolving rigid materialism, for trusting that security can include mystery.""",
        "sonic": """Your Neptune in the 2nd house contributes dreamlike harmonic richness, dissolving melodic groundedness, and rhythm that is both material and fluid. The quality of mystery is found in value, creating spiritual longing through visions of sacred abundance. Listen for music where material boundaries dissolve and resources become spiritualized.""",
    },
    "PLCMT_NEPTUNE_HOUSE3": {
        "core": """Your Neptune in the 3rd house means where you encounter mystery and dissolve boundaries is organized around communication, learning, and how ideas move. Your thinking is mystical. The 3rd house is thought and local connection, and your Neptune here makes your capacity for imagination connected to how you understand and speak. You dissolve boundaries through poetic communication. Your confusion lives in what's actually true versus what feels true. Your spiritual longing is for perfect understanding. You're wired to sense where rigid logic prevents intuitive knowing. Mental boundaries are permeable. The work is maintaining enough clarity that compassion includes actual communication rather than just mystical sensing.""",
        "behavioral": """You idealize communication, dream of perfect understanding, and dissolve boundaries around what counts as truth. When you're connecting to mystery, it arrives through visions of telepathy or universal language. Your confusion lives in the gap between ideal understanding and messy actual communication. You're learning that the dream of perfect clarity both inspires and deceives. This isn't just vagueness. It's genuine spiritual permeability of thought. The shadow is that dissolution can prevent actual speech. You may dream of perfect communication without doing the work of clear language, or you may use poetic ambiguity to avoid committing to specific meanings. The work is using your capacity to imagine fluid truth while maintaining enough clarity to actually communicate.""",
        "feed": """Neptune is moving through your 3rd house. Where you encounter mystery and dissolve boundaries is focused on communication, learning, and how ideas move right now. This is a time for spiritual visions of understanding, for dissolving rigid logic, for trusting that truth can include mystery.""",
        "sonic": """Your Neptune in the 3rd house contributes dreamlike melodic conversation, dissolving harmonic clarity, and rhythm that is both articulate and fluid. The quality of mystery is found in thought, creating spiritual longing through visions of universal understanding. Listen for music where mental boundaries dissolve and communication becomes poetic rather than purely rational.""",
    },
    "PLCMT_NEPTUNE_HOUSE4": {
        "core": """Your Neptune in the 4th house means where you encounter mystery and dissolve boundaries is organized around home, family, and emotional foundation. Your relationship to roots is mystical. The 4th house is sanctuary and belonging, and your Neptune here makes your capacity for imagination connected to what home means and where you come from. You dissolve boundaries through idealized family and home. Your confusion lives in what actually creates safety versus what feels like it should. Your spiritual longing is for perfect belonging. You're wired to sense where rigid family structures prevent actual emotional connection. Domestic boundaries are permeable. The work is maintaining enough foundation that compassion includes actual home rather than just idealized sanctuary.""",
        "behavioral": """You idealize home and family, dream of perfect belonging, and dissolve boundaries around what creates emotional safety. When you're connecting to mystery, it arrives through visions of unconditional family or spiritual home. Your confusion lives in the gap between ideal sanctuary and messy actual families. You're learning that the dream of perfect belonging both inspires and deceives. This isn't just escapism. It's genuine spiritual permeability around roots. The shadow is that idealization can prevent actual home-building. You may dream of perfect family without doing the work of real relating, or you may use spiritual longing to avoid facing actual family dynamics. The work is using your capacity to imagine sacred belonging while maintaining enough groundedness to create actual sanctuary.""",
        "feed": """Neptune is moving through your 4th house. Where you encounter mystery and dissolve boundaries is focused on home, family, and emotional foundation right now. This is a time for spiritual visions of belonging, for dissolving rigid family structures, for trusting that home can include mystery.""",
        "sonic": """Your Neptune in the 4th house contributes dreamlike emotional flow, dissolving harmonic foundations, and rhythm that is both protective and fluid. The quality of mystery is found in belonging, creating spiritual longing through visions of perfect home. Listen for music where domestic boundaries dissolve and family becomes spiritualized rather than rigidly defined.""",
    },
    "PLCMT_NEPTUNE_HOUSE5": {
        "core": """Your Neptune in the 5th house means where you encounter mystery and dissolve boundaries is organized around creativity, self-expression, and what joy means. Your relationship to pleasure is mystical. The 5th house is creative play and romance, and your Neptune here makes your capacity for imagination connected to what brings delight and how you express. You dissolve boundaries through idealized creativity and romance. Your confusion lives in what actually creates joy versus what you imagine should. Your spiritual longing is for perfect creative expression. You're wired to sense where rigid performance prevents actual flow. Creative boundaries are permeable. The work is maintaining enough form that compassion includes actual creation rather than just idealized art.""",
        "behavioral": """You idealize creativity, dream of perfect self-expression, and dissolve boundaries around what brings joy. When you're connecting to mystery, it arrives through visions of divine art or transcendent romance. Your confusion lives in the gap between ideal expression and messy actual creativity. You're learning that the dream of perfect art both inspires and deceives. This isn't just fantasy. It's genuine spiritual permeability around pleasure. The shadow is that idealization can prevent actual creation. You may dream of perfect art without making anything, or you may use romantic fantasy to avoid actual relationships. The work is using your capacity to imagine sacred creativity while maintaining enough discipline to actually express.""",
        "feed": """Neptune is moving through your 5th house. Where you encounter mystery and dissolve boundaries is focused on creativity, self-expression, and reimagining joy right now. This is a time for spiritual visions of art, for dissolving rigid performance, for trusting that pleasure can include mystery.""",
        "sonic": """Your Neptune in the 5th house contributes dreamlike creative expression, dissolving harmonic play, and rhythm that is both joyful and fluid. The quality of mystery is found in creativity, creating spiritual longing through visions of perfect art. Listen for music where creative boundaries dissolve and expression becomes transcendent rather than merely performative.""",
    },
    "PLCMT_NEPTUNE_HOUSE6": {
        "core": """Your Neptune in the 6th house means where you encounter mystery and dissolve boundaries is organized around work, health, and daily practice. Your relationship to service is mystical. The 6th house is useful labor and wellness, and your Neptune here makes your capacity for imagination connected to what heals and what serves. You dissolve boundaries through idealized service and healing. Your confusion lives in what actually creates health versus what feels like it should. Your spiritual longing is for perfect wellness and sacred work. You're wired to sense where rigid medicine prevents actual healing. Boundaries around body and work are permeable. The work is maintaining enough discipline that compassion includes actual health rather than just spiritual ideals.""",
        "behavioral": """You idealize healing and service, dream of perfect health, and dissolve boundaries around what counts as useful work. When you're connecting to mystery, it arrives through visions of sacred medicine or spiritual craft. Your confusion lives in the gap between ideal wellness and messy actual bodies. You're learning that the dream of perfect health both inspires and deceives. This isn't just bypassing. It's genuine spiritual permeability around function. The shadow is that idealization can prevent actual care. You may dream of perfect healing without developing real skill, or you may use spiritual medicine to avoid necessary medical intervention. The work is using your capacity to imagine sacred service while maintaining enough groundedness to care for actual bodies.""",
        "feed": """Neptune is moving through your 6th house. Where you encounter mystery and dissolve boundaries is focused on work, health, and daily practice right now. This is a time for spiritual visions of healing, for dissolving rigid medicine, for trusting that service can include mystery.""",
        "sonic": """Your Neptune in the 6th house contributes dreamlike precision, dissolving harmonic functionality, and rhythm that is both exact and fluid. The quality of mystery is found in service, creating spiritual longing through visions of perfect healing. Listen for music where boundaries around work dissolve and wellness becomes sacred rather than purely mechanical.""",
    },
    "PLCMT_NEPTUNE_HOUSE7": {
        "core": """Your Neptune in the 7th house means where you encounter mystery and dissolve boundaries is organized around partnership, relationship, and what equality means. Your relationship to others is mystical. The 7th house is one-on-one connection, and your Neptune here makes your capacity for imagination connected to how you relate and who you partner with. You dissolve boundaries through idealized partnership. Your confusion lives in who people actually are versus who you imagine them to be. Your spiritual longing is for perfect union. You're wired to sense where rigid boundaries prevent actual intimacy. Relational boundaries are permeable. The work is maintaining enough discernment that compassion includes seeing others clearly rather than just idealizing them.""",
        "behavioral": """You idealize partners, dream of perfect relationship, and dissolve boundaries around who others are. When you're connecting to mystery, it arrives through visions of soulmates or divine partnership. Your confusion lives in the gap between ideal others and actual people. You're learning that the dream of perfect union both inspires and deceives. This isn't just naivete. It's genuine spiritual permeability around relationship. The shadow is that idealization can prevent real connection. You may project divine qualities onto partners without seeing who they actually are, or you may use romantic fantasy to avoid the work of genuine relating. The work is using your capacity to imagine sacred partnership while maintaining enough discernment to see others clearly.""",
        "feed": """Neptune is moving through your 7th house. Where you encounter mystery and dissolve boundaries is focused on partnership, relationship, and reimagining equality right now. This is a time for spiritual visions of union, for dissolving rigid boundaries with others, for trusting that relationship can include mystery.""",
        "sonic": """Your Neptune in the 7th house contributes dreamlike melodic dialogue, dissolving harmonic partnership, and rhythm that is both relational and fluid. The quality of mystery is found in others, creating spiritual longing through visions of perfect union. Listen for music where boundaries between partners dissolve and relationship becomes transcendent rather than merely transactional.""",
    },
    "PLCMT_NEPTUNE_HOUSE8": {
        "core": """Your Neptune in the 8th house means where you encounter mystery and dissolve boundaries is organized around transformation, shared resources, and what's hidden. Your relationship to depth is mystical. The 8th house is psychological truth and power, and your Neptune here makes your capacity for imagination connected to what transforms and what's shared. You dissolve boundaries through idealized intimacy and spiritual transformation. Your confusion lives in what's actually happening in shadow versus what feels like spiritual depth. Your spiritual longing is for perfect merger and transcendent transformation. You're wired to sense where rigid boundaries prevent actual intimacy. Boundaries around power and shadow are permeable. The work is maintaining enough discernment that compassion includes seeing clearly rather than just spiritualizing everything.""",
        "behavioral": """You idealize depth and transformation, dream of perfect intimacy, and dissolve boundaries around what's hidden. When you're connecting to mystery, it arrives through visions of complete merger or spiritual alchemy. Your confusion lives in the gap between ideal transformation and messy actual shadows. You're learning that the dream of perfect depth both inspires and deceives. This isn't just avoidance. It's genuine spiritual permeability around power. The shadow is that idealization can prevent facing actual shadows. You may spiritualize darkness without doing the psychological work, or you may use transcendent visions to avoid dealing with real power dynamics. The work is using your capacity to imagine sacred transformation while maintaining enough groundedness to face actual shadows.""",
        "feed": """Neptune is moving through your 8th house. Where you encounter mystery and dissolve boundaries is focused on transformation, shared resources, and facing shadow right now. This is a time for spiritual visions of depth, for dissolving rigid boundaries around power, for trusting that intimacy can include mystery.""",
        "sonic": """Your Neptune in the 8th house contributes dreamlike chromatic depth, dissolving harmonic intensity, and rhythm that is both transformative and fluid. The quality of mystery is found in shadow, creating spiritual longing through visions of perfect merger. Listen for music where boundaries around power dissolve and transformation becomes sacred rather than purely psychological.""",
    },
    "PLCMT_NEPTUNE_HOUSE9": {
        "core": """Your Neptune in the 9th house means where you encounter mystery and dissolve boundaries is organized around belief, meaning, and what truth is. Your relationship to understanding is mystical. The 9th house is philosophy and expansion, and your Neptune here makes your capacity for imagination connected to what you believe and how you understand. You dissolve boundaries through idealized wisdom and spiritual philosophy. Your confusion lives in what's actually true versus what feels spiritually right. Your spiritual longing is for perfect understanding and universal truth. You're wired to sense where rigid belief prevents actual wisdom. Philosophical boundaries are permeable. The work is maintaining enough discernment that compassion includes clear thinking rather than just mystical sensing.""",
        "behavioral": """You idealize wisdom, dream of perfect understanding, and dissolve boundaries around what counts as truth. When you're connecting to mystery, it arrives through visions of universal philosophy or transcendent meaning. Your confusion lives in the gap between ideal wisdom and messy actual beliefs. You're learning that the dream of perfect understanding both inspires and deceives. This isn't just confusion. It's genuine spiritual permeability around truth. The shadow is that idealization can prevent actual learning. You may dream of perfect wisdom without doing the work of rigorous study, or you may use spiritual philosophy to avoid committing to any specific truth. The work is using your capacity to imagine universal understanding while maintaining enough clarity to actually learn and teach.""",
        "feed": """Neptune is moving through your 9th house. Where you encounter mystery and dissolve boundaries is focused on belief, meaning, and reimagining truth right now. This is a time for spiritual visions of wisdom, for dissolving rigid philosophy, for trusting that understanding can include mystery.""",
        "sonic": """Your Neptune in the 9th house contributes dreamlike melodic expansion, dissolving harmonic philosophy, and rhythm that is both exploratory and fluid. The quality of mystery is found in belief, creating spiritual longing through visions of universal truth. Listen for music where philosophical boundaries dissolve and meaning becomes transcendent rather than rigidly defined.""",
    },
    "PLCMT_NEPTUNE_HOUSE10": {
        "core": """Your Neptune in the 10th house means where you encounter mystery and dissolve boundaries is organized around career, public life, and what achievement means. Your relationship to success is mystical. The 10th house is vocation and reputation, and your Neptune here makes your capacity for imagination connected to what you do publicly and how you're known. You dissolve boundaries through idealized career and spiritual vocation. Your confusion lives in what you're actually called to do versus what feels like spiritual purpose. Your spiritual longing is for perfect vocation that serves the divine. You're wired to sense where rigid career paths prevent actual calling. Professional boundaries are permeable. The work is maintaining enough structure that compassion includes actual work rather than just idealized vocation.""",
        "behavioral": """You idealize your calling, dream of perfect vocation, and dissolve boundaries around what counts as success. When you're connecting to mystery, it arrives through visions of sacred work or spiritual achievement. Your confusion lives in the gap between ideal calling and messy actual career. You're learning that the dream of perfect vocation both inspires and deceives. This isn't just lack of ambition. It's genuine spiritual permeability around public work. The shadow is that idealization can prevent actual achievement. You may dream of perfect calling without building actual career, or you may use spiritual visions to avoid developing real professional competence. The work is using your capacity to imagine sacred vocation while maintaining enough discipline to actually work and succeed.""",
        "feed": """Neptune is moving through your 10th house. Where you encounter mystery and dissolve boundaries is focused on career, public achievement, and reimagining success right now. This is a time for spiritual visions of vocation, for dissolving rigid professionalism, for trusting that work can include mystery.""",
        "sonic": """Your Neptune in the 10th house contributes dreamlike melodic ambition, dissolving harmonic achievement, and rhythm that is both structured and fluid. The quality of mystery is found in vocation, creating spiritual longing through visions of perfect calling. Listen for music where professional boundaries dissolve and success becomes sacred rather than purely material.""",
    },
    "PLCMT_NEPTUNE_HOUSE11": {
        "core": """Your Neptune in the 11th house means where you encounter mystery and dissolve boundaries is organized around friendship, collective vision, and what community means. Your relationship to groups is mystical. The 11th house is friendship networks and shared dreams, and your Neptune here makes your capacity for imagination connected to how you belong to collectives and what future you envision. You dissolve boundaries through idealized community and spiritual collective vision. Your confusion lives in who people actually are versus who you imagine the collective to be. Your spiritual longing is for perfect community and universal brotherhood. You're wired to sense where rigid group structures prevent actual connection. Boundaries between self and collective are permeable. The work is maintaining enough individuality that compassion includes actual participation rather than just dissolving into the group.""",
        "behavioral": """You idealize community, dream of perfect collective, and dissolve boundaries around who belongs and what's shared. When you're connecting to mystery, it arrives through visions of universal family or spiritual movements. Your confusion lives in the gap between ideal community and messy actual groups. You're learning that the dream of perfect belonging both inspires and deceives. This isn't just naivete. It's genuine spiritual permeability around collective life. The shadow is that idealization can prevent real participation. You may dream of perfect community without doing the work of actual friendship, or you may lose yourself entirely in group visions without maintaining individual voice. The work is using your capacity to imagine sacred collective while maintaining enough self to actually contribute.""",
        "feed": """Neptune is moving through your 11th house. Where you encounter mystery and dissolve boundaries is focused on friendship, community, and collective vision right now. This is a time for spiritual visions of belonging, for dissolving rigid group structures, for trusting that community can include mystery.""",
        "sonic": """Your Neptune in the 11th house contributes dreamlike collaborative textures, dissolving harmonic collectivity, and rhythm that is both shared and fluid. The quality of mystery is found in groups, creating spiritual longing through visions of perfect community. Listen for music where boundaries between individuals dissolve and collective becomes sacred rather than merely organized.""",
    },
    "PLCMT_NEPTUNE_HOUSE12": {
        "core": """Your Neptune in the 12th house, its natural home, means where you encounter mystery and dissolve boundaries is at maximum capacity for transcendence, compassion, and spiritual connection. You dissolve most easily. The 12th house is the unconscious and what's beyond ego, and your Neptune here operates at full strength—sensing what's collective, creating what's universal, serving what's larger. Your confusion lives everywhere and nowhere. Your spiritual longing is for complete dissolution of separation. You're wired to sense all boundaries as illusion. Complete permeability is your nature. The work is maintaining enough self that compassion includes being present rather than just disappearing entirely.""",
        "behavioral": """You idealize transcendence itself, dream of complete dissolution, and dissolve boundaries around everything. When you're connecting to mystery, it's always and everywhere—you live in spiritual space more easily than material reality. Your confusion lives in what's real at all. You're learning that the dream of complete transcendence both inspires and prevents embodiment. This isn't just confusion. It's genuine spiritual permeability at maximum. The shadow is that dissolution can mean never showing up. You may live so completely in spiritual space that you're never actually present in material reality, or you may use transcendence to avoid all earthly responsibility. The work is using your profound capacity for spiritual connection while maintaining enough self to actually exist in the world and serve with your presence, not just your dissolution.""",
        "feed": """Neptune is moving through your 12th house, its natural home. Where you encounter mystery and dissolve boundaries is at maximum spiritual capacity right now. This is a time for profound transcendence, for dissolving all separation, for trusting complete spiritual permeability.""",
        "sonic": """Your Neptune in the 12th house contributes total harmonic dissolution, completely fluid melodic lines, and rhythm that barely exists as structure. The quality of mystery is absolute, creating spiritual longing through complete loss of boundaries. Listen for music where all separation dissolves and what remains is pure spiritual presence beyond form.""",
    },
}
