"""Uranus in houses 1-12 — Phase 3 placement copy (core, behavioral, feed, sonic)."""

UPDATES: dict[str, dict[str, str]] = {
    "PLCMT_URANUS_HOUSE1": {
        "core": """Your Uranus in the 1st house means where you innovate and break patterns is inseparable from your immediate presence and how you show up. Your individuality is revolutionary. The 1st house is self-presentation, and your Uranus here makes your capacity for innovation visible in how you appear. You disrupt through being yourself. Your insights arrive about identity and presentation. Your breakthrough is learning that your authentic presence is inherently unconventional. You're wired to see where self-expression has become performance of normalcy. Personal rebellion through existing exactly as you are is your work.""",
        "behavioral": """You break patterns through your presence, innovate in how you show up, and contribute to revolution simply by being visible as yourself. When you're being disruptive, it's through existing authentically rather than conforming to expected presentation. Your insights arrive suddenly about where you've been performing normalcy. You're learning that your natural way of being is the disruption. This isn't attention-seeking. It's genuine innovation through authentic presence. The shadow is that unconventionality can become performance. You may disrupt just to be different, or you may confuse being unusual with being free. The work is ensuring that what you're showing is actually who you are, not just what looks revolutionary.""",
        "feed": """Uranus is moving through your 1st house. Where you innovate and break patterns is focused on self-presentation, identity, and how you show up right now. This is a time for disrupting through authentic presence, for allowing your natural way of being to challenge norms, for trusting that being yourself is revolutionary.""",
        "sonic": """Your Uranus in the 1st house contributes unexpected melodic presence in the foreground, innovative harmonic self-expression, and rhythmic breaks in how identity is performed. The quality of innovation is immediate and personal, creating breakthrough through unconventional presence. Listen for music where showing up disrupts expectations and authentic being becomes revolution.""",
    },
    "PLCMT_URANUS_HOUSE2": {
        "core": """Your Uranus in the 2nd house means where you innovate and break patterns is organized around resources, value, and what security means. Your relationship to material reality is revolutionary. The 2nd house is resources and worth, and your Uranus here makes your capacity for innovation connected to reimagining how value works. You disrupt through unconventional relationship to money and earth. Your insights arrive about what actually has value and what security requires. Your breakthrough is learning that stability can be revolutionized. You're wired to see where conventional approaches to resources prevent actual sustainability. Material revolution is your work.""",
        "behavioral": """You break patterns around resources, innovate in how you create value, and contribute to revolution through reimagining what wealth and security mean. When you're being disruptive, it's through unconventional approaches to money, work, or physical reality. Your insights arrive suddenly about where traditional resource management prevents actual abundance. You're learning that security doesn't require conventional stability. This isn't instability. It's genuine innovation in how material reality operates. The shadow is that disruption can prevent building anything. You may break patterns around resources without creating sustainable alternatives, or you may confuse innovation with just refusing to earn money conventionally. The work is ensuring that your unconventional approaches actually create security rather than just avoiding traditional work.""",
        "feed": """Uranus is moving through your 2nd house. Where you innovate and break patterns is focused on resources, value, and reimagining security right now. This is a time for disrupting conventional approaches to money, for innovating in how you create value, for trusting that stability can be revolutionized.""",
        "sonic": """Your Uranus in the 2nd house contributes unexpected rhythmic accumulation, innovative harmonic value creation, and melodic breaks in conventional resource patterns. The quality of innovation is material and revolutionary, creating breakthrough through reimagined security. Listen for music where traditional approaches to stability are disrupted and new forms of sustainable abundance emerge.""",
    },
    "PLCMT_URANUS_HOUSE3": {
        "core": """Your Uranus in the 3rd house means where you innovate and break patterns is organized around communication, learning, and how ideas move. Your thinking is revolutionary. The 3rd house is thought and local connection, and your Uranus here makes your capacity for innovation connected to reimagining how we understand and communicate. You disrupt through unconventional ideas and communication. Your insights arrive about what counts as knowledge and how information should flow. Your breakthrough is learning that thought itself can be revolutionized. You're wired to see where conventional education and communication prevent actual understanding. Intellectual revolution is your work.""",
        "behavioral": """You break patterns in how you think and communicate, innovate in learning and sharing ideas, and contribute to revolution through unconventional intellectual approaches. When you're being disruptive, it's through thinking differently or communicating in ways that challenge norms. Your insights arrive suddenly about where conventional thought and language prevent actual understanding. You're learning that new ideas require new ways of thinking. This isn't just being difficult. It's genuine innovation in how minds work. The shadow is that unconventionality can prevent communication. You may think so differently that no one understands you, or you may confuse innovation with just being obscure. The work is ensuring that your unconventional thinking actually serves understanding rather than just proving you're original.""",
        "feed": """Uranus is moving through your 3rd house. Where you innovate and break patterns is focused on communication, learning, and how ideas move right now. This is a time for disrupting conventional thought, for innovating in how you understand and share, for trusting that thinking itself can be revolutionized.""",
        "sonic": """Your Uranus in the 3rd house contributes sudden melodic connections, innovative harmonic communication, and rhythmic breaks in conventional thought patterns. The quality of innovation is mental and disruptive, creating breakthrough through reimagined understanding. Listen for music where ideas move in unexpected ways and communication disrupts normal patterns of thought.""",
    },
    "PLCMT_URANUS_HOUSE4": {
        "core": """Your Uranus in the 4th house means where you innovate and break patterns is organized around home, family, and what belonging means. Your relationship to roots is revolutionary. The 4th house is foundation and private life, and your Uranus here makes your capacity for innovation connected to reimagining what home and family are. You disrupt through unconventional approaches to domesticity and emotional foundation. Your insights arrive about what actually creates belonging and safety. Your breakthrough is learning that home itself can be revolutionized. You're wired to see where traditional family structures prevent actual emotional connection. Domestic revolution is your work.""",
        "behavioral": """You break patterns around home and family, innovate in how you create emotional foundation, and contribute to revolution through reimagining what belonging means. When you're being disruptive, it's through unconventional living situations or relationships to family. Your insights arrive suddenly about where traditional domesticity prevents actual safety. You're learning that genuine home might look nothing like what previous generations created. This isn't just rebellion against family. It's genuine innovation in how we belong. The shadow is that disruption can prevent rootedness. You may break every domestic pattern without building actual foundation, or you may confuse innovation with just refusing to settle anywhere. The work is ensuring that your unconventional approaches actually create sanctuary rather than just avoiding traditional home.""",
        "feed": """Uranus is moving through your 4th house. Where you innovate and break patterns is focused on home, family, and emotional foundation right now. This is a time for disrupting conventional domesticity, for innovating in how you create belonging, for trusting that home can be revolutionized.""",
        "sonic": """Your Uranus in the 4th house contributes unexpected emotional rhythms, innovative harmonic foundations, and melodic breaks in conventional family structures. The quality of innovation is domestic and revolutionary, creating breakthrough through reimagined belonging. Listen for music where traditional notions of home are disrupted and new forms of sanctuary emerge.""",
    },
    "PLCMT_URANUS_HOUSE5": {
        "core": """Your Uranus in the 5th house means where you innovate and break patterns is organized around creativity, self-expression, and what joy means. Your relationship to pleasure is revolutionary. The 5th house is creative expression and play, and your Uranus here makes your capacity for innovation connected to reimagining what art and celebration are. You disrupt through unconventional creativity and romance. Your insights arrive about what actually brings joy and what creative expression serves. Your breakthrough is learning that play itself can be revolutionized. You're wired to see where conventional approaches to art and pleasure have become formulaic. Creative revolution is your work.""",
        "behavioral": """You break patterns around creativity and pleasure, innovate in how you express yourself and celebrate, and contribute to revolution through unconventional art and joy. When you're being disruptive, it's through creating in ways that challenge norms or finding pleasure in unexpected places. Your insights arrive suddenly about where conventional art and romance prevent actual expression and connection. You're learning that genuine creativity might look nothing like what's been done before. This isn't just shock value. It's genuine innovation in how expression works. The shadow is that disruption can replace actual creation. You may break creative patterns without making anything, or you may confuse innovation with just being outrageous. The work is ensuring that your unconventional approaches actually serve expression rather than just proving you're different.""",
        "feed": """Uranus is moving through your 5th house. Where you innovate and break patterns is focused on creativity, self-expression, and reimagining joy right now. This is a time for disrupting conventional art and pleasure, for innovating in how you create and celebrate, for trusting that expression can be revolutionized.""",
        "sonic": """Your Uranus in the 5th house contributes sudden creative bursts, innovative harmonic play, and rhythmic breaks in conventional expression. The quality of innovation is artistic and celebratory, creating breakthrough through reimagined creativity. Listen for music where traditional forms of art are disrupted and new ways of expressing joy emerge.""",
    },
    "PLCMT_URANUS_HOUSE6": {
        "core": """Your Uranus in the 6th house means where you innovate and break patterns is organized around work, health, and daily practice. Your relationship to service is revolutionary. The 6th house is useful work and wellness, and your Uranus here makes your capacity for innovation connected to reimagining what functional means. You disrupt through unconventional approaches to work and body care. Your insights arrive about what actually creates health and what useful service requires. Your breakthrough is learning that work itself can be revolutionized. You're wired to see where conventional approaches to labor and wellness prevent actual function. Work revolution is your work.""",
        "behavioral": """You break patterns around work and health, innovate in daily practice and service, and contribute to revolution through unconventional approaches to function. When you're being disruptive, it's through working differently or caring for your body in unexpected ways. Your insights arrive suddenly about where traditional work and medical models prevent actual wellness and usefulness. You're learning that genuine health and service might look nothing like conventional approaches. This isn't just laziness or quackery. It's genuine innovation in how bodies function and work serves. The shadow is that disruption can prevent actual care. You may break every health pattern without building sustainable wellness, or you may confuse innovation with just refusing conventional work. The work is ensuring that your unconventional approaches actually serve your body and create useful contribution.""",
        "feed": """Uranus is moving through your 6th house. Where you innovate and break patterns is focused on work, health, and daily practice right now. This is a time for disrupting conventional labor and wellness, for innovating in how you serve and care for your body, for trusting that function can be revolutionized.""",
        "sonic": """Your Uranus in the 6th house contributes unexpected rhythmic precision, innovative harmonic functionality, and melodic breaks in conventional work patterns. The quality of innovation is practical and revolutionary, creating breakthrough through reimagined service. Listen for music where traditional approaches to work are disrupted and new forms of sustainable function emerge.""",
    },
    "PLCMT_URANUS_HOUSE7": {
        "core": """Your Uranus in the 7th house means where you innovate and break patterns is organized around partnership, relationship, and how you relate to equals. Your partnerships are revolutionary. The 7th house is committed connection, and your Uranus here makes your capacity for innovation connected to reimagining what partnership means. You disrupt through unconventional relationships. Your insights arrive about what genuine equality requires. Your breakthrough is learning that partnership itself can be revolutionized. You're wired to see where conventional relating prevents actual connection. Relationship revolution is your work.""",
        "behavioral": """You break patterns in partnership, innovate in how you relate to equals, and contribute to revolution through unconventional relationship structures. When you're being disruptive, it's through relating in ways that challenge traditional partnership. Your insights arrive suddenly about where conventional marriage or commitment prevents actual intimacy. You're learning that genuine partnership might look nothing like traditional models. This isn't just commitment-phobia. It's genuine innovation in how equals relate. The shadow is that disruption can prevent actual partnership. You may break every relationship pattern without building genuine connection, or you may confuse innovation with just avoiding commitment. The work is ensuring that your unconventional approaches actually serve partnership rather than just proving you're different.""",
        "feed": """Uranus is moving through your 7th house. Where you innovate and break patterns is focused on partnership, relationship, and reimagining commitment right now. This is a time for disrupting conventional relating, for innovating in how you connect with equals, for trusting that partnership can be revolutionized.""",
        "sonic": """Your Uranus in the 7th house contributes unexpected harmonic dialogue, innovative melodic partnership, and rhythmic breaks in conventional relationship patterns. The quality of innovation is relational and revolutionary, creating breakthrough through reimagined equality. Listen for music where traditional partnership is disrupted and new forms of relating emerge.""",
    },
    "PLCMT_URANUS_HOUSE8": {
        "core": """Your Uranus in the 8th house means where you innovate and break patterns is organized around transformation, shared resources, and facing what's hidden. Your relationship to depth is revolutionary. The 8th house is psychological truth and power, and your Uranus here makes your capacity for innovation connected to reimagining what intimacy and transformation mean. You disrupt through unconventional approaches to shadow and shared power. Your insights arrive about what actually transforms and how power should be shared. Your breakthrough is learning that depth itself can be revolutionized. You're wired to see where conventional psychology prevents actual transformation. Shadow revolution is your work.""",
        "behavioral": """You break patterns around intimacy and transformation, innovate in how you share power and face shadows, and contribute to revolution through unconventional depth work. When you're being disruptive, it's through relating to darkness in unexpected ways or sharing resources unconventionally. Your insights arrive suddenly about where traditional psychology or conventional intimacy prevents actual transformation. You're learning that genuine depth might look nothing like conventional therapy or expected intimacy. This isn't just rebellion against therapy. It's genuine innovation in how transformation works. The shadow is that disruption can prevent actual healing. You may break every psychological pattern without doing real shadow work, or you may confuse innovation with just exposing everything. The work is ensuring that your unconventional approaches actually serve transformation rather than just proving you're intense.""",
        "feed": """Uranus is moving through your 8th house. Where you innovate and break patterns is focused on transformation, shared resources, and reimagining depth right now. This is a time for disrupting conventional psychology, for innovating in how you face shadow, for trusting that intimacy can be revolutionized.""",
        "sonic": """Your Uranus in the 8th house contributes sudden chromatic shifts, innovative harmonic depth, and rhythmic breaks in conventional transformation patterns. The quality of innovation is psychological and revolutionary, creating breakthrough through reimagined intimacy. Listen for music where traditional approaches to shadow are disrupted and new forms of transformation emerge.""",
    },
    "PLCMT_URANUS_HOUSE9": {
        "core": """Your Uranus in the 9th house means where you innovate and break patterns is organized around belief, meaning, and what truth is. Your philosophy is revolutionary. The 9th house is understanding and expansion, and your Uranus here makes your capacity for innovation connected to reimagining what wisdom means. You disrupt through unconventional beliefs and radical philosophy. Your insights arrive about what actually constitutes truth and understanding. Your breakthrough is learning that belief itself can be revolutionized. You're wired to see where conventional education and religion prevent actual wisdom. Philosophical revolution is your work.""",
        "behavioral": """You break patterns in belief, innovate in how you understand and find meaning, and contribute to revolution through unconventional philosophy. When you're being disruptive, it's through believing in ways that challenge traditional religion or education. Your insights arrive suddenly about where conventional wisdom prevents actual understanding. You're learning that genuine truth might look nothing like what's been taught. This isn't just skepticism. It's genuine innovation in how meaning works. The shadow is that disruption can prevent any stable worldview. You may break every belief system without building coherent understanding, or you may confuse innovation with just being contrarian. The work is ensuring that your unconventional beliefs actually serve wisdom rather than just proving you think differently.""",
        "feed": """Uranus is moving through your 9th house. Where you innovate and break patterns is focused on belief, meaning, and reimagining truth right now. This is a time for disrupting conventional wisdom, for innovating in how you understand, for trusting that philosophy can be revolutionized.""",
        "sonic": """Your Uranus in the 9th house contributes unexpected melodic expansion, innovative harmonic philosophy, and rhythmic breaks in conventional belief systems. The quality of innovation is intellectual and revolutionary, creating breakthrough through reimagined wisdom. Listen for music where traditional understanding is disrupted and new forms of truth emerge.""",
    },
    "PLCMT_URANUS_HOUSE10": {
        "core": """Your Uranus in the 10th house means where you innovate and break patterns is organized around career, public achievement, and how you're known. Your vocation is revolutionary. The 10th house is professional life and authority, and your Uranus here makes your capacity for innovation connected to reimagining what success and leadership mean. You disrupt through unconventional career paths and challenging hierarchies. Your insights arrive about what work should actually be and how authority should operate. Your breakthrough is learning that professional life itself can be revolutionized. You're wired to see where conventional career paths prevent actual contribution. Vocational revolution is your work.""",
        "behavioral": """You break patterns in career, innovate in how you achieve and lead, and contribute to revolution through unconventional professional life. When you're being disruptive, it's through working in unexpected ways or challenging traditional authority structures. Your insights arrive suddenly about where conventional success prevents actual meaningful work. You're learning that genuine achievement might look nothing like traditional careers. This isn't just job-hopping. It's genuine innovation in how work operates. The shadow is that disruption can prevent building anything. You may break every professional pattern without developing actual expertise, or you may confuse innovation with just refusing all structure. The work is ensuring that your unconventional career actually serves contribution rather than just proving you're different.""",
        "feed": """Uranus is moving through your 10th house. Where you innovate and break patterns is focused on career, public achievement, and reimagining success right now. This is a time for disrupting conventional professionalism, for innovating in how you work and lead, for trusting that vocation can be revolutionized.""",
        "sonic": """Your Uranus in the 10th house contributes unexpected structural breaks, innovative harmonic achievement, and rhythmic disruption of conventional hierarchies. The quality of innovation is professional and revolutionary, creating breakthrough through reimagined authority. Listen for music where traditional career paths are disrupted and new forms of legitimate leadership emerge.""",
    },
    "PLCMT_URANUS_HOUSE11": {
        "core": """Your Uranus in the 11th house, its natural home, means where you innovate and break patterns is at maximum capacity for collective vision, revolutionary community, and reimagining what progress means. Revolution is your element. The 11th house is friendship networks and shared dreams, and your Uranus here operates at full strength—disrupting groups, envisioning new futures, challenging what community means. You disrupt through being yourself in collective space. Your insights arrive about how humanity should organize. Your breakthrough is recognizing that you are the revolution. Collective innovation is your nature.""",
        "behavioral": """You break patterns in groups naturally, innovate in collective space as your essence, and contribute to revolution through simply being part of communities. When you're being disruptive, it's often just through existing as yourself within collectives. Your insights arrive suddenly about where groups have become rigid or where friendship has become conformity. You're learning that genuine community might look nothing like any existing model. This isn't just rebellion against groups. It's your natural capacity for collective innovation. The shadow is that disruption can prevent actual belonging. You may break every group pattern without creating sustainable community, or you may confuse revolution with just refusing to commit to any collective. The work is using your profound capacity for innovation to actually liberate communities rather than just proving you're ahead of your time.""",
        "feed": """Uranus is moving through your 11th house, its natural home. Where you innovate and break patterns is at maximum revolutionary capacity in collective space right now. This is a time for natural disruption of groups, for trusting that your presence changes communities, for recognizing that revolution is your nature.""",
        "sonic": """Your Uranus in the 11th house contributes maximum collaborative innovation, naturally disruptive harmonic collectivity, and rhythmic patterns that challenge all group conventions. The quality of innovation is communal and unlimited, creating breakthrough through reimagined humanity. Listen for music where every pattern of belonging is disrupted and community itself becomes the revolution.""",
    },
    "PLCMT_URANUS_HOUSE12": {
        "core": """Your Uranus in the 12th house means where you innovate and break patterns is organized around the unconscious, spirituality, and what's hidden. Your relationship to mystery is revolutionary. The 12th house is transcendence and the invisible, and your Uranus here makes your capacity for innovation connected to reimagining what spiritual practice and unconscious work mean. You disrupt through unconventional spirituality and sudden breakthroughs from the unconscious. Your insights arrive from invisible realms. Your breakthrough is learning that even the formless can be revolutionized. You're wired to see where conventional spirituality prevents actual transcendence. Spiritual revolution is your work.""",
        "behavioral": """You break patterns in spiritual practice, innovate in how you work with the unconscious, and contribute to revolution through unconventional approaches to mystery. When you're being disruptive, it's through relating to the invisible in unexpected ways. Your insights arrive suddenly from dreams, meditation, or unconscious spaces about where traditional spirituality prevents actual connection to the divine. You're learning that genuine transcendence might look nothing like conventional religious practice. This isn't just New Age rebellion. It's genuine innovation in how we relate to mystery. The shadow is that disruption can prevent grounding. You may break every spiritual pattern without building sustainable practice, or you may confuse innovation with just chaotic spiritual experimentation. The work is ensuring that your unconventional approaches actually serve connection to the divine rather than just proving you're spiritually unique.""",
        "feed": """Uranus is moving through your 12th house. Where you innovate and break patterns is focused on the unconscious, spirituality, and reimagining mystery right now. This is a time for disrupting conventional spiritual practice, for innovating in how you work with the invisible, for trusting that even transcendence can be revolutionized.""",
        "sonic": """Your Uranus in the 12th house contributes sudden dissolution, innovative harmonic transcendence, and rhythmic breaks that emerge from unconscious space. The quality of innovation is spiritual and revolutionary, creating breakthrough through reimagined mystery. Listen for music where traditional spirituality is disrupted and new forms of connection to the invisible emerge from unexpected silence.""",
    },
}
