"""Saturn in houses 1-12 — Phase 3 placement copy (core, behavioral, feed, sonic)."""

UPDATES: dict[str, dict[str, str]] = {
    "PLCMT_SATURN_HOUSE1": {
        "core": """Your Saturn in the 1st house means where you face limitation and build mastery is inseparable from your immediate presence and how you appear. You're learning to show up. The 1st house is self-presentation, and your Saturn here makes your challenges visible in how you enter rooms and claim space. You struggle with being seen. Your discipline develops through learning that your presence matters. Your mastery comes from building genuine confidence in existing. You're learning that you deserve to take up space. Self-effacement feels familiar to your Saturn but embodied authority is what you're building toward. The work is developing the capacity to be visible without either hiding or overcompensating.""",
        "behavioral": """You struggle with visibility, work to build confidence in your presence, and develop mastery through learning to show up without apology. When you need to be visible, you might shrink or overcompensate with rigid performance. When you're developing your sense of self, you're learning the difference between genuine authority and defensive posturing. Your growth is measured in how you overcome fear of being seen. You take your presence seriously. This isn't vanity. It's genuine work with difficult material. The maturation is learning that you can exist visibly, that your presence is legitimate, that showing up doesn't require perfection. Your mastery is earned presence—the capacity to be seen without needing validation or fearing judgment.""",
        "feed": """Saturn is moving through your 1st house. The areas where you face limitation and build mastery are focused on self-presentation, visibility, and learning to claim space right now. This is a time for working with how you show up, for building genuine presence, for earning the right to exist without apology.""",
        "sonic": """Your Saturn in the 1st house contributes measured rhythmic presence, disciplined melodic assertion in the foreground, and harmonic restraint around visibility. The quality of limitation is found in fear of being seen, creating mastery through earned confidence. Listen for music where presence is built through patient practice, where showing up is learned rather than assumed.""",
    },
    "PLCMT_SATURN_HOUSE2": {
        "core": """Your Saturn in the 2nd house means where you face limitation and build mastery is organized around resources, self-worth, and learning that you're enough. You're learning security. The 2nd house is material reality and value, and your Saturn here makes your challenges show up around money and worthiness. You struggle with feeling you have enough or are enough. Your discipline develops through building resources carefully. Your mastery comes from creating genuine stability. You're learning that your value isn't proven through scarcity. Resource anxiety feels familiar to your Saturn but earned abundance is what you're building toward. The work is developing the capacity to feel secure without needing to control everything material.""",
        "behavioral": """You struggle with feeling worthy or secure, work to build material stability, and develop mastery through learning when enough is actually enough. When you're facing resource questions, you might restrict excessively or work compulsively to earn security. When you're developing your sense of value, you're learning the difference between genuine worth and the illusion that more money equals more value. Your growth is measured in how you overcome scarcity thinking. You take resources and self-worth seriously. This isn't greed. It's genuine work with difficult material. The maturation is learning that you can be secure, that you're inherently worthy, that value doesn't require constant proof. Your mastery is earned groundedness—the capacity to feel stable in material reality and in your own worth.""",
        "feed": """Saturn is moving through your 2nd house. The areas where you face limitation and build mastery are focused on resources, self-worth, and learning security right now. This is a time for working with money and value, for building genuine stability, for earning the right to feel you have enough and are enough.""",
        "sonic": """Your Saturn in the 2nd house contributes measured rhythmic accumulation, disciplined harmonic building, and melodic restraint around resources. The quality of limitation is found in scarcity fear, creating mastery through earned abundance. Listen for music where security is built through patient work, where worth is proven through sustained presence rather than constant acquisition.""",
    },
    "PLCMT_SATURN_HOUSE3": {
        "core": """Your Saturn in the 3rd house means where you face limitation and build mastery is organized around communication, learning, and trusting your mind. You're learning to speak with authority. The 3rd house is thought and local connection, and your Saturn here makes your challenges show up when you need to communicate or learn. You struggle with feeling intellectually adequate. Your discipline develops through mental rigor and careful speech. Your mastery comes from building genuine intellectual confidence. You're learning that your ideas matter even when imperfectly expressed. Mental inadequacy feels familiar to your Saturn but earned articulation is what you're building toward. The work is developing the capacity to think and speak without requiring perfection.""",
        "behavioral": """You struggle with communication, work to build intellectual confidence, and develop mastery through learning to express ideas clearly despite fear. When you need to speak, you might stay silent or cover insecurity with excessive formality. When you're developing your mind, you're learning the difference between genuine understanding and performance of intelligence. Your growth is measured in how you overcome fear of appearing foolish. You take ideas and communication seriously. This isn't intellectual inadequacy. It's genuine work with difficult material. The maturation is learning that you can think clearly, that your words matter, that communication serves connection even when imperfect. Your mastery is earned voice—the capacity to speak with both authority and humility.""",
        "feed": """Saturn is moving through your 3rd house. The areas where you face limitation and build mastery are focused on communication, learning, and intellectual authority right now. This is a time for working with your voice and mind, for building genuine mental confidence, for earning the right to speak without apology.""",
        "sonic": """Your Saturn in the 3rd house contributes careful melodic articulation, disciplined harmonic phrasing, and rhythmic restraint around communication. The quality of limitation is found in fear of speech, creating mastery through earned clarity. Listen for music where ideas are expressed with patient precision, where communication is built through practice rather than assumed ease.""",
    },
    "PLCMT_SATURN_HOUSE4": {
        "core": """Your Saturn in the 4th house means where you face limitation and build mastery is organized around home, family, and emotional foundation. You're learning to create sanctuary. The 4th house is roots and private life, and your Saturn here makes your challenges show up around emotional safety and belonging. You struggle with feeling at home anywhere. Your discipline develops through building foundation deliberately. Your mastery comes from creating genuine sanctuary. You're learning that home can be built, not just inherited. Emotional restriction feels familiar to your Saturn but earned safety is what you're building toward. The work is developing the capacity to feel rooted without requiring perfect conditions.""",
        "behavioral": """You struggle with feeling safe at home, work to build emotional foundation, and develop mastery through learning to create sanctuary even when family origins were difficult. When you're trying to belong, you might stay defended or work compulsively to make home perfect. When you're developing your roots, you're learning the difference between genuine safety and the illusion that perfect control creates security. Your growth is measured in how you overcome fear of emotional vulnerability in private. You take home and family seriously. This isn't coldness. It's genuine work with difficult material. The maturation is learning that you can create home, that you deserve sanctuary, that emotional safety doesn't require perfection. Your mastery is earned rootedness—the capacity to feel at home in your body and your life.""",
        "feed": """Saturn is moving through your 4th house. The areas where you face limitation and build mastery are focused on home, emotional foundation, and creating sanctuary right now. This is a time for working with your roots and private life, for building genuine safety, for earning the right to feel at home.""",
        "sonic": """Your Saturn in the 4th house contributes deep harmonic grounding with restraint, disciplined emotional phrasing, and rhythm that is protective but learning to flow. The quality of limitation is found in emotional restriction, creating mastery through earned sanctuary. Listen for music where home is built through patient work, where safety is created through deliberate foundation-building.""",
    },
    "PLCMT_SATURN_HOUSE5": {
        "core": """Your Saturn in the 5th house means where you face limitation and build mastery is organized around creativity, self-expression, and learning to play. You're learning joy. The 5th house is creative pleasure and romance, and your Saturn here makes your challenges show up around allowing yourself to create and enjoy. You struggle with feeling you deserve pleasure. Your discipline develops through taking creativity seriously. Your mastery comes from building genuine capacity for joy. You're learning that play is legitimate work. Seriousness feels familiar to your Saturn but earned delight is what you're building toward. The work is developing the capacity to create and enjoy without requiring productive justification.""",
        "behavioral": """You struggle with allowing pleasure, work to build creative confidence, and develop mastery through learning that joy serves life. When you're trying to create or play, you might block yourself or turn everything into work. When you're developing your capacity for pleasure, you're learning the difference between genuine joy and performance of happiness. Your growth is measured in how you overcome fear that pleasure is frivolous. You take creativity and joy seriously. This isn't joylessness. It's genuine work with difficult material. The maturation is learning that you can play, that you deserve pleasure, that creativity doesn't require productivity to be legitimate. Your mastery is earned joy—the capacity to create and delight without apology.""",
        "feed": """Saturn is moving through your 5th house. The areas where you face limitation and build mastery are focused on creativity, self-expression, and learning to play right now. This is a time for working with your capacity for joy, for building genuine creative confidence, for earning the right to pleasure.""",
        "sonic": """Your Saturn in the 5th house contributes measured creative expression, disciplined melodic play, and harmonic restraint around pleasure that's learning to celebrate. The quality of limitation is found in fear of joy, creating mastery through earned delight. Listen for music where creativity is built through patient practice, where play is learned rather than spontaneous.""",
    },
    "PLCMT_SATURN_HOUSE6": {
        "core": """Your Saturn in the 6th house means where you face limitation and build mastery is organized around work, health, and useful service. You're learning skillful labor. The 6th house is daily practice and physical function, and your Saturn here makes your challenges show up around work and wellness. You struggle with feeling competent or healthy. Your discipline develops through careful practice and attention to your body. Your mastery comes from building genuine skill and sustainable health. You're learning that competence is earned, not innate. Harsh self-criticism feels familiar to your Saturn but earned craftsmanship is what you're building toward. The work is developing the capacity to work and care for your body without perfectionism destroying you.""",
        "behavioral": """You struggle with feeling competent or well, work to build genuine skill and health, and develop mastery through learning when good enough is actually good enough. When you're working or tending your body, you might avoid from fear of failure or work obsessively chasing impossible standards. When you're developing your craft or wellness, you're learning the difference between genuine refinement and self-punishment disguised as improvement. Your growth is measured in how you overcome fear of incompetence or illness. You take work and health seriously. This isn't perfectionism. It's genuine dedication to craft and care. The maturation is learning that you can be skillful, that your work is valuable even when imperfect, that health includes rest. Your mastery is earned competence—the capacity to work well and care for your body without destroying yourself through impossible standards.""",
        "feed": """Saturn is moving through your 6th house. The areas where you face limitation and build mastery are focused on work, health, and daily practice right now. This is a time for building genuine skill, for tending your body, for earning competence through sustained effort without perfectionism.""",
        "sonic": """Your Saturn in the 6th house contributes precise rhythmic execution with restraint, disciplined melodic detail, and harmonic refinement that's learning self-compassion. The quality of limitation is found in fear of incompetence, creating mastery through earned skill. Listen for music where craft is built through patient practice, where work is sustained without perfectionism destroying the process.""",
    },
    "PLCMT_SATURN_HOUSE7": {
        "core": """Your Saturn in the 7th house means where you face limitation and build mastery is organized around partnership, commitment, and learning to relate as equals. You're learning partnership. The 7th house is one-on-one connection, and your Saturn here makes your challenges show up in relationships. You struggle with trusting partnership or feeling worthy of genuine equals. Your discipline develops through learning when commitment serves both people. Your mastery comes from building genuine equality in relationship. You're learning that partnership requires work but is possible. Isolation or imbalanced relationships feel familiar to your Saturn but earned partnership is what you're building toward. The work is developing the capacity to commit without losing yourself or avoiding commitment from fear.""",
        "behavioral": """You struggle with partnership, work to build capacity for commitment, and develop mastery through learning to relate as equals. When you're in relationships, you might avoid commitment or take on too much responsibility. When you're developing your capacity to partner, you're learning the difference between genuine equality and either merging or isolation. Your growth is measured in how you overcome fear of depending on another or being depended upon. You take relationship seriously. This isn't commitment-phobia. It's genuine work with difficult material. The maturation is learning that you can partner, that you're worthy of equals, that commitment can be mutual rather than one-sided. Your mastery is earned partnership—the capacity to commit while maintaining your own development.""",
        "feed": """Saturn is moving through your 7th house. The areas where you face limitation and build mastery are focused on partnership, commitment, and relating as equals right now. This is a time for working with relationship, for building genuine equality, for earning the capacity to commit without losing yourself.""",
        "sonic": """Your Saturn in the 7th house contributes measured melodic dialogue, disciplined harmonic partnership, and rhythmic restraint around commitment that's learning to trust. The quality of limitation is found in fear of depending on others, creating mastery through earned equality. Listen for music where partnership is built through patient work, where commitment is learned rather than assumed.""",
    },
    "PLCMT_SATURN_HOUSE8": {
        "core": """Your Saturn in the 8th house means where you face limitation and build mastery is organized around transformation, shared resources, and facing what's hidden. You're learning depth. The 8th house is psychological truth and power, and your Saturn here makes your challenges show up around intimacy and shared power. You struggle with trusting deep connection or facing shadows. Your discipline develops through learning when vulnerability serves transformation. Your mastery comes from building genuine capacity for psychological intimacy. You're learning that depth is earned, not just felt. Emotional distance feels familiar to your Saturn but earned intimacy is what you're building toward. The work is developing the capacity to merge and transform without controlling or avoiding the process.""",
        "behavioral": """You struggle with deep intimacy, work to build capacity for transformation, and develop mastery through learning to share power and face shadows. When you're in situations requiring vulnerability or shared resources, you might control rigidly or avoid entirely. When you're developing your capacity for depth, you're learning the difference between genuine transformation and either forced change or stagnation. Your growth is measured in how you overcome fear of losing control or being transformed. You take depth and power seriously. This isn't coldness. It's genuine work with difficult material. The maturation is learning that you can be vulnerable, that you can share power, that transformation serves growth when faced consciously. Your mastery is earned depth—the capacity to merge and transform while maintaining your integrity.""",
        "feed": """Saturn is moving through your 8th house. The areas where you face limitation and build mastery are focused on transformation, shared resources, and psychological depth right now. This is a time for working with intimacy and power, for building genuine capacity for vulnerability, for earning the right to transform.""",
        "sonic": """Your Saturn in the 8th house contributes restrained chromatic depth, disciplined harmonic intensity, and rhythmic confrontation with power that's learning to surrender. The quality of limitation is found in fear of loss of control, creating mastery through earned transformation. Listen for music where depth is built through patient work with shadow, where intimacy is earned through facing what's hidden.""",
    },
    "PLCMT_SATURN_HOUSE9": {
        "core": """Your Saturn in the 9th house means where you face limitation and build mastery is organized around belief, meaning, and learning to trust larger truths. You're learning wisdom. The 9th house is philosophy and expansion, and your Saturn here makes your challenges show up around believing and understanding. You struggle with trusting your own philosophical insights or feeling educated enough. Your discipline develops through rigorous study and testing beliefs. Your mastery comes from building genuine wisdom through experience. You're learning that understanding is earned through questioning. Intellectual insecurity feels familiar to your Saturn but earned wisdom is what you're building toward. The work is developing the capacity to believe and teach without requiring perfect knowledge.""",
        "behavioral": """You struggle with trusting your beliefs, work to build philosophical authority, and develop mastery through learning that wisdom comes from questioning rather than certainty. When you're forming beliefs or teaching, you might doubt yourself or compensate with rigid dogma. When you're developing your understanding, you're learning the difference between genuine wisdom and either intellectual insecurity or defensive certainty. Your growth is measured in how you overcome fear of not knowing enough. You take belief and understanding seriously. This isn't ignorance. It's genuine work with difficult material. The maturation is learning that you can have wisdom, that your understanding matters, that teaching doesn't require knowing everything. Your mastery is earned philosophy—the capacity to believe and teach while remaining humble and open.""",
        "feed": """Saturn is moving through your 9th house. The areas where you face limitation and build mastery are focused on belief, meaning, and philosophical authority right now. This is a time for working with your understanding, for building genuine wisdom, for earning the right to your own truths.""",
        "sonic": """Your Saturn in the 9th house contributes measured melodic expansion, disciplined harmonic philosophy, and rhythmic restraint around belief that's learning to trust. The quality of limitation is found in fear of not understanding enough, creating mastery through earned wisdom. Listen for music where understanding is built through patient questioning, where wisdom is earned through experience rather than assumed.""",
    },
    "PLCMT_SATURN_HOUSE10": {
        "core": """Your Saturn in the 10th house means where you face limitation and build mastery is organized around career, public achievement, and earning legitimate authority. You're learning professional mastery. The 10th house is vocation and reputation, and your Saturn here makes your challenges show up in your public life and career. You struggle with feeling adequate professionally or worthy of recognition. Your discipline develops through patient work toward long-term goals. Your mastery comes from building genuine authority through demonstrated competence. You're learning that achievement requires time and sustained effort. Professional inadequacy feels familiar to your Saturn but earned authority is what you're building toward. The work is developing the capacity to succeed publicly without requiring perfection or fearing judgment.""",
        "behavioral": """You struggle with feeling professionally adequate, work to build genuine authority, and develop mastery through learning that achievement is earned through sustained effort. When you're pursuing career goals or public visibility, you might hold back from fear of failure or work compulsively to prove worth. When you're developing your professional capacity, you're learning the difference between genuine mastery and either self-doubt or overcompensation. Your growth is measured in how you overcome fear of professional inadequacy. You take career and achievement seriously. This isn't lack of ambition. It's genuine work with difficult material. The maturation is learning that you can succeed, that you can earn authority, that professional achievement serves your life when pursued consciously. Your mastery is earned authority—the capacity to succeed publicly while maintaining integrity and balance.""",
        "feed": """Saturn is moving through your 10th house. The areas where you face limitation and build mastery are focused on career, public achievement, and professional authority right now. This is a time for working toward long-term goals, for building genuine mastery, for earning legitimate authority through demonstrated competence.""",
        "sonic": """Your Saturn in the 10th house contributes structured rhythmic ambition, disciplined harmonic achievement, and melodic building toward public mastery. The quality of limitation is found in fear of professional inadequacy, creating mastery through earned authority. Listen for music where success is built through patient work, where achievement is earned through sustained effort over time.""",
    },
    "PLCMT_SATURN_HOUSE11": {
        "core": """Your Saturn in the 11th house means where you face limitation and build mastery is organized around friendship, collective goals, and learning to contribute to groups. You're learning community. The 11th house is friendship networks and shared vision, and your Saturn here makes your challenges show up in groups and around collective work. You struggle with feeling you belong in communities or that your contribution matters. Your discipline develops through learning when and how to participate in collective action. Your mastery comes from building genuine friendships and contributing to groups without losing yourself. You're learning that belonging is built through sustained participation. Social isolation or overwork for the collective feels familiar to your Saturn but earned community is what you're building toward. The work is developing the capacity to participate in groups without requiring perfect belonging or avoiding connection entirely.""",
        "behavioral": """You struggle with belonging to groups, work to build genuine friendships, and develop mastery through learning to contribute to collective goals without losing individual identity. When you're in group settings or pursuing shared vision, you might stay on the outside or overwork to prove you belong. When you're developing your capacity for community, you're learning the difference between genuine participation and either isolation or self-sacrifice for the collective. Your growth is measured in how you overcome fear of rejection or loss of self in groups. You take friendship and collective work seriously. This isn't antisocial behavior. It's genuine work with difficult material. The maturation is learning that you can belong, that your contribution matters, that community includes your individual needs. Your mastery is earned belonging—the capacity to participate in groups while maintaining your own development.""",
        "feed": """Saturn is moving through your 11th house. The areas where you face limitation and build mastery are focused on friendship, community, and collective contribution right now. This is a time for working with groups, for building genuine friendships, for earning your place in communities through sustained participation.""",
        "sonic": """Your Saturn in the 11th house contributes measured collaborative rhythms, disciplined harmonic participation, and melodic contribution to the ensemble that's learning to trust belonging. The quality of limitation is found in fear of rejection, creating mastery through earned community. Listen for music where belonging is built through patient participation, where friendship is earned through showing up over time.""",
    },
    "PLCMT_SATURN_HOUSE12": {
        "core": """Your Saturn in the 12th house means where you face limitation and build mastery is organized around the unconscious, spirituality, and learning to surrender. You're learning spiritual discipline. The 12th house is what's hidden and transcendent, and your Saturn here makes your challenges show up in your relationship to the ineffable. You struggle with trusting what can't be controlled or seeing value in invisible work. Your discipline develops through spiritual practice and service that requires no recognition. Your mastery comes from building genuine capacity for surrender and working with the unconscious. You're learning that some work happens in darkness. Fear of formlessness feels familiar to your Saturn but earned surrender is what you're building toward. The work is developing the capacity to release control and trust mystery without avoiding necessary earthly responsibility.""",
        "behavioral": """You struggle with surrendering control, work to build spiritual discipline, and develop mastery through learning that not everything can or should be mastered. When you're facing situations requiring surrender or invisible work, you might avoid entirely or try to control the uncontrollable. When you're developing your spiritual capacity, you're learning the difference between genuine surrender and either spiritual bypassing or refusal to engage mystery. Your growth is measured in how you overcome fear of what can't be seen or controlled. You take spirituality and the unconscious seriously. This isn't weakness. It's genuine work with difficult material. The maturation is learning that you can surrender, that invisible work matters, that mystery serves growth when approached with discipline. Your mastery is earned surrender—the capacity to release control while maintaining groundedness in earthly reality.""",
        "feed": """Saturn is moving through your 12th house. The areas where you face limitation and build mastery are focused on the unconscious, spirituality, and learning to surrender right now. This is a time for working with what's hidden, for building spiritual discipline, for earning the capacity to trust mystery.""",
        "sonic": """Your Saturn in the 12th house contributes restrained dissolution, disciplined harmonic transcendence, and rhythmic patterns that are learning to release structure. The quality of limitation is found in fear of formlessness, creating mastery through earned surrender. Listen for music where mystery is approached with discipline, where surrender is built through patient spiritual practice.""",
    },
}
