"""Neptune in Libra–Pisces — Phase 3 sign placement copy (core, behavioral, feed, sonic)."""

UPDATES: dict[str, dict[str, str]] = {
    "PLCMT_NEPTUNE_LIBRA": {
        "core": """Your Neptune in Libra means where you encounter mystery and dissolve boundaries is organized around relationship, justice, and reimagining what partnership means. Your generation dreams of perfect harmony. Neptune is the capacity for imagination and dissolution, and in Libra it operates through idealizing partnership and questioning what fairness actually is. Your generation's dream is about perfect relationship. The collective longing is for partnership that's both equal and transcendent. You're wired to sense where harmony has become suppression, where partnership has hardened into prescribed roles. The generational work is holding the vision of relating that serves both justice and love.""",
        "behavioral": """You idealize partnership, dream of perfect harmony, and dissolve boundaries around what relationship means. When you're connecting to the mystery, it arrives through visions of perfect union or divine partnership. Your confusion lives in the gap between ideal relating and the messiness of actual partnerships. You're learning that the dream of perfect harmony both inspires and deceives. This isn't just naivete. It's genuine spiritual longing for relationship that's both fair and beautiful. The shadow is that idealization can prevent real connection. You may dream of perfect partners without seeing who people actually are, or you may confuse spiritual bypassing with enlightened relating. The work is using your capacity to imagine sacred partnership while remaining grounded in what actual equality requires.""",
        "feed": """Neptune is moving through Libra in your chart. Where you encounter mystery and dissolve boundaries is focused on relationship, justice, and reimagining partnership right now. This is a time for spiritual visions of harmony, for dissolving rigid patterns of relating, for trusting your generation's dream of sacred connection.""",
        "sonic": """Your Neptune in Libra contributes dreamlike harmonic balance, dissolving melodic partnership, and rhythm that is both fair and fluid. The quality of mystery is found in idealized relating, creating spiritual longing through visions of perfect harmony. Listen for music where boundaries between partners dissolve and relationship becomes sacred rather than transactional.""",
    },
    "PLCMT_NEPTUNE_SCORPIO": {
        "core": """Your Neptune in Scorpio means where you encounter mystery and dissolve boundaries is organized around transformation, power, and reimagining what depth means. Your generation dreams of perfect intimacy. Neptune is the capacity for imagination and dissolution, and in Scorpio it operates through idealizing transformation and questioning what power actually is. Your generation's dream is about complete merger. The collective longing is for intimacy that's both intense and transcendent. You're wired to sense where depth has become manipulation, where transformation has hardened into trauma cycles. The generational work is holding the vision of power that serves both truth and healing.""",
        "behavioral": """You idealize transformation, dream of perfect intimacy, and dissolve boundaries around what depth means. When you're connecting to the mystery, it arrives through visions of complete merger or alchemical transformation. Your confusion lives in the gap between ideal depth and the messiness of actual shadows. You're learning that the dream of perfect intimacy both inspires and deceives. This isn't just intensity. It's genuine spiritual longing for transformation that's both powerful and healing. The shadow is that idealization can prevent facing actual shadows. You may dream of perfect depth without doing psychological work, or you may confuse spiritual bypassing with enlightened relationship to power. The work is using your capacity to imagine sacred transformation while remaining grounded in what actual healing requires.""",
        "feed": """Neptune is moving through Scorpio in your chart. Where you encounter mystery and dissolve boundaries is focused on transformation, power, and reimagining depth right now. This is a time for spiritual visions of intimacy, for dissolving rigid patterns of control, for trusting your generation's dream of sacred power.""",
        "sonic": """Your Neptune in Scorpio contributes dreamlike chromatic intensity, dissolving harmonic depth, and rhythm that is both powerful and fluid. The quality of mystery is found in idealized transformation, creating spiritual longing through visions of perfect merger. Listen for music where boundaries around power dissolve and intimacy becomes sacred rather than manipulative.""",
    },
    "PLCMT_NEPTUNE_SAGITTARIUS": {
        "core": """Your Neptune in Sagittarius means where you encounter mystery and dissolve boundaries is organized around belief, expansion, and reimagining what truth means. Your generation dreams of perfect wisdom. Neptune is the capacity for imagination and dissolution, and in Sagittarius it operates through idealizing understanding and questioning what knowing actually is. Your generation's dream is about universal truth. The collective longing is for philosophy that's both expansive and sacred. You're wired to sense where belief has become dogma, where exploration has hardened into tourism. The generational work is holding the vision of wisdom that serves both understanding and mystery.""",
        "behavioral": """You idealize wisdom, dream of perfect understanding, and dissolve boundaries around what truth means. When you're connecting to the mystery, it arrives through visions of universal philosophy or transcendent meaning. Your confusion lives in the gap between ideal wisdom and the messiness of actual beliefs. You're learning that the dream of perfect understanding both inspires and deceives. This isn't just relativism. It's genuine spiritual longing for truth that's both expansive and humble. The shadow is that idealization can prevent commitment to any truth. You may dream of perfect wisdom without doing the work of rigorous study, or you may confuse spiritual bypassing with enlightened philosophy. The work is using your capacity to imagine universal understanding while remaining grounded in what actual wisdom requires.""",
        "feed": """Neptune is moving through Sagittarius in your chart. Where you encounter mystery and dissolve boundaries is focused on belief, expansion, and reimagining truth right now. This is a time for spiritual visions of wisdom, for dissolving rigid patterns of dogma, for trusting your generation's dream of sacred understanding.""",
        "sonic": """Your Neptune in Sagittarius contributes dreamlike melodic expansion, dissolving harmonic philosophy, and rhythm that is both exploratory and fluid. The quality of mystery is found in idealized wisdom, creating spiritual longing through visions of universal truth. Listen for music where boundaries around belief dissolve and understanding becomes sacred rather than dogmatic.""",
    },
    "PLCMT_NEPTUNE_CAPRICORN": {
        "core": """Your Neptune in Capricorn means where you encounter mystery and dissolve boundaries is organized around structure, achievement, and reimagining what mastery means. Your generation dreams of perfect authority. Neptune is the capacity for imagination and dissolution, and in Capricorn it operates through idealizing structure and questioning what legitimate power actually is. Your generation's dream is about sacred governance. The collective longing is for achievement that's both disciplined and compassionate. You're wired to sense where structure has become oppression, where mastery has hardened into exploitation. The generational work is holding the vision of authority that serves both order and humanity.""",
        "behavioral": """You idealize structure, dream of perfect achievement, and dissolve boundaries around what mastery means. When you're connecting to the mystery, it arrives through visions of sacred governance or enlightened authority. Your confusion lives in the gap between ideal structure and the messiness of actual systems. You're learning that the dream of perfect authority both inspires and deceives. This isn't just idealism. It's genuine spiritual longing for power that's both legitimate and compassionate. The shadow is that idealization can prevent building actual structures. You may dream of perfect systems without doing the work of governance, or you may confuse spiritual bypassing with enlightened relationship to authority. The work is using your capacity to imagine sacred mastery while remaining grounded in what actual structure requires.""",
        "feed": """Neptune is moving through Capricorn in your chart. Where you encounter mystery and dissolve boundaries is focused on structure, achievement, and reimagining mastery right now. This is a time for spiritual visions of authority, for dissolving rigid patterns of power, for trusting your generation's dream of sacred governance.""",
        "sonic": """Your Neptune in Capricorn contributes dreamlike structural flow, dissolving harmonic authority, and rhythm that is both disciplined and fluid. The quality of mystery is found in idealized mastery, creating spiritual longing through visions of perfect governance. Listen for music where boundaries around structure dissolve and authority becomes sacred rather than oppressive.""",
    },
    "PLCMT_NEPTUNE_AQUARIUS": {
        "core": """Your Neptune in Aquarius means where you encounter mystery and dissolve boundaries is organized around collective vision, innovation, and reimagining what progress means. Your generation dreams of perfect liberation. Neptune is the capacity for imagination and dissolution, and in Aquarius it operates through idealizing progress and questioning what freedom actually is. Your generation's dream is about universal brotherhood. The collective longing is for innovation that's both revolutionary and compassionate. You're wired to sense where progress has become ideology, where collective good has hardened into conformity to new norms. The generational work is holding the vision of freedom that serves both individual and collective.""",
        "behavioral": """You idealize progress, dream of perfect liberation, and dissolve boundaries around what freedom means. When you're connecting to the mystery, it arrives through visions of universal humanity or technological transcendence. Your confusion lives in the gap between ideal progress and the messiness of actual change. You're learning that the dream of perfect freedom both inspires and deceives. This isn't just utopianism. It's genuine spiritual longing for innovation that's both radical and human. The shadow is that idealization can prevent grounded action. You may dream of perfect revolution without doing the work of actual organizing, or you may confuse spiritual bypassing with enlightened relationship to progress. The work is using your capacity to imagine universal liberation while remaining grounded in what actual change requires.""",
        "feed": """Neptune is moving through Aquarius in your chart. Where you encounter mystery and dissolve boundaries is focused on collective vision, innovation, and reimagining progress right now. This is a time for spiritual visions of liberation, for dissolving rigid patterns of conformity, for trusting your generation's dream of sacred revolution.""",
        "sonic": """Your Neptune in Aquarius contributes dreamlike innovative textures, dissolving harmonic progress, and rhythm that is both revolutionary and fluid. The quality of mystery is found in idealized freedom, creating spiritual longing through visions of universal humanity. Listen for music where boundaries around progress dissolve and innovation becomes sacred rather than merely technological.""",
    },
    "PLCMT_NEPTUNE_PISCES": {
        "core": """Your Neptune in Pisces, its home sign, means where you encounter mystery and dissolve boundaries is at maximum capacity for compassion, transcendence, and spiritual connection. Dissolution is your generation's element. The 12th sign is universal love and what's beyond form, and your Neptune here operates at full strength—sensing all suffering, creating from the collective unconscious, serving what's larger than ego. Your generation's dream is about perfect compassion. The collective longing is for complete transcendence of separation. You're wired to sense all boundaries as ultimately permeable. The generational work is holding the vision of universal love while remaining embodied enough to actually serve.""",
        "behavioral": """You idealize compassion itself, dream of complete transcendence, and dissolve boundaries around everything. When you're connecting to the mystery, it's everywhere—your generation lives in spiritual space more easily than material reality. Your confusion lives in what's real at all. You're learning that the dream of perfect universal love both inspires profound service and can prevent necessary embodiment. This isn't just confusion. It's genuine spiritual permeability at maximum capacity. The shadow is that idealization of transcendence can mean never showing up in the world. Your generation may dream of perfect compassion without developing the boundaries needed to actually help, or may confuse spiritual bypassing with enlightenment. The work is using your profound capacity for universal love while maintaining enough self to actually be present and serve with discernment, not just dissolve into everything.""",
        "feed": """Neptune is moving through Pisces, its home sign, in your chart. Where you encounter mystery and dissolve boundaries is at maximum spiritual capacity right now. This is a time for profound compassion, for trusting complete permeability, for recognizing that your generation's gift is sensing universal connection.""",
        "sonic": """Your Neptune in Pisces contributes total harmonic dissolution, completely fluid melodic currents, and rhythm that dissolves all structure into pure spiritual flow. The quality of mystery is absolute and oceanic, creating spiritual longing through complete loss of separation. Listen for music where all boundaries dissolve completely and what remains is pure compassion beyond form.""",
    },
}
