"""Uranus in houses 1-6 — Phase 3 placement copy (core, behavioral, feed, sonic).

Houses 7-12 pending supplied batch copy."""

UPDATES: dict[str, dict[str, str]] = {
    "PLCMT_URANUS_HOUSE1": {
        "core": """Your Uranus in the 1st house means where you innovate and break patterns is inseparable from your immediate presence and how you show up. Your individuality is revolutionary. The 1st house is self-presentation, and your Uranus here makes your capacity for innovation visible in how you appear. You disrupt through being yourself. Your insights arrive about identity and presentation. Your breakthrough is learning that your authentic presence is inherently unconventional. You're wired to see where self-expression has become performance of normalcy. Personal rebellion through existing exactly as you are is your work.""",
        "behavioral": """You break patterns through your presence, innovate in how you show up, and contribute to revolution simply by being visible as yourself. When you're being disruptive, it's through existing authentically rather than conforming to expected presentation. Your insights arrive suddenly about where you've been performing normalcy. You're learning that your natural way of being is the disruption. This isn't attention-seeking. It's genuine innovation through authentic presence. The shadow is that unconventionality can become performance. You may disrupt just to be different, or you may confuse being unusual with being free. The work is ensuring that what you're showing is actually who you are, not just what looks revolutionary.""",
        "feed": """Uranus is moving through your 1st house. Where you innovate and break patterns is focused on self-presentation, identity, and how you show up right now. This is a time for disrupting through authentic presence, for allowing your natural way of being to challenge norms, for trusting that being yourself is revolutionary.""",
        "sonic": """Your Uranus in the 1st house contributes unexpected melodic presence in the foreground, innovative harmonic self-expression, and rhythmic breaks in how identity is performed. The quality of innovation is immediate and personal, creating breakthrough through unconventional presence. Listen for music where showing up disrupts expectations and authentic being becomes revolution.""",
    },
    "PLCMT_URANUS_HOUSE2": {
        "core": """Your Uranus in the 2nd house means where you innovate and break patterns is organized around resources, value, and what security means. Your relationship to material reality is revolutionary. The 2nd house is resources and worth, and your Uranus here makes your capacity for innovation connected to reimagining how value works. You disrupt through unconventional relationship to money and earth. Your insights arrive about what actually has value and what security requires. Your breakthrough is learning that stability can be revolutionized. You're wired to see where conventional approaches to resources prevent actual sustainability. Material revolution is your work.""",
        "behavioral": """You break patterns around resources, innovate in how you create value, and contribute to revolution through reimagining what wealth and security mean. When you're being disruptive, it's through unconventional approaches to money, work, or physical reality. Your insights arrive suddenly about where traditional resource management prevents actual abundance. You're learning that security doesn't require conventional stability. This isn't instability. It's genuine innovation in how material reality operates. The shadow is that disruption can prevent building anything. You may break patterns around resources without creating sustainable alternatives, or you may confuse innovation with just refusing to earn money conventionally. The work is ensuring that your unconventional approaches actually create security rather than just avoiding traditional work.""",
        "feed": """Uranus is moving through your 2nd house. Where you innovate and break patterns is focused on resources, value, and reimagining security right now. This is a time for disrupting conventional approaches to money, for innovating in how you create value, for trusting that stability can be revolutionized.""",
        "sonic": """Your Uranus in the 2nd house contributes unexpected rhythmic accumulation, innovative harmonic value creation, and melodic breaks in conventional resource patterns. The quality of innovation is material and revolutionary, creating breakthrough through reimagined security. Listen for music where traditional approaches to stability are disrupted and new forms of sustainable abundance emerge.""",
    },
    "PLCMT_URANUS_HOUSE3": {
        "core": """Your Uranus in the 3rd house means where you innovate and break patterns is organized around communication, learning, and how ideas move. Your thinking is revolutionary. The 3rd house is thought and local connection, and your Uranus here makes your capacity for innovation connected to reimagining how we understand and communicate. You disrupt through unconventional ideas and communication. Your insights arrive about what counts as knowledge and how information should flow. Your breakthrough is learning that thought itself can be revolutionized. You're wired to see where conventional education and communication prevent actual understanding. Intellectual revolution is your work.""",
        "behavioral": """You break patterns in how you think and communicate, innovate in learning and sharing ideas, and contribute to revolution through unconventional intellectual approaches. When you're being disruptive, it's through thinking differently or communicating in ways that challenge norms. Your insights arrive suddenly about where conventional thought and language prevent actual understanding. You're learning that new ideas require new ways of thinking. This isn't just being difficult. It's genuine innovation in how minds work. The shadow is that unconventionality can prevent communication. You may think so differently that no one understands you, or you may confuse innovation with just being obscure. The work is ensuring that your unconventional thinking actually serves understanding rather than just proving you're original.""",
        "feed": """Uranus is moving through your 3rd house. Where you innovate and break patterns is focused on communication, learning, and how ideas move right now. This is a time for disrupting conventional thought, for innovating in how you understand and share, for trusting that thinking itself can be revolutionized.""",
        "sonic": """Your Uranus in the 3rd house contributes sudden melodic connections, innovative harmonic communication, and rhythmic breaks in conventional thought patterns. The quality of innovation is mental and disruptive, creating breakthrough through reimagined understanding. Listen for music where ideas move in unexpected ways and communication disrupts normal patterns of thought.""",
    },
    "PLCMT_URANUS_HOUSE4": {
        "core": """Your Uranus in the 4th house means where you innovate and break patterns is organized around home, family, and what belonging means. Your relationship to roots is revolutionary. The 4th house is foundation and private life, and your Uranus here makes your capacity for innovation connected to reimagining what home and family are. You disrupt through unconventional approaches to domesticity and emotional foundation. Your insights arrive about what actually creates belonging and safety. Your breakthrough is learning that home itself can be revolutionized. You're wired to see where traditional family structures prevent actual emotional connection. Domestic revolution is your work.""",
        "behavioral": """You break patterns around home and family, innovate in how you create emotional foundation, and contribute to revolution through reimagining what belonging means. When you're being disruptive, it's through unconventional living situations or relationships to family. Your insights arrive suddenly about where traditional domesticity prevents actual safety. You're learning that genuine home might look nothing like what previous generations created. This isn't just rebellion against family. It's genuine innovation in how we belong. The shadow is that disruption can prevent rootedness. You may break every domestic pattern without building actual foundation, or you may confuse innovation with just refusing to settle anywhere. The work is ensuring that your unconventional approaches actually create sanctuary rather than just avoiding traditional home.""",
        "feed": """Uranus is moving through your 4th house. Where you innovate and break patterns is focused on home, family, and emotional foundation right now. This is a time for disrupting conventional domesticity, for innovating in how you create belonging, for trusting that home can be revolutionized.""",
        "sonic": """Your Uranus in the 4th house contributes unexpected emotional rhythms, innovative harmonic foundations, and melodic breaks in conventional family structures. The quality of innovation is domestic and revolutionary, creating breakthrough through reimagined belonging. Listen for music where traditional notions of home are disrupted and new forms of sanctuary emerge.""",
    },
    "PLCMT_URANUS_HOUSE5": {
        "core": """Your Uranus in the 5th house means where you innovate and break patterns is organized around creativity, self-expression, and what joy means. Your relationship to pleasure is revolutionary. The 5th house is creative expression and play, and your Uranus here makes your capacity for innovation connected to reimagining what art and celebration are. You disrupt through unconventional creativity and romance. Your insights arrive about what actually brings joy and what creative expression serves. Your breakthrough is learning that play itself can be revolutionized. You're wired to see where conventional approaches to art and pleasure have become formulaic. Creative revolution is your work.""",
        "behavioral": """You break patterns around creativity and pleasure, innovate in how you express yourself and celebrate, and contribute to revolution through unconventional art and joy. When you're being disruptive, it's through creating in ways that challenge norms or finding pleasure in unexpected places. Your insights arrive suddenly about where conventional art and romance prevent actual expression and connection. You're learning that genuine creativity might look nothing like what's been done before. This isn't just shock value. It's genuine innovation in how expression works. The shadow is that disruption can replace actual creation. You may break creative patterns without making anything, or you may confuse innovation with just being outrageous. The work is ensuring that your unconventional approaches actually serve expression rather than just proving you're different.""",
        "feed": """Uranus is moving through your 5th house. Where you innovate and break patterns is focused on creativity, self-expression, and reimagining joy right now. This is a time for disrupting conventional art and pleasure, for innovating in how you create and celebrate, for trusting that expression can be revolutionized.""",
        "sonic": """Your Uranus in the 5th house contributes sudden creative bursts, innovative harmonic play, and rhythmic breaks in conventional expression. The quality of innovation is artistic and celebratory, creating breakthrough through reimagined creativity. Listen for music where traditional forms of art are disrupted and new ways of expressing joy emerge.""",
    },
    "PLCMT_URANUS_HOUSE6": {
        "core": """Your Uranus in the 6th house means where you innovate and break patterns is organized around work, health, and daily practice. Your relationship to service is revolutionary. The 6th house is useful work and wellness, and your Uranus here makes your capacity for innovation connected to reimagining what functional means. You disrupt through unconventional approaches to work and body care. Your insights arrive about what actually creates health and what useful service requires. Your breakthrough is learning that work itself can be revolutionized. You're wired to see where conventional approaches to labor and wellness prevent actual function. Work revolution is your work.""",
        "behavioral": """You break patterns around work and health, innovate in daily practice and service, and contribute to revolution through unconventional approaches to function. When you're being disruptive, it's through working differently or caring for your body in unexpected ways. Your insights arrive suddenly about where traditional work and medical models prevent actual wellness and usefulness. You're learning that genuine health and service might look nothing like conventional approaches. This isn't just laziness or quackery. It's genuine innovation in how bodies function and work serves. The shadow is that disruption can prevent actual care. You may break every health pattern without building sustainable wellness, or you may confuse innovation with just refusing conventional work. The work is ensuring that your unconventional approaches actually serve your body and create useful contribution.""",
        "feed": """Uranus is moving through your 6th house. Where you innovate and break patterns is focused on work, health, and daily practice right now. This is a time for disrupting conventional labor and wellness, for innovating in how you serve and care for your body, for trusting that function can be revolutionized.""",
        "sonic": """Your Uranus in the 6th house contributes unexpected rhythmic precision, innovative harmonic functionality, and melodic breaks in conventional work patterns. The quality of innovation is practical and revolutionary, creating breakthrough through reimagined service. Listen for music where traditional approaches to work are disrupted and new forms of sustainable function emerge.""",
    },
}
